### ISSUE TITLE
Виставлення рахунку. Печатная форма. Адрес

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#101]
Исправлено отображение длинного текста. В т.ч. и в PDF.
[566](https://github.com/a2develop/bugTracker/issues/566)

**Comment by Anestezia** [comment]
подтверждаю, все ок.
![image](https://user-images.githubusercontent.com/42540074/46796851-426b2600-cd56-11e8-962d-86430955df3c.png)
