### ISSUE TITLE
В отчетности добавлен отчет неприбыльной организации

### ISSUE THREAD

**Issue by shevchuk-vadim** [a2develop/testing#104]

**Comment by Anestezia** [comment]
Для Звіту передбачено два звітні (податкові) періоди: рік та місяць. Ставиться позначка у полі: — «Місяць» — у разі якщо неприбутковою організацією порушено вимоги, встановлені п. 133.4 ПКУ. При цьому зазначають не позначку «х», а номер календарного місяця, в якому порушено вимоги п. 133.4 ПКУ та нараховане податкове зобов’язання з податку на прибуток. У такому разі Звіт складають за період з початку року (або з початку визнання організації неприбутковою в установленому порядку, якщо таке визнання відбулося пізніше) по останній день місяця, в якому вчинено таке порушення; — у полі «Рік» — роблять позначку «х» неприбуткові організації, які відповідають вимогам, п. 133.4 ПКУ та внесені до Реєстру

Нужны редактируемые периоды?

В остальном все ок. Перенос в сонату кнопкой (Соната) и через хмл с последующей проверкой ок.

Заполняется вручную или автоматом у меня не тянет, потому что на определенных счетах нет поступлений?

**Comment by shevchuk-vadim** [comment]
Добавил возможность выбирать период месяц при создании отчета.
Заполнение - отдельное ишью.
Это закрываем?

**Comment by Anestezia** [comment]
Закрываем
