### ISSUE TITLE
Операция "Експорт запасів"

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#105]
Новая операция.
Проверить пересчет грн <-> валюта.

Проверить отражение в отчетах:
1. По объекту - Оборотная ведомость по складу.
2. Загальна оборотна-сальдова відомість.
3. По покупателю - Оборотна відомість за розрахунками з покупцями у валюті.

Проверить создание связанной НН.

**Comment by Anestezia** [comment]
1. Пересчет работает как и в импорте запасов. 
2. Ведомости в порядке.
3. НН - в порядке. 
В связанной НН автоматом ставит умовний ипн 100000000000, а не должен 300000000000? как правильно?
![image](https://user-images.githubusercontent.com/42540074/46802512-2ec7bb80-cd66-11e8-8081-bcb477ebd77e.png)
И еще вопрос. У нас где-то было реализовано с банковскими валютными счетами - запрет на выбор, например, у контрагента есть только долларовый счет, а платеж в евро, и система, как только делался выбор валюты (евро), сбрасывала на красное поле р\с в валюте у контрагента. А здесь у моего контрагента только евровый счет добавлен, а долларовая операция провелась, что при импорте запасов, что при экспорте. Это важно?

У нас автоматически нигде в НН не ставится галочка Не підлягає видачі з причини, і тип причини (в данном случае 02 или 07?)?

**Comment by AlexeyTishkin** [comment]
> В связанной НН автоматом ставит умовний ипн 100000000000, а не должен 300000000000? как правильно?

Не знаю. Надо где-то проконсультироваться... Если не правильно, то отдельный issue.

**Comment by AlexeyTishkin** [comment]
> У нас где-то было реализовано с банковскими валютными счетами - запрет на выбор, например, у контрагента есть только долларовый счет, а платеж в евро, и система, как только делался выбор валюты (евро), сбрасывала на красное поле р\с в валюте у контрагента. А здесь у моего контрагента только евровый счет добавлен, а долларовая операция провелась, что при импорте запасов, что при экспорте. Это важно?

У платежа есть непосредственная связь между валютой платежа и валютой счета, с которого осуществляется платеж. В данном случае связи с платежом нет, мы делаем только отгрузку.

**Comment by AlexeyTishkin** [comment]
> У нас автоматически нигде в НН не ставится галочка Не підлягає видачі з причини, і тип причини (в данном случае 02 или 07?)?

Отдельный issue с перечнем что и когда устанавливать.

**Comment by shevchuk-vadim** [comment]
> Не знаю. Надо где-то проконсультироваться... Если не правильно, то отдельный issue.

Далеко за консультацией идти не надо.
При экспорте товаров в НН тип причины должен быть 07, а ИНН - 300000000000.

**Comment by AlexeyTishkin** [comment]
Тогда отдельный issue. Этот закрываю.
