### ISSUE TITLE
Отчёт "Справка о доходах"

### ISSUE THREAD

**Issue by Illya-Lykhachov** [a2develop/testing#106]
Сотрудники - выбранный сотрудник - закладка "отчёты".
Пока нет возможности указать период, Поэтому отчёт строится за предыдущие 6 месяцев от сегодняшней даты.

**Comment by Anestezia** [comment]
Может его как отдельную операцию сделать, а не как отчет? И так далеко запрятан, трудно найти. Я сама случайно наткнулась, а ведь у меня про него клиенты спрашивали.

**Comment by Illya-Lykhachov** [comment]
так и решили. Справки будут отдельным подразделом (как исходящие документы)
