### ISSUE TITLE
Зарплата. Расчёт ЕСВ на ФОТ. Доначисление до минимальной только на сотрудников по основному месту работы

### ISSUE THREAD

**Issue by Illya-Lykhachov** [a2develop/testing#107]

**Comment by Anestezia** [comment]
Есть такая функция. Работает, как заявлено.
![image](https://user-images.githubusercontent.com/42540074/47075496-5951c280-d205-11e8-892b-b0706807fd46.png)
Это по основному месту работы.
![image](https://user-images.githubusercontent.com/42540074/47075585-84d4ad00-d205-11e8-90a8-4a79a24e82c4.png)
А это совместитель.
