### ISSUE TITLE
Добавлено заполнение отчета неприбыльной организации

### ISSUE THREAD

**Issue by shevchuk-vadim** [a2develop/testing#109]
Для неприбыльных организаций добавлено много операций. Нужно проверять, правильно ли их суммы попадают в отчет.

Сумма попадает в доходы (строка отчета выбирается их списка видов поступлений):
безвозмездное получение запасов и услуг,
безвозвратное получения целевых и нецелевых денежных средств по кассе и счетам в банках в национальной и иностранной валютах.

Сумма попадает в расходы (строка отчета выбирается их списка видов расходов):
безвозмездная передача запасов и услуг,
безвозвратная выдача денежных средств по кассе и счетам в банках в национальной валюте.

Сумма не попадает никуда:
признание операционного дохода за счет целевых поступлений.

Также нужно проверить, чтобы суммы всех остальных видов доходов и расходов попали в отчет, как прочие доходы и расходы.

Расходы - это себестоимость реализованных запасов и полученных услуг, начисленная зарплата, командировочные расходы, комиссия банка, курсовые разницы, и т.п. Кроме тех, что идут на дебет счетов 23 и 91, потому что с них суммы уйдут в дебет других счетов 9 класса.

Доходы - это доходы от реализации запасов и услуг, курсовые разницы, и т.п.

**Comment by Anestezia** [comment]
Суммы в отчет попадают правильно. ЗП - 91, не идет в отчет.
