### ISSUE TITLE
Проверить отображение перечня операций

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#112]
[596](https://github.com/a2develop/bugTracker/issues/596)

- [ ] Придбання / Операції
- [ ] Продажі / Операції
- [ ] Запаси / Операції
- [ ] НА / Операції
- [ ] Бухгалтерія / ...
- [ ] Персонал / Документи

**Comment by Anestezia** [comment]
1. Все работает корректно. В сочетании с отбором в указанном периоде и с отбором главного фильтра по конкретным операциям тоже все ок.
2. Аналогично.
3. Аналогично.
4. Пока не реализовано.
5. По всем операциям ок.
6. Не реализовано.

**Comment by Anestezia** [comment]
1. Работает корректно, и в сочетании с отбором в указанном периоде, и с главным отбором по конкретной операции, тоже все ок.
2. Аналогично.
3. Аналогично.
4. Не реализовано.
5. По всем операциям ок.
6. Не реализовано.

**Comment by Anestezia** [comment]
Работает корректно, и в сочетании с отбором в указанном периоде, и с главным отбором по конкретной операции, тоже все ок.
Аналогично.
Аналогично.
Не реализовано.
По всем операциям ок.
Не реализовано.
