### ISSUE TITLE
Диалог создания нового фискального отчета

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#114]
[592](https://github.com/a2develop/bugTracker/issues/592)
Проверить возможность отображения в перечне всех отчетов. К примеру, ФОП - не плательщик НДС, в случае "перелік звітів для встановленої" не должен показывать в перечне Декларацию НДС, а при выборе "усі звіти" - должен показать.

**Comment by Anestezia** [comment]
Работает, как заявлено.
