### ISSUE TITLE
Таблица 6 отчёта "Персонифицированный учёт плательщиков ЕСВ (Додаток 4)"

### ISSUE THREAD

**Issue by Illya-Lykhachov** [a2develop/testing#116]
Последние изменений: выделены строки с больничными и календарные дни работы отображаются только в нужных строках.
Нужно погонять во всех ситуациях:
- больничными прошлых периодов;
- переходящие отпускные;
- начисление больше ограничения;
- начисления меньше минималки;
- ...

**Comment by Anestezia** [comment]
Переходящие отпускные - ОК, меньше минималки - тоже ОК, остальные пункты Соната не пропускает
