### ISSUE TITLE
Операция "Реалізація запасів". Добавлено поле "Через кого" для указания реквизитов доверенности

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#12]
[339](https://github.com/a2develop/bugTracker/issues/339)
Проверить отражение в т.ч. в печатной форме.

**Comment by kattrina-brekhova** [comment]
замечаний нету. строчка позволяет ввести ФИО получателя и прописать №, дату доверенности

**Comment by kattrina-brekhova** [comment]
строчка позволяет ввести ФИО получателя и прописать №, дату доверенности. сомнения вызывает само название строчки. уже есть строки "сдав", "прийняв", куда можно указать лица получателя и отправителя. как насчет переименовать строку на "Через кого, підстава". Изначально это и имел в виду Андрей.

**Comment by AlexeyTishkin** [comment]
Переименовал.

**Comment by kattrina-brekhova** [comment]
ура!

**Comment by AndriyNesterenya** [comment]
Т.е. предполагается, что в "Через кого, підстава" мы пишем реального получателя и номер доверенности, а в "Прийняв" - подотчетное лицо получателя?

**Comment by AlexeyTishkin** [comment]
"Через кого" - лицо из доверенности и ее реквизиты.
Принял - получается, что тоже самое лицо. Только там еще его подпись.
