### ISSUE TITLE
В свойствах расчетного счета добавлен признак активности.

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#124]
Если признак активности не установлен, то счет не отображается в списках для выбора.
Проверить отображение не активного счета.

**Comment by AndriyNesterenya** [comment]
Ведет себя кривовато.
Заходим в Бухгалтерию-Счета, выбираем счет, который хотим спрятать, жмем на Изменить, убираем признак активности, сохраняем - записть счета в центральном фрейме остается, исчезает только номер.
![image](https://user-images.githubusercontent.com/38098758/47711215-5e6b3480-dc3d-11e8-810f-ab424b0eba1d.png)

После принудительного обновления - исчезает совсем.

**Comment by AndriyNesterenya** [comment]
Заявленный косяк исправлен.
Добавлена маркировка активных счетов отдельной иконкой.
Добавлено средство отображения всего списка счетов или только активных счетов.

В нынешнем виде пропадает необходимость выделения неактивных счетов ярким цветом, и может быть стоит вернуть все к обычному серому.
Неактивный счет в общем списке интуитивно ожидаешь видеть менее заметным, чем активный.
А-ля недоступный принтер в панели управления Windows

**Comment by AlexeyTishkin** [comment]
> В нынешнем виде пропадает необходимость выделения неактивных счетов ярким цветом, и может быть стоит вернуть все к обычному серому.

Имеется ввиду красная иконка ?

**Comment by AndriyNesterenya** [comment]
Да.
Пока интерфейс не переделали и вел он себя иначе - была потребность как-то выделять скрываемые счета.
В нынешнем варианте такой необходимости уже нет, как по мне.

**Comment by AlexeyTishkin** [comment]
Иконку поменяли на серую.
