### ISSUE TITLE
Импорт выписки из клиент-банка

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#126]
[625](https://github.com/a2develop/bugTracker/issues/625)
При создании нового контрагента в случае, если МФО его счета равен 899998, то ему присваивается роль "Державний орган".

**Comment by AndriyNesterenya** [comment]
Пока не получилось. 
В существующем аккаунте убил контрагента УДКСУ У ШЕВЧЕНКIВСЬКОМУ РАЙОНI М.КИЄВА с банком- Казначейство України (ел.адм.подат.) в м. Київ, Код банку 899998

Поотменял проводки по этому контрагенту.
Заново провел платежки из выписки - контрагент автоматом не создался.

**Comment by AlexeyTishkin** [comment]
Контрагент создается в момент импорта выписки из клиент-банка. Нужно удалить выписку и проимпортировать заново.

**Comment by AndriyNesterenya** [comment]
... попутно нашлась еще одна проблема.
Была выписка с несколькими платежками.
Часть проведена, у части проведение отменено.
Нажал удалить - удалилось и закрылось окно насовсем.

Как идеологически должно вести себя удаление выписки при наличии проведенных платежек?

**Comment by AndriyNesterenya** [comment]
При повторном импорте все отработало как надо

**Comment by AlexeyTishkin** [comment]
> Как идеологически должно вести себя удаление выписки при наличии проведенных платежек?

Скорее всего нужно запрещать удаление. Напиши отдельный issue.

**Comment by AlexeyTishkin** [comment]
Этот закрываю.
