### ISSUE TITLE
Платежные поручения

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#127]
Поменялась внутрення модель документа. В связи с этим необходимо проверить операции:
Надання коштів підзвітній особі
Виплата зарплати
Повернення коштів підзвітною особою
Повернення зарплати

**Comment by Anestezia** [comment]
Все вроде норм работает. Есть вопрос. У нас подстановка счета плательщика теперь не обязательный реквизит для заполнения, и платежка без расчетного счета проводится. Может хоть подсказку сделать, чтоб люди не провтыкивали его писать?

**Comment by AlexeyTishkin** [comment]
Платежку изначально делал Вадим. Он ответил: "Чтобы провести документ, счет контрагента не нужен, поэтому я валидатор не добалял"

**Comment by AlexeyTishkin** [comment]
Если нужен контроль - отдельный issue.
Этот закрываю.
