### ISSUE TITLE
Кнопка "друк" в отчетах

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#129]
[633](https://github.com/a2develop/bugTracker/issues/633)
Отчеты:
Добавил кнопку "друк" в отчеты:
Відомість за розрахунками з постачальниками
Відомість за розрахунками з постачальниками у валюті
Відомість за розрахунками з покупцями
Відомість за розрахунками з покупцями у валюті
Відомість за розрахунками з іншими дебіторами
Оборотна відомість по складу
Валовий прибуток
Оборотність запасів

Проверить печать.

**Comment by AndriyNesterenya** [comment]
На превьюхе не показывает правую границу
![image](https://user-images.githubusercontent.com/38098758/47956329-61528600-dfab-11e8-8598-fcdfee3f16e2.png)

**Comment by AlexeyTishkin** [comment]
Так это же печать html as is. Идеала не будет, дальше только играться настройками печати (ориентация, отступы и т.п.)

**Comment by AndriyNesterenya** [comment]
ЗЫ Там название нашей фирмы не нужно выводить?

**Comment by AlexeyTishkin** [comment]
Пока у нас одна "моя фирма" есть смысл ? Это же внутренний отчет.
Когда в тенанте будет больше одной фирмы, то тогда уже имеет смысл выводить.

**Comment by AndriyNesterenya** [comment]
Так я ж в будущее смотрю :)
Вроде как к этому дойдем довольно скоро.

По всем заявленным отчетам все ОК, кнопка есть и печатает.

**Comment by AlexeyTishkin** [comment]
> Вроде как к этому дойдем довольно скоро.

Ну да... По моему, даже в этом месяце... По этому поводу еще будет куча issue :)

**Comment by AlexeyTishkin** [comment]
> По всем заявленным отчетам все ОК, кнопка есть и печатает.

Ок. Тогда закрываю.
