### ISSUE TITLE
НН. Исправлена подстановка кода инспекции

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#13]
Необходимо проверить:
1. Податковий кредит. Отдельно созданная.
2. Податковий кредит. Созданная из счета.
3. Податкове зобов'язання. Отдельно созданная.
4. Податкове зобов'язання. Созданная из счета.

**Comment by kattrina-brekhova** [comment]
в налоговом кредите с "отдельно созданном" не активно поле для № плательщика ндс поставщика, и автоматически не подтягивает (на основе счета такой проблемы нету)
с налоговым обязательствомм тоже на деве все ок

**Comment by AlexeyTishkin** [comment]
Это в другое issue. Оно уже, кстати, есть.
