### ISSUE TITLE
Форма № Д4. Экспорт в XML основного отчета.

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#134]
Исправлен экспорт в XML.
Проверить экспорт в XML основного отчета + приложения.
Проверить импорт сформированных файлов в Сонату. В Сонате для файлов должен быть сформирован пакет.

**Comment by AlexeyTishkin** [comment]
Пока пауза. Еще вносятся изменения.

**Comment by Anestezia** [comment]
Как должен быть сформирован пакет? Они переданы отдельно, начиная от додатков и заканчивая головным документом, так в Сонате и есть, потом в Сонате уже вручную добавляем в пакет. 

П.С. У меня в отчете за месяц нет принятых, соответственно Дод.5 не заполнен. Я его удалила. В головном документе галочка при Дод.5 не установлена. При переносе в Сонату кнопкой "Отправить в Сонату" она там появилась.
![image](https://user-images.githubusercontent.com/42540074/48121800-8fbbb400-e27e-11e8-8e00-e215706c1850.png)

**Comment by AlexeyTishkin** [comment]
> Как должен быть сформирован пакет? Они переданы отдельно, начиная от додатков и заканчивая головным документом, так в Сонате и есть, потом в Сонате уже вручную добавляем в пакет.

Передача работает как и раньше, т.е. пакет не формирует.
А если сделать "Экспорт в XML" главного + приложения, а потом в Сонате импорт, то должен быть пакет.

**Comment by AlexeyTishkin** [comment]
> П.С. У меня в отчете за месяц нет принятых, соответственно Дод.5 не заполнен. Я его удалила. В головном документе галочка при Дод.5 не установлена. При переносе в Сонату кнопкой "Отправить в Сонату" она там появилась.

Еще вношу изменения. Сообщу когда будет окончательный вариант.

**Comment by AlexeyTishkin** [comment]
Изменения внесены. Можно проверять.

**Comment by Anestezia** [comment]
Експорт главного документа и дополнений работает как надо.  Лишний додаток в Сонате не показывает. Пакет формирует при специфическом моменте. Нужна мощная подсказка пользователю, что есть такая возможность и как именно ею воспользоваться.

**Comment by Anestezia** [comment]
С этим что?
https://github.com/a2develop/bugTracker/issues/489

**Comment by AlexeyTishkin** [comment]
> Пакет формирует при специфическом моменте

Что значит "специфический момент" ?

**Comment by AlexeyTishkin** [comment]
> Нужна мощная подсказка пользователю, что есть такая возможность и как именно ею воспользоваться.

В хелпе нужно описать два механизма подготовки отчетов.

**Comment by AlexeyTishkin** [comment]
> С этим что? a2develop/bugTracker#489

Это второй механизм. Он в разработке.

**Comment by AlexeyTishkin** [comment]
> Експорт главного документа и дополнений работает как надо. 

Этот issue закрываю.
