### ISSUE TITLE
Переименование пользователя

### ISSUE THREAD

**Issue by alex-kukhtin** [a2develop/testing#135]
https://github.com/a2develop/bugTracker/issues/513

Проверить, как работает.
И нужно проверить смену телефона и регистрацию. Я там глубоко залез - мог напортачить.

**Comment by AndriyNesterenya** [comment]
Переименование работает ОК.
Дятлы проходили полный цикл регистрации с подтверждением - проблем на обнаружено.

**Comment by AndriyNesterenya** [comment]
смена телефона тоже ОК
