### ISSUE TITLE
Декларация НДС. Экспорт в XML.

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#136]
Теперь при импорте файлов XML в Сонату они формируют пакет.
Проверить импорт в Сонату.

**Comment by Anestezia** [comment]
Пакет при действиях, аналогичных с импортом отчета по ЕСВ, не формируется.

**Comment by AlexeyTishkin** [comment]
Подробней. Файлы сформированы при помощи "Экспорт в XML" ?
На тестовом аккаунте это можно увидеть ?

**Comment by Anestezia** [comment]
Я на деве делала, вчера с есв так сработало. Каждый документ (Декл. + додатки 1 и 5) я сохранила в хмл, открыла сонату, и в одной сессии добавила все три файла. Они затянулись все три вместе, но в пакет не объединены

**Comment by Anestezia** [comment]
Уже все работает. Можно закрывать
