### ISSUE TITLE
Автоопределение кодировки dbf

### ISSUE THREAD

**Issue by alex-kukhtin** [a2develop/testing#138]
Нужно бы проверить.
[639] (https://github.com/a2develop/bugTracker/issues/639)

**Comment by AndriyNesterenya** [comment]
Это все еще касается только Привата?
Или чьи-то еще файлы понимаем уже?

**Comment by alex-kukhtin** [comment]
Пока только привата. Скоро будем еще понимать.

**Comment by AndriyNesterenya** [comment]
Мои Приватовские выписки в автокодировке хавает без проблем
Можно по умолчанию эту опцию назначать, думается
