### ISSUE TITLE
Форма документа "Налоговая накладная" 

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#139]
Сделана версия 10.
В связи с этим необходимо проверить старую версию (чтобы ничего не поломалось :) ):
1. Создание.
2. Редактирование.
3. Проведение.
4. Экспорт в XML.

Новая версия будет отображаться для документов, дата которых начинается с 01.12.2018.
Проверить:
1. Создание.
2. Наличие новых и отсутствие старых реквизитов.
3. Редактирование.
4. Проведение.
5. Экспорт в XML.

**Comment by Anestezia** [comment]
Что могла просмотрела, обсудили, остальное - это взаимодействие с Сонатой. В этом их обновлении тоже еще нет новых бланков НН и РК. Ждем.

**Comment by AlexeyTishkin** [comment]
Ок. Тогда это закрываю. Дальше - в рабочем порядке.
