### ISSUE TITLE
Форма документа "Расчет корректировки к налоговой накладной"

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#140]
Сделана версия 10.
В связи с этим необходимо проверить старую версию (чтобы ничего не поломалось :) ):
1. Создание.
2. Редактирование.
3. Проведение.
4. Экспорт в XML.

Новая версия будет отображаться для документов, дата которых начинается с 01.12.2018.
Проверить:
1. Создание.
2. Наличие новых и отсутствие старых реквизитов.
3. Редактирование.
4. Проведение.
5. Экспорт в XML.

**Comment by Anestezia** [comment]
Не нашла к чему придраться. 
Единственное, не поняла как заполняется графа 2.2. "номер з\п групи коригування" .Пояснений в инете не нашла.
