### ISSUE TITLE
Операция "Реалізація запасів". Печатная форма. Отображение длинного адреса

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#141]
[661](https://github.com/a2develop/bugTracker/issues/661)
Проверить отображение и печать.

**Comment by Anestezia** [comment]
Да, теперь лучше
![image](https://user-images.githubusercontent.com/42540074/48477097-60222400-e809-11e8-9cac-0f6a5a2c5460.png)
Но не все: сохранение в ПДФ барахлит
![image](https://user-images.githubusercontent.com/42540074/48477158-834cd380-e809-11e8-89dd-12540f18e2a8.png)

**Comment by AlexeyTishkin** [comment]
Исправил.

**Comment by Anestezia** [comment]
Все ок.
