### ISSUE TITLE
Вид склада

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#142]
У складов добавлено свойство "Вид". "Загальний склад" - обычный склад, использовался ранее. "Склад комітента", "Склад комісіонера" - используются в операциях, связанных с комиссионной торговлей.

Проверить создание, редактирование и отображения складов разных видов.

**Comment by AndriyNesterenya** [comment]
Пока гонял - создал два склада комиссионера через комиссионные же операции.
Лишний решил удалить через справочники - ошибка 
![image](https://user-images.githubusercontent.com/38098758/48677354-3310a100-eb7c-11e8-8a0d-8953fda76469.png)

![image](https://user-images.githubusercontent.com/38098758/48677361-4f144280-eb7c-11e8-9e19-283bcbfb8196.png)

**Comment by AndriyNesterenya** [comment]
... и непонятка №2
Теперь у нас признак "ОСНОВНОЙ" будет иметь один обычный склад и один склад типа "Склад комиссионера"?
Если по одному складу каждого типа - оба основные?

**Comment by AlexeyTishkin** [comment]
>  Лишний решил удалить через справочники - ошибка

Исправил.

**Comment by AlexeyTishkin** [comment]
> Теперь у нас признак "ОСНОВНОЙ" будет иметь один обычный склад и один склад типа "Склад комиссионера"?

Да.

> Если по одному складу каждого типа - оба основные?

Да. Основной внутри вида. Склады разных видов в одном свойстве документа пересекаться не могут.

**Comment by AndriyNesterenya** [comment]
При создании из справочника первого "Склада коммитента" при наличии "Склада комиссионера" автоматом не ставится признак Основной.
В остальном работает

**Comment by AlexeyTishkin** [comment]
> При создании из справочника первого "Склада коммитента" при наличии "Склада комиссионера" автоматом не ставится признак Основной.

Такого функционала нет. Основной - только вручную. Если нужен - отдельный issue.

**Comment by AlexeyTishkin** [comment]
> В остальном работает

Тогда закрываю.
