### ISSUE TITLE
Операция "Отримання товарів від комітента"

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#143]
[662](https://github.com/a2develop/bugTracker/issues/662)

Проверить создание, редактирование, проведение.
Склад должен выбираться из складов вида "Склад комісіонера".

**Comment by AlexeyTishkin** [comment]
Объекты должны выбираться из объектов вида "Товар".

**Comment by MaksymTikhomirov** [comment]
Отлично
Услуги когда будешь запиливать?

**Comment by AndriyNesterenya** [comment]
Отримує аж бігом.
Только при попытке продать - показывает весь товар, с основного склада + со склада комиссионера.

**Comment by AlexeyTishkin** [comment]
> Только при попытке продать - показывает весь товар, с основного склада + со склада комиссионера.

Диалог выбора везде показывает полный перечень. Есть колонка "Остаток", она заполняется по конкретному складу.
По поводу отображения только того, что есть на остатке - уже есть отдельный issue.
