### ISSUE TITLE
Операция "Придбання матеріальних активів"

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#144]
Проверить создание, редактирование, проведение.
В связи с добавление новой операции для формы "Приходная накладная" проверить, чтобы ничего не поломалось :)

**Comment by AndriyNesterenya** [comment]
Не формирует Придбання из счета
В Оплате по банку желтая кнопка Отправить в банк (при настроенном АПИ) выдает ошибку "Object reference not set to an instance of an object."
![image](https://user-images.githubusercontent.com/38098758/48900006-d6ea9d00-ee59-11e8-8b23-08b90f4e10e1.png)

**Comment by AlexeyTishkin** [comment]
> Не формирует Придбання из счета

По Необоротным активам ? Это отдельное issue, к тому же относится к счету.

**Comment by AlexeyTishkin** [comment]
> В Оплате по банку желтая кнопка Отправить в банк

Это точно не сюда :)
