### ISSUE TITLE
Персонал. Зарплатные проекты

### ISSUE THREAD

**Issue by Illya-Lykhachov** [a2develop/testing#147]
Нужно проверить создание и заполнение договоров на обслуживание карточных счетов сотрудников. Важно: карточные счета это счета в банках физических лиц.

**Comment by Anestezia** [comment]
Не получается. Ввела данные по одному банку, поставила договор основной, ввела второй договор, в первом данные сотрудников слетели
![image](https://user-images.githubusercontent.com/42540074/48711881-052b6b00-ec15-11e8-92e9-9af797f0c9e8.png)
Попереставляла знак основного договора, и из второго договора тоже данные сотрудников слетели. Может Основной и не при чем совсем.

**Comment by Anestezia** [comment]
1. Система не терпит двух договоров. Один слетает.
2. Не терпит перемещения знака основного договора, тоже слетает.

**Comment by Illya-Lykhachov** [comment]
Исправлено

**Comment by Anestezia** [comment]
Не сохраняет изменений при нажатии на "зберегти та закрити". Я обновляла. 
![image](https://user-images.githubusercontent.com/42540074/48763941-08773300-ecb7-11e8-8b1d-aa2f44e1fbc6.png)

**Comment by Anestezia** [comment]
Теперь не конфликтуют два договора, но небольшая деталь: при изменениях в списке операций пропадает названия банка, помогает, если за значок отбора по банку дернуть, притом неважно в какую сторону.
![image](https://user-images.githubusercontent.com/42540074/48780429-8bfa4980-ece2-11e8-93f9-6d94d2fef792.png)

**Comment by Illya-Lykhachov** [comment]
Это я изменил. Нужно просто сохранить договоры один раз
