### ISSUE TITLE
Операция "Передача товарів комісіонеру"

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#148]
[662](https://github.com/a2develop/bugTracker/issues/662)

Проверить создание, редактирование, проведение.
Склад должен выбираться из складов вида "Загальний склад". Это склад, с которого мы передаем товары на комиссию.
Склад комитента должен выбираться из складов вида "Склад комітента". Это склад, на котором мы учитываем товар до момента отчета комиссионера.
Объекты должны выбираться из объектов вида "Товар".

**Comment by AndriyNesterenya** [comment]
За последние дни косяков не обнаружено
