### ISSUE TITLE
Операция "Звіт комітенту"

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#149]
[662](https://github.com/a2develop/bugTracker/issues/662)

Пока только рабочая форма.
Проверить создание, редактирование, проведение.

**Comment by AndriyNesterenya** [comment]
Поймал в один момент ошибку
Method not found: 'Void A2v10.Infrastructure.DynamicHelpers.AppendIfNotExists(System.Dynamic.ExpandoObject, System.Dynamic.ExpandoObject)'.
Появилась при попытке выборе контрагента 

Расшифровку думал скопипастить на повторе - не могу пока повторить.

**Comment by AlexeyTishkin** [comment]
> Появилась при попытке выборе контрагента

Странно, выбор контрагента там такой же как и в остальных формах (приходная, расходная и др).

**Comment by AndriyNesterenya** [comment]
Повторить так и не удалось.
Считаем, что это из области полтергейста.
