### ISSUE TITLE
Доработан отчет неприбыльной организации

### ISSUE THREAD

**Issue by shevchuk-vadim** [a2develop/testing#150]
1. Сделано редактируемым поле "Дата подання". Проверить,чтобы в XML его корректное значение попадало в DECLARHEAD.D_FILL и DACLARBODY.HFILL.
2. Добавлена возможность выбирать налоговую инспекцию. Проверить,чтобы в XML код выбранной налоговой инспекции попадал в DECLARHEAD..C_STI_ORIG.
3. Добавлено поле для ввода номера нового отчетного или уточняющего документа. Проверить,чтобы в XML он попадал в DECLARHEAD..C_DOC_TYPE.
4. Добавлена возможность задавать уточняемый отчетный период. Проверить,чтобы в XML данные по нему попадали в DACLARBODY.HZYP и (DACLARBODY.HZMP или DACLARBODY.HYP).
5. Проверить работу контроля корректности года и месяца в отчетном и уточняемом отчетном периоде.
6. Проверить, чтобы при заполнении не портились значения в заголовке отчета (по налоговую инспекцию включительно) и нижней части (начиная с наличия приложений).

**Comment by Anestezia** [comment]
По строкам все в таком порядке, как описано. п.1-4. 
п.5 Корректная проверка периода.
п.6 без изменений.

п.с. В Сонату не переносится период отчетности и уточнения  - месяц.
