### ISSUE TITLE
Доработан диалог создания фискального отчета

### ISSUE THREAD

**Issue by shevchuk-vadim** [a2develop/testing#151]
Если выбрать бланк отчета о неприбыльной организации, то период внизу диалога должен автоматически установиться в "Рік". Раньше надо был устанавливать его вручную.

**Comment by Anestezia** [comment]
Да, ставится автоматически год. И только год, месяц исчез. уже внутри можно исправить, но Соната его все равно не воспринимает, если за месяц сделан отчет или уточняющий.
