### ISSUE TITLE
Добавлено приложение ГД к отчету неприбыльной организации

### ISSUE THREAD

**Issue by shevchuk-vadim** [a2develop/testing#152]
Проверить:
1. Приложение может создваться только их непроведенного отчета.
2. Отменить проведение приложения нельзя, если отчет проведенный.
3. Данные из таблиц приложения 1-5 идут в XML.
4. Данные в заголовке и подписях приложения не радактируемые и копируются из отчета при создании приложения и сохранении отчета. При этом также формируются разделы LINKED_DOCS в приложении и отчете.

**Comment by Anestezia** [comment]
1. есть такое.
2. все верно, не проводится.
3. идут. нет кнопки Відправити в Сонату. Так и надо?
4. Данные в заголовке не редактируются. Табличные части редактируются.
Ждем подтягивания данных о контролирующем органе
