### ISSUE TITLE
Создании нового тенанта. "Кінцевий споживач".

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#154]
[689](https://github.com/a2develop/bugTracker/issues/689)
При создании нового тенанта контрагент "Кінцевий споживач" теперь не создается. Проверить создание нового тенанта.

**Comment by mik-man** [comment]
Проверено. Мин нет.
(правда в Контрагентах и Договорах нет стрелочки-подсказки, но это уже совсем другой ишью)
