### ISSUE TITLE
Операция "Отримання рахунку". Создание связанных.

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#155]
[687](https://github.com/a2develop/bugTracker/issues/687)
Варианты:
1. В счете только товары.
2. В счете только услуги.
3. В счете только необоротные активы.
4. В счете товары, услуги и необоротные активы.

Проверить создание операции "Придбання", "Податковий кредит".
В случае, если в счете есть услуги, то для них должна быть создана отдельная операция "Придбання послуг".
В операцию "Податковий кредит" должны попасть все объекты.

**Comment by Anestezia** [comment]
Все создается, только несколько странно. 
По отдельности вообще все ок. 
Когда все вместе или товар и услуга в одном, то сначала мы видим 1 документ створити придбання. Нажимаем, открывается акт услуг. Проводим, закрываем, оказывается уже создан документ приходная накладная, он уже показывается в счете в списке документов по приходу во второй строке (до этого была одна строка и предлагалось создать 1 документ). Открываем, проводим. Вроде я видела в выставленном счете сразу с товарами и услугами сразу предлагалось создать 2 документа, акт и накладную.

Странность №2: Есть у нас объект учета. В моем случае ОС, в карточке которого не указан НДС. Мы вписываем его в счет вместе с остальными позициями, ставка пдв но нему отсутствует, в счете же в этой таблице выбираем 20%, проводим. Создаем на основании приходную накладную, ставка пдв 20% есть. А вот при создании Налоговой накладной в этой позиции пдв нет. Выход = открыть карточку товара (справочник объектов учета) и внести пдв туда.

А вообще все работает.

**Comment by AlexeyTishkin** [comment]
> Вроде я видела в выставленном счете сразу с товарами и услугами сразу предлагалось создать 2 документа, акт и накладную.

Такого никогда не было.

> до этого была одна строка и предлагалось создать 1 документ

Предлагается создать не документ,а операцию "Придбання". И это всегда одна строка.

**Comment by AlexeyTishkin** [comment]
> Когда все вместе или товар и услуга в одном, то сначала мы видим 1 документ створити придбання. 

В одном окне нельзя показать два документа, поэтому если создается два, то показывается последний созданный. В родительском документе на taskpad показываются все связанные.

**Comment by AlexeyTishkin** [comment]
> А вообще все работает.

Тогда закрываю.
