### ISSUE TITLE
Изменена процедура списания с/с запасов

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#156]
Проверить списание с/с в нескольких операциях, как минимум:
1. Переміщення.
2. Реалізація запасів.

**Comment by Anestezia** [comment]
1. Приобрели 1 шт 26.11 по 3 грн.
2. Приобрели 1 шт 27.11 по 6 грн.
3. Переместили 2 шт 28.11 на другой склад. В проводках должны быть партии 26.11 по 3 грн, 27.11 по 6 грн.
4. Реализовали 1 шт 29.11 В проводках должна быть партия 26.11 по 3 грн.

![image](https://user-images.githubusercontent.com/42540074/49142865-6da7d580-f302-11e8-9ed9-4474fdf65021.png)

![image](https://user-images.githubusercontent.com/42540074/49142889-78fb0100-f302-11e8-8de4-504f4e6e9ce4.png)
