### ISSUE TITLE
Операция "Звіт комісіонера"

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#157]
[662](https://github.com/a2develop/bugTracker/issues/662)

Пока только рабочая форма.
Проверить создание, редактирование, проведение.

**Comment by Anestezia** [comment]
Вопрос 1: разве должен подставляться для выбора список Постачальников?
![image](https://user-images.githubusercontent.com/42540074/49144754-ce391180-f306-11e8-98df-9aea1355334a.png)

2. У меня на складе комиссионера только один товар, а тут показывается несколько, притом, только товары и услуги. А ведь готовая продукция может тоже передаваться для реализации на комиссии?
![image](https://user-images.githubusercontent.com/42540074/49144970-5c14fc80-f307-11e8-9cb7-c9379f39f182.png)

3. Странный выбор склада внутри при подборе объекта учета, по умолчанию в выборе по складу стоит склад комитента. Если нажать  выбор склада, в списке отображаются только другие склады, кроме склада комитента.
![image](https://user-images.githubusercontent.com/42540074/49146375-b5caf600-f30a-11e8-90fe-826016aeadd6.png)

**Comment by AlexeyTishkin** [comment]
> Вопрос 1: разве должен подставляться для выбора список Постачальников?

А кем для нас (комиссионера) является комитент ?

**Comment by AlexeyTishkin** [comment]
> У меня на складе комиссионера только один товар, а тут показывается несколько,

Показывается весь ассортимент из справочника + колонка "Остаток". Функционала "отобразить только то, что есть на остатке" еще нет.

> притом, только товары и услуги. А ведь готовая продукция может тоже передаваться для реализации на комиссии?

Здесь [описание](https://docs.google.com/document/d/1uC7NuE5Cn9zej8W302NCIK-t5wjof3yQAscB63MnlHU/edit) речь идет только о товарах и услугах. Кроме того, фигурирует 283 счет, а это "товары на комиссии".

**Comment by AlexeyTishkin** [comment]
>> Вопрос 1: разве должен подставляться для выбора список Постачальников?

> А кем для нас (комиссионера) является комитент ?

Перепутал операции. Должен быть покупатель. Переделаю.

**Comment by AlexeyTishkin** [comment]
> Вопрос 1: разве должен подставляться для выбора список Постачальников?

Изменил на покупателей.

**Comment by AlexeyTishkin** [comment]
> Странный выбор склада внутри при подборе объекта учета, по умолчанию в выборе по складу стоит склад комитента. Если нажать выбор склада, в списке отображаются только другие склады, кроме склада комитента.

Исправил.

**Comment by Anestezia** [comment]
ок, проверила. Товары левые с других складов должны быть в списке все равно, если у нас выбран определенный склад комитента (я его у себя так назвала)?

**Comment by AlexeyTishkin** [comment]
> Товары левые с других складов должны быть в списке все равно, если у нас выбран определенный склад комитента (я его у себя так назвала)?

Они не левые :) они из справочника. В колонке остаток у них пусто. Нет еще функционала "отобразить только то, что на остатках". По этому поводу есть отдельный issue.

**Comment by AlexeyTishkin** [comment]
> ок, проверила.

Тогда закрываю.
