### ISSUE TITLE
Персонал. Посади.

### ISSUE THREAD

**Issue by mik-man** [a2develop/testing#158]
- [x] Проверить установку счетов отнесения затрат в диалоге "Посади".
- [x] В расчете заплаты проверить правильность установки счетов отнесения затрат при проведении документа в учёте.

Перенесено из: https://github.com/a2develop/bugTracker/issues/691

**Comment by Anestezia** [comment]
Счета затрат по каждой должности выставляются, к изначальным 91,92,93 добавлен счет 23. По зп ведомостям отображается корректно по каждому сотруднику. В ОСВ за период закрываются счета 91,92,93. Счет 23 для закрытия ждет отдельной операции.

**Comment by mik-man** [comment]
Т.е. все хорошо и правильно? )) Можно закрывать?

**Comment by Anestezia** [comment]
да. претензий нет.
