### ISSUE TITLE
Операция "Звіт комітенту". Печатная форма

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#159]
[662](https://github.com/a2develop/bugTracker/issues/662)
Добавлена печатная форма. Проверить печать.
Пример взят отсюда: [Бланк](https://uteka.ua/ua/publication/commerce-12-dokumentooborot-2-dogovor-komissii-oformlyaem-otchet-komissionera).

**Comment by AndriyNesterenya** [comment]
Поймал в один момент ошибку 
Method not found: 'Void A2v10.Infrastructure.DynamicHelpers.AppendIfNotExists(System.Dynamic.ExpandoObject, System.Dynamic.ExpandoObject)'.
Расшифровку думал скопипастить на повторе - не могу пока повторить.

Не очень понимаю смысл отчета - заполняем вручную из головы что продалось?
Автоматом ничего не подтянулось.
На печати чуток косячит:
![image](https://user-images.githubusercontent.com/38098758/49039405-4fd65580-f1c8-11e8-88e9-5054dae9dcdb.png)
если галку "комиссия удерживается" поставлена - на печати все равно
![image](https://user-images.githubusercontent.com/38098758/49039466-81e7b780-f1c8-11e8-9ae1-a864522d56cd.png)

**Comment by AlexeyTishkin** [comment]
> Не очень понимаю смысл отчета - заполняем вручную из головы что продалось?

На данном этапе - вручную.
Потом можно будет добавить заполнение на основе "Реализации, принятых на комиссию". С заполнение не совсем понятно с услугами. Мы для услуг не делаем отдельную операцию.
Можешь написать отдельный issue для заполнения.

**Comment by AlexeyTishkin** [comment]
> если галку "комиссия удерживается" поставлена - на печати все равно

Не понял. Что с итогом не так ?
Если по поводу 39 грн и 221 грн, то на печати они расшифрованы в п. 3 и 4. В рабочей форме краткий итог, в печатной - полный.

**Comment by AndriyNesterenya** [comment]
Да, в этом и вопрос был - цифры разные в документе и на печати
Если так и надо - то и ОК

**Comment by AlexeyTishkin** [comment]
> Да, в этом и вопрос был - цифры разные в документе и на печати

Почему разные ?
В рабочей (в таблице): Разом = 260, В печатной (в таблице): Разом = 260, ПДВ = 0, Всього = 260.
В рабочей (в таблице): Винагорода = 39. В печатной (после таблицы, п. 3) Винагорода = 339.
В рабочей (в таблице): Підлягає перерахуванню = 221, В печатной (после таблицы, п. 4) Підлягає перерахуванню = 221.
В печатной итог не ограничивается таблицей.

**Comment by AndriyNesterenya** [comment]
Явных косяков не обнаружено
