### ISSUE TITLE
Ссылка на help в сервисе (сделано)

### ISSUE THREAD

**Issue by alex-kukhtin** [a2develop/testing#16]
https://github.com/a2develop/bugTracker/issues/484

**Comment by DenisClone** [comment]
На странице входа и странице регистрации по прежнему ссылка на домен bookkeepertech

**Comment by alex-kukhtin** [comment]
Ты на чем смотришь? На бете еще не публиковали

**Comment by DenisClone** [comment]
Точно! Вопрос снимается :)
