### ISSUE TITLE
Акт приема-передачи нематериальных активов #676

### ISSUE THREAD

**Issue by htrofymova** [a2develop/testing#160]
https://github.com/a2develop/bugTracker/issues/676
Новая форма. Операция: НА - Придбання об`єктів нематеріальних активів. 
Проверить: создание,  сохранение,  проведение.

**Comment by Anestezia** [comment]
Нет печати, не активна кнопка, даже после проведения. В остальном вопросов нет. в ОСВ идет.

**Comment by Anestezia** [comment]
Друк не виправлено.

**Comment by Anestezia** [comment]
Возможно задать один  и тот же номер документа на одинаковую дату двум отдельным документам
![image](https://user-images.githubusercontent.com/42540074/49222160-cb601e80-f3e3-11e8-8eb3-94c2f25412c7.png)

**Comment by htrofymova** [comment]
.Добавлена печать, пожалуйста, проверьте. Одинаковые номера - повторить не могу.
