### ISSUE TITLE
Формы "Налоговая накладная", "Расчет корректировки к НН". Поле "Дата реєстрації".

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#161]
В формы "Налоговая накладная", "Расчет корректировки к НН" добавлено поле "Дата реєстрації". Эта дата нужна в случае, когда дата документа в периоде действия старой формы (до 01.12.2018), а регистрироваться в реестре будет в период действия новой формы (после 01.12.2018).
Проверить правильность отображения старой/новой форм в зависимости от дат документа/регистрации.

**Comment by Anestezia** [comment]
Вроде все ок. 

Только в РК есть небольшой глючок. Ввожу его старой формой, ставлю код причины корректировки, меняю дату регистрации наперед, и код причины слетает. Если его снова ввести вручную, а потом вернуть дату регистрации на ноябрь, то он остается. Попереклацивать форму туда-сюда между новым и старым бланком, остается в обе стороны. Только при первом переключении исчезает.

**Comment by AlexeyTishkin** [comment]
> ставлю код причины корректировки, 

Это в таблице с номенклатурой ? В новой форме колонка 2.1 ? Так в старой форме такой нет. В старой "Причина коригування" и она не соответствует ни одной из новых.

**Comment by AlexeyTishkin** [comment]
![image](https://user-images.githubusercontent.com/35917940/49156717-b2456800-f326-11e8-8421-a99d3725dddb.png)

**Comment by AlexeyTishkin** [comment]
![image](https://user-images.githubusercontent.com/35917940/49156757-cdb07300-f326-11e8-92e1-7a4eed9c312b.png)

**Comment by Anestezia** [comment]
тогда закрываем, филиалы переносятся куда надо, код ипн подставляется при переходе на новую, галочка Зведеной ПН превращается в поле для введения кода причины "Зведення". Все ок.
