### ISSUE TITLE
Должности. Счета затрат

### ISSUE THREAD

**Issue by Illya-Lykhachov** [a2develop/testing#162]
В свойствах должности теперь можно установить счёт отнесения затрат. Этот счёт используется при формировании проводок начисления зарплаты и взноса в ЕФСС.

**Comment by Anestezia** [comment]
Судя по тестированию все работает, ведомость формирует проводки, 91.92,93 - закрываются сразу. 23 - нужен для закрытия счета отдельный документ. 

В хелпе обязательно нужно прописать о возможности устанавливать счет затрат в должностях!!!

**Comment by kattrina-brekhova** [comment]
приняла
