### ISSUE TITLE
Необоротные активы. Новые операции.

### ISSUE THREAD

**Issue by htrofymova** [a2develop/testing#163]
Новые операции: Вибуття (ліквідація) необоротних активів,
                               Переміщення .... для продажу,
                               Переміщення ... для тимчасового вибуття,
                               Введення в господарський оборот НА.
проверить создание, сохранение, проведение.

**Comment by Anestezia** [comment]
1) Вибуття: а можно проводки расположить по порядку? Мы где-то так делали. Удобнее для восприятия пользователям. И операции нумеровали. Нет печати документов.
1.Дебет 133
кредит 127
2.Дебет 976
кредит 127
2) Переміщення .... для продажу - По проводкам и отсутствия печати документов то же самое.
![image](https://user-images.githubusercontent.com/42540074/49213310-af9d4e00-f3cc-11e8-8bee-c75a737aaed9.png)
Нужно указывать склад и МВО и те, на которых в данный момент находится объект учета и те, куда передается. 
Например, у меня был объект на основном складе и числился на МВО Тишкин А. На следующий день я перевела на склад Витрина на МВО Тихомиров М. 
![image](https://user-images.githubusercontent.com/42540074/49213488-1d497a00-f3cd-11e8-925a-b06dce9e6b74.png)
А в проводках получается, что с списалось не с Тишкина, а с Тихомирова. А что с него вообще могло списаться? Должно было прибыть на его склад. Там тоже нужно добавить аналитики на двух персон. На вкладке Необорот. активы в проводках.
![image](https://user-images.githubusercontent.com/42540074/49213605-541f9000-f3cd-11e8-80a1-49dbeee22102.png)

**Comment by mik-man** [comment]
Отличные пожелания.
Вопрос: создание, сохранение и проведение работает для этих документов? :)

**Comment by htrofymova** [comment]
Путаница, в общем-то. Все не совсем так. 
1. На самом деле, сущность "склад"  не есть сущность "подразделение", а есть "склад оборотных активов" (товаров, сырья и проч.). Поэтому необоротные активы учитываются только по МОЛ. 
2. Операции для передачи с Тишкина на Тихомирова (простого внутреннего перемещения) пока не существует. 
3. Вывод для продажи "преобразует" необоротный актив в необоротный актив для продажи (т.о. приравнивает его к обортным активам),  исчезает МОЛ и появляется Склад. 
В остальном:
- Контроль остатков исправлен.
- Проводки упорядочены.
- Печать дорисовывается.
