### ISSUE TITLE
В диалоге свойств договора добавлен вид договора

### ISSUE THREAD

**Issue by shevchuk-vadim** [a2develop/testing#167]
Для договора комиссии на вкладе "Умови" добавлены поля для процента вознаграждения и признака удержания вознаграждения из выручки.

**Comment by Anestezia** [comment]
Поля есть. Работает. 

Вопрос, при подборе этого комиссионера и его договора в Отчете комиссионера, должны ли из договора подставляться данные о проценте вознаграждения и признаке удержания вознаграждения из выручки?

**Comment by AlexeyTishkin** [comment]
Сейчас не должны. Это надо делать.

**Comment by AlexeyTishkin** [comment]
> при подборе этого комиссионера и его договора в Отчете комиссионера, должны ли из договора подставляться данные о проценте вознаграждения и признаке удержания вознаграждения из выручки

Теперь должны.

**Comment by Anestezia** [comment]
Странно, у меня пока не подставляется.

**Comment by AlexeyTishkin** [comment]
Тестовый аккаунт. При выборе договора "Комиссии"в "Звітах..." подставляется % вознаграждения.

**Comment by Anestezia** [comment]
Сделала по одному человеку два договора комиссии. Поставила на одном из них значок "Основний". Выбираю человека в Отчете комиссионера, договор (назначенный основным) подтягивается, а данные по проценту - нет. Вручную меняю договор на второй оставшийся - данные подтягиваются. снова меняю договор на первый (назначенный основным) - данные подтягиваются. Данные по проценту не подтягиваются при отметке на договоре "Основной" автоматически. Только после вмешательства. Притом, если назначен основной договор, сам он подтянулся в окошко Договор, а данные по нему нет, то если вручную кликнуть в выборе снова же по нему, то данные не подтягиваются. Нужно сменить договор, а потом снова выбрать нужный, тогда подтягиваются по обоим договорам.

**Comment by Anestezia** [comment]
При попытке удалить договор прямо из Документа отчета выдает ошибку 
![image](https://user-images.githubusercontent.com/42540074/49437839-4438ef00-f7c5-11e8-8ab1-ec27318ab871.png)

**Comment by Anestezia** [comment]
Один из договоров удалила, на единственном оставшемся установлен признак "Основной". Договор подтягивается при выборе контрагента, данные по проценту нет. Обновить через второй договор теперь нет возможности. Если убрать признак основного, то при выборе контрагента договор не подтягивается, можно его выбрать вручную и тогда данные про процент тоже подтягиваются. Эти операции в Документе Звіт комісіонера. Тот же принцип и в Отчете коммитента.

**Comment by AlexeyTishkin** [comment]
Исправил подстановку вознаграждения из договора, который загружается автоматически при выборе контрагента (основной договор).

**Comment by Anestezia** [comment]
Да, есть. Можно закрывать
