### ISSUE TITLE
Операция "Бухгалтерська довідка"

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#168]
[657](https://github.com/a2develop/bugTracker/issues/657)
Первая версия. Проверить создание, изменение, проведение. Отображение в отчетах.
Если какой-то счет отсутсвует в выборе или для счета не доступен выбор контрагента или договора - написать отдельный issue (это будет относится к плану счетов).

**Comment by Anestezia** [comment]
Вроде все работает, подставляются счета двумя способами, док. проводится, отменяется, по свойствам счетов вопросы с подстановкой контрагентов, где именно и что нужно, а где подстановка и должна быть неактивной. В ОСВ отображаются суммы. Редактируется. У меня претензий к документу нет. Есть небольшая опечатка в названии счета 685.
