### ISSUE TITLE
В документах выбор договора ограничен одним видом

### ISSUE THREAD

**Issue by shevchuk-vadim** [a2develop/testing#170]
Проверить выбор договора клавиатурой и из списка. По умолчанию во всех операциях вид договора "Загальний договір". В операциях перечисления денег комитенту и получения денег от комиссионера - "Договір комісії".
В заголовке диалога выбора договора написан вид договоров.
При создании договора из диалога выбора вид должен подставляться автосматически и его нельзя изменить. При создании договора из справочника вид изменить можно. При редактировании свойств существующего договора менять вид запрещено.

**Comment by AlexeyTishkin** [comment]
В операцих "Отримання товарів від комітенту", "Передача товарів комісіонеру", "Звіт комітенту", "Звіт комісіонера" установлен вид договора "Договір комісії".

**Comment by Anestezia** [comment]
Протестировала, к чему придраться не нашла. Все ок, по-моему.
