### ISSUE TITLE
Добавлены операции по выдаче и получению краткосрочной финансовой помощи по счетам в банках

### ISSUE THREAD

**Issue by shevchuk-vadim** [a2develop/testing#171]
Проверить 4 операции одновременно с отчетами по прочим дебиторам и кредиторам.

**Comment by Anestezia** [comment]
Проверила, придраться не к чему, кроме самой ведомости по кредиторам (с ней что-то не в порядке, не раскрывается). Сами суммы в ведомостях отражаются.
