### ISSUE TITLE
В документах разделов "Придбання", "Продажі", "Запаси" добавлена возможность заполнения списком объектов учета

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#172]
[707](https://github.com/a2develop/bugTracker/issues/707)
Проверить заполнение.

**Comment by Anestezia** [comment]
Может, со временем и в Виготовлення добавить во второй таблице материалов? В остальных все ок.

**Comment by AlexeyTishkin** [comment]
> Может, со временем и в Виготовлення добавить во второй таблице материалов?

Да, позже. Там специфический документ (две таблицы).

**Comment by AlexeyTishkin** [comment]
> В остальных все ок.

Тогда закрываю.
