### ISSUE TITLE
Новый отчёт в "Звітність" J3001001 и F3001001

### ISSUE THREAD

**Issue by alexeijur** [a2develop/testing#173]
Проверить работоспособность и экспорт в Сонату.

**Comment by mik-man** [comment]
Где их можно увидеть?

**Comment by alexeijur** [comment]
Забыл накатить скрипт. Уже есть в списке отчётов при создании.

**Comment by Anestezia** [comment]
Да, уже все нормально, номер приказа подтягивается. Проверка в Сонате нормально проходит, только с периодом подачи человек должен разобраться. Ссылка на документ-основание еще недоступна.

**Comment by alexeijur** [comment]
Ссылок на документы там и не предполагалось. 
Там я ещё внёс изменения.
