### ISSUE TITLE
Персонал. Зарплатні проекти.

### ISSUE THREAD

**Issue by alexeijur** [a2develop/testing#174]
Проверить контроль повторного карточного счёта в документе.

**Comment by AndriyNesterenya** [comment]
... если можно - чуток развернуть, как для человеков, не являющихся бухгалтерами :)

**Comment by alexeijur** [comment]
В документе (договоре) "Зарплатні проекти" при вводе повторяющегося значения в поле "Картковий рахунок" должен ругаться на повтор и не сохранять.

**Comment by AndriyNesterenya** [comment]
Таки ругается - уже проверяли :)
