### ISSUE TITLE
Всплывающее окно "Ціни"

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#175]
1. Добавлена информация о ценах приобретения: таблица "Придбання" с колонками "Склад", "Дата", "Залишок", "Ціна". Проверить отображение информации.
2. Диалог выбора объектов учета в документах. При клике на значении цены должно показаться всплывающее окно "Ціни".

**Comment by AndriyNesterenya** [comment]
Проверяли. 
Если на основе прихода делать прайсы - таки работает :)
