### ISSUE TITLE
Добавлен вид расчетного счета моей фирмы

### ISSUE THREAD

**Issue by shevchuk-vadim** [a2develop/testing#176]
Проверить установку вида счета в диалоге свойств счета, диалоге свойств и мастере создания моей фирмы.
Проверить подставновку 311 - 315 или 321 - 316 счетов в проводки платежных поручений в зависимости от вида счета моей фирмы.

**Comment by AndriyNesterenya** [comment]
Селектор вида счета наблюдаю.

Есть какие-то ограничения на работу со спецсчетами?
Что еще по этому поводу проверить?

**Comment by Anestezia** [comment]
311-315 работает.

**Comment by shevchuk-vadim** [comment]
Нужно еще раз проверить подстановку счетов 315 и 316. Теперь они подставляются, если код счета моей фирмы начинается с 2604 или 3751.

**Comment by shevchuk-vadim** [comment]
Поле вида счета удалено в диалоге свойств счета, диалоге свойств и мастере создания моей фирмы. Проверить работоспособность диалогов.

**Comment by AndriyNesterenya** [comment]
Пока еще не удалено
![image](https://user-images.githubusercontent.com/38098758/49877856-ff4d3200-fe2e-11e8-8729-a6878bccd917.png)

**Comment by AndriyNesterenya** [comment]
Вижу, исчезло.
По созданию и работе со счетами прошлись - без замечаний пока.

**Comment by AndriyNesterenya** [comment]
Для протокола из Fast Issues
![image](https://user-images.githubusercontent.com/38098758/49886376-23663e80-fe42-11e8-87bb-8f618a6ab352.png)

**Comment by AndriyNesterenya** [comment]
Победили вроде бы
