### ISSUE TITLE
Добавлен "Додаток ВП" в отчет неприбыльной организации.

### ISSUE THREAD

**Issue by mik-man** [a2develop/testing#177]
Проверить создание, редактирование, сохранение, проведение, выгрузку в XML-файл, в Сонанту и удаление. Сам отчет заполняется вручную.

**Comment by AndriyNesterenya** [comment]
Пробовал сотворить неприбульную организацию.
Данные гуглил.

Создается, заполняется, сохраняется, проводится нормально.
При экспорте отчета - ошибка
The element 'LINKED_DOCS' has incomplete content. List of possible elements expected: 'DOC'.

Свежесозданная контора с нулевыми показателями.

**Comment by AndriyNesterenya** [comment]
Галку ВП наблюдаю неактивную.
Чего ей нужно для работы?

**Comment by mik-man** [comment]
Там обновилось немного. Можно проверить еще раз.
Галка ВП взводится сама, когда создаешь додаток ВП.

**Comment by AndriyNesterenya** [comment]
Уже поправлено.
Без додатков экспортируется нормально.
Додатки формируются оба.
С додатками экспортируется нормально.

**Comment by Anestezia** [comment]
> Уже поправлено.
> Без додатков экспортируется нормально.
> Додатки формируются оба.
> С додатками экспортируется нормально.

Еще не поправлено. Созданный с нуля одиночный отчет главный без додатков не экспортируется. Если создать хоть один додаток, даже не заполняя и не проводя, а потом его удалить - тогда экспорт выполняется нормально.

**Comment by mik-man** [comment]
Теперь точно поправлено.

**Comment by Anestezia** [comment]
Как по мне, то все работает.
