### ISSUE TITLE
Удаление "Платежного поручения", которое выбрано в строке "Банковской выписки"

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#180]
[722](https://github.com/a2develop/bugTracker/issues/722)
Проверить отображение корректного сообщения.

**Comment by Anestezia** [comment]
есть сообщение нормальное. 
![image](https://user-images.githubusercontent.com/42540074/49863974-1f1e2f00-fe0a-11e8-97a1-1b404e675284.png)
