### ISSUE TITLE
Персонал. Робочий час.  Відпустка без збереження заробітної плати

### ISSUE THREAD

**Issue by alexeijur** [a2develop/testing#182]
Прошу проверить документ и возможность его печати и печати обычного отпуска.

**Comment by Illya-Lykhachov** [comment]
Связанное с этим изменением issue https://github.com/a2develop/bugTracker/issues/540

**Comment by Anestezia** [comment]
Ну, я смотрела, все работает. Валидаторы дат ловят разные ситуации, все норм. Вопрос учета дней отпуска, которые рассчитываются автоматически. У нас написано насчет дат (у т.ч.) В моем примере: приказ от 18.12., отпуск от 02.01 по 08.01 (у т.ч.) То есть должно быть 7 к.д. отпуска
![image](https://user-images.githubusercontent.com/42540074/50143550-9c87ea80-02b5-11e9-9256-b2136d41d570.png)
А фиксируется в приказе 6 дней.
![image](https://user-images.githubusercontent.com/42540074/50143575-ac9fca00-02b5-11e9-9135-930ad4f7a058.png)

**Comment by Illya-Lykhachov** [comment]
Неправильно считаются дни в печатной форме

**Comment by alexeijur** [comment]
Поправил.

**Comment by Anestezia** [comment]
Да, в печатной форме поправлено, подтверждаю. Вопрос № 2: В Расчетной ведомости этот отпуск в графе отпуска не учитывается, говорят, что это правильно, так как мы не платим. А вот отображение количества отработанных дней считается у нас без учета календаря, по схеме 22 рабочих дня минус 9 календарных дней отпуска. = 13 рабочих, хотя правильно 15 рабочих дней.
![image](https://user-images.githubusercontent.com/42540074/50145447-4b2e2a00-02ba-11e9-83a3-3e901b1d42db.png)

**Comment by Anestezia** [comment]
На данном этапе что нам делать? Сделать подсказку пользователю, "Сверьте кол-во рабочих дней в календаре самостоятельно!" ? Либо автоматически не заполнять эту ячейку, чтоб пользователь догадался, что ему нужно посмотреть в календарь (или табель) самому.

**Comment by Illya-Lykhachov** [comment]
Предлагаю вообще не заполнять колонку с отработанными днями, если мы не можем их корректно посчитать (отпуска или болезнь). Пусть пользователь сам считает. Неудобно, зато претензий не будет.

**Comment by Anestezia** [comment]
да, по всем этим докам - отпуска те и другие, больничные. Это будет более правильно.

**Comment by alexeijur** [comment]
Тогда убираю заполнение столбца с  с отработанными днями. Всё верно коллеги?

**Comment by Illya-Lykhachov** [comment]
Не совсем. Если сотрудник работал весь месяц (нет отпусков (в т.ч. неоплачиваемого) и больничных), то заполняем днями по графику

**Comment by alexeijur** [comment]
хорошо.

**Comment by Anestezia** [comment]
Все нормально, думаю, можно закрывать.
