### ISSUE TITLE
Персонал. Кадри. Переведення.

### ISSUE THREAD

**Issue by alexeijur** [a2develop/testing#184]
Проверить возможность печати и форму в документе "Переведення".

**Comment by AndriyNesterenya** [comment]
Пока общее замечание по по всем документам в персонале - они у нас сейчас проводятся практически пустыми.
Номер уже требует - все остальное почти не проверяется и дает провести с незаполненными полями.

Считаем, что так и надо?

**Comment by alexeijur** [comment]
Добавлю проверок в следующий релиз.
