### ISSUE TITLE
Персонал. Заробітна плата. Розрахунок заробітної плати.

### ISSUE THREAD

**Issue by alexeijur** [a2develop/testing#185]
В документе теперь из отработанных дней должны отниматься отпуска без оплаты (нигде отдельно не отображаются).

**Comment by Anestezia** [comment]
В рассчетной ведомости не ставится количество отработанных дней, если у человека был в периоде отпуск, отпуск без сохр.зп, больничный. Пользователь заглядывает в календарь и ставит сам, на данный момент по нулям. Это правильно в этой ситуации. Думаю, ишью можно закрывать, я так понимаю.
