### ISSUE TITLE
Персонал. Кадри. Звільнення.

### ISSUE THREAD

**Issue by alexeijur** [a2develop/testing#186]
Проверить возможность печати и форму в документе "Звільнення".

**Comment by Anestezia** [comment]
![image](https://user-images.githubusercontent.com/42540074/50096442-60567a80-0220-11e9-824d-deb5a79e2cf7.png)
А должна Інша підстава идти на печать? Если ее выбираем, то нужно еще что-то писать о причине? а поля для этого нет. В остальном вопросов нет. Все работает.

**Comment by alexeijur** [comment]
Завтра обсужу это с Ильёй.

**Comment by Illya-Lykhachov** [comment]
Нужно в форме приказа при выборе причины "Iнша" показать обязательное поле для ввода этой причины руками. Сохраняем её в документе (Row или Document без разницы, где есть поле в базе) и показываем в печатной форме приказа.

**Comment by alexeijur** [comment]
принято в работу
