### ISSUE TITLE
Механизм импорта объектов учета. Импорт объектов типа "Услуга"

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#187]
[685](https://github.com/a2develop/bugTracker/issues/685)
В файле импорта в колонке "Рахунок" необходимо указать "послуга".
Проверить импорт.

**Comment by Anestezia** [comment]
Не выполняется перемещение файла с номенклатурой с моего компа в сервис путем перетаскивания файла. 
![image](https://user-images.githubusercontent.com/42540074/50165006-af69e180-02ec-11e9-9b50-d7fd40c5df9f.png)
Сразу предлагает мне же снова на мой комп сохранить этот файл. А потом еще и жалуется, когда я нажимаю сохранить, что файл уже существует.
Только выбор из списка можно сделать. Перетащить и бросить - нет.

В остальном вроде все ок. Проводки создает на 703.

**Comment by AlexeyTishkin** [comment]
> Только выбор из списка можно сделать. Перетащить и бросить - нет.

Если критично - отдельный issue. Это вопрос связан с элементом управления выбора файла, а не с механизмом импорта.

**Comment by AlexeyTishkin** [comment]
> В остальном вроде все ок.

Тогда этот issue закрываю.
