### ISSUE TITLE
Механизм импорта объектов учета. Создание операции "Створення прайс-листа"

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#188]
Принцип создания аналогичен созданию операции "Початковий баланс":
1. Создается не проведенной. Дата = последнему дню предыдущего месяца (запускаем в декабре - дата равна 30.11).
2. При повторном импорте, если операция не проведена, то происходит обновление.
3. Вверху над таблицей с товарами отображается статус импорта операции с возможностью ее открытия.

Проверить импорт.

**Comment by AndriyNesterenya** [comment]
Импорт откуда? 
Из пользовательского файла? 
Образец где смотреть?

**Comment by AlexeyTishkin** [comment]
В диалоге импорта "Завантажити зразок".

**Comment by AndriyNesterenya** [comment]
Там в файле импорта адовое количество кацапизмов и опечаток

Плівка упаковочна - пакувальна
Бумага для друку А4 - Папір
Миш компьютерна - Миша комп'ютерна (Маніпулятор Миша)
Стул офісний - Стілець
Стіл для комьютера - комп'ютера

**Comment by AlexeyTishkin** [comment]
Файл готовил Коля :)
Коля, исправишь ?

**Comment by mik-man** [comment]
Исправил.

**Comment by AndriyNesterenya** [comment]
Вообще работает - есть замечания:

1. Добавил в файл примера несколько позиций услуг НАД черной линией. При импорте создалось три страницы товаров из файла + целая 4 страница с пустыми записями.

2. После успешного импорта остается висеть желтое окно импорта, после закрытия которого список объектов учета по традиции остается пустым - и тут тоже нужен автоматический возврат на список объектов учета и его принудительное обновление.

**Comment by AlexeyTishkin** [comment]
> Добавил в файл примера несколько позиций услуг НАД черной линией. При импорте создалось три страницы товаров из файла + целая 4 страница с пустыми записями.

Кинь сюда файл.

**Comment by AlexeyTishkin** [comment]
> После успешного импорта остается висеть желтое окно импорта, после закрытия которого список объектов учета по традиции остается пустым - и тут тоже нужен автоматический возврат на список объектов учета и его принудительное обновление.

Подробней.

**Comment by AndriyNesterenya** [comment]
[Імпорт-товари-послуги.xlsx](https://github.com/a2develop/testing/files/2710108/-.-.xlsx)
Файло, с которого импортил. Из изменений - только несколько услуг добавлено

**Comment by AndriyNesterenya** [comment]
![image](https://user-images.githubusercontent.com/38098758/50444113-42b79e00-090f-11e9-9f4a-6917ad5d97a8.png)
Страница с пустыми записями

**Comment by AlexeyTishkin** [comment]
> Страница с пустыми записями

Попробуй сейчас.

**Comment by AndriyNesterenya** [comment]
Во. Теперь все красиво с тем же файлом

**Comment by AlexeyTishkin** [comment]
Issue закрываем ?

**Comment by AndriyNesterenya** [comment]
да
