### ISSUE TITLE
В список видов объектов учета добавлен вид "Послуги з оренди"

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#189]
[735](https://github.com/a2develop/bugTracker/issues/735)

Проверить:
1. Создание.
2. В операции "Реалізація послуг" Кт должен быть 713.
3. В операции "Безоплатне надання послуг" проведение такое как и для остальных объектов.

**Comment by Anestezia** [comment]
Да, все как описано в задании
