### ISSUE TITLE
Операция "Отримання рахунку". Создание связанного приобретения

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#190]
[728](https://github.com/a2develop/bugTracker/issues/728)
Если в Счете присутствуют объекты типа "Нематериальные активы", то в качестве связанной операции приобретения теперь создается операция "Придбання об'єктів нематеріальних активів". 
Проверить варианты:
1. В счете только нематериальные активы.
2. В счете нематериальные активы, услуги, ОС.

**Comment by Anestezia** [comment]
1. Работает как описано
2. Создается несколько документов разного подходящего назначения. в зависимости от объекта учета, возврат, созданный на основании, в одной из операций работает корректно.
