### ISSUE TITLE
В диалоге свойств счета в банке добавлено отображение вида счета и всплывающая подсказка к нему

### ISSUE THREAD

**Issue by shevchuk-vadim** [a2develop/testing#192]
Вид счета определяется автоматически по первым четырем цифрам номера счета: 2610 - "Короткостроковий депозитний рахунок" (балансовый счет 351), 2615 - "Довгостроковий депозитний рахунок" (балансовый счет 184), 3751 - "Спеціальний рахунок в системі адміністрування ПДВ" (балансовый счет 315), 2604 - "Поточний рахунок для коштів ФССУ" (балансовый счет 311), другие - "Поточний рахунок" (балансовый счет 311 для гривны и 312 для валюты).

Кроме того, для каждого вида счета проверить, чтобы
1. Балансовый счет подставлялся в проводку по дебету в приходных операциях и кредиту в расходных.
2. Правильно отображался остаток на счете в списке счетов в банках моей фирмы.
3. Правильно строился отчет по счету в банке.

**Comment by AndriyNesterenya** [comment]
По крайней мере создание работает согласно заявленной логике и подсказки показывает. 👍 

Осталось два вопроса : 

1. Не стоит ли эти подсказки показывать не по клику, а по наведению мыши?

2. Где на окне создания нового счета задать ВАЛЮТУ?

![image](https://user-images.githubusercontent.com/38098758/50350724-af661d80-0548-11e9-84c4-0df71983e991.png)
