### ISSUE TITLE
Реализация необоротных активов. 

### ISSUE THREAD

**Issue by htrofymova** [a2develop/testing#194]
Нужно проверить всю "цепочку" реализации от счета до возврата от покупателя.

**Comment by Anestezia** [comment]
Все ок.

Есть момент, который может понадобиться: в печатной форме накладной на возврат нужно создать возможность длинный адрес переносить на следующую строку
![image](https://user-images.githubusercontent.com/42540074/50227890-78103900-03af-11e9-910e-6bcba36f6572.png)
Вот в здесь больше влазит символов адреса:
![image](https://user-images.githubusercontent.com/42540074/50227930-90805380-03af-11e9-832c-85d4b3244d45.png)
И желательно потом сразу проверить сохранение в ПДФ. Там при переносе длинного адреса переносилось не на все строки, а пол строки поперек могло урезать, или верхнюю строку с началом адреса затереть.
