### ISSUE TITLE
Необоротные активы. Объекты учета. Изменен вид списка. 

### ISSUE THREAD

**Issue by htrofymova** [a2develop/testing#195]
Список объектов разделен на 2 части. В меню "Об'єкти обліку" отображаются все объекты типов, относящихся к необоротным активам. Если есть введенные в эксплуатацию, то появляется список связанных элементов. В меню "Необоротні активи" отображаются только объекты необоротных активов, введенные в эксплуатацию. 
Нужно проверить:
1. Адекватность отображения информации
2. Создание операций
3. Построение отчетов.

**Comment by Anestezia** [comment]
Отчеты строятся, операции при создании из списка объектов подтягивают объект, который выбран, правда еще без распознавания вида объекта и уместности его у той или иной операции.
По адекватности: пока не подтягивается балансовая стоимость и количество объекта, что делает неактивной кнопку Провести, нужен сложный механизм обхода: перевыбрать другой объект, а затем снова перевыбрать исходный. Тогда все функции включаются и сумма с количеством подтянется.
