### ISSUE TITLE
В ведомости выплаты на карты добавлено создание платежного поручения

### ISSUE THREAD

**Issue by shevchuk-vadim** [a2develop/testing#196]
Проверить, чтобы связанное с ведомостью платежное поручение формировало проводки в разрезе физлиц..
Также проверить, не сломалось ли индивидаульная выплата зарплаты, т.е. когда платежное поручение создается самостоятельно.

**Comment by Anestezia** [comment]
1. Проводки в разрезе физлиц на 661
![image](https://user-images.githubusercontent.com/42540074/50441681-88bb3480-0904-11e9-85e0-c8bd2bf03fbb.png)
2.  Работают немного по-разному. Когда создается из цепочки документов, то Ведомость на пополнение карточных счетов при выборе зарплатного проекта уже заполнена, а когда эту операцию создаешь отдельно, не на основании, ведомость даже после выбора зп проекта не заполнена, нужно нажать кнопку Заполнить.
