### ISSUE TITLE
Отчет "Податкова декларація платника єдиного податку - фізичної особи - підприємця (квартальна)". Сообщение об отсутствии начисления налога

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#198]
[558](https://github.com/a2develop/bugTracker/issues/558)

**Comment by AndriyNesterenya** [comment]
Пробовал.
Пустые 1-2-3 кварталы и наличие доходов в 4м.
При попытке создать отчет получил сообщение об отсутствии начисления налогов в 1-2-3-4 кварталах.
Начислил налоги в 4 квартале - создался отчет.

Вменяемо.
