### ISSUE TITLE
Банковская выписка. При отмене проведения удаляются операции, которые были автоматически созданы в момент проведения

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#199]
[757](https://github.com/a2develop/bugTracker/issues/757)
1. Проверить отмену проведения строки, в которой не было вручную выбрано ПП. В момент проведения ПП должно быть создано, в момент отмены проведения - удалено.
2. Проверить отмену проведения строки, в которой  было вручную выбрано ПП. В момент отмены проведения документ должен остаться быть выбранным в строке.

**Comment by AndriyNesterenya** [comment]
1. Работает как заявлено
2. Пока не понятно - буду разбираться.
Работал со свое реальной выпиской за прошлые периоды. Выставил счет на известную мне суму из выписки. Под него создал оплату покупателя на счет в банке с известным из выписки номером и датой. Полез проводить выписку - не смог выбрать в поле ПП вот эту ранее созданную платежку.
Покупатель/сумма/дата совпадает. Ищу, где накосячил.

**Comment by AlexeyTishkin** [comment]
> Работает как заявлено

Тогда закрываю.
По поводу п.2 - если есть глюк - отдельный issue.
