### ISSUE TITLE
Сумма документа с НДС и скидкой

### ISSUE THREAD

**Issue by shevchuk-vadim** [a2develop/testing#2]
Проверить, чтобы в списках документов сумма документа отображалась правильно, т.е. включала НДС и скидку:
а) в операциях по Бухгалтерии
б) в операциях по контрагенту
в) в операциях по договору
г) в операциях по счету в банке.
Документы, в которых может быть НДС - это, кроме приходных и расходных накладных и актов, еще приходные платежное поручение и кассовый ордер.

**Comment by AlexeyTishkin** [comment]
д) в операциях "Придбання"
е) в операциях "Продажі"
ж) в операциях "Запаси"

**Comment by kattrina-brekhova** [comment]
считает
