### ISSUE TITLE
Операция "Виготовлення". Печатная форма

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#200]
Проверить печать.

**Comment by Anestezia** [comment]
А где подписи?
![image](https://user-images.githubusercontent.com/42540074/50444845-61b82f00-0913-11e9-9d34-debbeef09637.png)

**Comment by AlexeyTishkin** [comment]
Какие должны быть подписи ?

**Comment by Anestezia** [comment]
Что-то типа Виписав и линия.  А то как-то пустовато смотрится

**Comment by AlexeyTishkin** [comment]
Добавил "Виконавець", вроде больше подходит...
"Виписав", наверное, больше для Счетов...
