### ISSUE TITLE
Персонал. Заробітна плата. Розрахунок зарплати по звільненню

### ISSUE THREAD

**Issue by alexeijur** [a2develop/testing#202]
Добавлен документ, рассчитывается только по корреспонденту добавленному в ручную. Предупреждает о повторном документе по этому корреспонденту за текущий период.

**Comment by Anestezia** [comment]
Відпустка компенсація - это дней? (тогда нужна подсказка или в каждом поле таблицы добавить единицы измерения данных в таблице), а то непонятно.
За текущий период не дает начислить повторно. ОК.

**Comment by alexeijur** [comment]
Дни добавил.
