### ISSUE TITLE
Печатные формы. Исправлен формат отображения суммы скидки в итоге

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#204]
В документах:
1. Счет исходящий.
2. Счет из Кабинета.
2. Расходная накладная.
3. Акт выполненных работ.
4. Акт выполненных работ с материалами.

В печатных формах проверить отображение формата чисел в итоге в случаях:
1. Есть скидка.
2. Нет скидки.

В Счете из Кабинета скидки не бывает.

**Comment by Anestezia** [comment]
да, все в порядке в этих документах, и с большими суммами и с маленькими, старых ошибок больше не наблюдается
