### ISSUE TITLE
Таблица с дочерними документами

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#206]
[762](https://github.com/a2develop/bugTracker/issues/762)

Проверить отображение таблицы в следующих документах:
1. Счет входящий.
2. Приходная накладная.
3. Акт полученных услуг.
4. Входящая налоговая накладная.
5. Счет исходящий.
6. Расходная накладная.
7. Акт оказанных услуг.
8. Акт с материалами.
9. Исходящая налоговая накладная.
10. Инвентаризационная опись.

**Comment by Anestezia** [comment]
В каждом документе дочерние проведенные указываются одноименным символом. Все ок
