### ISSUE TITLE
Отчет "Відомість за розрахунками з контрагентами"

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#207]
Запускается:
1. Со счетов, которые ведутся в разрезе контрагентов (361, 631 и др.).
2. Придбання - звіти - Відомість за розрахунками з постачальниками.
3. Продажі - звіти - Відомість за розрахунками з покупцями.

Проверить построение.

**Comment by Anestezia** [comment]
Работает как заявлено, во всех трех случаях. по каждому контрагенту дальше разворачивается оборотная ведомость со списком всех документов.
