### ISSUE TITLE
Отчет "Відомість за розрахунками з контрагентами у валюті"

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#208]
Запускается:
1. Со счетов, которые ведутся в разрезе контрагентов и валюты (362, 632 и др.).
2. Придбання - звіти - Відомість за розрахунками з постачальниками у валюті.
3. Продажі - звіти - Відомість за розрахунками з покупцями у валюті.

Проверить построение.

**Comment by Anestezia** [comment]
Так же, как и в счетах в национальной валюте, все работает. Оборотки и документы непосредственно по контрагенту открываются, формируются за разные периоды.
