### ISSUE TITLE
Отчет "Схема счета"

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#209]
Запускается с конечного счета, по которому проходят обороты. К примеру, в ветке 3 - 36 - 361 отчет будет только на 361.
Проверить построение.
При клике на сумме должен открыться отчет "Реест документов", который показывает документы по корреспонденции счетов: основной счет (по которому строится отчет) + счет, по которому проходит сумма.

**Comment by Anestezia** [comment]
работает как заявлено, отображает все корреспондирующие с заданным счета плюс разворачивает реестр документов, не только от конечной суммы, но и от общей суммы одного конкретного счета в каждой из строк.
