### ISSUE TITLE
Добавлена операция вступительного баланса по необоротным активам.

### ISSUE THREAD

**Issue by shevchuk-vadim** [a2develop/testing#210]
Проверить проведение и его отмену.
Проверить начисление износа после всупительного баланса.
После начисления износа отмена проведения должна быть запрещена.

**Comment by AndriyNesterenya** [comment]
Нет возможности создать объект
![image](https://user-images.githubusercontent.com/38098758/50782171-fd508480-12af-11e9-9f2f-71b63f038fa8.png)

**Comment by shevchuk-vadim** [comment]
Добавлена возможность создать объект.

**Comment by AndriyNesterenya** [comment]
Забыл же отписаться. 
Вроде все ОК
