### ISSUE TITLE
Счета в банках. Проверить учет валюты при дубликатах номеров счетов

### ISSUE THREAD

**Issue by alex-kukhtin** [a2develop/testing#211]

**Comment by AndriyNesterenya** [comment]
Добавить возможность создания счетов с дублирующимися номерами при разных валютах в свойствах Моей Фирмы.
В списке счетов создается ОК.

**Comment by AndriyNesterenya** [comment]
... после прошлого релиза тестируем на живых клиентах.
Пока ОК
