### ISSUE TITLE
Из карточки вступительного баланса удалена дата.

### ISSUE THREAD

**Issue by shevchuk-vadim** [a2develop/testing#212]
Проверить проведение и автонумерацию (https://github.com/a2develop/bugTracker/issues/744) карточек.
Проверить, как попадают операции вступительного баланса в отчеты. Должны всегда попадать в остатки на начало.

**Comment by AndriyNesterenya** [comment]
Забавный гулючок.
Дата удалена, проводится.
Но при этом в фильтре показывает невиданное значение
![image](https://user-images.githubusercontent.com/38098758/50741579-a4c5ac80-1207-11e9-948c-4c08e048bc1c.png)

**Comment by shevchuk-vadim** [comment]
Исправлено. Эта ошибка была во всех списках бухгалтерских операций.
А в списке опрераций вступительного баланса выбор периода удален вообще. И столбец с датой тоже.

**Comment by AndriyNesterenya** [comment]
В остальном все ОК, вроде бы.
