### ISSUE TITLE
Отчет "Реестр документов"

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#213]
Колонки разделены на две группы: Документ, Операция. Добавлено наименование формы документа (Накладная, Акт и т.д.). Колонка "Сумма" присутствует в двух группах. В группе "Документ" - это общая сумма документа (отображается в списках документов и в итоге самого докуметна). В группе "Операции" - это сумма документа, которая отражается на определенном счете. К примеру, "Придбання", в котором объект типа "товар" на 100 грн и объект типа "Материал" на 100 грн, при построении Реестра по счету 281 в "Сумме документа" будет 200 грн, в "Сумме операции" - 100 грн.
Проверить отображение сумм.

**Comment by Anestezia** [comment]
В сумме документа отображается вся сумма по этому документу, а в сумме операции -- сумма которая проходит конкретно по заданному счету. Даже с описанием я не сразу поняла принцип. Может в названия колонок "сумма" внести изменения уточняющие параметр? Например, сумма по операции назвать "Сумма по счету".

**Comment by AlexeyTishkin** [comment]
Сумму по операции назвал "Сума по рахунку".

**Comment by Anestezia** [comment]
Хорошо)
