### ISSUE TITLE
Отчет "Оборотна відомість по об'єктах обліку"

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#215]
Строится со счетов, которые ведутся в разрезе объектов учета (201, 281 и др.). Для детализации оборотов отображается отчет "Оборотная ведомость" по счету, объекту учета в разрезе даты, документа.
Сверить с отчетом "Оборотная ведомость по складу". Учесть, что в случае использования комиссионной торговли "Оборотная ведомость по складу" показывает обороты по более чем одному балансовому счету (024, 281, 283). В этом случае необходимо ограничить данные при помощи выбора склада.
Проверить детализацию оборотов (также можно сверить с детализацией из отчета "Оборотная ведомость по складу").

**Comment by Anestezia** [comment]
Отчеты строятся, детализация сходится. к чему придраться не нашла.
