### ISSUE TITLE
Добавлен отчет F0100110 "Декларація про майно і доходи (ФОП)"

### ISSUE THREAD

**Issue by mik-man** [a2develop/testing#216]
Для ФОП на общей системе. Заполняется за год. Проверить обычные действия с отчетом: создание, сохранение, редактирование, заполнение, выгрузку в файл и Сонату.

**Comment by AndriyNesterenya** [comment]
Вродь все ОК, только по-моему по форме нужно добавить типе в
"особа, яка припинила підприємницьку діяльність протягом звітного року - 3 датою __.__.____"
По крайней мере в Инструкции вроде как с тире

**Comment by AndriyNesterenya** [comment]
Дало провести отчет с нулями в таблице.
При потытке экспортировать - 

The element 'DECLARBODY' has invalid child element 'HNAMEAG'. List of possible elements expected: 'H07, HLIQ'.

**Comment by AndriyNesterenya** [comment]
Исправили
