### ISSUE TITLE
Необоротные активы. Дашбоард.

### ISSUE THREAD

**Issue by htrofymova** [a2develop/testing#217]
Изменено или исправлено, теперь надо проверить:
1. Акт ввода в эксплуатацию. 
- Автоматическое заполнение склада при создании из панели задач.
- Очистка и заполнение полей при изменении объекта или склада.
- валидаторы дополнительных полей в таблице.
- копирование.
- отображение остатков склада при выборе объекта.
2. Добавлен диалог выбора МОЛ - теперь только сотрудники.
3. Инвентаризация.
- автоматическое заполнение/очистка после выбора МОЛ.
4. Копирование операций по нематериальным активам.
5. Заполнение итоговых суммы на дашбоарде.

**Comment by Anestezia** [comment]
Акт ввода
1. Ставится основной склад.
2. При изменении склада после заполнения всех полей, объект учета и другая информация введенная по нему дальше колонки с первичной стоимостью, остаются. Количество и цена убираются.
Кнопка Друк/Експорт не активна.
3. Валидаторы есть, работают.
4. Документ копируется со всеми данными в нем.
5. Остатки на складе актуальные
6. Да. выбирается из списка сотрудников МОЛ
7. Из дашборда формируется, отдельный вопрос по печати, смещен центр, это мои настройки или что-то еще?:
![image](https://user-images.githubusercontent.com/42540074/50898217-25a6c300-1417-11e9-8081-24056809f797.png)
 8. Автоматическое заполнение после выбора МОЛ работает, очистка, только при нажатии на Очистить. Если на МОЛ был объект, а потом я поменяла МОЛ, то данные по объекту остаются в таблице, хотя после нажатия Провести или Печать исчезают, если на человеке ничего не числится. Что уже хорошо.
9. копируются
10. Изменения в суммах на дашборде и в задачах отображаются сразу.
