### ISSUE TITLE
Добавлены операции вступительного баланса по дебету и кредиту заданного счета

### ISSUE THREAD

**Issue by shevchuk-vadim** [a2develop/testing#218]
Проверить проведение и отмеру проведения в этих операциях, и хотя бы в одной из существующих ранее операций (вдруг поломалось).
Проверить копирование операций вступительного баланса.

**Comment by Anestezia** [comment]
Проводятся и отменяется проведение нормально. В ведомостях указывается. 
Вопрос копирования. После нажатия на копировать, открывается, видимо, копия этого документа, так как номер стоит следующий, но уже ПРОВЕДЕННАЯ. 1. Закрываю, спрашивает Сохранить изменения? 
![image](https://user-images.githubusercontent.com/42540074/51121315-d0582080-181f-11e9-9a57-38d80db96753.png)

Нажимаю да, в списке операций документ непроведенный.
2. Нажимаю в только что скопированном документе, не закрывая, Скасувати проведення.
Пишет, что скасовано, при этом все остается без изменений.
![image](https://user-images.githubusercontent.com/42540074/51121418-1319f880-1820-11e9-8cae-e5bf1a000558.png)

**Comment by Anestezia** [comment]
Уже все в порядке.
