### ISSUE TITLE
Продажі - Прайс-листи. Ввод цены, равной 0

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#219]
Добавлен запрет на ввод цены, равной 0.
Попробовать внести цену равную 0. До добавления запрета была возможность внести 0, при условии того, что у объекта уже была установлена цена. К примеру, 11.01 установлена цена 3 грн, 12.01 можно было установить 0 грн. Теперь после установки 0 должно быть сообщение об ошибке и возврат в ячейку предыдущего значения цены.

**Comment by Anestezia** [comment]
да, так и есть
![image](https://user-images.githubusercontent.com/42540074/51038649-76a3ec00-15bc-11e9-911e-0f9a0aa69c8e.png)
 Только теперь нет возможности удаления цены ошибочно введенной. Кнопка делит или бекспейс также воспринимается как 0.

**Comment by AlexeyTishkin** [comment]
> Только теперь нет возможности удаления цены ошибочно введенной. Кнопка делит или бекспейс также воспринимается как 0.

Здесь варианты. Удалить нужно цену, которую только что внесли ? В тот момент когда она "жирная", т.е. установлена датой, которая вверху ?
Или удалить цену, которая была внесена ранее ? Когда она не "жирная", т.е. установлена в предыдущих периодах ?
Со вторым случаем и связан запрет. Дело в том, что в этом случае значение не удаляется, а создается новое нулевое на текущую дату. Это как раз не правильно. Плюс возникают дополнительные вопросы при последующем редактировании цен в диалоге "Цены".

**Comment by Anestezia** [comment]
Давайте хотя бы, чтоб жирную можно было удалить.

**Comment by AlexeyTishkin** [comment]
Сделал возможность удаления значения цены, которая внесена текущей датой (которая установлена вверху).
Проверить:
1. Дата, к примеру, 25/01. Установить значение, изменить, удалить. Все действия должны быть разрешены.
2. Дата 25/01. Установить значение, изменить дату на 26/01. Удалить значение разрешить не должно, изменить - должно.

**Comment by Anestezia** [comment]
Да. Можно закрывать
