### ISSUE TITLE
В документы разделов "Придбання", "Продажі", "Запаси" на тулбар добавлена кнопка "Help"

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#221]
[613](https://github.com/a2develop/bugTracker/issues/613)
Проверить ссылки.

**Comment by AndriyNesterenya** [comment]
В целом - работает.

Косяки : 

1. Ссылка на хелп со страницы "Запаси-Створення рецептури" 
http://dev.a2start.com/document/recipe/edit/new?operation=recp
ведет на индекс хелпа.

2. Не обнаружил ссылок на хелп с новых операций в блоках
в разделе "Придбання"
- Видаток з рахунку в банку
- Податковий облік
- За активами
- За пасивами
 в разделе "Продаж"
- Комісія (операції комітента)
- Послуги
- Надходження на рахунок в банку
- Податковий облік
- За активами
- За пасивами
и в разделе "Запаси"
- За активами
Так задумано?

3. Во всех трех разделах в нижней части меню создания новой операции из названий не ясно, что речь идет о начальном балансе
![image](https://user-images.githubusercontent.com/38098758/51445169-bda38700-1d0a-11e9-9f4b-79b23b34c8af.png)

**Comment by AlexeyTishkin** [comment]
> Ссылка на хелп со страницы "Запаси-Створення рецептури"
http://dev.a2start.com/document/recipe/edit/new?operation=recp
ведет на индекс хелпа.

"Створення рецептури | еще нет". Нет хелпа.

**Comment by AlexeyTishkin** [comment]
> Не обнаружил ссылок на хелп с новых операций в блоках
в разделе "Придбання"
Податковий облік
Комісія (операції комітента)
Послуги

Не понял. Есть же.

**Comment by AlexeyTishkin** [comment]
> Видаток з рахунку в банку

Это операции из раздела "Бухгалтерия". Этот issue касается ТМЦ и услуг.

**Comment by AlexeyTishkin** [comment]
> Во всех трех разделах в нижней части меню создания новой операции из названий не ясно, что речь идет о начальном балансе

Тоже не сюда.

**Comment by AndriyNesterenya** [comment]
В остальном все ОК.
