### ISSUE TITLE
Отчет "Прайс-лист". Экспорт в Excel

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#224]
[788](https://github.com/a2develop/bugTracker/issues/788)
Проверить экспорт в Excel.

**Comment by Anestezia** [comment]
Сохраняет нормально. Вопрос по поводу переноса длинного названия, или это у меня в екселе такие настройки ячейки?
![image](https://user-images.githubusercontent.com/42540074/51238337-59399e00-197f-11e9-900e-1b92ebacd41b.png)
![image](https://user-images.githubusercontent.com/42540074/51238347-6191d900-197f-11e9-9b9c-e34bad7cce44.png)
Но в основном все ок, это мелочь.

**Comment by AlexeyTishkin** [comment]
> по поводу переноса длинного названия

По моему это так внесено наименование объекта. Если открыть свойства объекта, стать после "упаковочная" и нажать Del до тех пор пока не сольется с "ттт", а потом поставить пробел, что будет ?

**Comment by Anestezia** [comment]
Да, вылечилось.
