### ISSUE TITLE
В диалоге свойств и мастере создания моей фирмы добавлен орган статистики

### ISSUE THREAD

**Issue by shevchuk-vadim** [a2develop/testing#225]

**Comment by Anestezia** [comment]
Пока что-то не так. Это при вызове списка
![image](https://user-images.githubusercontent.com/42540074/51241981-9efa6480-1987-11e9-9e5d-b42fdbbc8c8a.png)
а это при попытке выбора из списка
![image](https://user-images.githubusercontent.com/42540074/51242023-af124400-1987-11e9-81e4-0c0fbac908bc.png)

**Comment by Anestezia** [comment]
Теперь все в порядке.
