### ISSUE TITLE
В диалоге свойств и мастере создания моей фирмы добавлено поле для указания территориальной единицы

### ISSUE THREAD

**Issue by shevchuk-vadim** [a2develop/testing#228]

**Comment by AndriyNesterenya** [comment]
Там же коды КОАТУУ 2018 должны выбираться?

Не получается там выбрать Киев или районы.
Из всего Киевоподобного находится только [110136600] КИЇВСЬКИЙ район Симферополя.

**Comment by AndriyNesterenya** [comment]
PS поле видно только у юрлиц, у ФОПов не видно.
Так надо?

**Comment by AndriyNesterenya** [comment]
Вроде решили. 
По поводу дерева с районами сотворили новое ишью https://github.com/a2develop/bugTracker/issues/805

**Comment by Anestezia** [comment]
С этим вроде все, классификатор увеличено, через поиск по коду найти можно, сохраняется.
