### ISSUE TITLE
 Добавлен отчет Додаток Ф2 до Декларації про майно і доходи фізичної особи (F0111410)

### ISSUE THREAD

**Issue by mik-man** [a2develop/testing#230]
Проверить обычные действия с отчетами: редактирование, сохранение, проведение, выгрузка в XML.

**Comment by AndriyNesterenya** [comment]
Формируется, но отображается не только для ФОП на общей системе, но и у 3 группы, например

**Comment by mik-man** [comment]
> Формируется, но отображается не только для ФОП на общей системе, но и у 3 группы, например

Это не ошибка. Пока что в системе перечень доступных отчетов фильтруется только по двум показателям:
- фоп или юрик,
- плательщик ндс или нет.

Возможно, требуется фильтрация перечня отчетов по группам налогобложения. Это отдельный ишью ко всему разделу "Отчетность".
