### ISSUE TITLE
В свойствах банка и контрагента (если он банк) удален контроль уникальности кода ЕДРПОУ

### ISSUE THREAD

**Issue by shevchuk-vadim** [a2develop/testing#232]
https://github.com/a2develop/bugTracker/issues/779

**Comment by Anestezia** [comment]
Создать можно только через Довідники-Банки-пошук за кодом МФО. Разнные МФО при одинаковых ЕГРПОУ принимает и в списке контрагентов эти банки появляются.
![image](https://user-images.githubusercontent.com/42540074/51596293-4c79f480-1f01-11e9-91a9-ee4ee1cc7f3a.png)
