### ISSUE TITLE
Добавлен Баланс (S0100113)

### ISSUE THREAD

**Issue by shevchuk-vadim** [a2develop/testing#234]
Проверить, правильно ли выгружаются данные в Сонату. Желательно все поля.

**Comment by AndriyNesterenya** [comment]
Баланс создается ОК, но на Сонате проверить не могу,

**Comment by shevchuk-vadim** [comment]
На Сонате надо проверить, как туда переносятся сроки с износом (аморитзацией) в активе, и с неоплаченным и изъятым капиталом в пассиве.

**Comment by Anestezia** [comment]
Износ перенесся нормально, ошибок при проверке не выдает. Суммы сходятся.
неоплаченный и изъятый переносится в скобки в сонате.
![image](https://user-images.githubusercontent.com/42540074/51907991-28bb2080-23d1-11e9-9136-fccc1c7b5958.png)
![image](https://user-images.githubusercontent.com/42540074/51908014-3cff1d80-23d1-11e9-8bc1-ac5107bb3a2f.png)
Нам надо при переносе данных не переводить их в тысячи, т.е. не дописывать в хмл. трех нулей, так как в сонату попадает в готовом виде, и у нас многомиллионные суммы в балансе получаются.
![image](https://user-images.githubusercontent.com/42540074/51908389-68363c80-23d2-11e9-9ead-e7bed07a3734.png)

**Comment by shevchuk-vadim** [comment]
Убрал перевод из тысяч в гривны.
