### ISSUE TITLE
Вступительный баланс по зарплате. Новая форма. 

### ISSUE THREAD

**Issue by alexeijur** [a2develop/testing#235]
Нужна проверка.

**Comment by AndriyNesterenya** [comment]
![image](https://user-images.githubusercontent.com/38098758/51604561-ccaa5500-1f15-11e9-9684-d37252a93e56.png)
Нельзя добавить сотрудника, что неудобно.

**Comment by AndriyNesterenya** [comment]
Уже можно.
Вродь работает.
