### ISSUE TITLE
Доработан баланс

### ISSUE THREAD

**Issue by shevchuk-vadim** [a2develop/testing#237]
Добавлена подстановка среднесписочной численности работников при заполнении.
Добавлен запрет проведения, если итоговые суммы активов и пассивов не совпадают.
Добавлена возможность выбирать из каталога непостредственно в документе терииторию, организационно-правовую форму, и вид деятельности.
Разрешено редактировать адрес и телефон.
Добавлены служебные поля для указания даты подачи отчета и органа статистики, куда подается отчет.

**Comment by Anestezia** [comment]
Среднесписочная численность работников автоматически не заполняется, только вручную.
Запрет проведения есть. с хорошей подсказкой.
1 и 2 из каталога выбирается, вид деятельности при попытке выбора выдает ошибку
![image](https://user-images.githubusercontent.com/42540074/51894271-f2b97480-23af-11e9-8dbe-2df9d740cee2.png)
Адрес и телефон редактируется
Орган статистики выбирается, странно, что наряду с остальными показателями, которые указаны в свойствах фирмы и подтягиваются в баланс, название Органа статистики изначально не подтягивается. Только код его. Если задать вручную, то после проведения опять же код остается. название исчезает. Может так и надо, так как при переносе в Сонату в видимых полях этого реквизита нет. Но несколько смущает. 
Дата подачи отчета выставляется.
Должна ли эта выделенная дата совпадать с датой подачи, которую мы указываем?
![image](https://user-images.githubusercontent.com/42540074/51894475-88550400-23b0-11e9-8d6b-cb4924d91705.png)
 Также в таблице актив продублирован номер третьей строки 1001 как и у второй. Должен быть 1002

**Comment by shevchuk-vadim** [comment]
Опечатку исправил.
В Дата число должно быть всегда 1. Поэтому даты совпадать не обязаны.
Все остальное должно работать.
