### ISSUE TITLE
Акт ввода в эксплуатацию необоротных активов.

### ISSUE THREAD

**Issue by htrofymova** [a2develop/testing#238]
Изменен документ: 
1. Разрешен ввод количества, т.е. можно вводить в эксплуатацию несколько одинаковых объектов: если на складе несколько штук, то можно ввести по одному (поставить кол-во = 1) или все (кол-во запролняется автоматически), или любое количество в пределах наличия. Таким образом, получаем групповой учет однотипных необоротных активов.
2. Исправлена проблема появления в сумме  более двух знаков после запятой.
3. Добавлена возможность формирования первоначальной стоимости необоротных активов. К покупной стоимости можно добавить стоимость материалов и работ/услуг. Материалы, работы/услуги должны быть списаны предварительно на один из 15-х счетов ( операции: Списание запасов, Приобретение услуг).
Нужно проверить создание, заполнение всех элементов, сохранение и проведение операции.

**Comment by Anestezia** [comment]
Количество редактируется, вопросов к операции нет. все исправлено.
