### ISSUE TITLE
В справочнике счетов в банках список операций в фильтре и меню ограничен в зависимости от наличия валюты

### ISSUE THREAD

**Issue by shevchuk-vadim** [a2develop/testing#24]

**Comment by Anestezia** [comment]
У меня на счету 70 дол., а список операций ограничен все равно. 
![image](https://user-images.githubusercontent.com/42540074/45205524-165a1200-b28b-11e8-8502-61d9787a5ed5.png)

**Comment by Anestezia** [comment]
Теперь все работает, как задумано.
