### ISSUE TITLE
Список операций в разделах "Придбання", "Продажі". Экспорта списка операций в файл в формате Excel

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#241]
[760](https://github.com/a2develop/bugTracker/issues/760)
Рядом с выбором периода кнопка "Експортувати до Excel".
Проверить экспорт.

**Comment by Anestezia** [comment]
Работает. Качается весь, а не постранично -- это хорошо.
Вопрос: Если сделать отбор по критериям: контрагент, дата, вид документа, примечание (особенно это!), то все равно качается весь список. Может понадобиться именно качать список с учетом отбора. Проводить отбор позже непосредственно в екселе не совсем удобно - данные перемешивает.

**Comment by AlexeyTishkin** [comment]
> Вопрос: Если сделать отбор по критериям: контрагент, дата, вид документа, примечание (особенно это!), то все равно качается весь список. 

Да. Файл формируется без связи с фильтрами списка. И это везде так: в объектах, контрагентах.

> Может понадобиться именно качать список с учетом отбора. 

Тогда - отдельный issue. Этот закрываю.
