### ISSUE TITLE
Групповой учет однотипных необоротных активов

### ISSUE THREAD

**Issue by htrofymova** [a2develop/testing#243]
Реализована возможность группового учета однотипных необоротных активов. 
Нужно проверить "цепочку": ввод в эксплуатацию - расчет аммортизации -выбытие/перемещение

**Comment by Anestezia** [comment]
Все ок, только списать можно тоже только группой, так как один на всех инв. номер. 
Вопрос по материалам, на 152 счете уже партия исчерпана, а остаток показывается, и проводится документ. Правда после распроведения его не провести уже -- остаток не соответствует.

**Comment by Anestezia** [comment]
Исправлено, подтверждаю.
