### ISSUE TITLE
Взнос в уставный фонд основными средствами

### ISSUE THREAD

**Issue by htrofymova** [a2develop/testing#247]
Добавлены операции:
1. Внесення ОЗ до статутного капіталу (емітент) - делает тот, кто получает ОС в свой уставный капитал. После этой операции ОС можно вводить в эксплуатацию обычным порядком.
2. Внесення ОЗ до статутного капіталу (інвестор) -  делает тот, кто вносит свои ОС в уставный капитал другого предприятия. Прежде чем передавать ОС, нужно его вывести из эксплуатации так же, как для продажи.
Нужно проверить: создание-заполнение-сохранение-проведение.

**Comment by Anestezia** [comment]
Порядок
