### ISSUE TITLE
Декларация НДС. Приложения 1, 5.

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#25]
Изменился принцип создания. Теперь создаются как связанные отчеты к Декларации НДС.
Необходимо протестировать создания для юр. лица и физ. лица.

**Comment by Anestezia** [comment]
Все работает корректно, информация подтягивается в текущем периоде. В Сонату переносится и проходит проверку Д(1) и Д(5) хорошо, А сама декларация з ПДВ в Сонате выдает снова такой глюк, как при арифметическом превышении обязательства над кредитом, выдает ошибку, типа кредит должен превышать.
![image](https://user-images.githubusercontent.com/42540074/45214259-a35c9580-b2a2-11e8-890b-4fa76d18d1f5.png)

**Comment by Anestezia** [comment]
Так как у нас нет такого документа, как Уточняющая декларация ПДВ, а Д1 и Д5 прикреплены к основной декларации, то эти документы нельзя сделать уточняющими, хотя в бланке такая отметка есть, но она недоступна.

**Comment by AlexeyTishkin** [comment]
> А сама декларация з ПДВ в Сонате выдает снова такой глюк, как при арифметическом превышении обязательства над кредитом, выдает ошибку, типа кредит должен превышать.

Строку 9 не вижу, а 17 = 0. Т.е. 17 - 9 будет меньше 0. Там же вроде написано, что "позитивне значення". Какая цифра там должна быть ?

**Comment by AlexeyTishkin** [comment]
> Так как у нас нет такого документа, как Уточняющая декларация ПДВ

Будет.

> а Д1 и Д5 прикреплены к основной декларации, то эти документы нельзя сделать уточняющими, хотя в бланке такая отметка есть, но она недоступна.

Из уточняющей они будут создаваться уточняющими.

**Comment by Anestezia** [comment]
Если мы в дальнейшем делаем уточняющий отчет по ПДВ, то при формировании Додатков Д1 и Д5 не за текущий период, а, например, за более ранние, информация заполняется автоматически только из текущего периода. При этом в шапке документа указывается период ранний (заданный нами в главном документе).  Когда будет вводиться документ уточненка, лучше эти характеристики учесть. Или все вручную удалять и перезаполнять.

**Comment by AlexeyTishkin** [comment]
Если период меняется внутри Декларации (а не при создании), то нужно нажимать кнопку "Заполнить" в самой Декларации и в Приложениях.

**Comment by Anestezia** [comment]
А сама декларация з ПДВ в Сонате выдает снова такой глюк, как при арифметическом превышении обязательства над кредитом, выдает ошибку, типа кредит должен превышать.

Строку 9 не вижу, а 17 = 0. Т.е. 17 - 9 будет меньше 0. Там же вроде написано, что "позитивне значення". Какая цифра там должна быть ?

Там арифметика правильная. Строка 9 = 430, строка 17=0. Строка 18=430, а строка 19 и должна быть равна 0. При нажатии кнопки Консолидация данных в Сонате или Розрахунок, форма как бы обновляется, и эту ошибку уже не выдает. Вот я и думаю, это Сонатовский глюк на всех поголовно Декл. или только наши как-то не так переносятся.

**Comment by AlexeyTishkin** [comment]
Если вначале сформировать XML, а потом его затянуть в Сонату, такая же ошибка будет ?

**Comment by Anestezia** [comment]
Если период меняется внутри Декларации (а не при создании), то нужно нажимать кнопку "Заполнить" в самой Декларации и в Приложениях.

Декларация после задания раннего периода при нажатии кнопки Заполнить подтягивает данные этого раннего периода, а Додатки 1 и 5, после нажатия этой кнопки, тянут данные только текущего периода. Видимо, привязано к дате заполнения, а не к периоду. Декларация привязана к периоду и независимо от даты заполнения тянет данные за нужный период.

**Comment by AlexeyTishkin** [comment]
> Декларация после задания раннего периода при нажатии кнопки Заполнить подтягивает данные этого раннего периода, а Додатки 1 и 5, после нажатия этой кнопки, тянут данные только текущего периода.

Проверю.

**Comment by Anestezia** [comment]
https://github.com/a2develop/testing/issues/25#issuecomment-419405434

То же самое выдает, если через хмл затягивать.

**Comment by AlexeyTishkin** [comment]
Тогда можно связаться со службой поддержки Сонаты, дать XML и спросить почему ругается, если арифметика правильная.

**Comment by AlexeyTishkin** [comment]
> Так как у нас нет такого документа, как Уточняющая декларация ПДВ, а Д1 и Д5 прикреплены к основной декларации, то эти документы нельзя сделать уточняющими, хотя в бланке такая отметка есть, но она недоступна.

Уже есть :) Сделал отдельный issue для тестирования https://github.com/a2develop/testing/issues/38

**Comment by AlexeyTishkin** [comment]
> Декларация после задания раннего периода при нажатии кнопки Заполнить подтягивает данные этого раннего периода, а Додатки 1 и 5, после нажатия этой кнопки, тянут данные только текущего периода. Видимо, привязано к дате заполнения, а не к периоду. Декларация привязана к периоду и независимо от даты заполнения тянет данные за нужный период.

Исправил заполнение после изменения даты внутри отчета. Issue для тестирования https://github.com/a2develop/testing/issues/39

**Comment by AlexeyTishkin** [comment]
Этот issue можно закрывать ?

**Comment by Anestezia** [comment]
Можно закрывать.
