### ISSUE TITLE
Счет исходящий, Расходная накладная. Печатная форма. Договор

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#252]
[822](https://github.com/a2develop/bugTracker/issues/822)

Проверить печать, экспорт в PDF, изображение:
1. Договор не выбран.
2. Договор с обычным названием.
3. Договор с длинным названием.

В Расходной накладной проверить печать длинного поля "Через кого".

**Comment by Anestezia** [comment]
![image](https://user-images.githubusercontent.com/42540074/52406368-34e06580-2ad6-11e9-92c1-a382a2187a7b.png)
Чуть сливаются в формате Рисунок жирные условия договора

Остальное все ок, в разных форматах и с разным количеством символов

**Comment by AlexeyTishkin** [comment]
> Чуть сливаются в формате Рисунок жирные условия договора

Подкорректировал. Сейчас как ?

**Comment by Anestezia** [comment]
Сейчас достаточно места между символами, читается нормально. На деве.
