### ISSUE TITLE
Операция "Виставлення інвойсу"

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#253]
[816](https://github.com/a2develop/bugTracker/issues/816)

Новая операция.

Проверить:
1. Создание.
2. Редактирование.
3. Проведение.
4. Создание связанных.
5. Отмену проведения.
6. Удаление.

**Comment by AndriyNesterenya** [comment]
Принял в работу.
Буду пробовать проверить на собственном реальном кейсе с молдаванами :)

**Comment by AlexeyTishkin** [comment]
В свойствах "моей фирмы" сейчас нельзя внести английское наименование и адрес.
Issue есть [399](https://github.com/a2develop/bugTracker/issues/399).
Сделаю на следующей неделе.

**Comment by AndriyNesterenya** [comment]
У нас сейчас по умолчанию выводится строка "Represented by , who acts according to the charter | в особі , що діє на підставі Статуту"

Соображения:
1. Эта строка не всем нужна.
Условный ФОП действует сам, без представителя (если не указано другое лицо из сотрудников или семьи).
2. Поле для ввода этого лица есть только одно, украиноязычное, и оно же подставляется в англоязычный вариант. 
Получается "Represented by Вася Пупкин, who acts according..."
3. Не все действуют на основании Статута. 
Те же ФОПы или вообще ничего тут не пишут, или діє на підставі (народные варианты) виписки з ЄДРПОУ, или свідоцтва про реєстрацію.

**Comment by AlexeyTishkin** [comment]
Надо это все формализовать и преобразовать в:
1. Выкинуть...
2. Показывать, если...
3. Дать редактировать..

:)

**Comment by AndriyNesterenya** [comment]
Боюсь сейчас лишнего натребовать - изучаю матчасть.

Для юриков нужно или добавлять поле для ФИО представителя в англ. варианте, или и русскоязычное удалять, и давать просто редактировать поля в самом документе произвольно.

Ищу живых юзеров, продающих на экспорт что-то, кроме услуг.
По результатам буду приходить с идеями.

**Comment by AlexeyTishkin** [comment]
Давай тогда это общее issue закрывать и делать отдельные на конкретные вопросы.

**Comment by AndriyNesterenya** [comment]
Поддерживаю
