### ISSUE TITLE
В документы раздела "Бухгалтерия" добавлен механизм исправления ошибок

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#255]
[823](https://github.com/a2develop/bugTracker/issues/823)

Проверить возможность корректировки.

**Comment by Anestezia** [comment]
У нас в банковских документах поле называется не "Примітка", а "Призначення"
![image](https://user-images.githubusercontent.com/42540074/52553940-f2789a80-2ded-11e9-807e-4dd36ca09f85.png)
![image](https://user-images.githubusercontent.com/42540074/52553886-cb21cd80-2ded-11e9-92d7-994b895548ce.png)
В списке операций это поле тоже называется "Примітка"

![image](https://user-images.githubusercontent.com/42540074/52553965-fefcf300-2ded-11e9-8648-ef0cef13ff98.png)
В остальном все норм. работает

**Comment by AlexeyTishkin** [comment]
Примечание - свойство документа, такое же как дата и номер. В некоторых строгих документах это поле отсутствует (в качестве "Примечание") и используется для других целей (в качестве "Назначение платежа").
Но все равно это именно "Примечание документа".
Если вопрос принципиальный - нужно обсуждать перенос "Назначения платежа" в другое свойство документа.
