### ISSUE TITLE
Формы "Налоговая накладная", "Расчет корректировки к НН". Поле "Посадова..."

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#256]
[824](https://github.com/a2develop/bugTracker/issues/824)
Изменен формат отображения значения в поле "Посадова (уповноважена) особа / фізична особа": вначале инициалы, потом фамилия.
Проверить отображение.

**Comment by Anestezia** [comment]
В хмл идет все равно сначала фамилия, потом инициалы
![image](https://user-images.githubusercontent.com/42540074/52553602-b0028e00-2dec-11e9-8230-d7ca5aec0dec.png)
![image](https://user-images.githubusercontent.com/42540074/52553614-bc86e680-2dec-11e9-954d-8085c77a702e.png)
в Сонату тоже 
![image](https://user-images.githubusercontent.com/42540074/52553653-dfb19600-2dec-11e9-82b9-64be6b14aaf1.png)
Корректировка тоже так переносит.

**Comment by AlexeyTishkin** [comment]
Исправил.

**Comment by Anestezia** [comment]
Да, можно закрывать
