### ISSUE TITLE
Отчет "Податкова декларація з податку на прибуток підприємств"

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#260]
Проверить:
1. Создание.
2. Редактирование.
3. Заполнение.

По поводу проверки экспорта в XML напишу дополнительно.

**Comment by Anestezia** [comment]
нормально сохраняются, заполняются, проводятся, отправляются в сонату кнопкой и через хмл, сонатовские проверки проходят. Номер паспорта вместо инн тоже норм проводит и в сонату подтягивает.
