### ISSUE TITLE
Добавлен отчет "Розрахунок частки сільськогосподарського товаровиробництва" (J0303308).

### ISSUE THREAD

**Issue by shevchuk-vadim** [a2develop/testing#262]

**Comment by Anestezia** [comment]
Заполняется вручную, валидаторы работают, сохраняется, проводится, эскпортируется в хмл, отправляется в Сонату, сонатовскую проверку проходит.
Можно чуть подровнять по центру фамилии
![image](https://user-images.githubusercontent.com/42540074/52947461-721ee000-337f-11e9-9f99-9762757a3c29.png)
В Сонату переносятся уже по центру
![image](https://user-images.githubusercontent.com/42540074/52947481-82cf5600-337f-11e9-963c-246fe2472150.png)
