### ISSUE TITLE
В фискальных отчетах добавлен запрет проведения, если существует проведенный отчет с такими же реквизитами.

### ISSUE THREAD

**Issue by shevchuk-vadim** [a2develop/testing#265]
Реквизиты, которые проверяются:
код отчета,
отчетный период,
номер нового отчетного или уточняющего документа (для отчетного документа равен 0),
номер однотопного документа в периоде (для отчетов, которые подаются однокоратно, равен 1).

**Comment by Anestezia** [comment]
Ошибок не нашла. Запрет есть.
