### ISSUE TITLE
Всплывающее окно для контрагента

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#266]
[842](https://github.com/a2develop/bugTracker/issues/842)
Для нерезидента добавлены отчеты "Оборотна відомість за розрахунками з покупцями у валюті", "Оборотна відомість за розрахунками з постачальниками у валюті". 
Проверить построение.

**Comment by Anestezia** [comment]
Вроде все ок. К чему придраться не нашла.
