### ISSUE TITLE
Во вступительном балансе по произвольному счету добавлена очистка данных, ненужных для выбранного счета

### ISSUE THREAD

**Issue by shevchuk-vadim** [a2develop/testing#268]

**Comment by Anestezia** [comment]
Данные очищаются, после сохранения и после проведения-распроведения-изменения счета.
Вопрос: Здесь должны из списка контрагентов разве выбираться? на 661 Особи.
![image](https://user-images.githubusercontent.com/42540074/53893466-ea9bc700-4036-11e9-83de-80c4d3065501.png)

**Comment by Anestezia** [comment]
Исправлено, список физических лиц по 661 счету в подборе есть. Можно закрывать
