### ISSUE TITLE
В балансе (S0100113) добавлены проверки статей

### ISSUE THREAD

**Issue by shevchuk-vadim** [a2develop/testing#269]
1) запрет на ввод отрицательных чисел (кроме статей прибыли и дополнительного капитала),
2) запрет превышения износа (накопленной амортизации) над первоначальной стоимостью,
3) запрет превышения сумм незарегистрированного, неоплаченного, и изъятого капитала над суммой уставного капитала,
3) запрет превышения суммы статей "в том числе" над суммой детализируемой статьи.

**Comment by Anestezia** [comment]
Не совсем понятная подсказка по этой строке. 
![image](https://user-images.githubusercontent.com/42540074/53945273-ecfb3100-40c9-11e9-8545-3ad5ad6c3b5d.png)

Предлагаю что-то типа: Значення не може бути меншим, ніж сума значень по рядкам 1166, 1167
Быть может аналогично и по другим сделать.
1. Запрет на ввод отрицательных выполняется.
2. Есть запрет
3. Запретов по капиталам не увидела. Что-то не выполняется. Ставлю любые превышающие суммы.
4. есть

**Comment by Anestezia** [comment]
Есть запрет по капиталу. Можно закрывать.
