### ISSUE TITLE
Декларация о Прибыли. Расчет значения суммы в строке 6

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#271]
[872](https://github.com/a2develop/bugTracker/issues/872)

Проверить расчет.

**Comment by Anestezia** [comment]
Да, минус уже не идет в 6, 17 и 19 строки. Эти строки при отрицательном значении остаются пустыми. По строке 19 вопросов нет. Я так понимаю, что годовики строку 18 не заполняют, соответственно проблем быть не должно

**Comment by AlexeyTishkin** [comment]
Все правильно ? Закрываем ?
