### ISSUE TITLE
Механизм исправления проведенного документа с последующим перепроведением связанных документов

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#277]

**Comment by GalinaLuk** [comment]
Я изменила курс в ГТД с 31,5 на 31,45. По идее, это должно было повлиять на уменьшение 
стоимости товара. и на проводки списания себестоимости при дальнейшей продаже. У меня таких изменений не произошло

**Comment by AlexeyTishkin** [comment]
> Я изменила курс в ГТД с 31,5 на 31,45

После изменения курса делался пересчет (кнопка "перерахувати" справа от валюты) ?

**Comment by GalinaLuk** [comment]
да, с кнопкой работает, но я ее не увидела, пока не сказали, что она должна появляться.

**Comment by AlexeyTishkin** [comment]
> но я ее не увидела, пока не сказали, что она должна появляться.

Такой алгоритм пересчета (сумм после изменения курса) в самой ГТД.
В данном случае, к механизму исправления, это не имеет отношения.

**Comment by Anestezia** [comment]
Как по мне, то работает. в связанные доки идет, если нет состыковки по остаткам, то показывает где именно, начиная с первого документа в котором произошла нехватка и который не удалось провести.

**Comment by AlexeyTishkin** [comment]
Отлично! Все остальное - в рабочем порядке.
