### ISSUE TITLE
Операция "Реалізація запасів". Исправлена ошибка, из-за которой отображался остаток с учетом возврата, оформленного будущим числом

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#278]
[888](https://github.com/a2develop/bugTracker/issues/888)

Проверить отображение остатка, сформированного возвратной накладной 26.03 в расходной накладной от 25.03. Проверить проведение расходной накладной от 25.03.

**Comment by Anestezia** [comment]
Видит нехватку товара на складе на 25.03. красное поле в количестве товара
меняю в накладной число на 26.03- уже видит появившийся остаток, красное поле исчезло и можно провести.
