### ISSUE TITLE
Операция "Реалізація послуг з матеріалами". Создание связанной НН

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#280]
[883](https://github.com/a2develop/bugTracker/issues/883)
Изменен порядок следования номенклатуры (вначале услуги по номеру строки, затем материалы по номеру строки).
Проверить создание НН.

**Comment by Anestezia** [comment]
у меня вперемешку в счете услуги и материалы, в Н накладной порядок просто идентичный сохранился.

**Comment by AlexeyTishkin** [comment]
> у меня вперемешку в счете услуги и материалы, в Н накладной порядок просто идентичный сохранился.

Вопрос был о создании НН из Счета или из Акта ?

Если из Счета, то порядок должен быть идентичен Счету.
Если из Акта, то в НН вначале услуги по порядку, потом материалы по порядку.

**Comment by Anestezia** [comment]
да, подтверждаю. все работает. В любом случае уже понятно пользователю.
