### ISSUE TITLE
Опция "ПДВ в т.ч."

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#281]
[885](https://github.com/a2develop/bugTracker/issues/885).
Добавлена в операции "Виставлення рахунку", "Реалізація запасів", "Реалізація послуг", "Реалізація послуг з матеріалами".
Проверить расчет.

**Comment by Anestezia** [comment]
в общем, функционал есть, работает. Подгонка, правда, смущает. Ну, посмотрим, что пользователи на реальных кейсах еще предложат.
