### ISSUE TITLE
Новый раздел меню Кассові  ордери (beta).

### ISSUE THREAD

**Issue by htrofymova** [a2develop/testing#283]
В Бухгалтерии создан новый раздел меню "Касові ордери" в новом интерфейсе. Нужно проверить все режимы. Также нужны пожелания по внешнему виду, удобству, понятности, функциональности.

**Comment by Anestezia** [comment]
Не идет в печатную форму информация о Паспорте
![image](https://user-images.githubusercontent.com/42540074/55315895-fb90fa00-5475-11e9-854a-cc99e332243c.png)
![image](https://user-images.githubusercontent.com/42540074/55315948-15324180-5476-11e9-9357-5d91c55100f1.png)
Также как и в банке предлагается сделать на видном месте кнопки 
![Касса](https://user-images.githubusercontent.com/42540074/55316627-80304800-5477-11e9-88a8-be96c3819627.jpg)
На печать не выводятся фио подписантов документа
Не выводиться кореспондуючий рахунок
Вид надходжень прописан и в приходном кассовом ордере и в расходном именно с такой формулировкой.
Нет второго счета в проводке и не проводится документ.
![image](https://user-images.githubusercontent.com/42540074/55318264-0e59fd80-547b-11e9-98b9-6a760aaa95f2.png)
Немного не помещается в окно при подборе, и вообще Повернення ЗП, а подбор через список контрагентов
![image](https://user-images.githubusercontent.com/42540074/55318508-9e984280-547b-11e9-9a2c-eee05fa88d6e.png)

И нужна внутри кнопка "Видалити"
