### ISSUE TITLE
Операции "Отримання рахунку", "Виставлення рахунку". Создание/открытие существующих документов оплаты

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#284]
Осуществляется в новом интерфейсе (в диалоге).
Проверить создание/редактирование/отображение.

**Comment by Anestezia** [comment]
1.В старых изнутри счета открывается в диалоге, сохраняет изменения корректировку номера и прим. Добавляю комменты, внутри счета не показывается наличие комментов,  в списке операций тоже. рисунок тот же.
2.В оплате, созданной из счета, и отображаемой в списке операций нет возможности задействовать функции ДІЇ.
![image](https://user-images.githubusercontent.com/42540074/55169008-a2c31800-517c-11e9-856e-0033f3b3ba98.png)
После отмены проведения платежки, мы переместились на страницу счета и там все еще висел признак Проведено, обновлять понадобилось.
Нет возможности внести коментарий во входящие платежи по банку
![image](https://user-images.githubusercontent.com/42540074/55176706-4f57c680-518a-11e9-95c2-c887916f63a4.png)


В остальном: создание/редактирование/отображение -- все ок. даже созжается вторая платежка, если я не всю сумму по счету заплатила.

**Comment by AlexeyTishkin** [comment]
> После отмены проведения платежки, мы переместились на страницу счета и там все еще висел признак Проведено, обновлять понадобилось.

Исправил.

**Comment by AlexeyTishkin** [comment]
> Нет возможности внести коментарий во входящие платежи по банку

В issue по платежкам.

**Comment by AlexeyTishkin** [comment]
Список операций пока не трогаем. Будет новый.

**Comment by Anestezia** [comment]
Исправлено, подтверждаю.
