### ISSUE TITLE
Операция "Виставлення рахунку". Печатная форма. Коды объектов

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#285]
Диалог "Колонтитули форми для друку" переименован в "Налаштування форми для друку". В этот диалог добавлен выбор кода (Артикул, Код УКТ ЗЕД) который будет отображаться в печатной форме в колонке с кодом.
Проверить варианты печати.

**Comment by Anestezia** [comment]
1. Внешне не переименовано, клиент не догадается. Предлагаю в самой форме написать Верхній колонтитул/Налаштування форми..так же  и нижним.
2. А если кому-то надо вывести на печать и штрихкод?
3. А почему на выбор либо что-то одно, либо другое.  
У нас был вариант как все разместить. 
4. Весь артикул не влезает, уже были просьбы увеличить поле по количеству символов на печати
![image](https://user-images.githubusercontent.com/42540074/55163049-be74f100-5171-11e9-9016-2413588b5158.png)
5. в ворде смещены строки. хотя это уже попытка указать весь код, просто в двух строках
![image](https://user-images.githubusercontent.com/42540074/55163283-2f1c0d80-5172-11e9-8b49-37fe6ae6f813.png)
А вообще, все работает. Можно запускать

**Comment by AlexeyTishkin** [comment]
"Верхний колонтитул" - это не относится к кнопке "Змінити".
Тогда уже кнопку переименовать в "Налаштування" и иконку сменить.

**Comment by AlexeyTishkin** [comment]
> А если кому-то надо вывести на печать и штрихкод?
> А почему на выбор либо что-то одно, либо другое.

Это все к обсуждению. Окончательный вариант не принят. Сделали очередное промежуточное решение.

**Comment by AlexeyTishkin** [comment]
> А вообще, все работает. Можно запускать

Тогда этот issue закрываю.
