### ISSUE TITLE
Операция "Реалізація послуг з матеріалами". Создание связанной налоговой накладной.

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#286]
[884](https://github.com/a2develop/bugTracker/issues/884)
При заполении добавлено округление цен (если это не искажает сумму) до 2-х знаков. 
Проверить создание НН на примере цен из issue.

**Comment by Anestezia** [comment]
теперь ндс на копейку больше в последней позиции, чем в тестовом примере.
![image](https://user-images.githubusercontent.com/42540074/55242916-e5512700-5246-11e9-93e9-cc67e3e0bf0a.png) было 540,50.

ндс старой формы последней позиции в акте 72,83, а в новой 72,84. По этой позиции 72,8346. Скорее всего перевешивают округления верхних позиций.
В налоговой им тоже не понравится, что цены изменились на 1 коп. во 2 и 4 позициях.
![image](https://user-images.githubusercontent.com/42540074/55245578-15e78f80-524c-11e9-9708-40bead9f3e90.png)

а реально создать алгоритм, чтоб цены внутри подразумевали такую корректировку, а выводились на печать, какими в акте были. И НДС чтоб отображался, как следствие, на один знак больше после запятой. Базу налогообложения округлять до 2 знаков, ценам исходным это не повредит.

**Comment by AlexeyTishkin** [comment]
А можешь создать этот Акт на тестовом аккаунте ?

**Comment by Anestezia** [comment]
Ну, цены уже не меняются, думаю так пойдет. 
![image](https://user-images.githubusercontent.com/42540074/55548023-42335e00-56db-11e9-9e38-52eb428bd8a0.png)
