### ISSUE TITLE
Создан новый раздел "Зарплата" (зарплатный калькулятор). Нужно проверить все операции этого раздела

### ISSUE THREAD

**Issue by Illya-Lykhachov** [a2develop/testing#287]

**Comment by Anestezia** [comment]
1. Долго грузится печать
2. Кассовый ордер на основании ведомости: Сумма не редактируется. 
3. Нажала кнопку Видалити, в исходной ведомости еще остался Призрак, так как эти новоинтерфейсные формы обновлять нельзя - они закрываются, то это может смутить пользователя. Я-то потом распровела ведомость нормально и все обновилось и ушло, но пользователи могут подумать, что-то не так.
![image](https://user-images.githubusercontent.com/42540074/55614263-42902f80-5795-11e9-8725-8cb109931f06.png)
4. 
![image](https://user-images.githubusercontent.com/42540074/55619512-7ffaba00-57a1-11e9-96ee-aba3d8aa8777.png)
5. В списке все документы черные, не открываются кликом.
![image](https://user-images.githubusercontent.com/42540074/55619642-c5b78280-57a1-11e9-9c78-16589000bfde.png)
6. В ведомости нет кнопки Видалити  - неудобно
![image](https://user-images.githubusercontent.com/42540074/55619813-2ba40a00-57a2-11e9-9a01-cc93d4e9a9ee.png)
Удалить из списка проведенный документ тоже невозможно. Нет таких действий с подчиненными.
7. Немного не влезла буква инициалов на печати при длинной фамилии. Вижу, что нет переноса.
![image](https://user-images.githubusercontent.com/42540074/55620627-fe585b80-57a3-11e9-9508-0f9d4ec3679a.png)
8. Сумма по банку, опять таки не редактируется в ведомости, что может стать неудобством.
Будет ли кнопка для Внесения изменений в проведенном документе?
9. То, что Додатково подставляется автоматически в платежке, не редактируется и не выбирается
10. На проекте есть рядом с увеличителем три точки "Зминити", а в Договоре такого нет.
![image](https://user-images.githubusercontent.com/42540074/55623983-387a2b00-57ad-11e9-867c-2fb07a9b2ffa.png)
11. Сообщение - текст с опечаткой: слово Будуть (Буде?)
![image](https://user-images.githubusercontent.com/42540074/55624897-f43c5a00-57af-11e9-8ad8-62343be84d22.png)
12. Дата при 1 клике с марта перепрыгивает на май, апрель - только клик на стрелку назад. (Так и в старом интерфейсе и в других разделах не плохо было бы проверить)
Используется как база какое-то внутреннее значение, а не то, которое я указала. Скорее всего из кадров тянет. Хорошо это или плохо?
![image](https://user-images.githubusercontent.com/42540074/55625144-978d6f00-57b0-11e9-9f60-40f44aaff78c.png) 
Также на этом фото в разделе Разом: есть графа Оклад, она не совпадает со значением графы Оклад, которую мы заполнили рядом с фамилией. Если это правильно, тогда она должна называться не Оклад, а как-то еще. Но не у всех такое. Так и не поняла, откуда считает.
13. Так и не увидела Донарахування до минимальной зп. А вот когда я поставила галочку Сумисник, а потом ее убрала, оно пересчиталось. А до этого непересчитанное так и провелось.
14. При длинной фамилии строка слева уходит и нет крестика удалить, и скрола тоже нет.
![image](https://user-images.githubusercontent.com/42540074/55626059-226f6900-57b3-11e9-98f3-863a6cc2e627.png)
Подвинула мышкой границу, главное, чтоб и пользователь догадался так сделать, а то гневаться будет.
15. Вопрос: если совершенно не будет привязки к Персоналу, то как заполнить Зарплатный проект, чтоб можно было хоть как-то деньги на карту сотруднику бросить?
И если у меня сотрудники вне зарплатного проекта, а я им просто на карту выплачиваю (это была жалоба реального юзера)
Соответственно, нельзя ли добавить внутрь таблицы кнопки Добавить / Удалить строку? Если больше одной строки, и заполнили колонку Зарплатный проект, значит одна платежка на транзитный счет. Если одна или несколько строк и не заполнена строка Зарплатный проект, то возможность создавать на основании несколько платежек по одной для каждой строки.
16. Также, если у меня изначально было поле Зарплатный проект пустое, потом я его выбрала, увидела, что мне это не подходит, то у меня должна быть возможность выбрать снова пустое поле.
17. Добавить распечатки всех ведомостей с датами и номером.

**Comment by Illya-Lykhachov** [comment]
1. Долго грузится печать
Быстрей не будет (оптимизировал запрос и структуру данных до предела). Документы зарплаты по структуре гораздо сложней бухгалтерских. Поэтому они и грузятся и обрабатываются дольше. Плюс печать в последней версии - это, кроме формирования документа, ещё и экспорт в pdf (т. е. 2 действия вместо одного раньше).

**Comment by Illya-Lykhachov** [comment]
2. Кассовый ордер на основании ведомости: Сумма не редактируется.
Посмотрел - так специально сделано в самом кассовом ордере. Вопрос к Галине.

**Comment by Illya-Lykhachov** [comment]
6. В ведомости нет кнопки Видалити - неудобно
Добавил во все документы кнопку "Удалить"

**Comment by Illya-Lykhachov** [comment]
3. Нажала кнопку Видалити, в исходной ведомости еще остался Призрак...
Призрака прогнал

**Comment by Illya-Lykhachov** [comment]
4. 
Посмотрел в журнале - действительно односторонняя проводка. Но это кассовый ордер, а не зарплата. Вопрос к Галине.

**Comment by Illya-Lykhachov** [comment]
5. В списке все документы черные, не открываются кликом.
Специально так сделал. Если сделать открытие по клику в любом поле, то любой **нечаянный** клик приводит к открытию документа.
Мой вариант - это работающее предложение, со следующим принципом:

- двойной клик - открывает документ (переходим в другой контекст);
-  одинарный клик - всплывает окно с подсказкой или расшифровкой (остаёмся в текущем контексте).

**Comment by htrofymova** [comment]
по п.2 Так всегда и было, думаю, что это правильно. 
по п.4 Исправлено

**Comment by Illya-Lykhachov** [comment]
7. Немного не влезла буква инициалов на печати при длинной фамилии. Вижу, что нет переноса.
Сделал пошире и добавил перенос

**Comment by Illya-Lykhachov** [comment]
8. Сумма по банку, опять таки не редактируется в ведомости, что может стать неудобством.
Будет ли кнопка для Внесения изменений в проведенном документе?
Банковские и кассовые документы используются из разделов банка и кассы. Это не мои вопросы.
Кнопку для изменения проведенных документов добавил (под кнопкой "Ещё")

**Comment by Illya-Lykhachov** [comment]
9. То, что Додатково подставляется автоматически в платежке, не редактируется и не выбирается
10. На проекте есть рядом с увеличителем три точки "Зминити", а в Договоре такого нет.
См. выше

**Comment by Illya-Lykhachov** [comment]
11. Сообщение - текст с опечаткой: слово Будуть (Буде?)
Исправлено

**Comment by Illya-Lykhachov** [comment]
12. Дата при 1 клике с марта перепрыгивает на май, апрель - только клик на стрелку назад. (Так и в старом интерфейсе и в других разделах не плохо было бы проверить)

Это к Кухтину. Он нам (прикладным программистам) дал control (календарь), во внутрь мы залезть не можем.
PS. Проблему отловил и Кухтину issue написал.

**Comment by Illya-Lykhachov** [comment]
12. ... Используется как база какое-то внутреннее значение, а не то, которое я указала. Скорее всего из кадров тянет. Хорошо это или плохо?

Это правильно. Используется вся начисленная зарплата **ЗА** указанный период. Иначе льготы и ограничения правильно не определить. При этом вытягивается и весь уже удержанный ранее налог **ЗА** этот же период. Считается **полная** сумма налога и **доудерживается** с учётом ранее удержанного.
При таком подходе всё по закону и не требуется годовой перерасчёт.

**Comment by Illya-Lykhachov** [comment]
12. ... Также на этом фото в разделе Разом: есть графа Оклад, она не совпадает со значением графы Оклад, которую мы заполнили рядом с фамилией. Если это правильно, тогда она должна называться не Оклад, а как-то еще. Но не у всех такое. Так и не поняла, откуда считает.

"Оклад" - имеется в виду "начислено по окладу" или "повременная зарплата". Если есть предложения как коротко и понятно назвать - давай.
Не совпадает потому что фактически отработанные дни не совпадают с плановыми (неполный месяц).

**Comment by Illya-Lykhachov** [comment]
13. Так и не увидела Донарахування до минимальной зп. А вот когда я поставила галочку Сумисник, а потом ее убрала, оно пересчиталось. А до этого непересчитанное так и провелось.

Исправлено

**Comment by Illya-Lykhachov** [comment]
14. При длинной фамилии строка слева уходит и нет крестика удалить, и скрола тоже нет.

Исправил. Теперь длинные строки переносятся.

**Comment by Illya-Lykhachov** [comment]
15. Вопрос: если совершенно не будет привязки к Персоналу, то как заполнить Зарплатный проект, чтоб можно было хоть как-то деньги на карту сотруднику бросить?

В раздел "Зарплата" добавлены необходимые подразделы, в т.ч. "Зарплатный проект"

**Comment by Illya-Lykhachov** [comment]
> И если у меня сотрудники вне зарплатного проекта, а я им просто на карту выплачиваю (это была жалоба реального юзера)
> Соответственно, нельзя ли добавить внутрь таблицы кнопки Добавить / Удалить строку? Если больше одной строки, и заполнили колонку Зарплатный проект, значит одна платежка на транзитный счет. Если одна или несколько строк и не заполнена строка Зарплатный проект, то возможность создавать на основании несколько платежек по одной для каждой строки.

Если зарплата выплачивается сотруднику на его личный счёт в банке (не в рамках зарплатного проекта), то делать ведомость вообще не нужно. Просто создаём платёж в банк, там и шаблон специальный есть - "Виплата зарплати фізичній особі". Таким же образом и по договорам ГПХ выплачиваем.

**Comment by Illya-Lykhachov** [comment]
16. Также, если у меня изначально было поле Зарплатный проект пустое, потом я его выбрала, увидела, что мне это не подходит, то у меня должна быть возможность выбрать снова пустое поле.

Так не получится. Это обязательное поле. Без зарплатного проекта перечисления на карты не будет.

**Comment by Illya-Lykhachov** [comment]
17. Добавить распечатки всех ведомостей с датами и номером.

Это отдельным issue

**Comment by Anestezia** [comment]
Исправленное подтверждаю. Из всего списка только переключение даты еще барахлит, но это не критично, всего ли пара лишних кликов.
