### ISSUE TITLE
Операции "Виставлення рахунку", "Реалізація", "Реалізація послуг з матеріалами"

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#289]
Для колонки "Цена с НДС" сделано форматирование значения до 2-х знаков после запятой.
В колонке "Цена без НДС" формат остался прежний, до 6-ти знаков.
Проверить отображение значений.

**Comment by Anestezia** [comment]
Да, все ок. 
Интересно, что на печать идет цена с двумя знаками. А вдруг мне важно с четырьмя вынести?
![image](https://user-images.githubusercontent.com/42540074/55554103-a3aef900-56ea-11e9-8feb-287f748ef37e.png)
Что на коробке -- то и в коробке!
![image](https://user-images.githubusercontent.com/42540074/55554193-dbb63c00-56ea-11e9-8d0a-dd58f1fce62b.png)

**Comment by AlexeyTishkin** [comment]
> Интересно, что на печать идет цена с двумя знаками. А вдруг мне важно с четырьмя вынести?

Это предмет отдельного обсуждения.

**Comment by AlexeyTishkin** [comment]
> Да, все ок.

Тогда это закрываю.
