### ISSUE TITLE
НН. Подстановка ИНН

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#29]
Исправлена подстановка ИНН покупателя и продавца.
[506](https://github.com/a2develop/bugTracker/issues/506)

- [ ] самостоятельный кредит

- [ ] связанный кредит

- [ ] самостоятельное обязательство

- [ ] связанное обязательство

- [ ] корректировка кредита

- [ ] корректировка обязательства

**Comment by Anestezia** [comment]
все уже в порядке в каждом документе.
