### ISSUE TITLE
Операции по умолчанию для входящего и исходящего платежей

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#290]
В свойства расчетного счета добавлен выбор операций по умолчанию для входящего и исходящего платежей. Эти операции используются при создании платежа вручную или при использовании механизма импорта из клиент-банка.
Проверить:
1. Выбор/изменение в свойствах расчетного счета.
2. Подстановку при ручном создании платежа.
3. Подстановку при импорте из клиент-банка.

**Comment by Anestezia** [comment]
1. Выбирается, изменяется без проблем.
2. В ручные платежки нового интерфейса подставляется.
3. Ждем тестирование этого.

**Comment by AlexeyTishkin** [comment]
Тестирование п.3 можно совместить с [296](https://github.com/a2develop/testing/issues/296).

**Comment by AndriyNesterenya** [comment]
3. При импорте входящего платежа работает - подставляет выбранную операцию.
При импорте исходящего платежа все по старому - подсвеченное красным поле с требованием выбрать операцию.

296 вроде ж проверяли и закрывали?

**Comment by AlexeyTishkin** [comment]
> При импорте исходящего платежа все по старому - подсвеченное красным поле с требованием выбрать операцию.

В свойствах счета какая операция выбрана ?

**Comment by AlexeyTishkin** [comment]
> 296 вроде ж проверяли и закрывали?

Да, закрыт.

**Comment by AndriyNesterenya** [comment]
3. Проверено. И исходящие и входящие выписки подставляют выбранные операции по умолчанию.
Долго гонял на примере Привата, еще поиграюсь остальными.

**Comment by AndriyNesterenya** [comment]
> В свойствах счета какая операция выбрана ?
Отбой тревоги - просто не сохранилась операция в админке.

Единственное, что слегка напрягает - что в свойствах фирмы и в счетах свойства счета разные.
Но это с непривычки, пройдет.

**Comment by AlexeyTishkin** [comment]
> Единственное, что слегка напрягает - что в свойствах фирмы и в счетах свойства счета разные.

В планах - единообразить :)
