### ISSUE TITLE
"Зарплатный калькулятор". Копирование документов

### ISSUE THREAD

**Issue by Illya-Lykhachov** [a2develop/testing#291]

**Comment by Anestezia** [comment]
Это не скопировалось
![image](https://user-images.githubusercontent.com/42540074/55728892-ba708b00-5a1d-11e9-9a8f-1d1ca5883bda.png)
Скопировала, провела, чтоб в списке у этого документа появилась отметка Проведен, нужно обновить.
![image](https://user-images.githubusercontent.com/42540074/55729080-1fc47c00-5a1e-11e9-9c8d-5260a23e83d9.png)
Остальное, вроде ок.

**Comment by Illya-Lykhachov** [comment]
исправлено

**Comment by Anestezia** [comment]
исправленное тоже копируется.
