### ISSUE TITLE
Новый раздел Підзвіт

### ISSUE THREAD

**Issue by htrofymova** [a2develop/testing#292]
Доработан новый раздел Підзвіт. Доработан "Звіт підзвітної особи...". Нужно проверить все ражимы в списке документов и документе "Звіт підзвітної особи..."

**Comment by Anestezia** [comment]
1. После проведения Автоматически создается новый отчет, пустой. Вместо того, чтобы остаться в этом же проведенном документе. 
2.  И если его закрыть, то в списке операций все равно остается эта новая непроведенная операция.
![image](https://user-images.githubusercontent.com/42540074/55951600-525db700-5c60-11e9-9440-3329d50734ad.png)
Попытка открыть такую операцию-призрак. Нужно автообновление списка.
![image](https://user-images.githubusercontent.com/42540074/55951624-62759680-5c60-11e9-85dd-a3a0d7e9389e.png)
3. Кнопки Дії в списке операций -- на печать выводится, копируется, но.. в таком документе нельзя ввести контрагента. Т.к. при нажатии на любое действие эта графа сбрасывается и вновь становится красной и пустой. При этом, на печати в  бланке выбранный контрагент фигурирует. если выбрала и сразу на печать нажала не проводя. Если сначала провести (тут бланк не закрывается сразу, как в первом случае), а потом нажать на печать, то контрагента и в печатной форме нет. 

3,5. Если при этом нажать на Провести, то выводится сообщение о том, что док проведен. При этом внешних признаков проведения внутри документа  нет. 
![image](https://user-images.githubusercontent.com/42540074/55952012-31e22c80-5c61-11e9-8265-d4983ef3563d.png)
В списке операций они все появились проведенные копии по числу количества попыток проведения.
4. Открывается вот так проведенная копия без контрагента
![image](https://user-images.githubusercontent.com/42540074/55952221-bb91fa00-5c61-11e9-9c81-3a532c0351f2.png)

![image](https://user-images.githubusercontent.com/42540074/55952249-ca78ac80-5c61-11e9-984d-be80ca6595a8.png)
этот документ явно не проведен. внутри он пуст, даже подотчетника нет. При обновлении кеша исчез.
5. Перевитрата видана только один раз, не зависимо от суммы. Я выдала через банк часть суммы, а часть хотела из кассы. Но такой возможности больше нет
![image](https://user-images.githubusercontent.com/42540074/55952689-dca71a80-5c62-11e9-9d41-dadb3729e50f.png)
6. И не очень хорошо, что при выборе фамилии в новом отчете сразу еще до проведения не подтягивается (как в старом) остатки по расчетам, должны ему за предыдущие разы или он должен. Это можно увидеть только после проведения, закрытия тут же создавшегося призрака, открытия только что проведенного документа. Долго.

**Comment by Anestezia** [comment]
С остальными операциями в списке так же:
по пунктам 1 и 2.  
3. Режим печати из списка операций -- нет бланка
![image](https://user-images.githubusercontent.com/42540074/55953566-1842e400-5c65-11e9-97a3-c2c3b09d2fc6.png) по операции платежка и ордер. Выдача. и повернення.
4. Так же в списке операций нет возможности определить не открывая документ, откуда именно была выдача, из кассы или из банка. Это не удобно. Нужен какой-то маркер.
5. В выдаче внутри документ называется Платижне доручення, а в Поверненні -- Вхідний платіж. Странно выглядит.

**Comment by htrofymova** [comment]
первая часть (авансовый отчет):
пп.1,2. Все явления, связанные с документами-призраками устранены  в корне.
пп.3.4, Не удается повторить ситуацию с контрагентом: поле "Кому" в таблице документа не является обязательным, не понятно, как удалось такого добиться. 
п.5. Так было всегда. если нужно расширение функционала - issue enhanecement.
п.6. При выборе подотчетного лица заполняется табличка с остатками расчетов и документами выдачи, если таковые имеются, не закрытые авансовыми отчетами. Не понятно, в какой ситуации этого не происходит. По призракам - см. выше.
вторая часть (прочие документы из списка):
пп.1.2 = пп.1.2. первой части
п.3. Исправлено
п.4. Добавлена колонка в названием операции
п.5. Так называются документы из раздела Банк-Платежи. Там не странно?

**Comment by Anestezia** [comment]
п.3 Все тот же. Создается такая ситуация в скопированном документе
![image](https://user-images.githubusercontent.com/42540074/56208235-5111fd00-6059-11e9-95ac-2c5eabf56ec7.png)
Теперь в нем внутри нет бланка для печати
![image](https://user-images.githubusercontent.com/42540074/56208441-d5648000-6059-11e9-83bf-3524b9181f37.png)
п6. Они не авансовыми отчетами не закрыты, а выдачей денег или внесением.

**Comment by htrofymova** [comment]
п. 3 и печать исправлена
