### ISSUE TITLE
Новый раздел Касса

### ISSUE THREAD

**Issue by htrofymova** [a2develop/testing#293]
Доработаны документы "Видатковий касовий ордер" и "Прибутковий касовий ордер". Нужно проверить создание, заполнение, сохранение, проведение.

**Comment by Anestezia** [comment]
1. Скопировала уже проведенный документ, изменила сумму, нажала провести. Документ провелся, а я осталась вот в таком окне - точной копии только что созданного, без признаков проведения. Нажала закрыть, он спросил Сохранить ли изменения, хотя я изменений не вносила после того, как провела.
![image](https://user-images.githubusercontent.com/42540074/55954195-c26f3b80-5c66-11e9-89e0-93a8c933ab53.png)
Закрыла, оказалась в списке операций, где была и проведенная мною первая копия и призрак несохраненной второй копии (которая создалась сама.) Обновила она исчезла.
2. печать есть изнутри и снаружи.
3. При операции надання безповоротноъ допомоги Вне зависимости от того, какой вид выберешь, при проведении все равно он меняется на Безповоротну фин. допомогу. 
![image](https://user-images.githubusercontent.com/42540074/55954585-bc2d8f00-5c67-11e9-8c5b-afc5ce45233c.png)

4. В видатковом все еще маленький список этих видов, тогда как в приходном мы уже его расширили в соответствии со старым интерфейсом.
![image](https://user-images.githubusercontent.com/42540074/55954880-8a68f800-5c68-11e9-9491-998dca31b370.png)

**Comment by htrofymova** [comment]
1. По операциям призракам - исправлено
3. Исправлено
4. Исправлено, хотя в старом интерфейсе список короткий.

**Comment by Anestezia** [comment]
Да, все исправлено, подтверждаю
