### ISSUE TITLE
Новый раздел Платежі в валюті

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#294]
Проверить:
1. Список документов:
 a. Отображение с учетом фильтра Вхідні, Вихідні и т.д и периода.
 b. Действия с документами : открыть, копировать, печатать, удалить.
 c. Печать и экспорта реестра документов.
2. Платіж контрагенту, Вхідний платіж:
 a. Создание.
 b. Редактирование: выбор операции, выбор контрагента, выбор банковских счетов, подставление курса, пересчет сумм.
 c. Проведение, отражение в отчетах.

Банковскую выписку в этом разделе пока не смотрим.

**Comment by AlexeyTishkin** [comment]
Банковская выписка:
 a. Ручное создание.
 b. Импорт.
 c. Редактирование: выбор операции, выбор контрагента, выбор банковских счетов, редактирование сумм.
 d. Проведение, отражение в отчетах.

**Comment by Anestezia** [comment]
1. a. b. -- все ок.
с. чуть не влезло в екселе слово
![image](https://user-images.githubusercontent.com/42540074/55959603-c190d680-5c73-11e9-8bcb-8c5a3f047c1e.png)
2. Все ок. кроме выбора банка в отдельной операции (ишью уже есть) -- нет возможности создать банк-нерезидент из платежки.
При подборе банка у нерезидента код банка и сам банк не редактируются, и до проведения не видно сам банк. 
![image](https://user-images.githubusercontent.com/42540074/55959973-8cd14f00-5c74-11e9-919d-2cd91ad93b66.png)
Он появляется только после нажатия на провести.
Курс подставяется. суммы пересчитываются.
В отчетах, оборотках эти суммы есть. Из обороток переход / открытие документа в старом интерфейсе.

**Comment by AlexeyTishkin** [comment]
> При подборе банка у нерезидента код банка и сам банк не редактируются, и до проведения не видно сам банк.

В данном случае счет предварительно создан в свойствах или номер счета внесен непосредственно в платежке ?

**Comment by AlexeyTishkin** [comment]
> Из обороток переход / открытие документа в старом интерфейсе.

В issue по платежам есть уже несколько отчетов из которых открывается в старом интерфейсе. Надо бы дополнить перечень.

**Comment by Anestezia** [comment]
По ручной выписке, неожиданно, что там нет курса и не пересчитывает в гривне валюту. Сами вносим. Но думаю, это так задумано.
![image](https://user-images.githubusercontent.com/42540074/55960452-7bd50d80-5c75-11e9-9fe2-93ccc35bce66.png)
То же с подбором и в выписке, нельзя создать новый банк, только выбрать, притом из резидентов, операция Списання коштів в валюті банком 
![image](https://user-images.githubusercontent.com/42540074/55960713-ff8efa00-5c75-11e9-9dc0-950279927862.png)
Было бы неплохо указывать валюту значком (на початок дня) на кинець
![image](https://user-images.githubusercontent.com/42540074/55962831-5696ce00-5c7a-11e9-9c19-47ba4b5e7fde.png)
а так все ок.
Интересно, что в проведенную выписку без распроведения можно додати рядок и дальше с ней работать
https://github.com/a2develop/testing/issues/294#issuecomment-482111039
Внесен в платежке.

**Comment by AlexeyTishkin** [comment]
> По ручной выписке, неожиданно, что там нет курса и не пересчитывает в гривне валюту. Сами вносим. Но думаю, это так задумано.

Да. В выписке вносим факт, который дал банк. Там две суммы: в валюте и эквивалент.

**Comment by AlexeyTishkin** [comment]
> Было бы неплохо указывать валюту значком (на початок дня) на кинець

Значком или прописью ? На початок 3000 USD ?

**Comment by AlexeyTishkin** [comment]
> Интересно, что в проведенную выписку без распроведения можно додати рядок и дальше с ней работать

Да. Выписка проводится построчно. Для всего документа отображается статус "Проведен" в том случае, если все строки проведены. При этом можно отменить проведение определенных строк. В таком случае статус документа будет "Чернетка".

**Comment by AlexeyTishkin** [comment]
> чуть не влезло в екселе слово

Исправил.

**Comment by AlexeyTishkin** [comment]
> Все ок. кроме выбора банка в отдельной операции (ишью уже есть) -- нет возможности создать банк-нерезидент из платежки.

Сделал.

**Comment by AlexeyTishkin** [comment]
> То же с подбором и в выписке, нельзя создать новый банк, только выбрать, притом из резидентов, операция Списання коштів в валюті банком

Сделал.

**Comment by AlexeyTishkin** [comment]
> Было бы неплохо указывать валюту значком (на початок дня) на кинець

Дописал код валюты.

**Comment by Anestezia** [comment]
Теперь МФО банка нерезидента стало проблемой в валютной платежке, ведь у них нет МФО, а у нас обязательное требование. 
![image](https://user-images.githubusercontent.com/42540074/56019876-7546a480-5d0e-11e9-92cc-62220d4cbd61.png)

**Comment by AlexeyTishkin** [comment]
> Теперь МФО банка нерезидента стало проблемой в валютной платежке, ведь у них нет МФО, а у нас обязательное требование.

Исправил.

**Comment by Anestezia** [comment]
Банк отримувача - нажимаю на подбор (картинка увеличителя), а ничего не происходит. Выбрать банк можно только из подбора в рядке Код банка (он не горит красным - это уже хорошо), но люди будут пытаться сделать подбор именно из клетки, что горит красным, а через код банка поискать не додумаются.
![image](https://user-images.githubusercontent.com/42540074/56191661-6d9c3e00-6035-11e9-9d33-f63d06ca0af6.png)
В остальном все ок.

**Comment by AlexeyTishkin** [comment]
> Банк отримувача - нажимаю на подбор (картинка увеличителя), а ничего не происходит. 

Исправил.

**Comment by Anestezia** [comment]
При проведении за секунду мфо загорается красным
![image](https://user-images.githubusercontent.com/42540074/56207146-b44e6000-6056-11e9-9bae-9154f76d2ddc.png)
а потом документ проведен и все в порядке. В остальном вопросов нет.
![image](https://user-images.githubusercontent.com/42540074/56207182-ce883e00-6056-11e9-9ff5-befc6bc899e7.png)
