### ISSUE TITLE
Необоротные активы. Операции (beta). Новый документ.

### ISSUE THREAD

**Issue by htrofymova** [a2develop/testing#295]
В "кнопку" [Створити документ] добавлен пункт "Введення в эксплуатацію необоротних активів". Нужно проверить все операции. 
Создаются операции: 
Ввод в єксплуатацию ОС и НМА
Ввод в хоз.оборот необоротных активов
Прием-передача в операцилнную аренду
Повторынй ввод посдле временного вывода.

**Comment by Anestezia** [comment]
Немного на бланке вылезает окошко за таблицу
![image](https://user-images.githubusercontent.com/42540074/56356788-7da55080-61e2-11e9-9c9f-3b2ef67462b5.png)
Не очень понятно, почему в скопированном документе нельзя поменять количество.
Нужен перенос длинных названий операций в сохраненных списках операций
![image](https://user-images.githubusercontent.com/42540074/56357140-76327700-61e3-11e9-9fb6-0bc8836f80f0.png)
Копирование, печать, создание новых работает, проводится.
Поиск, сохранение списка доков работает.

**Comment by Anestezia** [comment]
Сильно опущены названия граф, при печати их не видно полностью
![image](https://user-images.githubusercontent.com/42540074/56499636-e99ff580-650f-11e9-954c-158dff3273c0.png)

**Comment by Anestezia** [comment]
1.Тут не влезает Действия
![image](https://user-images.githubusercontent.com/42540074/56656227-99569e00-669d-11e9-9a3d-6762ba03947b.png)
2. Срок корисного використання не подставился, а до проведения, только при сохранении, не подставляется еще и стоимость.
![image](https://user-images.githubusercontent.com/42540074/56656422-23066b80-669e-11e9-8b79-7d9b5ffd9f43.png)
3. Все еще нет переноса длинных названий операций на печати. Это и в ПДФ так же. 
![image](https://user-images.githubusercontent.com/42540074/56656561-7c6e9a80-669e-11e9-98e1-1ff0fd5eb46e.png)

**Comment by htrofymova** [comment]
исправлено

**Comment by Anestezia** [comment]
Можно закрывать
