### ISSUE TITLE
В Счета (входящий, исходящий) добавлена возможность вставки строки всередину таблицы.

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#298]
[864](https://github.com/a2develop/bugTracker/issues/864)

Проверить возможность вставки строк.

**Comment by Anestezia** [comment]
1.В счетах входящих есть, работает корректно, на печать выводится, артикул переносится на печати.
2.Может и в инвойс этот функционал добавить? А там уже и в накладные (акты) тоже могут попросить.
3.В исходящих счетах все работает.

**Comment by AlexeyTishkin** [comment]
> Может и в инвойс этот функционал добавить? 

Подождем фидбэк. Потом добавим во все документы "Запасов".
