### ISSUE TITLE
Раздел "Зарплата". В документ "Расчётная ведомость" добавлена печатная форма.

### ISSUE THREAD

**Issue by Illya-Lykhachov** [a2develop/testing#299]

**Comment by Anestezia** [comment]
Аналогично, Есть, работает. Вопрос по рядку До виплати. Неплохо бы, чтоб он тоже был.
Вот бы и в раздел Персонал это все добавить! А то просили.

**Comment by Illya-Lykhachov** [comment]
К выплате имеет смысл только в авансе (для этого он и начисляется). Сумма к выплате в расчётной ведомости не соответствует сумме в ведомости на выплату - с неё уже был выплачен аванс.

**Comment by Anestezia** [comment]
Ладно, можно закрывать и ждать реакции пользователей.
