### ISSUE TITLE
НДС в том числе в приходных платежном поручении и кассовом ордере

### ISSUE THREAD

**Issue by shevchuk-vadim** [a2develop/testing#3]
Проверить, чтобы НДС правильно считался при изменении суммы или признака НДС, правильно работали валидаторы суммы документа и суммы НДС.
Проверить, чтобы сумма документа правильно попадала в проводки и выводилась на печать.
Проверить, чтобы сумма документа попадала в операцию начисления налогов без НДС.

**Comment by kattrina-brekhova** [comment]
![photo_2018-09-03_18-38-40](https://user-images.githubusercontent.com/38099938/44994768-d6eca680-afa8-11e8-8cdc-4d41b62fdda4.jpg)
в счете скидку посчитало, ндс тоже
но в ордере эта сумма взялась - не понимаю
![photo_2018-09-03_18-40-13](https://user-images.githubusercontent.com/38099938/44994780-e53ac280-afa8-11e8-9e18-f8cb660f5a89.jpg)

**Comment by AlexeyTishkin** [comment]
Исправил.

**Comment by kattrina-brekhova** [comment]
в какой базе можно проверять? дев? бета? сервис?

**Comment by AlexeyTishkin** [comment]
Дев. На бете после публикации.

**Comment by kattrina-brekhova** [comment]
ага, работает

**Comment by kattrina-brekhova** [comment]
считает, в том числе и при вычислении дохода - сумма попадает без ндс
