### ISSUE TITLE
Зарплата (beta). Существенно изменено заполнение отчёта по ЕСВ (Додаток 4)

### ISSUE THREAD

**Issue by Illya-Lykhachov** [a2develop/testing#300]
Отчёт должен работать без кадрового учёта, в режиме простой зарплаты. В т.ч. с договорами ГПХ. Для чистоты эксперимента, лучше проверять в тенанте, не имеющем кадровых операций

**Comment by Anestezia** [comment]
Табл. 1 - 22% считает от суммы начисленной (на фото это 9554.55 грн.) , но не учитывает доначисление до минималки, которое было.
![image](https://user-images.githubusercontent.com/42540074/56289729-4d9a7680-612a-11e9-81c6-639c4fbf688d.png)
а в документах 672.00 грн + 1836,12 грн. = 2508,12.
![image](https://user-images.githubusercontent.com/42540074/56289842-90f4e500-612a-11e9-8cdf-ffa029db4e0e.png)
![image](https://user-images.githubusercontent.com/42540074/56289853-994d2000-612a-11e9-9721-e6d618264375.png)
Та же история с табл. 6.
![image](https://user-images.githubusercontent.com/42540074/56290085-0eb8f080-612b-11e9-896b-f659d51425e3.png)
Четкие 22% от 3200 и 3300, без учета доначисления до минималки.
Совсем без кадров не обойтись у нас, юрлицо принимает человека все равно, чтоб подписать смог документы. ФОП тоже, а если ФОП без кадров, то ему и Додаток 4 не нужен.
Кроме того, как без кадров заполнить табл.5 Додатка 4? Только вручную.
ГПХ у нас только в кадрах пока и от туда инфу тянет.

**Comment by Illya-Lykhachov** [comment]
Таблица 1. Раздел с суммами ЕСВ исправил.
Таблица 6. Проверил - доначисление отражается правильно.
Таблица 5. Без кадров - только руками.
Подписанты. Вижу только один вариант: дать возможность выбора в отчёте, и при создании нового отчёта тянуть из предыдущего. Аналогично в документах (кассовые ордера, платёжки, ...)

**Comment by Illya-Lykhachov** [comment]
Насчёт решения с подписантами, нужно твоё мнение

**Comment by Illya-Lykhachov** [comment]
По таблице 5.
[https://github.com/a2develop/bugTracker/issues/912]

**Comment by Anestezia** [comment]
Доначисление отображается правильно. Насчет подписантов еще думаю.
