### ISSUE TITLE
Новый интерфейс Придбання-Операції (beta)

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#301]
Проверить в списке:
1. Отображение документов.
2. Открытие.
3. Создание.
4. Печать документа.
5. Печать списка документов.
6. Построение отчетов.

**Comment by Anestezia** [comment]
Было б круто, если бы еще и отражались стикеры или отдельный журнал документов, по которым не сформированы налоговые накладные.

**Comment by Anestezia** [comment]
В списке идет вверх сразу - это хорошо. 
Открываются, создаются, печатаются, стикеры хорошие, информативные.
Отчеты строятся, список сохраняется во всех форматах и печатается корректно, перенос длинных названий есть.
Поиск работает хорошо.
При наведении на изогнутую стрелку (Действия) в дочерних документах в списке, нет всплывающей подсказки, что за действие выполнится
![image](https://user-images.githubusercontent.com/42540074/56356422-88abb100-61e1-11e9-93b1-049c0bf9abfa.png)

В остальном все ок.

**Comment by AlexeyTishkin** [comment]
> И странно, что из этого места дочерний документ не открывается.

Подробней. Какой-то конкретный не открывается? Или все?

**Comment by AlexeyTishkin** [comment]
> При наведении на изогнутую стрелку (Действия) в дочерних документах в списке, нет всплывающей подсказки, что за действие выполнится

Добавил.

**Comment by AlexeyTishkin** [comment]
> Было б круто, если бы еще и отражались стикеры или отдельный журнал документов, по которым не сформированы налоговые накладные.

Перенес в https://github.com/a2develop/bugTracker/issues/916

**Comment by AlexeyTishkin** [comment]
Закрываем ?

**Comment by Anestezia** [comment]
Да, закрываем. Не открывается дочерний, я имела в виду кликом на нем. Но стрелкой тоже норм
