### ISSUE TITLE
Отчёт в ФССУ (форма №Д4.), таблица 5. Ручной ввод

### ISSUE THREAD

**Issue by Illya-Lykhachov** [a2develop/testing#302]
При отсутствии кадрового учёта и ручном вводе данных, добавлена возможность выбора физ.лица с подстановкой данных о его должности и профессии (из документа последнего начисления за отчётный период). Кнопка в строке в колонке действий (справа).

**Comment by Anestezia** [comment]
Подбор идет из списка, если в персонале есть данные про Приказ о приеме, посада, профессия, то они подтягиваются вместе с фамилией. Если нет данных, то вручную.  Мне нормально все.
