### ISSUE TITLE
Зарплата (beta). В ведомость на выплату наличных добавлено округление сумм к выплате.

### ISSUE THREAD

**Issue by Illya-Lykhachov** [a2develop/testing#303]

**Comment by Anestezia** [comment]
1. В самом окошке округления после выбора вида (1 грн или 10 грн) это значение не отображается, просто пустое окошко, хотя операция совершена. 
2. Выбрала сначала округлить до 1 грн. - сработало, потом выбираю тут же округлить до 10 грн. - сработало, а потом тут же снова до 1 грн - Не сработало.
3. В остальном все работает. Добавить в персонал и вообще круто будет.

**Comment by Illya-Lykhachov** [comment]
Это выбор действия с суммами. После округления первоначальные значения сумм теряются (если предварительно не сохранили). Поэтому если округлили до 10 грн, то до 1 грн. уже не имеет смысла. Поэтому в комбике и значение не сохраняется
