### ISSUE TITLE
В документы Счет входящий, Счет исходящий, Приходная накладная, Расходная накладная, Акт полученных услуг, Акт оказанных услуг, Акт оказанных услуг с материалами добавлены комментарии

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#304]
[910](https://github.com/a2develop/bugTracker/issues/910).

В списке документов комментарии отображаются только в новых интерфейсах. 
Проверить:
1. Добавление комментария.
2. Отображение в списке документов (только в новом интерфейсе).
3. Удаление комментария.

**Comment by Anestezia** [comment]
Все работает как заявлено. Только вот отображается в списке документов нового интерфейса только в Придбанни. В продажах пока посмотреть нельзя, что там висят комменты. Заготовка для нового интерфейса продаж.

**Comment by AlexeyTishkin** [comment]
> В продажах пока посмотреть нельзя, что там висят комменты. 

Скоро и в продажах новый интерфейс будет :)
