### ISSUE TITLE
Проведение/отмена проведения расходных документов (Расходная накладная, Акт списания, Накладная на перемещение и др.) "задним" числом

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#306]
[918](https://github.com/a2develop/bugTracker/issues/918).

В механизме проверки учитываются только расходные документы. 
Проверить проведение/отмену проведения при условии:
1. Объект присутсвует в расходных документах более поздним числом. Должнем быть запрет с указанием даты последнего движения.
2. Объект присутсвует в приходных документах более поздним числом. Проведение/отмена должны быть разрешены.

**Comment by Anestezia** [comment]
Да, все так.
