### ISSUE TITLE
Необоротные активы. Операции (beta). Новые диалоги.

### ISSUE THREAD

**Issue by htrofymova** [a2develop/testing#307]
Нужно проверить новые документы в виде диалогов ( в "кнопку" [Створити документ] добавлен пункты):
Вибуття (ліквідація) необоротних активів,
Прийом-передача необоротних активів (передача),
Прийом-передача необоротних активів (прийом).

**Comment by Anestezia** [comment]
Все ок. 
Только артикул странно печатается
![image](https://user-images.githubusercontent.com/42540074/57238078-3ff15600-7031-11e9-8fd1-c2dc560d3546.png)
![image](https://user-images.githubusercontent.com/42540074/57238107-526b8f80-7031-11e9-9999-7e4390d8da9d.png)
первая и последняя цифра не влезли.

**Comment by htrofymova** [comment]
Договорились же артикул убрать из этизх актов. Убрала и из печатных форм.
