### ISSUE TITLE
Бухгалтерія - Рахунки

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#308]
В список документов добавлен режим "Банківські виписки".
Проверить:
1. Отображение списка выписок.
2. Открытие выписок.

**Comment by AndriyNesterenya** [comment]
Работает. 
Еще бы сохранять состояние фильтра по периоду при переходе со счета на счет :)

**Comment by AlexeyTishkin** [comment]
> Еще бы сохранять состояние фильтра по периоду при переходе со счета на счет :)

Не мешаем все в одну кучу :)
Issue о режиме. Закрываю.
