### ISSUE TITLE
В документы "Приходная накладная", "Расходная накладная", "Акт полученных услуг", "Акт оказанных услуг", "Акт оказанных услуг с материалами" добавлена возможность создания связанной оплаты

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#309]
[915](https://github.com/a2develop/bugTracker/issues/915)

Проверить возможность создания оплаты. Создание должно быть доступно в документах, у которых нет родительского документа (Счета). В документах, у которых есть родительский Счет должно быть предупреждение о том, что оплата создается из Счета.

**Comment by Anestezia** [comment]
Акт виконаних робит - Продажи - что-то с оплатой по кассе не сработало. Я нажала создать, окно документа подернулось серой пеленой. Как будто при переходе к кассовому документу, И дальше ничего не произошло. Так и зависло. Я нажала ЕСКейп, вернулась в исходный акт, а справа уже показывается, что оплата по кассе создана, на всю сумму, оплату по банку нет дальше возможности создать (возможно, потому что уже вся сумма "выплачена" по кассе). При попытке его - ордер - открыть (чтоб провести хотя бы) опять серая пелена и зависон.
![image](https://user-images.githubusercontent.com/42540074/57239075-919ae000-7033-11e9-910d-3a5e660160ae.png)
Извне из списка операций оплата непроведенная по кассе открылась. и провелась. Вид старого интерфейса. Я изменила перед проведением сумму на меньшую, провела и открыла снова акт. Справа появились возможности создать недостающую оплату по кассе и по банку. Банк открылся в новом интерфейсе. Отметки о проведении оплаты в самом акте есть.
![image](https://user-images.githubusercontent.com/42540074/57239288-26054280-7034-11e9-9ab2-91f0453ea4b8.png)
То же самое в акте с материалами. И в накладной раздела продажи. В Покупке со всеми этими документами порядок.

**Comment by AlexeyTishkin** [comment]
> И дальше ничего не произошло. Так и зависло. 

Исправил.

**Comment by Anestezia** [comment]
Все работает
