### ISSUE TITLE
Новый интерфейс Продажі-Операції (beta)

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#310]
Проверить в списке:
1. Отображение документов.
2. Открытие.
3. Создание.
4. Печать документа.
5. Печать списка документов.
6. Построение отчетов.

**Comment by AndriyNesterenya** [comment]
Из мелочей:
При привязке к счету ранее не привязанного платежа не обновляет автоматически состояние метки 
![image](https://user-images.githubusercontent.com/38098758/57083349-18348200-6d01-11e9-9047-12437d912d19.png)

**Comment by AlexeyTishkin** [comment]
> При привязке к счету ранее не привязанного платежа не обновляет автоматически состояние метки

Как привязывался платеж ? Платеж проведен ?

**Comment by AndriyNesterenya** [comment]
Ситуация была и такая:
Юзер переезжает к нам с другой бухгалтерии.
Втаскивает данные по очереди, затянул выписки (не проводил) понасоздавал счетов, и вот прямо из окна на скрине пытался подвязывать к платежам счета.

Переделаю с нуля - доложу.

**Comment by AlexeyTishkin** [comment]
> и вот прямо из окна на скрине пытался подвязывать к платежам счета.

Насколько я понимаю, он связывает счет с платежем в выписке ? Но в режиме на скрине нет выписок. Там уже конечные платежи, которые появляются после проведения выписки.

**Comment by AlexeyTishkin** [comment]
> Переделаю с нуля - доложу.

Да. Давай точную последовательность действий.

**Comment by AndriyNesterenya** [comment]
Ой, а чё заметил... в Операциях (бета) пропал фильтр по типу операций.
Сортировка есть - возможности отфильтровать по типу нет.
Верните взад, пжлст.

**Comment by AndriyNesterenya** [comment]
Или считаем, что группировки достаточно?

**Comment by AlexeyTishkin** [comment]
> Ой, а чё заметил... в Операциях (бета) пропал фильтр по типу операций.

Выноси на обсуждение в общий чат. Решили, что не нужно.

**Comment by AlexeyTishkin** [comment]
Закрываем ?

**Comment by AndriyNesterenya** [comment]
Так точно
