### ISSUE TITLE
Новый интерфейс Персонал - Кадры

### ISSUE THREAD

**Issue by Illya-Lykhachov** [a2develop/testing#311]
Нужно проверить создание и работу со всеми кадровыми документами и со списком документов

**Comment by Illya-Lykhachov** [comment]
Нужно проверить создание и работу со всем кадровыми документами и со списком документов

**Comment by Anestezia** [comment]
Все формы открываются, цепочки доков создаются, печатаются, сохраняются. Изменения вносятся. Документ назначения из диалога открывается, оплаты и расчет при увольнении создаются. Копирование из списка работает.
