### ISSUE TITLE
Бухгалтерия-Підзвіт. Новый внешний вид списка.

### ISSUE THREAD

**Issue by htrofymova** [a2develop/testing#312]
Изменен внешний вид списка операций. Нужно проверить правильность отображения.

**Comment by Anestezia** [comment]
1. А может на Незавершенные тоже нужен период?
![image](https://user-images.githubusercontent.com/42540074/57303037-1e51a680-70e5-11e9-9365-355a8d992f04.png)
Этот раздел заимствует период из других разделов. Например, я в разделе Все выбрала период, а потом переключилась на Незавершенные и там уже идет отображение выбранного мной периода. А переставить его находясь в этом разделе возможности нет.
2. Странная печать списка операций. Документы скопом без указания границы, где именно авансовые, а где идет выдача и т.д. 
![image](https://user-images.githubusercontent.com/42540074/57303256-9d46df00-70e5-11e9-894c-b83996d6705a.png)
то же самое при сохранении списка в разных форматах. 
В остальном претензий нет.

**Comment by htrofymova** [comment]
1. Пределала.  [Не завершенные] - всегда период "за весь час"
 2. Добавила колонку Операція

**Comment by Anestezia** [comment]
да, есть. Закрываем?

**Comment by htrofymova** [comment]
ага
