### ISSUE TITLE
Печатные формы документов "Счет", "Расходная накладная", "Акт оказанных услуг", "Акт оказанных услуг с материалами"

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#313]
Колонка "Цена". Строгое форматирование значений до 2-х знаков после запятой изменено на динамическое до 6-ти знаков.
Проверить печать.

**Comment by Anestezia** [comment]
1. Счет: Если нет галочки в т.ч. ПДВ, то цена в самой форме сохраняется со многими знаками после запятой, даже после проведения. если поставить такую галочку, в форме-диалоге сразу видится цена, как округленная. При этом  на печати отображается со многими знаками после запятой, как и было заявлено, но только уже будучи ценой БЕЗ НДС (что в самом печатном бланке не указано). Получается, что цена, которую пользователь видит в диалоговом окне и цена на печати разные, что, во-первых, может стать неожиданностью для пользователя, а во-вторых, уж точно не интуитивно. Т.е. увидеть округление, не согласиться с этим, так как вводишь нужную цену и никаких преображений не ожидаешь, но таки догадаться послать на печать - это героизм. (Что на картинке, то и на печати!)
2. В расходной накладной также, на печать идут цены со множеством знаков после запятой. И с округлением при выделении НДС.
3. Акт так же.
4. Акт с материалами, печатается точно так же.
В общем претензий нет, только сначала не всем будет понятно.

**Comment by AlexeyTishkin** [comment]
Режим "ПДВ в т.ч." изначально делался для облегчения ввода первичного документа. Базовая цена - без НДС.
Цену с НДС на печать вывести можно, но это - предмет отдельного обсуждения.

**Comment by AlexeyTishkin** [comment]
> В общем претензий нет, только сначала не всем будет понятно.

Тогда закрываю.
