### ISSUE TITLE
Новый интерфейс Персонал - Рабочее время

### ISSUE THREAD

**Issue by Illya-Lykhachov** [a2develop/testing#314]
Нужно проверить создание и работу со всеми документами невыходов и со списком документов

**Comment by Anestezia** [comment]
Нет кнопки обновить, отбор по документам, печать, сохранение списка операций.
Отпуск - так и не решили, что делать с дополнительными днями, если припадают на праздник, а работодателю все равно придется оплачивать.
Все доки копируются, открываются, в принципе список сам обновляется при сотворении документа. Вроде все ок.

**Comment by Illya-Lykhachov** [comment]
> Нет кнопки обновить, отбор по документам, печать, сохранение списка операций.

Исправлено

> Отпуск - так и не решили, что делать с дополнительными днями, если припадают на праздник, а работодателю все равно придется оплачивать.

Добавил корректировку дней руками
