### ISSUE TITLE
Продажі. Dashboard

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#316]
Проверить:
1. Создание операций из схемы.
2. Отображение списка задач (не закрытые Счета).
3. Отображение списка черновиков (не проведенные операции).
4. Дебиторскую задолженность (долг Дб по 361).
5. Построение отчетов.

**Comment by Anestezia** [comment]
1. Операции все создаются и проводятся, печатаются.
2. Пометки есть, правильные, открываются эти задачи нормально.
3. Тоже все ок. Вопрос: а нельзя ли в списке черновиков сверху справа сделать кнопку экспорта списка?
4. цифры правильные
5. формируются, экспортируются, печатаются, переход к исходным документам возможен.

**Comment by AlexeyTishkin** [comment]
> Вопрос: а нельзя ли в списке черновиков сверху справа сделать кнопку экспорта списка?

Экспорт куда ?
Этот же список можно увидеть в операциях, режим "Чернетки", там есть печать и экспорт.
В любом случае - это в отдельный issue.
