### ISSUE TITLE
Персонал - Зарплата (beta). "Расчётная ведомость"теперь диалог.

### ISSUE THREAD

**Issue by Illya-Lykhachov** [a2develop/testing#317]
Нужно проверить работу диалога и создание оплат из него

**Comment by Anestezia** [comment]
Чувака нет в ведомости начисления, но в ведомости на выплату он появляется, может это потому что ему ранее начислено, но не выплачено?
![image](https://user-images.githubusercontent.com/42540074/57304663-6aeab100-70e8-11e9-8b79-6e5280d661d6.png)
 В остальном никаких проблем не заметила.

**Comment by Illya-Lykhachov** [comment]
> Чувака нет в ведомости начисления, но в ведомости на выплату он появляется, может это потому что ему ранее начислено, но не выплачено?
Именно так. Если создаём выплату не из аванса, а из расчётной ведомости, то при заполнении пытаемся выплатить всё и всем, что должны (не выплачено ранее).
