### ISSUE TITLE
1. Новый интерфейс подраздела Персонал - Зарплата

### ISSUE THREAD

**Issue by Illya-Lykhachov** [a2develop/testing#319]

**Comment by Anestezia** [comment]
1. Не копируется АКТ 
![image](https://user-images.githubusercontent.com/42540074/57303464-0c243800-70e6-11e9-8c8e-3b6f3b8abb57.png)
2. Эта операция вообще не понятна, ее как в старом интерфейсе просто так не внести. Вопрос, зачем она здесь вообще
![image](https://user-images.githubusercontent.com/42540074/57303542-3bd34000-70e6-11e9-80b8-813fb9011d91.png)
Изнутри акта печать пустого документа 
![image](https://user-images.githubusercontent.com/42540074/57303590-59080e80-70e6-11e9-911b-09a560891aa0.png)
3. Тут номер рахунку сотрудника и не должен печататься или должен подтягиваться из свойств?
![image](https://user-images.githubusercontent.com/42540074/57303804-c9af2b00-70e6-11e9-82be-687a1ddb2bbb.png)
4. Виплата касса на основании ведомости, я выплачиваю двум людям, выбираю \выплата зп сотруднику, получатель у меня один. Тут подразумевается, каждый кассовый ордер на одного сотрудника или получателем я ставлю кассира и потом под подпись в ведомости выдаю зп сотрудникам с одного ордера?
![image](https://user-images.githubusercontent.com/42540074/57304138-6e316d00-70e7-11e9-8267-dced63e7ac19.png)
5. В списке операций нет справа сверху функции печати и сохранения списка операций.
![image](https://user-images.githubusercontent.com/42540074/57304255-a933a080-70e7-11e9-84fe-d0497f3222a2.png)
В остальном все ОК

**Comment by Anestezia** [comment]
Нет отбора по виду операции. Я считаю, что он нужен.

**Comment by Anestezia** [comment]
Не отображаются комментарии во внешнем списке
![image](https://user-images.githubusercontent.com/42540074/57305219-5ce96000-70e9-11e9-94f0-5c3fd43ac794.png)

**Comment by Illya-Lykhachov** [comment]
1. Исправлено.
2. Здесь отображаются все операции, касающиеся 661-го счёта. Пока как и раньше (просто показываются), потом переделаю акт с возможностью его заполнения (выбор договора). Аналогично переделаю и начисление при увольнении (добавлю выбор приказа об увольнении). Если акт заполнен, то печатается нормально.
3. Исправлено, подтягивается из договора.
4. При выплате заплаты ведомостью, кассовый ордер выписывается на кассира. Он из кассы получает всю сумму и раздаёт по ведомости.
5. Сделаю потом (себе зафиксировал)

**Comment by Illya-Lykhachov** [comment]
> Нет отбора по виду операции. Я считаю, что он нужен.

Нигде нет (банк, касса, ...). Это общее решение для всего проекта, примем его - добавлю

**Comment by Illya-Lykhachov** [comment]
> Не отображаются комментарии во внешнем списке
Добавлю

**Comment by Illya-Lykhachov** [comment]
> В списке операций нет справа сверху функции печати и сохранения списка операций.
Исправлено
