### ISSUE TITLE
Переделан расчёт зарплаты при увольнении.

### ISSUE THREAD

**Issue by Illya-Lykhachov** [a2develop/testing#320]
Нужно проверить:
 - интерфейс;
 - заполнение;
 - создания из списка документов начисления зарплаты;
 - ...

**Comment by Anestezia** [comment]
1. Компенсацию за отпуск не насчитывает
![image](https://user-images.githubusercontent.com/42540074/58102441-f46ea880-7be9-11e9-9029-bc84c0e9180d.png)
2. Не подтягиваются подписанты, хотя право подписи назначено
![image](https://user-images.githubusercontent.com/42540074/58104497-8c21c600-7bed-11e9-9afb-156f3a0147ad.png)
3. Он уволен, проверку нужно убрать
![image](https://user-images.githubusercontent.com/42540074/58104649-cab78080-7bed-11e9-9f9a-7464507ef72f.png)
4. Кассовый ордер на выплату не сохраняется в  форматах, лучше проверьте все кассовые, на ГПХ тоже такое.
![image](https://user-images.githubusercontent.com/42540074/58104811-1407d000-7bee-11e9-83c6-30356c9dc195.png)
5. Попытка удалить платежное поручение на выплату зп при увольнении
![image](https://user-images.githubusercontent.com/42540074/58105125-a8723280-7bee-11e9-9c57-942b81a162fb.png)
6. Наказ про звільнення из списка копируется, создается черновик, но там все данные уже уволенного человека и их не заменить. 
![image](https://user-images.githubusercontent.com/42540074/58105561-609fdb00-7bef-11e9-8b23-5d236633c0f3.png)
7. Странное поведение платежки на выплату в списке операций: оно было отдельно подпунктом прикреплено к рассчету зп при увольнении, я его открыла, закрыла, и он появился параллельно в списке, обновила - исчез.
![image](https://user-images.githubusercontent.com/42540074/58105980-081d0d80-7bf0-11e9-87de-4c707443c639.png)

**Comment by Illya-Lykhachov** [comment]
1. Исправлено

**Comment by Illya-Lykhachov** [comment]
6. Исправлено.
При копировании не заполнялись причины увольнения.
Должность, отношения и назначение подтягиваются из сотрудника и руками не меняются. Всё остальное можно менять.

**Comment by htrofymova** [comment]
2, 4. - исправлено

**Comment by htrofymova** [comment]
3. - исправлено

**Comment by Anestezia** [comment]
все ок.
