### ISSUE TITLE
Механизм исправления проведенного документа добавлен в операцию "Виставлення рахунку"

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#323]
Проверить возможность редактирования счета при наличии дочерних документов.

**Comment by Anestezia** [comment]
Изменения вносятся как обычно, все ок.
Единственное, если на основании создалась оплата, и там автоматически у нас прописывается назначение платежа, так вот, если она создана раньше изменений, то там указан номер счета старый
![image](https://user-images.githubusercontent.com/42540074/58106987-ae1d4780-7bf1-11e9-86d2-584de58b4ae5.png)

**Comment by AlexeyTishkin** [comment]
> если на основании создалась оплата

Связанные документы не обновляются. Изменения только в самом Счете.
