### ISSUE TITLE
Персонал - Зарплата. Проверить выплату из Акта к договору ГПХ.

### ISSUE THREAD

**Issue by Illya-Lykhachov** [a2develop/testing#324]
Касса или банк, на невыплаченный по акту остаток.

**Comment by Illya-Lykhachov** [comment]
Переделал вообще все выплаты из всех документов зарплаты с персоналом и зав зарплатном калькуляторе. Привёл всё к общему механизму.

**Comment by Anestezia** [comment]
1. В кассовом ордере не подтянулся Паспорт, хотя в карточке есть. 
![image](https://user-images.githubusercontent.com/42540074/58107985-a6f73900-7bf3-11e9-81ae-f13ec00998aa.png)
Так же Не подтянулись подписанты, провелось так же без подписантов.
2. Экспорта документов нет из кассы.
3. Список документов после удаления ордера не обновился автоматически
![image](https://user-images.githubusercontent.com/42540074/58108265-2c7ae900-7bf4-11e9-858b-8c1eedac20e9.png)
4. Подставляется автоматически в кассе и банке не сумма До сплати (1610,00), а сумма начисленная (2000,00) Или  так и должно быть?
![image](https://user-images.githubusercontent.com/42540074/58108570-c2af0f00-7bf4-11e9-9137-3eb379330e55.png)
5.На правой панели нет отметки, проведен ли документ об оплате в учете. На фото выше один из них проведен, а второй нет.

**Comment by Illya-Lykhachov** [comment]
2. Связанные документы не обновляются при их изменении в диалогах. Нигде. Пока.
Решение - переделка отображения цепочек документов в списках. Но пока не придумали как.

**Comment by Illya-Lykhachov** [comment]
4. Это, скорей всего, старый документ, в котором она рассчитывается неправильно. сделай новый акт. В новых актах сумма по документу (как и во всех зарплатных документах) - это сумма к выплате. Были глюки, но я все документы привёл к общему знаменателю.

**Comment by Illya-Lykhachov** [comment]
5. Сделано. Во всех документах раздела "Персонал"

**Comment by htrofymova** [comment]
1. исправлено

**Comment by Anestezia** [comment]
Ну, все вроде. Исправленное работает
