### ISSUE TITLE
Бухгалтерія - Рахунки. Список документов по счету.

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#326]
Добавлено:
* создание платежей;
* создание банковской выписки;
* импорт банковской выписки;
* фильтр списка документов по фрагменту (даты, номера, наименования контрагента, назначения платежа);
* печать списка документов;
* экспорт списка документов.

Проверить:
1. Для документов (платежки, выписка)  проверить создание, изменение, проведение, отображение в списке. При создании должен подставляться текущий счет.
2. Импорт выписки. В диалоге импорта должен подставляться текущий счет.
3. Поиск в списке документов (фильтр).
4. Печать и экспорт списка документов.

**Comment by Anestezia** [comment]
1. У нас в старом интерфейсе чем хорошо было, когда платежкой делалась операция Видаток в касу, то в этом же документе можно было создать и Надходження в касу. А теперь нужно переходить в другой документ (если додумаешься, а то будут кричать, мы отправили, а в кассе все равно не прибыло!).
![image](https://user-images.githubusercontent.com/42540074/58481661-81bf7900-8165-11e9-8b86-3b8837b2a086.png)
2. Здесь не отображаются в списке комментарии
![image](https://user-images.githubusercontent.com/42540074/58482645-69505e00-8167-11e9-9e75-9f51dd9d4051.png)
3. Проводки чуть не те, 311, а внутри 315  И должен ли в этом случае закрываться 311?
![image](https://user-images.githubusercontent.com/42540074/58483009-2b076e80-8168-11e9-8986-250a1d3108f2.png)
4. Нет второй проводки на внешнем поле справа. И у нас там кажется разбивка была по счетам и видам надходжень. 
![image](https://user-images.githubusercontent.com/42540074/58483910-c64d1380-8169-11e9-994d-377cceaee116.png)
5. Если у нас Операції Застарілі будут убираться, то как настроить в нових Рахунках Клиент-банк?
6. В остальном все ок. Експорт списка доков проверила.

Не проверила затягивание выписки. Нечем.

**Comment by AlexeyTishkin** [comment]
Пункты 1, 3, 4 - отдельный issue. К новому списку не относится. Тоже самое будет, если создавать из пункта "Платежи".
Можно в этот: https://github.com/a2develop/bugTracker/issues/851

**Comment by AlexeyTishkin** [comment]
Пункт 5 - настройка внутри диалога импорта.

**Comment by AndriyNesterenya** [comment]
Выписки я гоняю. Пока без замечаний.

**Comment by AlexeyTishkin** [comment]
Пункт 2 -добавил.

**Comment by Anestezia** [comment]
Есть пункт 2, в остальном у меня все без замечаний.
