### ISSUE TITLE
Отражение "транспортно-заготівельних витрат" (расходы, которые увеличивают с/с приобретенных материальных активов)

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#327]
1. Операция "Придбання послуг":
      * В перечень счетов для отнесения расходов (поле "Списання на") добавлен счет "2 Клас 2. Запаси". При выборе этого счета на форме появляется селектор для выбора документа, который является основанием для распределения расходов (поле "Підстава для розподілу"). В качестве основания можно выбрать любую проведенную операцию "Придбання матеріальних активів".
      * После выбора документа-основания дата текущего документа устанавливается равной дате документа-основания и запрещается для изменения.
      * В момент проведения операции с выбранным документом-основанием осуществляется распределение сумм расходов. В качестве базы распределения используется перечень объектов из документа-основания с суммой без НДС. По дебету операции отражается перечень объектов из документа-основания, счет - балансовый счет объекта (201, 281 и т.д.), сумма - распределенная сумма расходов, склад - из документа-основания. По кредиту отражается поставщик расходов, счет - 631, сумма - общая сумма расходов.
2. Операция "Придбання матеріальних активів":
      * В документ добавлена таблица "Витрати". Таблица предназначена для указания операций, которые увеличивают с/с материальных активов. Для выбора доступны непроведенные операции "Придбання послуг", дата которых равна дате текущей операции, а счет для отнесения расходов (поле "Списання на") равен счету "2 Клас 2. Запаси".
      * Распределение сумм расходов осуществляется в момент проведения операции.
      * В момент проведения операции осуществляется проведение всех операций, указанных в таблице "Витрати".
      * После проведения, в таблице с перечнем материальных активов появляется колонка "Сума з витратами". В ней отображается сумма окончательной с/с (с учетом распределения сумм расходов).
      * В момент отмены проведения операции осуществляется отмена проведения всех операций, указанных в таблице "Витрати".

**Comment by AlexeyTishkin** [comment]
Первый кейс:
1. "Придбання матеріальних активів".
   * Создать.
   * Дата 01/05/2019.
   * Перечень объектов - не менее двух. Количество и цена - любые.
   * Провести.
2. "Придбання послуг".
   * Создать.
   * Дата 29/05/2019.
   * Выбрать счет для отнесения расходов ("2 Клас 2. Запаси").
   * В селекторе "Підстава для розподілу" должна быть доступна для выбора операция от 01/05/2019. Проверить при помощи диалога выбора и при помощи быстрого поиска.
   * Выбрать операцию от 01/05/2019.
   * Дата текущей операции должна быть 01/05/2019 и запрещена от изменения.
   * Перечень объектов - не менее двух. Количество и цена - любые.
   * Провести.
   * Проводки:
      * В Дб перечень объектов и склад из операции "Придбання матеріальних активів". Счет - балансовый счет объектов. Количество - 0. Сумма - распределеная сумма текущей операции.
      * Проверить общую сумму по Дб, должна быть равна сумме без НДС текущей операции.
      * В Кр поставщик и сумма из текущей операции.
3. Открыть операцию "Придбання матеріальних активів" от 01/05/2019:
   * В таблице "Витрати" должна быть строка с операцией "Придбання послуг" от 01/05/2019.
   * В таблице с перечнем объектов должна быть колонка "Сума з витратами". Проверить сумму, должна быть сумма без НДС + сумма затрат из операции "Придбання послуг".
4. Операция "Реалізация запасів":
   * Создать.
   * Дата 02/05/2019.
   * Выбрать объекты из операции "Придбання матеріальних активів" от 01/05/2019.
   * Провести.
   * Проверить с/с в проводке Кр балансового счета (281, 201 и т.д.) - Дб 902. Должна быть с/с с учетом затрат.
5. Отчет "Оборотна-відомість по складу":
   * Проверить общие суммы прихода/расхода.
   * Построить детализирующий отчет "Оборотна-відомість" по одному объекту. Проверить суммы прихода/расхода по документам.
6. Отчет "Оборотна-відомість по об'єктах обліку" (строится по балансовому счету 281, 201 и т.д.):
   * Проверить общие суммы дебета/кредита.
   * Построить детализирующий отчет "Оборотна-відомість" по одному объекту. Проверить суммы дебета/кредита по документам.
7. Открыть операцию "Придбання матеріальних активів" от 01/05/2019. Попытаться отменить проведение. Должно быть сообщение о том, что отмена не возможна по причине того, что партии уже списаны.
8. Открыть операцию "Придбання послуг" от 01/05/2019. Попытаться отменить проведение. Должно быть сообщение о том, что отмена не возможна по причине того, что партии уже списаны.

**Comment by AlexeyTishkin** [comment]
Второй кейс:
1. "Придбання послуг".
   * Создать.
   * Дата 01/05/2019.
   * Выбрать счет для отнесения расходов ("2 Клас 2. Запаси").
   * Перечень объектов - не менее двух. Количество и цена - любые.
   * Проведение должно быть не доступно по причине отсутствия основания для распределения
   * Сохранить.
2. "Придбання матеріальних активів".
   * Создать.
   * Дата 01/05/2019.
   * Перечень объектов - не менее двух. Количество и цена - любые.
   * Таблица "Витрати":
      * Добавить строку.
      * В колонке "Документ" в селекторе должна быть доступна для выбора операция от 01/05/2019. Проверить при помощи диалога выбора и при помощи быстрого поиска.
   * Провести.
   * Проверить проводки. Проводки такие же, как и в обычной операции без расходов. В проводке Дб балансового счета (281, 201 и т.д.) - Кр 631 должна быть сумма с/с без НДС без расходов.
   * В таблице с перечнем объектов должна появиться колонка "Сума з витратами". Проверить сумму, должна быть сумма без НДС + сумма затрат из операции "Придбання послуг".
3. Открыть операцию "Придбання послуг" от 01/05/2019.
   * Открыть можно из таблицы "Витрати".
   * Операция должна быть проведенной.
   * Поле "Підстава для розподілу" должно быть заполненно операцией "Придбання матеріальних активів" от 01/05/2019.
   * Проводки:
      * В Дб перечень объектов и склад из операции "Придбання матеріальних активів". Счет - балансовый счет объектов. Количество - 0. Сумма - распределеная сумма текущей операции.
      * Проверить общую сумму по Дб, должна быть равна сумме без НДС текущей операции.
      * В Кр поставщик и сумма из текущей операции.

Выполнить пункты 4-8 из первого кейса.

**Comment by Anestezia** [comment]
1. Кейс 1. Операция "Реалізация запасів": Проверить с/с в проводке Кр балансового счета (281, 201 и т.д.) - Дб 902. Должна быть с/с с учетом затрат. Я делала все по инструкции, по порядку.
Вопрос: Услуги должны быть разбиты и входить в с\с этих запасов? У меня на 902 по этим позициям суммы четко, как покупались в первый раз. 
![image](https://user-images.githubusercontent.com/42540074/58637690-ba915680-82fb-11e9-902e-732a64f6b8b2.png)
![image](https://user-images.githubusercontent.com/42540074/58637730-da287f00-82fb-11e9-8efd-2e72805f5db5.png)
И еще на складе с минусом и красным, так должно быть?
![image](https://user-images.githubusercontent.com/42540074/58637799-ffb58880-82fb-11e9-8fcd-4b72e373d499.png)
2. Обе операции распровелись свободно, и придбання мат. активов и придбання послуг, хотя реализация этих активов у меня проведена. Может это быть потому что на складе этого товара еще полно?
Кейс 2 Реализация и проводки 902 (943) как написано выше.
Остальные пункты  работают как описано.

**Comment by AlexeyTishkin** [comment]
> У меня на 902 по этим позициям суммы четко, как покупались в первый раз.

Приходная + Акт каким числом ? В реализации партии от 03/12/18 и 24/03/19.

**Comment by AlexeyTishkin** [comment]
> И еще на складе с минусом и красным, так должно быть?

Да. По складу расход с минусом.

**Comment by AlexeyTishkin** [comment]
> Обе операции распровелись свободно, и придбання мат. активов и придбання послуг, хотя реализация этих активов у меня проведена. 

Какие партии в приходе, акте, расходе ?

**Comment by Anestezia** [comment]
Приходный и акты числами как в кейсе, от 01.05 и 02.05 расходные соответственно. Партии в приходе
![image](https://user-images.githubusercontent.com/42540074/58697645-86bd3c00-83a2-11e9-8d1a-caedb3a18a7e.png)
![image](https://user-images.githubusercontent.com/42540074/58698172-840f1680-83a3-11e9-9208-4aa69e133980.png)

Партии в расходе
![image](https://user-images.githubusercontent.com/42540074/58697917-e61b4c00-83a2-11e9-9ecc-89590a357037.png)

**Comment by AlexeyTishkin** [comment]
В расходе партии, оприходованные ранее.
В расходе надо поставить максимальное количество, чтобы списался весь остаток.
Либо кейсы прогнать на объектах, по которым еще не было приходов.

**Comment by Anestezia** [comment]
Да, подтверждаю с\с по новой партии идет в расходе с учетом затрат. 
Я понимаю, есть округление при распределении затрат, но смотрится это странно: 305,44 х 2 = 610,89.
![image](https://user-images.githubusercontent.com/42540074/58786739-e9a41280-85f0-11e9-8d90-e7f06c778e7f.png)

**Comment by AlexeyTishkin** [comment]
> Я понимаю, есть округление при распределении затрат, но смотрится это странно: 305,44 х 2 = 610,89.

Да, цена рассчитывается и форматируется до 2-х знаков.
Показывать как есть ?

**Comment by Anestezia** [comment]
А как есть может быть и слишком длинное число? Можно пока оставить так, и ждать отзывов.

**Comment by AlexeyTishkin** [comment]
> А как есть может быть и слишком длинное число? 

Да, с большим хвостом.

**Comment by AlexeyTishkin** [comment]
> Можно пока оставить так, и ждать отзывов.

Ок, ждем.
