### ISSUE TITLE
Механизм исправления проведенного документа добавлен в операцию "Отримання рахунку"

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#328]
[935](https://github.com/a2develop/bugTracker/issues/935)

Проверить возможность редактирования счета при наличии дочерних документов.

**Comment by Anestezia** [comment]
Редактируется: дата, кто выписал счет, добавляются позиции, меняется контрагент. При проведении, если ранее счет был погашен, то снова появляются возможности дополнительной оплаты и отгрузки. Попыталась распровести оплату, чтоб проверить, подставится ли другой контрагент. Не подставился и не редактируется, даже если сменить счет-основание на новый, в котором уже стоит другой контрагент. Вдруг это важно. 
Вообще, у меня претензий нет, все работает.

**Comment by AlexeyTishkin** [comment]
> Попыталась распровести оплату, чтоб проверить, подставится ли другой контрагент. 

Не подставится. Связанные документы не обновляются.
В этом случае - удалять и создавать заново.

**Comment by AlexeyTishkin** [comment]
> Вообще, у меня претензий нет, все работает.

Тогда закрываю.
