### ISSUE TITLE
Исправлено отображение кода банка

### ISSUE THREAD

**Issue by shevchuk-vadim** [a2develop/testing#33]
Проверить отображение кода банка при выборе банка из списка и при вводе с клавиатуры в
а) диалоге свойств и местре создания моей фирмы,
б) диалоге свойств и местре создания контрагента,
а) диалоге свойств банка,
а) диалоге свойств счета в банке.

Проверить отображение кода банка в гривневых и валютных платежных поручениях, при выборе счета в банке из списка и при вводе с клавиатуры.

**Comment by AndriyNesterenya** [comment]
Пока изменений не наблюдаю.
По крайней мере в ситуации создания счета новому контрагенту.
В моем случае - прямо из оплаты по банку

Выбираю банк, у которого есть код
![image](https://user-images.githubusercontent.com/38098758/45169690-d2bdc480-b206-11e8-9161-84cd7729151b.png)
название и город заполняется автоматом, код - нет
![image](https://user-images.githubusercontent.com/38098758/45169784-fd0f8200-b206-11e8-8fbd-c7be634ae522.png)

**Comment by mik-man** [comment]
Работает только локально у Вадима.
Видимо, не выложено на деве.
Что делать в таких случаях?
Просто ждать и сколько ждать?
Или сообщать кому-то?

**Comment by mik-man** [comment]
Можно тестировать.

**Comment by alex-kukhtin** [comment]
Вадим! Писать в гит только после публикации на деве.

**Comment by shevchuk-vadim** [comment]
А как я должен узнавать о публикации?
