### ISSUE TITLE
Поиск по тексту комментария

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#331]
[926](https://github.com/a2develop/bugTracker/issues/926)

Добавлено в фильтр списка документов в разделах "Бухгалтерія - Рахунки", "Бухгалтерія - Платежі", "Бухгалтерія - Платежі в валюті", "Придбання - Операції (beta)", "Продажі - Операції (beta)".

Проверить отображение списка документов.

**Comment by Anestezia** [comment]
Да, все хорошо! Теперь можно регулировать документы между менеджерами.
