### ISSUE TITLE
Операция "Внесення майна до статутного капіталу (емітент)"

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#332]
[812](https://github.com/a2develop/bugTracker/issues/812)

Операция "Внесення необоротних активів до статутного капіталу (емітент)" переименована в "Внесення майна до статутного капіталу (емітент)". Добавлена возможность ввода объектов, относящихся к "Класс 2. Запасы".

Проверить:
1. Ввод объектов различных типов: "Основні засоби", "Нематеріальні активи", "Сировина й матеріали", "Товари" и др.
2. Проведение.
3. Отражение в отчетах по движению.
4. Операцию расхода (реализацию, списание) с введенными объектами.

**Comment by Anestezia** [comment]
В списке отбора можно выбрать только эти виды, Запасов нет.
![image](https://user-images.githubusercontent.com/42540074/58872278-56d8a600-86cc-11e9-88ff-5c93d4794bb9.png)

**Comment by AlexeyTishkin** [comment]
Запасов в новом интерфейсе нет.
В старом: Придбання - Операції - Внесення майна...

**Comment by Anestezia** [comment]
А может тут нужно Додати списком?
![image](https://user-images.githubusercontent.com/42540074/58873321-c5b6fe80-86ce-11e9-86c5-b761f41a7699.png)
Все норм, остатки в расходе четко фиксирует, даты тоже.

**Comment by AlexeyTishkin** [comment]
> А может тут нужно Додати списком?

Появится в новом интерфейсе (в диалоге) - добавим.
