### ISSUE TITLE
Договора. Признак "Основний".

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#333]
[741](https://github.com/a2develop/bugTracker/issues/741)

Договора. Признак "Основний" теперь устанавливается внутри вида договора, т.е. теперь у контрагента может два основных договора: один "загальний", второй "комісії".
Операция "Отримання товарів від комітента". При выборе контрагента, у которого два договора ("загальний", "комісії") в операцию будет подставлен основной комиссионный договор.

Проверить:
1. Создать у контрагента договор "загальний". Номер "1". Сделать его основным.
2. У этого же контрагента создать договор "комісії".  Номер "2". Сделать его основным.
3. Проверить, что два договора имеют признак "Основний".
4. У этого же контрагента создать еще один договор "загальний". Номер "3". Сделать его основным.
5. Проверить, что признак "Основний" имеют договора "2", "3".
6. Создать операцию "Придбання матеріальних активів". Выбрать контрагента. В операцию 
должен быть подставлен договор "3".
7. Создать операцию "Отримання товарів від комітента". Выбрать контрагента. В операцию должен быть подставлен договор "2".

**Comment by Anestezia** [comment]
Так, все работает как указано.
