### ISSUE TITLE
Новые диалоги для документов типа "Бухгалтерська довідка"

### ISSUE THREAD

**Issue by htrofymova** [a2develop/testing#335]
Добавлены новые диалоги для документов типа "Бухгалтерська довідка": Бухгалтерська довідка (вручну), Бухгалтерська довідка, Нарахування податків, Курсові різниці.
Нужно проверить создание ( в т.ч. разніх операций), заполнение, сохранение, проведение.

**Comment by Anestezia** [comment]
упс, в предыдущем все написала по этому вопросу.
