### ISSUE TITLE
Новый раздел Бухгалтерия-Інше-Бухгалтерська довідка (beta).

### ISSUE THREAD

**Issue by htrofymova** [a2develop/testing#336]
Нужно проверить заполнение списка, "разделение".
Для документов - открытие, копирование, удаление.

**Comment by Anestezia** [comment]
1. Список по категориям разделяется, комментарии отображаются. 
2. Копирование не дает возможности редактировать, а при нажатии на Провести выдает ошибку
![image](https://user-images.githubusercontent.com/42540074/59018056-a8f50500-884d-11e9-9254-572255215fe8.png)
![image](https://user-images.githubusercontent.com/42540074/59018087-c033f280-884d-11e9-9c31-a4ebe444d06b.png)
3. Нужна кнопка Оновити (?)
![image](https://user-images.githubusercontent.com/42540074/59018164-ebb6dd00-884d-11e9-9b82-0b333057e6bb.png)
![image](https://user-images.githubusercontent.com/42540074/59018179-f4a7ae80-884d-11e9-9b59-ad8ff88d8dc2.png)
4. В скопированной валютной операции ячейка Валюта снова стала пустой и красной при Проведении. Нет сбоку второй проводки по Кт.
![image](https://user-images.githubusercontent.com/42540074/59018336-536d2800-884e-11e9-8ff1-b65e34ad2e00.png)
Так и провелась, данные про валюту и суммы обнулились. Сверху название не определенное. 
![image](https://user-images.githubusercontent.com/42540074/59018421-87484d80-884e-11e9-8af3-bb872878768c.png)
5. Это не только в скопированной операции курс. разницы, но и во вновь созданной.
6. Не отображаются проводки во внешнем окне.
![image](https://user-images.githubusercontent.com/42540074/59019433-b8298200-8850-11e9-8c01-f421290a1086.png)
7. Бух справка сначала копируется сразу проведенной, при этом внутри добавляется еще рядок - пустой и красный, пустой и красный номер, я тут же ставлю номер, удаляю пустой рядок проводок в таблице, меняю данные в счетах и сумме первой операции (скопированной), и это все в проведенной справке. 
![image](https://user-images.githubusercontent.com/42540074/59021059-cf1da380-8853-11e9-9e29-a859a48fc505.png)
7.1 Я невла свои изменения в скопированную проведенную справку, нажала закрыть. Спросило Сохранить, говорю да. С списке операций появилась эта операция не проведенной, без данных в колонках, открыть ее не удалось
![image](https://user-images.githubusercontent.com/42540074/59021194-1310a880-8854-11e9-861d-8b1a6a6ac205.png)
7.2 Создала такую же, Затем я таки сняла проведение. Все обнулилось. Я снова внесла свои данные, а кнопка Провести не активна.
![image](https://user-images.githubusercontent.com/42540074/59020144-130fa900-8852-11e9-851e-8d9e38cb5bfb.png)
8. После этого список автоматически не обновляется, кнопки тоже нет, в системе призрак удаленного (бывшего скопированного документа).
![image](https://user-images.githubusercontent.com/42540074/59020236-3d616680-8852-11e9-8412-87ef65282216.png)
9. При создании этой операции сумма не фиксируется, исчезает если нажать ентер или клик или провести. Кнопка Зберегти не активна
![image](https://user-images.githubusercontent.com/42540074/59020310-63870680-8852-11e9-8601-1cccf31608db.png)
10. Здесь между точкой и Довидкой нужен пробел.
![image](https://user-images.githubusercontent.com/42540074/59020473-be206280-8852-11e9-97c1-10b00150efe4.png)
11. Створення нарахування податкив - Нет возможности выбрать операцию, если стер (или просмотреть список операций)
![image](https://user-images.githubusercontent.com/42540074/59020644-18212800-8853-11e9-8178-652d4f874d61.png)
12. Не проводится по какой-то причине, все вроде заполнено.
![image](https://user-images.githubusercontent.com/42540074/59020732-4141b880-8853-11e9-917c-4f1dede67e35.png)

**Comment by htrofymova** [comment]
2. изменено - операции типа "Нарахування податків" скопировать нельзя (внутри есть кнопка Розрахувати).
Деление на 0 - исправлено
3. кнопка Обновить добавлена. 
4, 5. исправлено
6. Отображение Дебет и Кредит в панели справа отключено, как не имеющее смысла в операциях, где более одной проводки.
7-8. копирование и связанные с ним - исправлено.
9.  исправлено
10. изменено на полное название
11. изменено - нельзя стереть операцию
12. исправлено
