### ISSUE TITLE
Механизм исправления проведенного документа добавлен в операцию "Придбання матеріальних активів"

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#338]
Проверить кейс:
1. Операция "Придбання матеріальних активів".
   * Создать.
   * Дата 01/06/2019.
   * Перечень объектов - не менее двух. Количество и цена - любые.
   * Провести.
2. Операция "Реалізация запасів":
   * Создать.
   * Дата 02/06/2019.
   * Выбрать объекты из операции "Придбання матеріальних активів" от 01/06/2019.
   * Выбрать максимальное количество (для того, чтобы в списание попали партии от 01/06).
   * Провести.
   * Проверить с/с в проводке Кр балансового счета (281, 201 и т.д.) - Дб 902.
3. "Придбання матеріальних активів" от 01/06.
   * Открыть.
   * Войти в режим исправления проведенного документа (кнопка "змінити").
   * В панели задач в группе "Ланцюжок документів" должна быть накладная от 02/06.
   * Изменить цену любого объекта (можно нескольких).
   * Сохранить.
4. Операция "Реалізация запасів" от 02/06:
   * Открыть.
   * Проверить с/с в проводке Кр балансового счета (281, 201 и т.д.) - Дб 902. Должна быть с учетом изменений в п. 3.

**Comment by Anestezia** [comment]
да. все так.
