### ISSUE TITLE
Бухгалтерська довідка (beta). Новый диалог "Зарахування зустрічних однорідних вимог"

### ISSUE THREAD

**Issue by htrofymova** [a2develop/testing#339]
Добавлен новый диалог для документов типа "Акт зарахування зустрічних однорідних вимог".
Нужно проверить создание-заполнение-сохранение-удаление-проведение-печать.

**Comment by Anestezia** [comment]
Все ок.
п.с. На должности валидатор вроде стоит, но провести дает. Может это важно.

**Comment by htrofymova** [comment]
с валидатором - не повторяется
