### ISSUE TITLE
Бухгалтерська довідка (beta). Нові операції.

### ISSUE THREAD

**Issue by htrofymova** [a2develop/testing#340]
Для документа "Курсові різниці" додані операції: "Операційні курсові різниці (дохід)", "Операційні курсові різниці (витрати)". Треба перевірити: створення-заповнення-зберігання-проведення-скасування-видалення.

**Comment by Anestezia** [comment]
Не поставлен рахунок кредит, нужно другое сообщение, Типа Заповніть рахунок.
Єто в доходах и в витратах
![image](https://user-images.githubusercontent.com/42540074/59849437-47b25300-9370-11e9-82d4-5148a185249e.png)
 Остальное все ок.

**Comment by Anestezia** [comment]
Вопросов нет, то исправлено, можно закрывать.
