### ISSUE TITLE
Создание контрагента физлицо и ФОП под одним ИНН

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#341]
[961](https://github.com/a2develop/bugTracker/issues/961)

Изменен алгоритм проверки дубликата ИНН. Теперь можно создать контрагента с типом "Фізична особа-підприємець" при условии того, что уже существует контрагент с типом "Фізична особа" с таким же ИНН.

Проверить:
1. Создание контрагентов всех типов (всего 5 типов). При создании должен быть контроль:
   * наличия кода (кроме Нерезидентов и Інше)
   * формата кода (для юр. лиц - 8 цифр, для физ. лиц и физ. лиц - предпринимателей - 10 цифр, для нерезидента - только цифры).
   * проверка дубликата (проверка должна осуществляться в рамках типа, т.е. не может быть двух контрагентов с типом "Фізична особа-підприємець" с одинаковым ИНН).

2. Редактирование свойств контрагентов всех типов (всего 5 типов). При редактировании должен быть контроль кода (правила такие же как при создании).

**Comment by AlexeyTishkin** [comment]
Механизм импорта из клиент-банка. Изменен алгоритм идентификации существующих контрагентов. Поиск по ИНН осуществляется вначале среди контрагентов с типом "Фізична особа-підприємець", затем среди контрагентов с типом "Фізична особа". В случае отсутствия контрагента с нужным ИНН, он создается с типом "Фізична особа-підприємець".

Проверить кейсы (только для физ. лиц):
1. Контрагент из выписки отсутствует. Должен быть создан с типом "Фізична особа-підприємець".
2. Контрагент из выписки существует с типом "Фізична особа". В созданном документе "Банковская выписка" должен подставиться.
3. Контрагент из выписки существует с типом "Фізична особа-підприємець". В созданном документе "Банковская выписка" должен подставиться.
4. Контрагент из выписки существует с типом "Фізична особа" и с типом "Фізична особа-підприємець". В созданном документе "Банковская выписка" должен подставиться конетрагент с типом "Фізична особа-підприємець".

**Comment by AlexeyTishkin** [comment]
Банковская выписка. Добавлена проверка соответствия типа контрагента выбранной операции. К примеру, для операции "Надходження з каси" может быть выбран контрагент с типом "Юридична особа", для операции "Виплата зарплати фізичній особі" с типом "Фізична особа".

Проверить кейсы:
1. В строке выписки выбран контрагент с типом "Юридична особа":
   * выбрать операцию, которая применима для юр. лица (к примеру "Оплата покупця"). В строке выписке не должно быть ошибки.
   * выбрать операцию, которая применима для физ. лица (к примеру "Надання коштів підзвітній особі"). В строке выписки должна быть ошибка о не соответствии типа контрагента. В сообщении должен быть указан тип контрагента и тип, который разрешен для выбранной операции.
2. В строке выписки выбран контрагент с типом "Фізична особа". Те же действия, что для юр. лица, только другие операции.

Обратить внимание на то, что после выбора операции выбрать контрагента с неправильным типом невозможно. Выбрать контрагента нужно до выбора операции.

**Comment by AlexeyTishkin** [comment]
Механизм импорта контрагентов (из файла в формате xlsx). Изменен алгоритм идентификации существующих контрагентов. Поиск по ИНН осуществляется среди контрагентов с типом "Фізична особа-підприємець". В случае отсутствия контрагента с нужным ИНН, он создается с типом "Фізична особа-підприємець".

Проверить кейсы (только для физ. лиц):

1. Контрагент из файла отсутствует. Должен быть создан с типом "Фізична особа-підприємець".
2. Контрагент из файла существует с типом "Фізична особа". Должен быть создан новый с типом "Фізична особа-підприємець".
3. Контрагент из файла существует с типом "Фізична особа-підприємець". Должно быть сообщение, что контрагент существует.
4. Контрагент из файла существует с типом "Фізична особа" и с типом "Фізична особа-підприємець". Должно быть сообщение, что контрагент существует.

**Comment by GalinaLuk** [comment]
Изменен алгоритм проверки дубликата ИНН. Теперь можно создать контрагента с типом "Фізична особа-підприємець" при условии того, что уже существует контрагент с типом "Фізична особа" с таким же ИНН. 
- у меня не создался ФОП, говорит что с таким номером уже существует. С другой стороны, у меня не только в контрагентах физлицо, у меня и в сотрудниках есть это же физлицо с таким ИНН
![Screenshot at 2019-06-26 19-18-27](https://user-images.githubusercontent.com/46449132/60197440-07f3db80-9848-11e9-9a7b-3a5d8725e33e.png)
в левом окошке на скрине создан контрангент физлицо, а в правом я пыталась создать такого же ФОПа

**Comment by AlexeyTishkin** [comment]
> у меня не создался ФОП, говорит что с таким номером уже существует.

Ну так есть уже ФОП с таким кодом. ФОП Чебуркін В. А.

**Comment by Anestezia** [comment]
1.2. Все проверки проходит и создание и редактирование.
Клиент-банк проверить не могу 
Банковская выписка - платник юрик, операции физиков -- проверка работает
Платник физик -- операция юрика -- проверка не работает. 
По импорту через файл ексель -- все подтверждено.

**Comment by AlexeyTishkin** [comment]
> Платник физик -- операция юрика -- проверка не работает.

Какая операция ?

**Comment by Anestezia** [comment]
1. 
![image](https://user-images.githubusercontent.com/42540074/60267466-f6b3d900-98f2-11e9-8760-2db949cf2917.png)
2. 
![image](https://user-images.githubusercontent.com/42540074/60267488-059a8b80-98f3-11e9-916d-4252542f7834.png)

3. ![image](https://user-images.githubusercontent.com/42540074/60267434-e4399f80-98f2-11e9-91fe-c21ba089d872.png)

**Comment by Anestezia** [comment]
> > Платник физик -- операция юрика -- проверка не работает.
> 
> Какая операция ?

Все те, что в задании, только обратно.

**Comment by AlexeyTishkin** [comment]
> Все те, что в задании, только обратно.

В задании пример для физика не корректный. Оплата от покупателя применима для всех типов.
Надо выбрать физика и полистать операции. Есть только для юриков.

**Comment by Anestezia** [comment]
а, да. Некоторіе есть. проверка работает.

**Comment by AlexeyTishkin** [comment]
Исправил импорт из каталога по коду ЄДРПОУ.

**Comment by Anestezia** [comment]
да, затянулось по тому коду, что не шел.
