### ISSUE TITLE
В операциях "Оплата покупця", "Повернення коштів покупцю" теперь можно выбирать контрагента с типом "Інше"

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#342]
[970](https://github.com/a2develop/bugTracker/issues/970)

Проверить выбор и проведение в платежке и строке выписки.

**Comment by Anestezia** [comment]
"Повернення коштів покупцю" -- можно выбрать
"Оплата покупця" -- нет его в списке
Оплата постачальнику -- также нет в списке моего Инше

**Comment by AlexeyTishkin** [comment]
> "Оплата покупця"

Надо еще раз попробовать. Произошла накладка при добавлении операции "Внесення власних коштів на банківський рахунок".

**Comment by AlexeyTishkin** [comment]
> Оплата постачальнику

Здесь не должно быть.

**Comment by Anestezia** [comment]
Да, уже все норм.
