### ISSUE TITLE
Банковская выписка. Добавлен выбор видов доход/расходов для определенных операций (аналогично платежам)

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#345]
[962](https://github.com/a2develop/bugTracker/issues/962)

Проверить:
1. Возможность выбора.
2. Сохранение.
3. Изменение.
4. Проведение.
5. После проведения, в созданном платежном поручении проверить присутствие вида и проводки.

**Comment by Anestezia** [comment]
Есть, и в платежке тоже проводки меняются, вид тоже.
