### ISSUE TITLE
Банковская выписка. Проверка остатка р/с

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#347]
[977](https://github.com/a2develop/bugTracker/issues/977)

При проведении (отмене проведения) строки выписки убрана проверка остатка р/с.

Проверить проведение (отмену проведения):
1. Любой приходной операции в грн.
2. Любой расходной операции в грн.
3. Любой приходной операции в валюте.
4. Любой расходной операции в валюте.

Проверить кейс:
1. Создать выписку.
2. В первой строке операция "Оплата покупця", контрагент любой, сумма 1000 грн.
3. Во второй строке операция "Оплата постачальнику", контрагент любой, сумма такая, чтобы остаток на конец дня был отрицательным.
4. Провести строку № 2. Строка должна провестись, сообщений об ошибке быть не должно.
5. Провести строку № 1.
6. Отменить проведение строки № 1. Должна быть отмена проведения строки, сообщений об ошибке быть не должно.

**Comment by Anestezia** [comment]
Гривна валюта, проводится без ошибки, снимается проведение.
