### ISSUE TITLE
Дубликаты ИНН

### ISSUE THREAD

**Issue by alex-kukhtin** [a2develop/testing#35]
https://github.com/a2develop/bugTracker/issues/408

**Comment by kattrina-brekhova** [comment]
создать контрагента с таким же ЗКПОУ не возможно, пишет, что уже существует

**Comment by kattrina-brekhova** [comment]
а вот номер плательщика НДС сервис дает дублировать уже существующий и сохраняет такого контрагента

**Comment by alex-kukhtin** [comment]
Делайте новый issue. А этот закрывайте
