### ISSUE TITLE
Возможность привязки к Счету-основанию для кассовых ордеров.

### ISSUE THREAD

**Issue by htrofymova** [a2develop/testing#350]
https://github.com/a2develop/bugTracker/issues/54 Реализовано для кассовых ордеров. Нужно проверить.

**Comment by Anestezia** [comment]
Есть! Правда можно беспрепятственно подгрузить счет другого контрагента и провести. При том операция будет привязываться все же к контрагенту-получателю\отправителю, а не к счету в цепочке документов в списке операций. Стоит убрать или оставить как фичу?

**Comment by htrofymova** [comment]
исправлено
