### ISSUE TITLE
Парные операции на основании.

### ISSUE THREAD

**Issue by htrofymova** [a2develop/testing#352]
https://github.com/a2develop/bugTracker/issues/964. Реализовано создание парных операций на основании: из расходного ордера «Видаток з каси на рахунок в банку» создается платежка «Приход з каси», из платежки «Видаток в касу» создается приходный ордер «Надходження з рахунку в банку». Нужно проверить.

**Comment by Anestezia** [comment]
Здесь поле платник должно быть активным?
![image](https://user-images.githubusercontent.com/42540074/60542958-d97d7100-9d1d-11e9-8460-82d603a52a95.png)
В остальном вроде все ок.

**Comment by htrofymova** [comment]
Думаю, да, это же внутренний уже платеж с 333 счета.
