### ISSUE TITLE
Налоговая накладная. Контрагент нерезидент

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#353]
[876](https://github.com/a2develop/bugTracker/issues/876)

Для контрагента нерезидента в реквизите "Найменування; прізвище, ім'я, по батькові - для фізичної особи - підприємця" отображается его наименование и через запятую страна, в которой он зарегистрирован (из его свойств). 

Проверить отображение реквизита для:
1. Контрагента резидента. Должно быть полное наименование (если не указано, то обычное наименование).
2. Контрагента нерезидента. Должно быть полное наименование (если не указано, то обычное наименование) запятая страна.

**Comment by Anestezia** [comment]
Да, есть. Подтверждаю
