### ISSUE TITLE
Код КСПОВО

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#354]
* в свойствах единицы измерения добавлена проверка формата (четыре цифры, возможны лидирующие нули).
* в операциях "Податковий кредит/зобов'язання" добавлена проверка формата.

Проверить:
1. Ввод кода в свойствах единицы измерения.
2. Экспорт налоговой накладной в XML.
3. Экспорт налоговой накладной в Сонату с последующей проверкой корректности.

**Comment by Anestezia** [comment]
Все ок. Сонатовскую проверку прошла.
Насчет проверки в самих накладных, не совсем понятно, импорта в Буккипер накладных нет. Редактирования кода в накладных нет. Есть только тот код, что в свойствах объекта, а там уже проверка есть и неправильно его не введешь.

**Comment by AlexeyTishkin** [comment]
> Насчет проверки в самих накладных, не совсем понятно

Это для случая, если в базе уже есть неправильный код (введен до добавления проверки в свойствах единицы измерения).
