### ISSUE TITLE
Операция "Виставлення рахунку". Добавлена не строгая проверка на превышение остатка

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#355]
[326](https://github.com/a2develop/bugTracker/issues/326)

Проверить наличие проверки. Количество, которое превышает остаток должно быть подсвечено желтым, должна быть всплывающая подсказка с количеством остатка.

Проверить проведение при наличии:
1. Ошибок (к примеру: отсутствие покупателя, цены). Должно быть сообщение об ошибках, документ провести нельзя.
2. Предупреждений (превышение остатка). Должно быть сообщение о предупреждениях. Должен быть вопрос о подтверждении проведения. При согласии - документ должен быть проведен.

**Comment by Anestezia** [comment]
Да, в обоих случаях все работает как описано
