### ISSUE TITLE
Отчет "Оборотно-сальдова відомість по рахунку в банку". Добавлено предупреждение о наличии в выбранном периоде не проведенных документов.

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#356]
[984](https://github.com/a2develop/bugTracker/issues/984)

Проверить:
1. Правильность вывода предупреждения.
2. Проверить правильность подсчета количества не проведенных документов в сообщении.

**Comment by Anestezia** [comment]
Предлагаю для валютных чуть подправить текст в сообщении:  Бухгалтерия- Платежи в валюте - Чернетки, а то люди могут не сориентироваться. А так все ок. Подсчет верный

**Comment by AlexeyTishkin** [comment]
> Предлагаю для валютных чуть подправить текст в сообщении

Изменил.
