### ISSUE TITLE
Добавлена операция "Оплата покупця з комісією"

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#357]
[980](https://github.com/a2develop/bugTracker/issues/980)

Проверить:
1. Создание.
2. Изменение.
3. Проведение.
4. Отражение в отчетах (по банку, по контрагенту).

**Comment by Anestezia** [comment]
Есть, все проводится, изменения вносятся. В отчетах по контрагенту идет вся сумма с комиссией, а в отчет по банку, без комиссии. Через выписку создание тоже ок
