### ISSUE TITLE
Прайс-листы. Вид цены. Добавлено свойство "Ціна з ПДВ"

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#359]
[821](https://github.com/a2develop/bugTracker/issues/821)

В документах "Счет исходящий", "Расходная накладная", "Акт оказанных услуг", "Акт оказанных услуг с материалами" изменено поведение свойства "ПДВ в т.ч.". Теперь значение этого свойства зависит от значения свойства вида цены "Ціна з ПДВ". Если вид цены в документе не выбран, то значение можно менять вручную.

Проверить:
1. Изменение свойства в справочнике "Прайс-листы".
2. Выбор в документе вида цены с включенным свойством "Ціна з ПДВ":
   * свойство документа "ПДВ в т.ч." должно быть включено и запрещено.
   * значение цены должно считаться ценой с НДС. При цене 100 грн: разом без ПДВ = 83.33, ПДВ = 16.67, усього = 100.00 грн.
3. Выбор в документе вида цены с выключенным свойством "Ціна з ПДВ".
   * свойство документа "ПДВ в т.ч." должно быть выключено и запрещено.
   * значение цены должно считаться ценой без НДС. При цене 100 грн: разом без ПДВ = 100.00, ПДВ = 20.00, усього = 120.00 грн.
4. Удалить из документа прайс-лист или вид цены. Свойство документа "ПДВ в т.ч." должно быть доступно для изменения вручную.

**Comment by Anestezia** [comment]
Насчет пункта 2 представляю как посыплются вопросы, нужно будет хорошо в новости прописать эти взаимодействия
Все работает как описано.

**Comment by AlexeyTishkin** [comment]
> Насчет пункта 2 представляю как посыплются вопросы, нужно будет хорошо в новости прописать эти взаимодействия

И п. 3 :)
Да, надо будет описать.
