### ISSUE TITLE
Свойства "моей фирмы"

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#360]
[399](https://github.com/a2develop/bugTracker/issues/399)

Добавлены свойства: "Здійснюється зовнішньоекономічна діяльність", "Назва англійською мовою", "Адреса англійською мовою". 

Проверить:
1. Редактирование:
   * отбражение свойств "Назва англійською мовою", "Адреса англійською мовою" зависит от свойства "Здійснюється зовнішньоекономічна діяльність".
   * обязательность заполнения свойства "Назва англійською мовою" зависит от свойства "Здійснюється зовнішньоекономічна діяльність".
2. Отображение в печатной форме операции "Експорт послуг".

**Comment by Anestezia** [comment]
А в инвойсе должно идти наименование фирмы (на укр.) сокращенное?
В остальном все ок.

**Comment by AlexeyTishkin** [comment]
> А в инвойсе должно идти наименование фирмы (на укр.) сокращенное?

Сейчас - так. Если нужно по другому - отдельный issue.
