### ISSUE TITLE
Договоры ГПХ. НДФЛ и военный сбор были выделены в отдельные методы

### ISSUE THREAD

**Issue by Illya-Lykhachov** [a2develop/testing#362]
Изменения коснулись:
- Акт по договору ГПХ
- Отчёт "Расчётно-платёжная ведомость"
- Звіт в ЕФСС (Форма № Д4, Таблица 1, J3040112)

Может ещё где-то вылезти, нужно проверить все, где есть ГПХ

**Comment by Anestezia** [comment]
Никаких косяков не заметила. В табл. 1 нет ндфл и военного.
