### ISSUE TITLE
Необоротні активи. Численні зміни у документах "Акт введення в експлуатацію", "Поліпшення об'єктів НА", "Виготовлення ОЗ"

### ISSUE THREAD

**Issue by htrofymova** [a2develop/testing#363]
Треба перевірити функціонал операцій за документами "Акт введення в експлуатацію", "Поліпшення об'єктів НА", "Виготовлення ОЗ" з урахуванням змін:
1. #981 Додана можливість коригування вартості робіт/послуг. Залишок суми контролюється. Також, якщо сума вказана повністю, кількість автоматично заповнюється повністю.
2. #967 Додана автоматична нумерація для інвентарних номерів об'єктів необоротних активів.
3. #982 Додана можливість вибрати та зберегти у властивостях рахунок віднесення витрат для кожного об'єкту необоротних активів. Документ Відомість амортизації. Реалізована можливість віднесення витрат на різні рахунки, якщо таке вказано у властивостях об'єктів необоротних активів, або ж на один рахунок, який можна вибрати безпосередньо у документі.
4. #991 Виправлено некоректне відображення залишків матеріалів в скопійованому документі, та при зміні дати.

**Comment by GalinaLuk** [comment]
#981 Я так понимаю, что нужно проверять  "Поліпшення об'єктів НА", "Виготовлення ОЗ".   Не понимаю, как работает выбор материалов - во вкладке "материалы" при открытии номенклатуры я могу только создать новое, а не выбрать из того, что есть. Во вкладке "Услуги, " - можно тоже только создать две новых номенклатуры услуги и услуги аренды. Если работы еще и можно отнести к услугам, то ЗП сотрудника тоже предлагаем добавлять как услугу?
#967 инвентарный номер присваивается автоматически
#982 У меня почему-то при выборе счета в списке открывается сначала большое количество строк с 23 счетом, если прокрутить вниз, через некоторое время начинается список из одинаковых строк с 91 счетом и т.д. 
#991 при копировании какого документа был неправильный остаток материалов?

**Comment by htrofymova** [comment]
материалы и услуги - отображаются остатки 152, 153 или 154 счетов, в зависимости от того, какой необоротный актив "поліпшуеться". Сначала надо их "туда" списать

**Comment by htrofymova** [comment]
надо проверить копирование всех трех  "Акт введення в експлуатацію", "Поліпшення об'єктів НА", "Виготовлення ОЗ"

**Comment by htrofymova** [comment]
по множственности строк - не могу повторить, напишите свой логин-пароль.

**Comment by htrofymova** [comment]
ЗП сотрудника - єто ЗП сотрудника, которая отнесена на 152, 153 или 154 счет

**Comment by Anestezia** [comment]
В каком смысле ЗП сотрудника на 152, 153, 154? 
![image](https://user-images.githubusercontent.com/42540074/61868478-20f0ba80-aee2-11e9-9d20-833308f239e3.png)
У нас разве такое возможно?

**Comment by htrofymova** [comment]
на 152, 153 или 154 счета ЗП относится не постоянно, а , например, если сотрудники выполнили работы связанные с вводом в эксплуатацию, улучшением иои изготовлением необоротных активов и именно эту часть ЗП надо включить в стоимость необоротных активов.

**Comment by Anestezia** [comment]
1.,2.,3. все ок. Работает как описано. В амортизации есть разные счета затрат.
4. Если я списала ресурс при изготовлении 25 числом, то потом при создании подобного документа 15 числом, этого ресурса на складе на дату 15 число уже нет. Хотя по логике еще должно быть.

**Comment by htrofymova** [comment]
изменила диалог подбора материалов, теперь при выборе видно: [залишок] (на дату документа), [доступно] (с учтом того, что списано позднее), [списано пізніше].
изменила процедуру проведения - партия, которую выбрали, выбирая необоротный актив, теперь не меняется (цена-сумма - тоже).

**Comment by Anestezia** [comment]
С этим все ок. Работает.
