### ISSUE TITLE
Банковская выписка. Платежное поручение. Выбор документа-основания.

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#364]
Исправлена ошибка, из-за которой после выбора документа-основания выбранная операция менялась на "Оплата покупця на рахунок в банку".

Проверить:
1. В момент выбора основания операция выбрана ("Оплата покупця", "Оплата покупця з комісією", "Оплата постачальнику"). После выбора основания операция не должна меняться.
2. В момент выбора основания операция НЕ выбрана. После выбора основания для Входящего счета должна быть выбрана операция "Оплата покупця", для Исходящего - "Оплата постачальнику".
3. После выбора основания должна быть возможность изменения операции.

**Comment by Anestezia** [comment]
1. да
2. да
3. Основание выбрала, операцию уже изменить не могу. Ничего не проводила.

**Comment by AlexeyTishkin** [comment]
> Основание выбрала, операцию уже изменить не могу. Ничего не проводила.

Точно выбор "Підстави", не "Платіжне доручення" ?

**Comment by Anestezia** [comment]
Было пустое, просто зашла и выбрала платежку-основание на вкладке Дополнительно. Вернулась на вкладку основную, там заполнилась информация вся, и отримувач, и сумма и операция. И вот операцию я больше редактировать не могу, да и все остальное тоже. Пока не удалю платежку основание на дополнительной вкладке.

**Comment by AlexeyTishkin** [comment]
> выбрала платежку-основание 

Есть "Платіжне доручення" и есть "Підстава". Документ-основание - это "Підстава", в контексте обсуждаемых операций - Счет (входящий или исходящий).

**Comment by AlexeyTishkin** [comment]
> Вернулась на вкладку основную, там заполнилась информация вся, и отримувач, и сумма и операция. И вот операцию я больше редактировать не могу, да и все остальное тоже.

В случае с выбором "Платіжне доручення" - так и должно быть.

**Comment by Anestezia** [comment]
Тогда все ок.
