### ISSUE TITLE
Придбання - Операції, Продажі - Операції. Платежные поручения и кассовые ордера создаются и открываются в новом интерфейсе (диалогах).

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#365]
Проверить:
1. Создание.
2. Редактирование.
3. Проведение.
4. Копирование.
5. Удаление.

**Comment by Anestezia** [comment]
Эти операции пока будут? Не бета, а обычные? Список не обновляется автоматически, кнопки обновить нет. Созданный документ идет в конец первого листа.
![image](https://user-images.githubusercontent.com/42540074/62051966-384ee100-b21d-11e9-8c7f-5e8fed124677.png)
С основными задачами не нашла замечаний.

**Comment by AlexeyTishkin** [comment]
> Эти операции пока будут? Не бета, а обычные?

Будут пока не доделается новый интерфейс.

**Comment by AlexeyTishkin** [comment]
> Список не обновляется автоматически

После чего не обновляется ?

**Comment by AlexeyTishkin** [comment]
> Созданный документ идет в конец первого листа.

В новом интерфейсе операции, созданные при помощи диалога, везде добавляются в конец списка на первой странице.

**Comment by AlexeyTishkin** [comment]
> С основными задачами не нашла замечаний.

Тогда закрываю.
