### ISSUE TITLE
Добавлены отчет "Оборотно-сальдова відомість по рахунках в банках", "Оборотно-сальдова відомість по рахунках в банках в валюті".

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#366]
[1007](https://github.com/a2develop/bugTracker/issues/1007)
[1008](https://github.com/a2develop/bugTracker/issues/1008)

1. Добавлен отчет "Оборотно-сальдова відомість по рахунках в банках":
   * в плане счетов на счете 311.
   * Бухгалтерія - Платежі - Звіти. Вместо отчета "Оборотно-сальдова відомість по рахунку".
   * Бухгалтерія - Звіти. Вместо отчета "Оборотно-сальдова відомість по рахунку в банку в національній валюті".
2. Добавлен отчет "Оборотно-сальдова відомість по рахунках в банках в валюті":
   * в плане счетов на счете 312.
   * Бухгалтерія - Платежі в валюті - Звіти. Вместо отчета "Оборотно-сальдова відомість по рахунку".
   * Бухгалтерія - Звіти. Вместо отчета "Оборотно-сальдова відомість по рахунку в банку в іноземній валюті".

Проверить:
1. Построение отчетов.
2. Детализацию строк.

**Comment by Anestezia** [comment]
Замечаний нет.
