### ISSUE TITLE
Операция "Виставлення рахунку". Добавлена не строгая проверка на превышение остатка

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#368]
[999](https://github.com/a2develop/bugTracker/issues/999)

Проверка на превышение остатка не осуществляется для объектов типа "Послуги", "Послуги з аренди".

Проверить:
1. Объекты типа "Послуги", "Послуги з аренди":
   * количество меньше, либо равно 0 - должен быть запрет на проведение.
   * количество больше 0 - не должно быть ни запрета, ни предупреждения.
2. Объекты всех прочих типов. Должно быть предупреждение о превышении остатка.

**Comment by Anestezia** [comment]
Да, подтверждаю.
