### ISSUE TITLE
Ввода номера расчетного счета в формате украинского IBAN

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#372]
При ввода номера расчетного счета в формате украинского IBAN (мастер создания "моей фирмы", свойства "моей фирмы", мастер создания контрагента, свойства контрагента, платежное поручение, банковская выписка), поля "Код банку" и "Назва банку" заполняются автоматически и запрещаются.

Проверить:
1. Ввод номера в старом формате. Поля "Код банку" и "Назва банку" не заполняются и доступны для ввода.
2. Ввод номера в новом формате. Поля "Код банку" и "Назва банку" заполняются автоматически и запрещаются.

![photo_2019-08-06_14-12-04](https://user-images.githubusercontent.com/35917940/62535489-38219780-b854-11e9-9f8e-e3d2523a02c5.jpg)

**Comment by Anestezia** [comment]
Ввод номера в 1 и 2 случаях действует как описано, а если менять существующий р\с, то Поля "Код банку" и "Назва банку" доступны для ввода и идет разногласие в мфо и мфо в счете.
При вводе банк подтягивается правильно, а вот при редактировании пока проверок корректности нет.
При вводе в платежке, если у контрагента не заведен счет, то при редактировании мфо счета айбан, банк меняется вместе с мфо. То же самое в выписке и в свойствах контрагента и фирмы. Документы проводятся.

**Comment by AlexeyTishkin** [comment]
> а если менять существующий р\с, то Поля "Код банку" и "Назва банку" доступны для ввода и идет разногласие в мфо и мфо в счете.

Поля "Код банку" и "Назва банку" должны заполниться и запретиться после изменения номера (Enter или переход в другое поле). Если после завершения редактирования номера поля не запретились, то номер не в формате IBAN.

**Comment by AlexeyTishkin** [comment]
> а вот при редактировании пока проверок корректности нет

В момент редактирования никакого поиска быть не может, только после завершения ввода.

**Comment by Anestezia** [comment]
Как сейчас работает, то при корректном внесении, все ок. Люди же сами знают свои реквизиты, всякую ерунду туда вносить не будут.
