### ISSUE TITLE
Операция "Початковий баланс по запасах"

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#373]
1. Операция "Початковий баланс по запасах" сделана в новом интерфейсе (диалоге).
2. Механизм исправления проведенного документа добавлен в операцию "Початковий баланс по запасах". [1011](https://github.com/a2develop/bugTracker/issues/1011).

Проверить:
1. Создание.
2. Редактирование (добавление/удаление строк, выбор склада/объектов, пересчет количество-цена-сумма).
3. Проведение.
4. Отражение в отчетах.
5. Списание оприходованных партий в расходных документах.
6. Отмену проведения.
7. Удаление.
8. Копирование.
9. Исправление проведенного.

**Comment by Anestezia** [comment]
Создала, при редактировании проведенного:
1. строки добавились без проблем
2. цены и количество менялись, все сохранялось.
 3. при удалении строки не сохранились изменения и  сообщение возникло:
![image](https://user-images.githubusercontent.com/42540074/62623044-81431b80-b928-11e9-86b0-19c84e0b7599.png)
Теперь постоянно при любом редактировании, будь то цена, количество (что раньше редактировалось) выдается это сообщение.
Распровести исходный документ не могу, так как партии подставились в накладные, в которых ранее подставлялись партии, полученные при закупке товара, а не при начальных остатках. Это может быть неприятным сюрпризом для пользователей.
![image](https://user-images.githubusercontent.com/42540074/62623316-37a70080-b929-11e9-9616-49b657d780f4.png)
Вопрос: Если при вводе остатков большой список связанных документов, несколько документов по каждому из товаров, например, 100 позиций. То они все будут выведены туда? И не сломает ли это систему, окно документа...

**Comment by AlexeyTishkin** [comment]
> при удалении строки не сохранились изменения и сообщение возникло:

Надо убрать из цепочки "Акт изготовления". Механизмом исправления проведенного документа Акт пока не обрабатывается. Ему нужно отменить проведение.

**Comment by AlexeyTishkin** [comment]
> Распровести исходный документ не могу, так как партии подставились в накладные, в которых ранее подставлялись партии, полученные при закупке товара, а не при начальных остатках. Это может быть неприятным сюрпризом для пользователей.

Ну так ФИФО же. Все правильно.

**Comment by AlexeyTishkin** [comment]
> Вопрос: Если при вводе остатков большой список связанных документов, несколько документов по каждому из товаров, например, 100 позиций. То они все будут выведены туда? 

Будут выведены все.

**Comment by AlexeyTishkin** [comment]
> И не сломает ли это систему, окно документа...

По поводу окна - должен появиться скроллер.
По поводу системы - там перед включением механизма выдается предупреждение "може знадобитися перепровести довгий ланцюжок...". Систему поломать не должно... вроде... :)

**Comment by AlexeyTishkin** [comment]
> Теперь постоянно при любом редактировании, будь то цена, количество (что раньше редактировалось) выдается это сообщение.

Если какие-то новые изменения не получается сохранить, то можно закрыть без сохранения и вернуться к предыдущей версии.

**Comment by Anestezia** [comment]
Тогда все ок. Если без акта изготовления. Но удалить его я уже не могу, чтоб не болтался.

**Comment by AlexeyTishkin** [comment]
> Но удалить его я уже не могу, чтоб не болтался.

В режиме редактирования проведенного можно удалить все объекты, добавить один, по которому нет движения и сохранить. Если не будет недостач, то после сохранения документу можно отменить проведение и удалить.

**Comment by Anestezia** [comment]
Нет, там все равно висит призрак акта изготовления и больше никаких изменений не приемлет.

**Comment by AlexeyTishkin** [comment]
Акту отдельно отменить проведение, он тогда в цепочку попадать не будет.
