### ISSUE TITLE
Банковская выписка. Операции "Надходження з іншого власного рахунку", "Видаток на інший власний рахунок".

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#376]
При выборе операций "Надходження з іншого власного рахунку", "Видаток на інший власний рахунок" в качестве контрагента устанавливается "моя фирма" и запрещается поле выбора.

Проверить:
1. Установление "моей фирмы" при выборе операций "Надходження з іншого власного рахунку", "Видаток на інший власний рахунок".
2. Выбор контрагентов в других операциях.

**Comment by Anestezia** [comment]
Подтверждаю 1 и 2.
