### ISSUE TITLE
Свойства "моей фирмы"

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#377]
Добавлена проверка дубликата кода ЕДРПОУ/ИНН.

В мастере создания и диалоге свойств попытаться ввести уже существующий код:
1. ЕДРПОУ для юр. лица.
2. ИНН для физ. лица.

**Comment by Anestezia** [comment]
Да, все ок. ИНН для просто физлица, не фопа повторно ввести можно. Вдруг єто важно.
