### ISSUE TITLE
В алгоритм определения типа и балансового счета расчетного счета в банке добавлена обработка формата IBAN.

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#379]
Проверить:
1. Определение типа в свойствах расчетного счета.
2. Определение балансового счета в момент проведения операций при помощи платежного поручения.
3. Определение балансового счета в момент проведения операций при помощи банковской выписки.

**Comment by Anestezia** [comment]
Проводка снаружи 311, а внутри по классу счета 2610 - 351. 2615 -  184
![image](https://user-images.githubusercontent.com/42540074/63848290-4026b000-c998-11e9-981a-eab68ca6a6c1.png)
![image](https://user-images.githubusercontent.com/42540074/63848431-7e23d400-c998-11e9-988f-19b0a34b0865.png)
П.С. Я создала платежку, провела ее, а потом вручную пыталась создать выписку,и на вкладке Дополнительно подтянула эту проведенную платежку. Выписку мне система отказалась проводить. Не считаю, что это правильно.
![image](https://user-images.githubusercontent.com/42540074/63848670-f1c5e100-c998-11e9-8134-4c52c1683ced.png)

**Comment by Anestezia** [comment]
И еще вопрос. Я вносила изменения в один и тот же счет, 2610 заменила на 2615 и т.д. На счет начали поступать деньги. Счет вроде один и тот же. А в новой платежке после изменения показывает остаток ноль
![image](https://user-images.githubusercontent.com/42540074/63849335-8d0b8600-c99a-11e9-9cff-22884f8010b4.png)
![image](https://user-images.githubusercontent.com/42540074/63849376-a0b6ec80-c99a-11e9-9560-447c4723b0ec.png)
И после проведения пришла на остаток только та сумма, которая в платежке была. 6565 грн. Теперь в каждой ранее созданной платежке показывает Доступний залишок 6565 грн. В списке счетов остаток 65860 грн. Всего послуплений: 59000+295+6565 = 65860. 
![image](https://user-images.githubusercontent.com/42540074/63849565-086d3780-c99b-11e9-94b4-e658d258dcf7.png)

**Comment by AlexeyTishkin** [comment]
> Я создала платежку, провела ее, а потом вручную пыталась создать выписку,и на вкладке Дополнительно подтянула эту проведенную платежку. Выписку мне система отказалась проводить. 

Попробуй сейчас.
Надо проверить все варианта: выбор проведенного, выбор не проведенного, без выбора документа.

**Comment by AlexeyTishkin** [comment]
> Я вносила изменения в один и тот же счет, 2610 заменила на 2615 и т.д.

Остаток считается по р/с + балансовый бухгалтерский счет. После изменения кода бухгалтерский счет уже другой, поэтому остаток 0.

**Comment by Anestezia** [comment]
В остальном все проводится теперь, подкрепляется проведенный док, подкрепляется непроведенный док, без выбора - создается платежка, при проведении выписки она тоже проводится. Если подкреплялся проведенный док, то после распроведения самой выписки он тоже распроводится.
