### ISSUE TITLE
Уточнюючий розрахунок податкових зобов'язань з податку на додану вартість у зв'язку з виправленням самостійно виявлених помилок

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#38]
[491](https://github.com/a2develop/bugTracker/issues/491)
Протестировать:

- [ ] создание под юр. лицом

- [ ] создание под физ. лицом

- [ ] создание связанного Приложения 1

- [ ] создание связанного Приложения 5

- [ ] формирование XML самого расчета

- [ ] формирование XML связанного Приложения 1

- [ ] формирование XML связанного Приложения 5

**Comment by Anestezia** [comment]
По юр.лицу проверила, данные табличные заполняются вручную в декларации и приложениях 1 и 5. Перенос в Сонату после проведения корректный и кнопкой переноса прямого и через xml. Наследование даты такое же, как и в основной декларации и приложениях (т.е. ставится только текущая нередактируемая Д1 и Д5). 
Здесь странный автоматический нередактируемый подсчет, перенос отрицательной суммы в рядках 18, 19, колонка 6. 
![image](https://user-images.githubusercontent.com/42540074/45347944-f6419000-b5b5-11e8-9f4d-2d2005fa372a.png)
Соната эту цифру после проверки на ошибки переставляет в другую колонку с отрицательным знаком.

![image](https://user-images.githubusercontent.com/42540074/45348034-356fe100-b5b6-11e8-93e2-2ac7b1c3ba79.png)

**Comment by AlexeyTishkin** [comment]
Исправил наследование даты в Приложения 1, 5.

**Comment by AlexeyTishkin** [comment]
Изменил расчет итога в строках 18, 19.

**Comment by Anestezia** [comment]
Проверила. Все ок и по дате и по строкам 18, 19.
