### ISSUE TITLE
Мультифирменность. Разделы "Персонал" и "Зарплата"

### ISSUE THREAD

**Issue by Illya-Lykhachov** [a2develop/testing#380]
Нужно проверить работу с несколькими предприятиями в разделах "Персонал" и "Зарплата". Документы, справочники, отчёты

**Comment by Anestezia** [comment]
Отчеты регламентированные, данные из других фирм не перетягивает (я совместила роли, чтоб это проверить.) Данные внутренних зп отчетов не смешивает.
