### ISSUE TITLE
Неприбыльные просьбы.

### ISSUE THREAD

**Issue by htrofymova** [a2develop/testing#381]
Сделано https://github.com/a2develop/bugTracker/issues/976. Нужно проверить

**Comment by Anestezia** [comment]
Я так понимаю. подставляется отдельно Счет и отдельно описание вида поступления. Они могут сосуществовать мирно. Все ок, проводится в таком виде, ни проводка, ни вид поступления не сбиваются при проведении.

**Comment by htrofymova** [comment]
Ввод в экусплуатацию и начисление амортизации - тоже надо проверить. и потом отчет неприбыльных организаций посмотреть.

**Comment by Anestezia** [comment]
Не открывается меню вида видатков при вводе.
![image](https://user-images.githubusercontent.com/42540074/63866602-213a1500-c9bc-11e9-9b1a-d95bb8aeb209.png)
Тут же список не менялся счетов?
![image](https://user-images.githubusercontent.com/42540074/63866745-5f373900-c9bc-11e9-9c14-e63fba717780.png)
А что такое Вид видатку и Вид Видатків? Это разные вещи? Я сначала не заметила, что их два.
После проведения видно, что есть значок посмотреть проводки, а нет знака Связанных доков.
Изменений в начислении амортизации не вижу. Счет затрат есть, и все. Других меню видов затрат нет.

**Comment by htrofymova** [comment]
исправила
Вид видатків -это для расходной части ( строки 2 ... 2.6) отчета неприбыльной организации (то, что они хотят в ДТ 484 и в строку 2.4.1).
Выбор счета  не делала, поставила 484 по умолчанию для 2.4.1. благодійна допомога. 
В операции ввода в эксплуатацию - появится дополнительная проводка (дт 484-кт69), если выбрали "вид видатків"
В амортизации - тоже появится доп. проводка (дт69-кт746) на сумму амортизации тех объектов, при вводе в эксплуатацию которых был выбран "вид видатків"

**Comment by Anestezia** [comment]
Вроде работает как описано. И в отчет попадает по дт и кт. Ввод в экспл. есть выбор вида затрат, амортизация отражает указанными проводками.
