### ISSUE TITLE
Счета затрат в договорах ГПХ

### ISSUE THREAD

**Issue by Illya-Lykhachov** [a2develop/testing#382]
В договорах ГПХ добавлен выбор счёта отнесения затрат. Этот счёт подставляется в проводки акта по этому договору. Если не указан, то 91-й счёт как и раньше. 1028
Изменен алгоритм формирования проводок актов по договорам ГПХ. Теперь расходы на финрезультат (Дт 23, Кт 91) относятся только если затраты по договору относятся на счёт 91.

**Comment by Anestezia** [comment]
Да, есть. Умолчание на 91 тоже есть.
