### ISSUE TITLE
В свойствах физлица в поле ИНН теперь можно указывать паспорт

### ISSUE THREAD

**Issue by Illya-Lykhachov** [a2develop/testing#383]
Нужно проверить валидатор на соответствия формату и отражение значения этого поля в фискальных отчётах (вплоть до экспорта в XML)

**Comment by Illya-Lykhachov** [comment]
В таблицах 5 и 6 отчёта "Додаток 4" (персонификация) если ИНН представлен паспортом, к нему добавляются "БК" или "П".

**Comment by Anestezia** [comment]
все работает в персонале, в отчеты Д4 подставляется. 
Теперь ситуация 2, если он еще и наш контрагент. Нужно валидатор изменить на вводе ИНН и отследить, чтоб напрямую подтягивалось в НН и прочие доки.
![image](https://user-images.githubusercontent.com/42540074/64008911-9d993900-cb1f-11e9-9eb0-5cc9e05990f5.png)

**Comment by AlexeyTishkin** [comment]
> Теперь ситуация 2, если он еще и наш контрагент. Нужно валидатор изменить на вводе ИНН

Сделал.
