### ISSUE TITLE
Платіж контрагенту, Вхідний платіж, Банківська виписка. Выбор контрагента

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#384]
При выборе контрагента подставляется его основной договор.

Проверить выбор контрагента, у которого:
1. Нет договоров.
2. Один договор, который не является основным.
3. Один договор вида "Загальний договір", является основным. Должен подставляться во все операции, кроме операций по комиссионной торговле.
4. Один договор вида "Договір комісії", является основным. Должен подставляться в операции по комиссионной торговле (например, "Перерахування коштів комітенту").
5. Два договора, один вида "Загальний договір", является основным, второй вида "Договір комісії", является основным. В зависимости от операции должен подставляться соответствующий вид договора.

**Comment by Anestezia** [comment]
Да, сбоев нет.
