### ISSUE TITLE
Початковий баланс

### ISSUE THREAD

**Issue by htrofymova** [a2develop/testing#385]
Створен новий розділ меню Початковий баланс. Потрібно бета-тестування наступних підменю:
1. Банк, каса (додаткова "отмашка")
2. Підзвіт
3. Необоротні активи
4. Запаси
5. Дебітори/кредитори
6. Зарплата
7. Інше (додаткова "отмашка")
Треба перевірити ВСЕ: списки і документи.

**Comment by htrofymova** [comment]
Банк, каса - можна перевіряти

**Comment by Anestezia** [comment]
1. Зарплата, нет отчетов по этому разделу. по остальным вкладкам есть они. 
![image](https://user-images.githubusercontent.com/42540074/65136895-097d0c00-da11-11e9-840b-226602343787.png)
2. Інше:
Количество не редактируется. В проводках оприходовано 0 шт. 
![image](https://user-images.githubusercontent.com/42540074/65136971-2e717f00-da11-11e9-8921-4ff6b787a202.png)
3. При выставлении фильтра не идет отбор, НА
![image](https://user-images.githubusercontent.com/42540074/65139273-0421c080-da15-11e9-8340-1ce623bb4797.png)

**Comment by Anestezia** [comment]
4. Нет кнопки Провести. на обе операции.
![image](https://user-images.githubusercontent.com/42540074/65151236-591e0080-da2e-11e9-9ec0-77b256a7b474.png)
5. Если все заполнил, а потом написал комментарий, то становится не активной кнопка Зберегти. Даже если по пустому полю клацать. Выход только изменить еще что-то.
![image](https://user-images.githubusercontent.com/42540074/65151524-f1b48080-da2e-11e9-93f9-0378af62422e.png)
6. Также, раз эти операции не проведенные, они должны отображаться в чернетках, а там пусто.
7. Не понятно почему нельзя внести изменения в начальный по запасам, ошибка не ясна
![image](https://user-images.githubusercontent.com/42540074/65154235-d13af500-da33-11e9-89b6-ba6cca87466c.png)
8. Нет разделов ВСІ и Чернетки
![image](https://user-images.githubusercontent.com/42540074/65154389-1c550800-da34-11e9-8a02-4390ade0aaed.png)
Требуется обновить страницу, чтоб увидеть вверху сумму документов по запасам.
9. Підзвіт - Звіти - период не проставлен вообще. На глобальный период не ссылается ни один отчет раздела. В остальных по умолчанию стоит За весь час.
10. Податки у меня в этой фирме еще пустой, а в реестр и в ОСВ тянет данные из другой фирмы
![image](https://user-images.githubusercontent.com/42540074/65154945-0ac03000-da35-11e9-9501-5f5ab1a97883.png)

**Comment by AlexeyTishkin** [comment]
> Інше: Количество не редактируется. В проводках оприходовано 0 шт.

В "Інше" для НА количество не должно редактироваться. При выборе объекта сделал установление количества равное 1.

**Comment by AlexeyTishkin** [comment]
> Не понятно почему нельзя внести изменения в начальный по запасам, ошибка не ясна

Надо попробовать повторно.

**Comment by AlexeyTishkin** [comment]
> Нет разделов ВСІ и Чернетки

Во вступительном балансе таких разделов быть не должно.

**Comment by htrofymova** [comment]
> При выставлении фильтра не идет отбор, НА

исправлено

**Comment by htrofymova** [comment]
> Підзвіт - Звіти - период не проставлен вообще. На глобальный период не ссылается ни один отчет раздела. В остальных по умолчанию стоит За весь час.

во вступительном балансе период не имеет смысла и глобальный в том числе, так как все документы имеют одну дату = 0, т.е. раньше всех

**Comment by htrofymova** [comment]
> Нет кнопки Провести. на обе операции.

исправлено

**Comment by htrofymova** [comment]
> Если все заполнил, а потом написал комментарий, то становится не активной кнопка Зберегти. Даже если по пустому полю клацать. Выход только изменить еще что-то.

С комментариями везде так: когда вводится комментарий, документ сохраняется и, следовательно, кнопка Зберегти становится не активной.

**Comment by htrofymova** [comment]
> Податки у меня в этой фирме еще пустой, а в реестр и в ОСВ тянет данные из другой фирмы

Это не ОСВ было, теперь ОСВ

**Comment by Anestezia** [comment]
Поч. баланс - ЗП, кнопка Прийняти співробітника не работает пока в подборе.
![image](https://user-images.githubusercontent.com/42540074/65236227-d3a75880-dae0-11e9-95a5-b56f3d69bdb3.png)
Поиск за кодом та посадою не работает
![image](https://user-images.githubusercontent.com/42540074/65236453-487a9280-dae1-11e9-9be8-e624bb995b9b.png)

**Comment by Anestezia** [comment]
Нет отметки в списке операций, что начальный баланс по ЗП Проведено
![image](https://user-images.githubusercontent.com/42540074/65587892-44da8600-df8f-11e9-92ca-543022e5f215.png)

**Comment by Anestezia** [comment]
По банку. С сохранением проблема. Я нажала Провести. а затем отменила. Кнопка сохранить стала неактивной.  Я добавила коммент. И закрыла документ. А теперь в списке операций он есть, сохраненный, не проведенный. но не открывается
![image](https://user-images.githubusercontent.com/42540074/65590337-49a13900-df93-11e9-814d-d677c39d9c29.png)

**Comment by Anestezia** [comment]
Странное равнение по кассе в названии
![image](https://user-images.githubusercontent.com/42540074/65591729-b0275680-df95-11e9-91f9-3e2d96ecc7de.png)


Странные кавычки Заборгованисть Зобов'язання
![image](https://user-images.githubusercontent.com/42540074/65593077-799f0b00-df98-11e9-9dca-656a2b82b189.png)

Как насчет добавить другие налоги, по которым также может быть переплата или задолженность: земельный, акциз, да мало ли.. просто что-то универсальное на 641 
![image](https://user-images.githubusercontent.com/42540074/65593259-c2ef5a80-df98-11e9-8c4e-5b14280ff102.png)

Насчет налогов, вообще не понятно, что с проводками и почему сумма вместе и переплата и задолженность идет в проводки
![image](https://user-images.githubusercontent.com/42540074/65593490-3f823900-df99-11e9-8d39-79217868b29d.png)

**Comment by htrofymova** [comment]
> По банку. С сохранением проблема. Я нажала Провести. а затем отменила. Кнопка сохранить стала неактивной. Я добавила коммент. И закрыла документ. А теперь в списке операций он есть, сохраненный, не проведенный. но не открывается

после отмены проведения документ сохраняется, потому кнопка Зберегти не активна. Остальное повторить не могу.

**Comment by htrofymova** [comment]
> Странное равнение по кассе в названии

исправлено

> Странные кавычки Заборгованисть Зобов'язання

исправлено

> Насчет налогов, вообще не понятно, что с проводками и почему сумма вместе и переплата и задолженность идет в проводки

исправлено

> Как насчет добавить другие налоги, по которым также может быть переплата или задолженность: земельный, акциз, да мало ли.. просто что-то универсальное на 641

в разделе Інше можно создать начальный баланс по любым счетам.

**Comment by Anestezia** [comment]
Податок на землю, акцизний податок - 641 рах. У нас так нельзя сделать.
![image](https://user-images.githubusercontent.com/42540074/65674921-fc39d000-e055-11e9-9382-53c4272a6682.png)

**Comment by htrofymova** [comment]
> Податок на землю, акцизний податок - 641 рах. У нас так нельзя сделать.

В план счетов нужно добавлять счета, если нужно, начальный баланс не виноват
