### ISSUE TITLE
Глобальный период

### ISSUE THREAD

**Issue by htrofymova** [a2develop/testing#386]
Появился глобальный период. Нужно проверить все разделы и отчеты на адекватное взаимодействие с ним.

**Comment by Anestezia** [comment]
Глобальный Период переключает периоды отбора в списках операций по каждому разделу нормально.

Список операций сохраняется пустым после отбора
![image](https://user-images.githubusercontent.com/42540074/64767840-1ef5c000-d551-11e9-9660-878fc3aad525.png)
Так отобралось
А так сохранилось
![image](https://user-images.githubusercontent.com/42540074/64767884-3339bd00-d551-11e9-8b9c-bebe4d2a598a.png)

**Comment by Anestezia** [comment]
Это к отбору отношения не имеет. В разделе Запасы так. в других все нормально экспортируется
