### ISSUE TITLE
В список отчетов по бухгалтерскому счету добавлен отчет "Реестр проводок"

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#387]
[1126](https://github.com/a2develop/bugTracker/issues/1126)

Проверить построение.

**Comment by Anestezia** [comment]
Построение в порядке. Печать норм, правда по низу полоса между листами идет, но это мелочь.
![image](https://user-images.githubusercontent.com/42540074/64770035-0e474900-d555-11e9-96a6-725f2058e422.png)

**Comment by AlexeyTishkin** [comment]
> правда по низу полоса между листами идет, но это мелочь.

Это проблема Chrome. Во многих местах так.
