### ISSUE TITLE
Декларация НДС. Изменение периода внутри отчета.

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#39]
Протестировать заполнение данными после изменения периода внутри отчета:

- [ ] Декларации НДС

- [ ] Приложения 1

- [ ] Приложения 5

**Comment by Anestezia** [comment]
Если брать задачу сделать отчет просто не текущим периодом, а, например, более ранним, то и Декларация и Д1, Д5 подтягивают данные из указанного периода корректно. 
Только дата ставится в Д1 и Д5 текущая и редактированию не подлежит. Дата внизу документа (Дата подання) в Додатках наследуется. Дата заполнения (вверху) не наследуется.

**Comment by AlexeyTishkin** [comment]
Исправил наследование даты в Приложения 1, 5.

**Comment by Anestezia** [comment]
Все работает корректно по датам.
