### ISSUE TITLE
Операция "Отримання рахунку" в новом интерфейсе (диалоге)

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#391]
Проверить:
1. Создание.
2. Редактирование.
3. Проведение.
4. Создание связанных документов.
5. Отмену проведения.
6. Печать.
7. Режим редактирования проведенного документа.
8. Отображение в списках.
9. Копирование.

**Comment by Anestezia** [comment]
Мелковато написаны создания доков на основании. 
Долговато выводит на печать и долговато удаляет. 
Все остальное работает в норме, по всем пунктам.
