### ISSUE TITLE
Совместимость операций вступительного баланса

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#392]
Необходимо проверить, чтобы все операции, которые были сформированы при помощи старого интерфейса (Бухгалтерия - Вступительный баланс) корректно отображались в новом интерфейсе (Вступительный баланс).

Проверить:
1. Отображение операции из старого интерфейса в правильном разделе нового интерфейса.
2. Открытие операции в новом интерфейсе.
3. Корректное отображение всех данных.
4. Возможность отмены проведения.
5. Возможность внесения изменений.
6. Повторное проведение.
7. Корректное отражение в учете.

Проверить нужно все операции старого интерфейса.
Для операций (по податках) будет дана отдельная отмашка :)

**Comment by htrofymova** [comment]
Податки - тоже можно проверять

**Comment by Anestezia** [comment]
Так выглядит Початковий баланс по необоротних активах из старого интерфейса, открытый в новом.
![image](https://user-images.githubusercontent.com/42540074/65599232-0a301800-dfa6-11e9-9113-56de3fc59cab.png)
А так созданный непосредственно  в новом
![image](https://user-images.githubusercontent.com/42540074/65599255-1fa54200-dfa6-11e9-96bc-95d78139d16a.png)
После открытия в новом интерфейсе дока. созданного в старом, и закрытия его, в списке операций пропадает название и стоимость. И по второму разу его не открыть без обновления страницы, чтоб название снова появилось. Что будет с такими доками, созданными ранее, после изъятия старого интерфейса? 
![image](https://user-images.githubusercontent.com/42540074/65599652-ff29b780-dfa6-11e9-81ff-82081b280fd9.png)

**Comment by Anestezia** [comment]
В отборе по операциям списка операций старого появилось 2 названия По Необоротным активам. 1 показывает созданные в старом инт.. а 2 - созданные в новом. Вот только созданные в новом при открытии из старого выглядят так
![image](https://user-images.githubusercontent.com/42540074/65599807-5760b980-dfa7-11e9-8a2c-832b94da13b7.png)
а должны такую инфу содержать
![image](https://user-images.githubusercontent.com/42540074/65599850-76f7e200-dfa7-11e9-9b87-669cb6ee7044.png)
При этом, если из старого скопировать такой файл. то инфа будет в основном на месте
![image](https://user-images.githubusercontent.com/42540074/65599896-9262ed00-dfa7-11e9-8e32-8e8adf32f04b.png)

**Comment by Anestezia** [comment]
если Нерозподілений прибуток, непокритий збиток будут теперь создаваться в колонке Инши, то созданные ранее из старого образца должны в ней отображаться, а этого нет. 

Новая касса: 1. не отображается сумма по кассе и по банку вверху (как в дебиторах/кредиторах. например)
![image](https://user-images.githubusercontent.com/42540074/65602865-461aab80-dfad-11e9-993e-22321ff00eae.png)
2. Созданный в новом, при открытии его в старом не показывает сумму.
3. В новом скопировала начальный по кассе и провела. В Отчете по кассе есть только один исходный документ и еще какой-то непонятный (в старых его нет). При попытке открыть из отчета выдало ошибку
![image](https://user-images.githubusercontent.com/42540074/65602824-369b6280-dfad-11e9-8b51-e6dc6ae6cd3b.png)
Он из другой фирмы вообще.

**Comment by htrofymova** [comment]
Нужно проверить, чтобы операции, созданные в старом интерфейсе корректно отображались в новом, а НЕ НАОБОРОТ!. 
Прочие манипуляции, как то: создание, копирование, изменение, удаление, проведение и т.д. проверить для операций, созданных в новом интерфейсе.

**Comment by htrofymova** [comment]
А "выглядеть" операции, созданные в старом и новом интерфейсах могут по-разному: "старые" -  так же, как в старом, а новые  - нет.

**Comment by htrofymova** [comment]
> Новая касса: 1. не отображается сумма по кассе и по банку вверху (как в дебиторах/кредиторах. например)
> 3. В новом скопировала начальный по кассе и провела. В Отчете по кассе есть только один исходный документ и еще какой-то непонятный (в старых его нет). При попытке открыть из отчета выдало ошибку

сделано

> После открытия в новом интерфейсе дока. созданного в старом, и закрытия его, в списке операций пропадает название и стоимость. И по второму разу его не открыть без обновления страницы, чтоб название снова появилось.

сделано

> В отборе по операциям списка операций старого появилось 2 названия

исправлено

**Comment by AlexeyTishkin** [comment]
> если Нерозподілений прибуток, непокритий збиток будут теперь создаваться в колонке Инши, то созданные ранее из старого образца должны в ней отображаться, а этого нет.

Сделал.

**Comment by Anestezia** [comment]
Странное отображение в новом старых и новых документов. Сначала список выглядит так
![image](https://user-images.githubusercontent.com/42540074/65681875-7a03d880-e062-11e9-8be9-5d507f961090.png)
После того, как каждый открыла и закрыла:
![image](https://user-images.githubusercontent.com/42540074/65681735-301af280-e062-11e9-8a9b-a014d76fc0e5.png)
Внутри нет информации по двум, я так понимаю, новым. По одному, сделанному изначально в старом, инфа есть. 
![image](https://user-images.githubusercontent.com/42540074/65681992-b9322980-e062-11e9-91d6-3cd95742f449.png)
Так выглядят и если через новый открыть и если через старый.
В ведомости вообще не понятные объекты
Вместо Передплата, глобус, Автомобиль, вот эти
![image](https://user-images.githubusercontent.com/42540074/65682081-e54daa80-e062-11e9-9325-34b8afccd775.png)
Из другой фирмы объекты уже вроде не подтягиваются.
Касса/банк -- все ок.
441 442 созданные из старого, нет счета. Можно догадаться что это за операция, только по названию сбоку. Распроводится, проводится в таком же виде без конфликтов. В принципе, ничего страшного. Ведомость видит эти операции
![image](https://user-images.githubusercontent.com/42540074/65682535-cf8cb500-e063-11e9-9134-0f1e05e1c12e.png)

**Comment by AlexeyTishkin** [comment]
> 441 442 созданные из старого, нет счета. 

А в старом он есть ?
![image](https://user-images.githubusercontent.com/35917940/65682921-ad476700-e064-11e9-9aa5-042e72e8ec8b.png)

**Comment by htrofymova** [comment]
обображение списка операций в необоротных переделала. Часть операций начального баланса (старых) вводились, как "За рахунком дебет". 
Ведомость - строится правильно, ибо учитывает вот эти самые операции.
