### ISSUE TITLE
Операции "Придбання матеріальних активів", "Безоплатне одержання запасів" сделаны в новом интерфейсе (диалоге)

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#393]
Проверить:
1. Создание.
2. Редактирование.
3. Проведение.
4. Отражение в учете
5. Создание связанных документов.
6. Отмену проведения.
7. Печать.
8. Режим редактирования проведенного документа.
9. Отображение в списках.
10. Копирование.

**Comment by Anestezia** [comment]
Все ок, только в бета операциях Безоплатне одержання запасів - очікує оплати. 
![image](https://user-images.githubusercontent.com/42540074/65686616-e801cd00-e06d-11e9-87f4-3a88d5770732.png)

**Comment by AlexeyTishkin** [comment]
> только в бета операциях Безоплатне одержання запасів - очікує оплати.

Исправил.

**Comment by Anestezia** [comment]
исправилось
