### ISSUE TITLE
Операция "Отримання інвойсу" в новом интерфейсе (диалоге)

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#394]
Проверить:
1. Создание.
2. Редактирование.
3. Проведение.
4. Создание связанных документов.
5. Отмену проведения.
6. Режим редактирования проведенного документа.
7. Отображение в списках.
8. Копирование.

**Comment by Anestezia** [comment]
Создание редактирование. проведение, связанные, отмена, копирование, списки -- все ок. 
Режим редактирования проведенного: Если поменять контрагента, то не подставляется договор, даже если он отмечен как основной. Просто стирается. Хорошо, что хоть стирается, а не остается от другой фирмы.
Если заменить валюту, то нет пересчета автоматического.
![image](https://user-images.githubusercontent.com/42540074/65681272-30ff5480-e061-11e9-8cae-4290ead74d1e.png)
В результате с этими неправильными суммами проводится, и создаются документы на основании тоже с такими неправильными суммами.  
При копировании такого неправильного документа нет кнопки Перерахувати. Хотя пригодилась бы.

**Comment by AlexeyTishkin** [comment]
> Если заменить валюту, то нет пересчета автоматического.

При любом изменении курса валюты, в т.ч. после смены валюты, появляется кнопка "перерахувати":
![image](https://user-images.githubusercontent.com/35917940/65681905-8c7e1200-e062-11e9-851a-c6760b1cd1c2.png)

**Comment by Anestezia** [comment]
Главное, чтоб сообразили за нее дернуть. В остальном с этим документом все ок.

**Comment by AlexeyTishkin** [comment]
> Главное, чтоб сообразили за нее дернуть

В старом (в форме) тоже так было.

**Comment by AlexeyTishkin** [comment]
> В остальном с этим документом все ок.

Тогда закрываю.
