### ISSUE TITLE
Операции "Імпорт запасів", "Безоплатний імпорт запасів" сделаны в новом интерфейсе (диалоге)

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#395]
Проверить:
1. Создание.
2. Редактирование.
3. Проведение.
4. Отражение в учете
5. Отмену проведения.
6. Режим редактирования проведенного документа.
7. Отображение в списках.
8. Копирование.

**Comment by Anestezia** [comment]
Если отредактировать контрагента, а по старому уже введен договор, то при подстановке нового контрагента остается старый договор по старому контрагенту. Убирается только после распроведения вручную.  Если просто снять проведение. а потом тут же провести ничего не меняя, то договор по новому контрагенту не подтягивается. Более того, этот договор наследуется в платежку на основании. 

Проводки еле нашла.
Из отчета по складу перешла в реестр документов по объекту, а документ сам не открылся
![image](https://user-images.githubusercontent.com/42540074/65678096-63a64e80-e05b-11e9-9557-6e00310b6d68.png)
Создание. копирование, распроведение/проведение. Списки -- все работает.

**Comment by Anestezia** [comment]
В отчете Из списка объектов учета этот документ называется Митна декларация и открывается
![image](https://user-images.githubusercontent.com/42540074/65678380-d7485b80-e05b-11e9-8da2-dbf18eb23141.png)
а там, из ведомости по складу-реестр документов по строке - импорт запасов и не открывается

**Comment by Anestezia** [comment]
Тут чуточку подсказка уходит под край рамки
![image](https://user-images.githubusercontent.com/42540074/65679333-89345780-e05d-11e9-9685-8646619a702b.png)

**Comment by Anestezia** [comment]
В режиме коригування Безоплатного импорту нет кроме номера и примечания еще и контрагента, а в импорте запасов это есть. 
Та же история с отображением из ведомости по складу
![image](https://user-images.githubusercontent.com/42540074/65679646-2a231280-e05e-11e9-85e2-3131b56fc070.png)
Кроме того, если из самих объектов учета открыть ведомость по складу, то также идет разное наименование документа и не открывается все, что не называется Митна декларация.
В остальном все ок.

**Comment by AlexeyTishkin** [comment]
> Из отчета по складу перешла в реестр документов по объекту, а документ сам не открылся

Исправил.

**Comment by AlexeyTishkin** [comment]
> Если отредактировать контрагента, а по старому уже введен договор, то при подстановке нового контрагента остается старый договор по старому контрагенту. Убирается только после распроведения вручную. Если просто снять проведение. а потом тут же провести ничего не меняя, то договор по новому контрагенту не подтягивается. Более того, этот договор наследуется в платежку на основании.

Это в "Внести коригування" ? Если да - то отдельный issue о том, что при корректировке контрагента нужно еще и договор выбирать.

**Comment by AlexeyTishkin** [comment]
> а там, из ведомости по складу-реестр документов по строке - импорт запасов

Митна декларація - название документа, Импорт запасов - название операции.

**Comment by AlexeyTishkin** [comment]
> Тут чуточку подсказка уходит под край рамки

Пока так. Она там ни в какую сторону не влазит.

**Comment by Anestezia** [comment]
https://github.com/a2develop/testing/issues/395#issuecomment-535442984 А поверх? если она появляется при наведении, то этого достаточно. 
Исправленное подтверждаю, в общем, все ок. Договор в отдельное ишью на потом.
