### ISSUE TITLE
В документе "Митна декларація" добавлена возможность отражения "транспортно-заготівельних витрат".

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#396]
[890](https://github.com/a2develop/bugTracker/issues/890)

Механизм отражения аналогичен механизму в документе "Прибуткова накладна".
Issue с описанием тестрирования для Приходной накладной [327](https://github.com/a2develop/testing/issues/327).

**Comment by Anestezia** [comment]
Даты документов по затратам можно обойти через режим редактирования проведенного. 
![image](https://user-images.githubusercontent.com/42540074/65688004-00c0b180-e073-11e9-8298-754a6312e5d2.png)
действительно, с распроведением декларации, распроводятся и связанные услуги. 

И не понятен вопрос, относятся ли Витрати на повышение стоимости объектов в проводках и на складе.
![image](https://user-images.githubusercontent.com/42540074/65688326-9a885e80-e073-11e9-9f57-f8af363a1c2c.png)

**Comment by AlexeyTishkin** [comment]
> И не понятен вопрос, относятся ли Витрати на повышение стоимости объектов в проводках и на складе.

Затраты распределяются в проводках актов.

**Comment by AlexeyTishkin** [comment]
> Даты документов по затратам можно обойти через режим редактирования проведенного.

Какая последовательность действий ?

**Comment by Anestezia** [comment]
А мне нравится, что с\с правильно считает, а можно привязывать доки не только за одну одинаковую дату. Ведь и перевозка может быть по акту днем раньше, чем моя фирма оприходовала, или позже, чем МД выписана. 
![image](https://user-images.githubusercontent.com/42540074/65693089-606f8a80-e07c-11e9-80a5-377000391ca6.png)
Я Сначала привязала все одним днем, а потом в импорте через режим Редагування проведеного изменила дату. Дальше распровела один из актов, перевыбрала привязку (импорт) и провела. Затем снова Вернулась в импорт, еще раз изменила дату уже на третий вариант. В результате все три документа оказались разными датами.

**Comment by Anestezia** [comment]
Оставьте эту лазейку для тех, кому надо. А если что-то с датами и с\с поплывет у клиента от такого подхода, когда реализовать чуть ли не задним числом нужно будет. то сам будет думать, как правильно сделать, чтоб все сошлось.

**Comment by AlexeyTishkin** [comment]
> Оставьте эту лазейку для тех, кому надо.

Это не правильно. Ерунда же в оборотке получилась...

**Comment by Anestezia** [comment]
С\с в итоге правильно посчиталась. Я за то, чтоб оставить. Такой треш в голову никому не придет. Дай Бог, чтоб с исходной операцией разобрались. А у кого действительно будут доки разными датами, тот хоть сможет их провести.

**Comment by AlexeyTishkin** [comment]
> Я Сначала привязала все одним днем, а потом в импорте через режим Редагування проведеного изменила дату.

Исправил.

**Comment by Anestezia** [comment]
Работает :-(
