### ISSUE TITLE
Отчет "Реестр документов по контрагенту".

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#397]
* Добавлен в перечень отчетов по контрагенту (Контрагенты - Контрагент - Звіти).
* Колонка "Сумма" заменена на "Дебет", "Кредит".
* Добавлены фильтры по операции и счету.

Проверить построение.

**Comment by Anestezia** [comment]
Отчет на месте. строится, по фильтрам сортирует, документы из него открываются, печатает, экспорт работает.
