### ISSUE TITLE
Добавлены операции с разменной монетой. #1148

### ISSUE THREAD

**Issue by htrofymova** [a2develop/testing#400]
Бухгалтерія-Довідники: добавлен справочник Підрозділи - создаются подразделения; внутри подразделения - создаются кассьі.
Бухгалтерія-Каса: для кассовьіх ордеров длобавленьі операции Внесення до РРО и Винос з РРО; для этих операция добавлена возможность указать аналитику - Реєстратор.
Бухгалтерія-План рахунків: для счета 303 добавлен отчет Оборотно-сальдова відомість по касовим реєстраторам.

Нужно все это проверить.

**Comment by Anestezia** [comment]
1.Я только что в Довидныках удалила оба своих подразделения вместе с РРО. А документы проведенные по ним есть. И более того, в самих ордерах все еще можно выбрать из списка эти подразделения и РРО при создании нового ордера или редактировании старого.
И все прекрасно проводится.
2.Теперь отсюда из ордера при подборе решила удалить, раз кнопка есть.
![image](https://user-images.githubusercontent.com/42540074/66405025-2a25f980-e9f2-11e9-9f95-f81693a4b01e.png)

**Comment by Anestezia** [comment]
Чуть расширить поля отчета
![image](https://user-images.githubusercontent.com/42540074/66408377-850e1f80-e9f7-11e9-8305-fbae9eca248f.png)
Если отсюда нажать на все синие элементы, то открывается пустой лист 
![image](https://user-images.githubusercontent.com/42540074/66408537-ca325180-e9f7-11e9-9dab-62bbe8c36a7d.png)
![image](https://user-images.githubusercontent.com/42540074/66408707-18475500-e9f8-11e9-9cb5-c6661e83120d.png)
В остальном вроде все ок.

**Comment by AlexeyTishkin** [comment]
> Я только что в Довидныках удалила оба своих подразделения вместе с РРО

Исправил

**Comment by AlexeyTishkin** [comment]
> Теперь отсюда из ордера при подборе решила удалить, раз кнопка есть.

Исправил

**Comment by Anestezia** [comment]
Все ок
