### ISSUE TITLE
Операция "Виставлення рахунку" сделана в новом интерфейсе (диалоге)

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#401]
Проверить:
1. Создание.
2. Редактирование.
3. Проведение.
4. Создание связанных документов.
5. Отмену проведения.
6. Печать.
7. Режим редактирования проведенного документа.
8. Отображение в списках.
9. Копирование.

**Comment by Anestezia** [comment]
1. Не совсем понятно, почему не заполнен счет по умолчанию, основной, так сказать. Ведь даже при таком раскладе на печать выводится. 
![image](https://user-images.githubusercontent.com/42540074/66392934-e7f0be00-e9d9-11e9-9f55-76ada89b3bf5.png)
2. Нет подбора в редагуванни проведеного
![image](https://user-images.githubusercontent.com/42540074/66393018-21292e00-e9da-11e9-83ba-d45e19bf618d.png)
В остальном все норм.

**Comment by AlexeyTishkin** [comment]
> Не совсем понятно, почему не заполнен счет по умолчанию, основной, так сказать.

Ни для учета, ни для печати основной счет не нужен. При печати, если счет указан, то будет основной.

**Comment by AlexeyTishkin** [comment]
> Нет подбора в редагуванни проведеного

Исправил.

**Comment by Anestezia** [comment]
До, есть, можно закрывать.
