### ISSUE TITLE
Операции "Реалізація запасів", "Безоплатна передача запасів", "Реалізація товарів, прийнятих на комісію", "Передача товарів комісіонеру", "Реалізація необоротних активів " сделаны в новом интерфейсе (диалоге).

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#404]
Проверить:
1. Создание.
2. Редактирование.
3. Проведение.
4. Отражение в учете
5. Создание связанных документов.
6. Отмену проведения.
7. Печать.
8. Отображение в списках.
9. Копирование.

**Comment by Anestezia** [comment]
Вроде все норм, если не чудить и каждый документ использовать по назначению.

Загвоздка в том, что там можно поменять вид операции, например после распроведения. 
Оно потом смешивает проводки, которые не свойственны объекту исходя из счета, на котором он числится. 
Также в режиме редактирования проведенного на некоторых документах не дает поменять, выдавая ошибку, а вот необоротную реализацию поменять и сохранить изменения дало, только вот я меняла ее на комиссионную операцию, для которой склад нужен другой. В общем склад выбрать не удалось и оставился тот, на котором висел объект. 
![image](https://user-images.githubusercontent.com/42540074/66572344-75b6df80-eb79-11e9-840a-0c96129b8dd0.png)

**Comment by Anestezia** [comment]
и еще, я когда эти операции провожу на секунду каждый раз количество красным мигает. На остатках есть.
