### ISSUE TITLE
Добавлена операция "Формування відомості РРО".

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#406]
[1132](https://github.com/a2develop/bugTracker/issues/1132)

Новая операция.
Проверить:
1. Создание.
2. Редактирование.
3. Проведение.
4. Отражение в учете
5. Отмену проведения.
6. Отображение в списках.
7. Копирование.

**Comment by Anestezia** [comment]
многие вещи для редактирования закрыты, но открыт штрихкод. Если его отредактировать, то товар исчезнет и будет красная строка
![image](https://user-images.githubusercontent.com/42540074/66565808-0e466300-eb6c-11e9-95b9-265813fa6ec3.png)
В остальном все ок

**Comment by AlexeyTishkin** [comment]
> многие вещи для редактирования закрыты, но открыт штрихкод.

Исправил.

**Comment by AlexeyTishkin** [comment]
> В остальном все ок

Тогда закрываю.
