### ISSUE TITLE
Придбання/Продажі/Запаси - Операції. Экспорт списка в Excel

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#407]
[1168](https://github.com/a2develop/bugTracker/issues/1168)

* исправлен экспорт номера документа
* экспорт осуществляется с учетом периода списка
* экспорт осуществляется с учетом фильтра по операции

Проверить экспорт.

**Comment by Anestezia** [comment]
Да, все учитывает. Единственный момент, затянулись непроведенные тоже.
![image](https://user-images.githubusercontent.com/42540074/66568447-1ef9d780-eb72-11e9-9408-3b16e90a8e82.png)
Может нужен отбор по стану, или в екселе колонка стан, чтоб внутри можно было отбор сделать.

**Comment by AlexeyTishkin** [comment]
> Может нужен отбор по стану, или в екселе колонка стан, чтоб внутри можно было отбор сделать.

Этот экспорт наворачивать не будем. В планах убрать раздел Операции...
