### ISSUE TITLE
Придбання/Продажі - Операції (beta). Исправлен расчет суммы остатка оплаты/оприходования/реализации для валютных операций.

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#408]
[1166](https://github.com/a2develop/bugTracker/issues/1166)

Проверить отображение.

**Comment by Anestezia** [comment]
![image](https://user-images.githubusercontent.com/42540074/66559696-7b52fc00-eb5e-11e9-8aa9-a1e1701615e6.png)
Недоплата явно есть, а в операциях Бета вообще нет, ни в счетах ни в инше, нигде.

**Comment by AlexeyTishkin** [comment]
> Недоплата явно есть, а в операциях Бета вообще нет, ни в счетах ни в инше, нигде.

Опция ВЭД ?

**Comment by Anestezia** [comment]
Да, теперь все в порядке. Работает и остатки показывает корректно.
