### ISSUE TITLE
Декларация НДС. Добавлена возможность создания за квартал

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#41]
[522](https://github.com/a2develop/bugTracker/issues/522)

Создать Декларацию за месяц. Проверить:

- [ ] Заполнение
- [ ] Смена периода внутри отчета (внутри отчета переключаться между месячной и квартальной нельзя, только смена периода внутри типа)
- [ ] Приложения 1, 5
- [ ] Формирование XML

Создать Декларацию за квартал. Проверить:

- [ ] Заполнение
- [ ] Смена периода внутри отчета (внутри отчета переключаться между месячной и квартальной нельзя, только смена периода внутри типа)
- [ ] Приложения 1, 5
- [ ] Формирование XML

**Comment by Anestezia** [comment]
В Приложение 1 и 5 не попадает дата заполнения Декларации НДС. Ставится только текущая дата заполнения, фактическая. 

Квартальные формы ведут себя так же, как и прочие. Все ок, за исключением даты заполнения. 
Так же стоит обратить внимание, что дата заповнення та дата подання (внизу документа) не связаны. 
При переносе в Сонату декларация подтягивает дату Подання. Но если вручную ее так же откорректировать, то перенесется дата, выбранная нами.

Приложения 1 и 5 даже при корректировке даты внизу документа (дата подання) дату заповнення, закрытую для ручного редактирования, ставят все равно текущим числом. При переносе в Сонату дата видимо отражается только внизу документа и ставится та, которую мы выбрали вручную. Если в не видимых областях не фиксируется дата заполнения, то так в принципе можно сдавать.

**Comment by AlexeyTishkin** [comment]
Исправил наследование даты в Приложения 1, 5.

**Comment by AlexeyTishkin** [comment]
> Так же стоит обратить внимание, что дата заповнення та дата подання (внизу документа) не связаны.

Исправил.

**Comment by Anestezia** [comment]
Проверила. Все хорошо с датами. Квартальная декларация и приложения работают исправно.
