### ISSUE TITLE
Раходная накладная. Добавлена проверка соответствия вида объекта учета выбранной операции.

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#410]
Проверить срабатывание проверки после смены операции.

**Comment by Anestezia** [comment]
Копировать реализацию необоротных не удалось
![image](https://user-images.githubusercontent.com/42540074/66904610-09226180-f00d-11e9-89f0-53453af5a609.png)
Реализация запасов копируется нормально.
Сама проверка работает в оба направления, от необоротных до товаров, и от товаров до необоротных.

**Comment by AlexeyTishkin** [comment]
> Копировать реализацию необоротных не удалось

Исправил.

**Comment by Anestezia** [comment]
работает
