### ISSUE TITLE
Отчет "Валовий прибуток".

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#412]
[1180](https://github.com/a2develop/bugTracker/issues/1180).
Добавлены фильтры по контрагенту и объекту учета. 
Проверить построение отчета.

**Comment by Anestezia** [comment]
Строится хорошо, в разных комбинациях идет подбор. Печать и экспорт есть. Единственное, длинные названия с переносом в влезают в табличку в екселе
![image](https://user-images.githubusercontent.com/42540074/66908164-4984de00-f013-11e9-8ea5-ea8ca41c56fc.png)
