### ISSUE TITLE
Операции "Реалізація послуг", "Безоплатне надання послуг", "Реалізація послуг з матеріалами" сделаны в новом интерфейсе (диалоге).

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#413]
Проверить:
1. Создание.
2. Редактирование.
3. Проведение.
4. Отражение в учете
5. Создание связанных документов.
6. Отмену проведения.
7. Печать.
8. Отображение в списках.
9. Копирование.

**Comment by Anestezia** [comment]
Было бы хорошо, если бы в актах выводился на печать не код уктвед, а дкпп. А то код есть в свойствах объекта, а на печати графа называется код уктвэд и пустая.

В остальном замечаний нет
