### ISSUE TITLE
Печатная форма документа "Акт оказанных услуг".

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#414]
Оптимизирован внешний вид с целью увеличения вместимости информации на одном листе.

Вопрос клиента: "Коли створюю документ "реалізація послуг з матеріалами" при спробі надрукувати документ розбивається на дві сторінки. Навіть якщо позицій 3-4-5, а півсторінки залишається порожньою. Мені доводиться щоразу редагувати його, видаляючи зайві рядки. Виправте, будь-ласка, або підкажіть як налаштувати друк з максимальним наповненням текстом на першій сторінці."

Уменьшены: шапки таблиц, отступы страницы, отступы элементов реквизитов и подписей. На следующую страницу должно переноситься в случае, если не вмещается часть документа, начиная с "Усього за актом". Эта часть считается итогом документа и не должна разрываться на страницы.

Проверить печать при условиях:
1. В документе только услуги.
2. В документе услуги + материалы.
3. В документе столько строк, что он располагается на двух листах.
4. В документе столько строк, что он располагается на трех листах.

**Comment by Anestezia** [comment]
У меня влезло 9 рядков, 10 уже переносится на другую страницу, это если только материалы в акте.
С материалами и услугами смотрится вообще компактно, особенно если на два листа документ. 
Однако странный перенос по материалам, если страниц больше. Не по "начиная с "Усього за актом".

**Comment by Anestezia** [comment]
![image](https://user-images.githubusercontent.com/42540074/67326245-f208d580-f51e-11e9-9324-e0823b239287.png)

**Comment by AlexeyTishkin** [comment]
> Однако странный перенос по материалам, если страниц больше. Не по "начиная с "Усього за актом".

Вместе с "Усього за актом" на следующую страницу должна переноситься последняя строка (и итог, соответственно) таблицы.
