### ISSUE TITLE
Создание связанных документов из "Счета исходящего".

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#415]
[1123](https://github.com/a2develop/bugTracker/issues/1123).

В дочерние документы наследуются названия для печати.

Проверить создание связанных при условии:
1. В Счете только услуги.
2. В Счете только ТМЦ.
3. В Счете услуги и ТМЦ.
4. В Счете услуги, ТМЦ и ОС.

**Comment by Anestezia** [comment]
Да, все работает. Печатается только название для печати
