### ISSUE TITLE
Отмена проведения документов "Счет входящий", "Приходная накладная", "Счет исходящий", "Расходная накладная", "Акт оказанных услуг" разрешена при наличии не проведенных дочерних документов.

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#416]
[1184](https://github.com/a2develop/bugTracker/issues/1184).

Проверить отмену проведения при наличии:
1. Проведенных дочерних документов. Отмена должна запрещена.
2. Не проведенных дочерних документов. Отмена должна разрешена.

**Comment by Anestezia** [comment]
во всех указанных документах работает правильно.
