### ISSUE TITLE
Исходящая налоговая накладная.

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#417]
Если покупатель является неплательщиком НДС, то:
   * в качестве наименования отображается "Неплатник"
   * отмечается опция "Не підлягає наданню отримувачу (покупцю)"
   * тип причины устанавливается "02"

Проверить заполнение реквизитов, экспорт в XML при формировании связанной НН для:
1. Неплательщика НДС.
2. Плательщика НДС.

**Comment by Anestezia** [comment]
XML в связанных формируется, 
у неплательщака и у плательщика все реквизиты формируются правильно, в РК наследуются.
