### ISSUE TITLE
Операции "Придбання послуг", "Безоплатне одержання послуг", "Придбання послуг в інших дебіторів" сделаны в новом интерфейсе (диалоге).

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#419]
Проверить:
1. Создание.
2. Редактирование.
3. Проведение.
4. Отражение в учете
5. Создание связанных документов.
6. Возможность отнесения суммы на с/с приобретенных ТМЦ.
7. Отмену проведения.
8. Печать.
9. Отображение в списках.
10. Копирование.

**Comment by AlexeyTishkin** [comment]
[997](https://github.com/a2develop/bugTracker/issues/997)

**Comment by Anestezia** [comment]
Замечаний не нашла.
Отображается в учете, из осв открывается документ, копируется, редактируется. отнесение на сс есть.
