### ISSUE TITLE
Создание связанных документов из "Счета входящего".

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#420]
Т.к. в новом интерфейсе "Акта полученных услуг" появилась возможность оприходования ТМЦ, то при наличии в Счете объектов типа "Услуги" и "Материалы" создается связанный документ "Акт полученных услуг".

Проверить создание связанных при условии:
1. В Счете только услуги. Должен быть создан Акт.
2. В Счете только ТМЦ. Должна быть создана Приходная накладная.
3. В Счете услуги и ТМЦ. Должен быть создан Акт.
4. В Счете услуги, ТМЦ и Нематериальные активы. Должны быть созданы Акт полученных услуг, Акт приема-передачи нематериальных активов.
5. В Счете ТМЦ и Нематериальные активы. Должны быть созданы Приходная накладная, Акт приема-передачи нематериальных активов.

**Comment by Anestezia** [comment]
Счете услуги, ТМЦ и Нематериальные активы.
Все запихнулось в акт
![image](https://user-images.githubusercontent.com/42540074/67405497-84f84d00-f5bd-11e9-8bf1-e11ea6acb9c5.png)
Когда удалила из материалов акта єто ОС, и провела, то все равно при следующем формировании недостающего Придбання из счета, снова появился акт, в котором ОС стояли на месте материалов и появлялась ошибка.
В Счете ТМЦ и Нематериальные активы. Тогда создается накладная на приход матактивов и тмц вместе с ОС и без ошибки, что ОС тут не место. 
![image](https://user-images.githubusercontent.com/42540074/67405887-064fdf80-f5be-11e9-92fb-84a4b97f2e16.png)

**Comment by AlexeyTishkin** [comment]
> Счете услуги, ТМЦ и Нематериальные активы.

Здесь надо проверить именно Нематериальный актив. Для него другой документ на оприходование.

**Comment by AlexeyTishkin** [comment]
ОС в Акте услуг разрешил.

**Comment by Anestezia** [comment]
Припроведении акта немат активов. Хотя он создался
![image](https://user-images.githubusercontent.com/42540074/67409536-609f6f00-f5c3-11e9-8111-65d1edb6a850.png)

**Comment by Anestezia** [comment]
Здесь создалась накладная на тмц и акт на немат. Немат барахлит, я его удалила прямо изнутри кнопкой удалить, а накладную провела. В результате, в счете связанные доки в количестве 2 шт, вместо 1 накладной. Да еще и черновики оба. при попытке открыть 
![image](https://user-images.githubusercontent.com/42540074/67409983-0d79ec00-f5c4-11e9-991d-a98bf2d04301.png)

**Comment by AlexeyTishkin** [comment]
> Припроведении акта немат активов.

Надо повторно проверить создание и проведение Акта приема-передачи.

**Comment by AlexeyTishkin** [comment]
> Здесь создалась накладная на тмц и акт на немат.

Теперь если при создании связанных создается более одного документа, то выводится сообщение о том, какие документы были созданы и ни один из них автоматически не открывается. Дальнейшее открытие через панель связанных документов.
Если создался один документ, то он, как и раньше, автоматически открывается.

**Comment by Anestezia** [comment]
В счете услуги, тмц и ос. Создается акт с материалами, в котором наравне с материалами идет в списке и ос. 
![image](https://user-images.githubusercontent.com/42540074/67874124-2d1d9100-fb3d-11e9-977b-4ac7f289c590.png)
![image](https://user-images.githubusercontent.com/42540074/67874279-61914d00-fb3d-11e9-96c4-a5942ed5e3b1.png)
создался один документ без вопросов.

**Comment by AlexeyTishkin** [comment]
> В счете услуги, тмц и ос. Создается акт с материалами, в котором наравне с материалами идет в списке и ос.

Так и должно быть. А в чем проблема ?

**Comment by AlexeyTishkin** [comment]
На нематериальный актив должен быть отдельный документ.

**Comment by Anestezia** [comment]
Добавила еще и немат актив. Показало сообщение о созданных документах, все ок. создало два разных
