### ISSUE TITLE
В качестве основания для оплаты (платежные поручения, кассовые ордера, банковская выписка) теперь можно выбирать Накладные и Акты.

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#421]
[1157](https://github.com/a2develop/bugTracker/issues/1157).

Проверить в:
1. Платежных поручениях (входящих/исходящих)
2. Кассовых ордерах (входящих/исходящих)
3. Банковской выписке

Проверить выбор основания. Должен быть список из Счетов, Накладных, Актов.

**Comment by Anestezia** [comment]
Выбрать можно. Интересно, что в платежке при выборе подставляется автоматом и сумма документа-основания платежа, а в кассовом не подставляется.
Даже если написать сумму вручную в кассовом, а потом выбрать основание, то сумма не подставляется и не удаляется. Только вручную новую сумму писать надо. 
В банк. выписке все ок.

**Comment by AlexeyTishkin** [comment]
> а в кассовом не подставляется.

Такой алгоритм был и до добавления Накладных и Актов. Если нужна подстановка - отдельное issue.
