### ISSUE TITLE
Придбання/Продажі - Операції/Операції (бета). Сделано обновление детализирующего раздела "Дочерние документы".

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#422]
[1065](https://github.com/a2develop/bugTracker/issues/1065)

Надо повторить ситуацию на первой картинке, т.е. чтобы один документ был в спике два раза (один раз как самостоятельный, второй раз как дочерний).
При любых действиях (редактирование, проведение, отмена проведения) после:
1. Открытия как самостоятельного.
2. Открытия как дочернего.
3. Открытия как дочернего из родительского.
информация в списке документов должна быть согласованной.

Удаление из любого места должно приводит к удалению двух записей в списке документов.

**Comment by Anestezia** [comment]
скопированный документ имеет другое название. и подставился до обновления страницы в цепочку
![image](https://user-images.githubusercontent.com/42540074/68113080-9285cf00-fefb-11e9-8165-92ee9a8ff64d.png)
обновила, все норм. Только вопрос, должен ли он был подставиться в цепочку?
![image](https://user-images.githubusercontent.com/42540074/68113154-bf39e680-fefb-11e9-924f-68306f936564.png)

После удаления изнутри, через счет,  ордер удалился везде, даже без обновления страницы.
 Все вышеуказанные действия наследуются, все ок.

**Comment by AlexeyTishkin** [comment]
> скопированный документ имеет другое название

Исправил.

**Comment by AlexeyTishkin** [comment]
> Только вопрос, должен ли он был подставиться в цепочку?

У нас все документы копируются с сохранением родительского.

**Comment by Anestezia** [comment]
ок
