### ISSUE TITLE
Сделано изменение МВО или склада

### ISSUE THREAD

**Issue by htrofymova** [a2develop/testing#423]
https://github.com/a2develop/bugTracker/issues/1188
Во всех документах по нематериальным активам сделано изменение МВО или склада, если МВО или склад бьіли вьібраньі в диалоге вьібора объекта. 
Нужно проверить.

**Comment by Anestezia** [comment]
запрещает. В некоторых документах удаляет количество и горит строка красным, а в некоторых при проведении появляется сообщение, что количество равно 0.  Все ок.
