### ISSUE TITLE
Добавлена операция "Імпорт послуг".

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#424]
[1130](https://github.com/a2develop/bugTracker/issues/1130)

Новая операция.
Проверить:
1. Создание.
2. Редактирование.
3. Проведение.
4. Отражение в учете
5. Отмену проведения.
6. Отображение в списках.
7. Копирование.

**Comment by AndriyNesterenya** [comment]
Нет возможности распечатать созданный акт - просто отсутствует кнопка на диалоге, как во входящем инвойсе.

При попытке распечатать из списка операций Бета - "Report 'saic' not found"

**Comment by AlexeyTishkin** [comment]
А какая там печатная форма должна быть ?

**Comment by AndriyNesterenya** [comment]
Буржуям этот акт вообще не нужен.
А для нас - обычная форма акта, такая же как для резидента

**Comment by AlexeyTishkin** [comment]
Добавил обычную. Но там же валюты нет, только грн. Не нужна ?

**Comment by AndriyNesterenya** [comment]
Моя контактная группа предполагает, что там валюта, которая была в инвойсе.
Без эквивалента в гривне.
Надо еще Макса поспрошать, какие у него соображения для наших собственных кейсов.

**Comment by AlexeyTishkin** [comment]
Ну валюта туда не очень лепется...
Может тогда печатную форму из Инвойса исходящего/Экспорта услуг ? Которая "Invoice (offer) / Інвойс (оферта)" ?

**Comment by AndriyNesterenya** [comment]
Показал главным страдальцам-туристам - их такая форма вполне устраивает.

Надо еще у Макса переспросить, по нашим внутренним кейчам с оплатой хостингов, лицензий и прочих реклам.

**Comment by AlexeyTishkin** [comment]
> их такая форма вполне устраивает

А такая - это какая ? :)
Из Акта в грн или Invoice (offer) / Інвойс (оферта) ?

**Comment by MaksymTikhomirov** [comment]
Ну я тебе побросал формы инвойсов от поставшиков услуг нам 

Меня формат на базе моей формы бланка  инвойса на экспорт услуг вполне устраивает

**Comment by AndriyNesterenya** [comment]
> > их такая форма вполне устраивает
> 
> А такая - это какая ? :)
> Из Акта в грн или Invoice (offer) / Інвойс (оферта) ?

"Invoice (offer) / Інвойс (оферта)", как ты предлагал

**Comment by AlexeyTishkin** [comment]
Сделал "Invoice (offer) / Інвойс (оферта)". Пробуем.

**Comment by AlexeyTishkin** [comment]
[986](https://github.com/a2develop/bugTracker/issues/986)

Добавлена возможность создания связанных обязательства/кредита.

Проверить:
1. Создание.
2. Редактирование.
3. Проведение.
4. Отражение в учете.

**Comment by Anestezia** [comment]
печатная форма есть, накладные работают. Можно закрывать, если дело только в этом.
