### ISSUE TITLE
Создание связанных документов из "Инвойса входящего".

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#425]
Проверить создание связанных при условии:
1. В Инвойсе только услуги. Должен быть создан Акт.
2. В Инвойсе только ТМЦ. Должна быть создана Таможенная декларация.
3. В Инвойсе услуги и ТМЦ. Должны быть созданы Акт, Таможенная декларация.

**Comment by Anestezia** [comment]
да, все так работает.
