### ISSUE TITLE
В печатных формах выводится полное наименование (если указано) моей фирмы и контрагента.

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#426]
[1195](https://github.com/a2develop/bugTracker/issues/1195)

Проверить печать.

**Comment by Anestezia** [comment]
Идет полное название на печать, но если оно длинное, то не помещается и нет переноса
![image](https://user-images.githubusercontent.com/42540074/68119316-10050b80-ff0b-11e9-881a-b82ca1397443.png)
![image](https://user-images.githubusercontent.com/42540074/68119327-1b583700-ff0b-11e9-85aa-a0c1e2f5ccbe.png)
вот полное название

**Comment by AlexeyTishkin** [comment]
> но если оно длинное, то не помещается и нет переноса

Сделал перенос.

**Comment by Anestezia** [comment]
да. перенеслось
![image](https://user-images.githubusercontent.com/42540074/68128519-8e1fdd00-ff20-11e9-97b5-4f7f4aca0bbe.png)

**Comment by AlexeyTishkin** [comment]
В остальных формах нормально ? Закрываем ?

**Comment by Anestezia** [comment]
1.Инвойс входящий, импорт материалов и услуг
![image](https://user-images.githubusercontent.com/42540074/68294491-03162280-0099-11ea-8c48-dbc710391959.png)
2.Придбання об'єктів немат активів
![image](https://user-images.githubusercontent.com/42540074/68294704-728c1200-0099-11ea-9b8e-6d7a7a017fbe.png)
3.внесок в статутний майна и необоротніх тоже
![image](https://user-images.githubusercontent.com/42540074/68294824-bd0d8e80-0099-11ea-88d9-171c1a194a42.png)
4.Платежка постачальнику оплата и исходящая тоже
![image](https://user-images.githubusercontent.com/42540074/68295054-2ee5d800-009a-11ea-89e6-1a2c2a2e551d.png)
5. оплата пост. в валюте и исх. тоже
![image](https://user-images.githubusercontent.com/42540074/68295221-92700580-009a-11ea-95d6-4adf7dfc1bb2.png)
6. Оплата покупця а также оплата покупця с комиссией
![image](https://user-images.githubusercontent.com/42540074/68296195-ad437980-009c-11ea-9bc7-98c1552051f0.png)
7. експорт послуг - сокращенное название

**Comment by AlexeyTishkin** [comment]
> 1.Инвойс входящий, импорт материалов и услуг
> 4.Платежка постачальнику оплата и исходящая тоже
> 5. оплата пост. в валюте и исх. тоже
> 6. Оплата покупця а также оплата покупця с комиссией
> 7. експорт послуг - сокращенное название

Исправил.

**Comment by htrofymova** [comment]
2, 3 - переделала

**Comment by Anestezia** [comment]
Можно закрывать.
