### ISSUE TITLE
Добавлен отчет "Розрахунок податкових зобов’язань, нарахованих отримувачем послуг, не зареєстрованим як платник податку на додану вартість, які постачаються нерезидентами, у тому числі їх постійними представництвами, не зареєстрованими платниками податків, на митній території України" (F0215520, J0215520).

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#427]
[986](https://github.com/a2develop/bugTracker/issues/986)

Проверить:
1. Создание.
2. Заполнение.
3. Редактирование.
4. Экспорт в XML.
5. Экспорт в Сонату.

**Comment by AlexeyTishkin** [comment]
В операцию "Імпорт послуг" добавлен выбор ставки НДС. В отчет должны попадать только строки с основным НДС (20%).

**Comment by Anestezia** [comment]
![image](https://user-images.githubusercontent.com/42540074/68299060-981e1900-00a3-11ea-9f8c-d8101a52bf9d.png)
Кнопка соната работает. проверку проходит, хмл работает, автозаполнение работает, ручное заполнение есть,
