### ISSUE TITLE
Операция "Податкове зобов'язання"

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#428]
[986](https://github.com/a2develop/bugTracker/issues/986).

Добавлена возможность формирования обязательства для операций импорта услуг (тип причини невидачі податкової накладної: «14» — «Складена отримувачем (покупцем) послуг від нерезидента»). 

Операцию можно создать как самостоятельную или как связанную из операции "Импорт услуг".

Проверить создание/проведение:
1. Самостоятельного обязательства для плательщика НДС (тип причины не указывается).
2. Связанного обязательства для плательщика НДС из Счета/Накладной/Акта (тип причины не указывается).
3. Самостоятельного обязательства для неплательщика НДС (тип причины: "02").
4. Связанного обязательства для неплательщика НДС из Счета/Накладной/Акта (тип причины: "02").
5. Связанного обязательства для нерезидента из Акта (тип причины: "14").

Созданные накладные будут необходимы для тестирования заполнения Декларации НДС (отдельный issue). Желательно создать в одном периоде и под тестовым аккаунтом.

**Comment by Anestezia** [comment]
А здесь если мы неплатник НДС, то мы не должны иметь возможность создавать налоговые накладные из импорта услуг.

**Comment by Anestezia** [comment]
Зашла в список контрагентов раздел Продажи, выбрала нерезидента. открыла по нему операции, создала Налоговое обязательство
![image](https://user-images.githubusercontent.com/42540074/68312213-64e78400-00bb-11ea-8115-973d269f93aa.png)
Подставился Другой контрагент, тип причины не 14, а 2 и контрагент Неплатник вместо fresh ltd.
![image](https://user-images.githubusercontent.com/42540074/68312384-a2e4a800-00bb-11ea-9e76-bcb77765ef7d.png)
Тут же выбрала операцию Податковий кредит
![image](https://user-images.githubusercontent.com/42540074/68312595-f8b95000-00bb-11ea-95d2-9fad6900b0a2.png)

**Comment by Anestezia** [comment]
Выбираю в разделе Продажи - операции - нова операция - есть только податкове зобов. в списке операций - новый чистый документ, выбираю Фреш лтд, а подставляет Неплатника, как на фото выше. 
Захожу в раздел Придбання, там только кредит, выбираю, остальное как на фото. 

Вывод: Создать самостоятельный документ (не из импорта услуг) не получилось.

**Comment by AlexeyTishkin** [comment]
> Зашла в список контрагентов раздел Продажи, выбрала нерезидента. открыла по нему операции, создала Налоговое обязательство

При создании Обязательств/Кредита с контрагента причина "14" не должна выбираться автоматически.

**Comment by AlexeyTishkin** [comment]
> Вывод: Создать самостоятельный документ (не из импорта услуг) не получилось.

Создаем обычные кредит/обязательства. В созданном документе вручную выбираем «Складена отримувачем (покупцем) послуг від нерезидента» в типе причины.

**Comment by AlexeyTishkin** [comment]
> А здесь если мы неплатник НДС, то мы не должны иметь возможность создавать налоговые накладные из импорта услуг.

Исправил. У неплательщика не должно быть возможности создать НН.

**Comment by Anestezia** [comment]
Я платник ПДВ, отдельную создала, указала Нерезидента, указала тип причины 14, они поменялись местами, как и должно быть, но теперь у меня код ипн 1000000000, а не родной код плательщика.
![image](https://user-images.githubusercontent.com/42540074/68476936-cbdc7880-0234-11ea-9ea3-02d72d2358ff.png)

**Comment by AlexeyTishkin** [comment]
> Просто если обычную создавать, то покупець-продавець местами не поменяются.

Создать операцию "Податкове зобов'язання", выбрать причину «Складена отримувачем (покупцем) послуг від нерезидента».

**Comment by AlexeyTishkin** [comment]
> Я платник ПДВ

Это точно ?
Вот на тестовом создал:
![image](https://user-images.githubusercontent.com/35917940/68477065-1fe75d00-0235-11ea-9e6e-17df86b57539.png)

**Comment by Anestezia** [comment]
Да, осталось от неплатника 
![image](https://user-images.githubusercontent.com/42540074/68478747-56bf7200-0239-11ea-85ca-ae52d9288d7f.png)

**Comment by AlexeyTishkin** [comment]
> Да, осталось от неплатника

А сейчас ?

**Comment by Anestezia** [comment]
Все ок

**Comment by AlexeyTishkin** [comment]
Остались еще какие-то вопросы ? Или закрывать ?

**Comment by Anestezia** [comment]
закрывать
