### ISSUE TITLE
Отчет "ПОДАТКОВА ДЕКЛАРАЦІЯ З ПОДАТКУ НА ДОДАНУ ВАРТІСТЬ"

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#429]
[986](https://github.com/a2develop/bugTracker/issues/986).

Сделано автоматическое заполнение строк: 6, 13 - "Послуги, отримані від нерезидента, місце постачання яких визначено на митній території України". 

Особенности заполнения описаны, к примеру [здесь](https://i.factor.ua/journals/nibu/2017/june/issue-49/article-28325.html) в разделе "НДС-отчетность".

Для тестирования заполнения, кроме налоговых обязательств/кредита по импорту услуг желательно, чтобы в периоде были:
1. Обязательства, созданные в [428](https://github.com/a2develop/testing/issues/428).
2. Самостоятельный кредит.
3. Связанный кредит из Счета/Накладной/Акта.
4. Корректировка налогового кредита.
5. Корректировка налогового обязательства.

Проверить Декларацию, Приложение 1, Приложение 5:
1. Заполнение.
2. Проведение.
3. Экспорт в XML.

**Comment by AlexeyTishkin** [comment]
У Сонаты есть не понятный момент со строкой [13](https://github.com/a2develop/bugTracker/issues/986#issuecomment-549861155)

**Comment by AlexeyTishkin** [comment]
[1185](https://github.com/a2develop/bugTracker/issues/1185).

Сделано автоматическое заполнение строки 16.1 - "значення рядка 21 попереднього звітного (податкового) періоду".

**Comment by Anestezia** [comment]
Податковий кредит стандартный -- до сих пор автоматом сегодняшнее число не подставляется, вообще нет даты, кнопка провести не активна, а красным ничего не горит. Не сразу дату замечаешь.

**Comment by AlexeyTishkin** [comment]
> а красным ничего не горит

На это отдельное issue.
