### ISSUE TITLE
Отчет "Податкова декларація платника єдиного податку - фізичної особи - підприємця (квартальна)"

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#431]
[1203](https://github.com/a2develop/bugTracker/issues/1203).

Исправлено:
   * контроль наличия проведенного отчета в периоде
   * открытие документов "Нарахування податків"
   * заполнение строки 13

Проверить исправления.

**Comment by kattrina-brekhova** [comment]
все работает
