### ISSUE TITLE
Справочник "Страны". Добавлено свойство "Код числовий".

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#432]
Проверить:
1. Импорт из классификатора.
2. Установление кодов у существующих стран:
   * вручную
   * повторный импорт страны
3. Отображение в списке. Сортировка, поиск.

**Comment by Anestezia** [comment]
Импортируется, в ранее импортированных стоит код 000, при открытии для редактирования есть валидатор но этом поле. Вручную заполняется. При повторном импорте, если код был вручную заполнен не правильно, то просто происходит замена. Дублирований нет. Поиск работает и по названию и по коду, даже части кода. Все ок
