### ISSUE TITLE
Добавлен отчет "Звіт про експорт (імпорт) послуг" (S0500909).

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#433]
[986](https://github.com/a2develop/bugTracker/issues/986).

Автоматически заполняются разделы: 1 - Експорт послуг (крім послуг, пов'язаних з подорожами), 2 - Імпорт послуг (крім послуг, пов'язаних з подорожами). 

Проверить:
1. Создание.
2. Заполнение.
3. Редактирование.
4. Проведение.
5. Экспорт в XML.

**Comment by Anestezia** [comment]
Заполнение есть, правда если сумма контракта сильно маленькая, то там, где в тысячах одни нули, 
![image](https://user-images.githubusercontent.com/42540074/69072945-1f20a900-0a35-11ea-8f81-bae24ef6a947.png)
Експорт хмл работает. в сонату идет, редактирование, проведение-распроведение работает.
