### ISSUE TITLE
Добавлена операция "Перерахування інших податків".

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#434]
[1116](https://github.com/a2develop/bugTracker/issues/1116).

Проводки Дб 6419 - Кр 311. При выборе данной операции в платежном поручении/строке банковской выписки появляется селектор "Податок". 

Проверить:
1. Создание.
2. Выбор налога.
3. Проведение.
4. Отражение в отчетах.

Увидеть обороты в разрезе налоговов на данный момент нельзя.

**Comment by Anestezia** [comment]
1.Хорошо бы, чтоб видно было список, хоть немного. Особенно при копировании плохо.
![image](https://user-images.githubusercontent.com/42540074/68865799-14e07100-06fc-11ea-9be2-16a854a881df.png)
2.Додатково-Підстава-
![image](https://user-images.githubusercontent.com/42540074/68871679-7ce78500-0705-11ea-92e4-bf15da766ce5.png)

В остальном все ок.

**Comment by AlexeyTishkin** [comment]
> Хорошо бы, чтоб видно было список, хоть немного. Особенно при копировании плохо.

В работе.

**Comment by AlexeyTishkin** [comment]
> 2.Додатково-Підстава-

Как повторить ?

**Comment by AlexeyTishkin** [comment]
Добавлены элементы (балансовый счет - 6419): Акцизний податок, Земельний податок, Податок на нерухомість, Податок на репатріацію, Податок з реклами, Екологічний податок, Рентна плата, Транспортний податок, Інше. Добавлены элементы (балансовый счет - 642): Туристичний збір, Торгові патенти, Пенсійний збір.

**Comment by AlexeyTishkin** [comment]
Добавлена операция "Перерахування інших обов'язкових платежів". Дб 642 - Кр 311. При выборе данной операции в платежном поручении/строке банковской выписки появляется селектор "Податок (платіж)".

**Comment by AlexeyTishkin** [comment]
> 2.Додатково-Підстава-

Исправил.

**Comment by Anestezia** [comment]
Все работает, можно закрывать
