### ISSUE TITLE
Добавлен "Переказ між своїми рахунками".

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#436]
[1199](https://github.com/a2develop/bugTracker/issues/1199).

1. Бухгалтерия - Платежі в валюті - Створити платіж. Добавлен "Переказ між своїми рахунками". 
2. Банковская выписка в валюте. Добавлены операции: "Надходження з іншого власного рахунку", Видаток на інший власний рахунок".

Проверить:
1. Создание.
2. Редактирование.
3. Проведение.
4. Отражение в учете.
5. Отмену проведения.

**Comment by Anestezia** [comment]
А тут не надо два параллельных документа быть?
![image](https://user-images.githubusercontent.com/42540074/68859285-9978c280-06ef-11ea-9bf7-4b953f5f8c7b.png)
2. Нет проводок в поле информация по кнопке Проводки
![image](https://user-images.githubusercontent.com/42540074/68859356-c331e980-06ef-11ea-877c-32d89a271aa7.png)
Поле Информация в двух платежах разное
![image](https://user-images.githubusercontent.com/42540074/68860112-8109a780-06f1-11ea-9361-4285178b8a25.png)
![image](https://user-images.githubusercontent.com/42540074/68860202-b44c3680-06f1-11ea-8c78-9c81131dfa05.png)
В остальном все ок.

**Comment by AlexeyTishkin** [comment]
> А тут не надо два параллельных документа быть?

На данный момент - не понятно... Это же не дочерние документы... Надо подумать. Пока убрал вызов диалога связей на основном документе.

**Comment by AlexeyTishkin** [comment]
> 2. Нет проводок в поле информация по кнопке Проводки

И не должно быть. Убрал вызов диалога проводок на основном документе.

**Comment by AlexeyTishkin** [comment]
> Поле Информация в двух платежах разное

Исправил.

**Comment by Anestezia** [comment]
Все ок
