### ISSUE TITLE
Операция "Придбання послуг в інших дебіторів".

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#438]
[1187](https://github.com/a2develop/bugTracker/issues/1187).

В качестве связанных операций оплаты создаются "Перерахування коштів іншим дебіторам" по банку и/или "Оплата іншим дебіторам" по кассе. 

Проверить создание связанных оплат из:
1. Счета входящего. Должна быть операции "Оплата постачальнику" по банку и кассе.
2. Приходной накладной. Для операции "Придбання матеріальних активів" должны быть операции "Оплата постачальнику" по банку и кассе.
3. Акта полученных услуг.
   * для операции "Придбання послуг" должны  быть операции "Оплата постачальнику" по банку и кассе.
   * для операции "Придбання послуг в інших дебіторів" должны быть операции "Перерахування коштів іншим дебіторам" по банку и "Оплата іншим дебіторам" по кассе.

**Comment by Anestezia** [comment]
Вот тут зачем представник, если в кассе все равно запрет.
![image](https://user-images.githubusercontent.com/42540074/69328251-96358780-0c57-11ea-859e-3e4e99fef77a.png)
В остальном все работает как описано.

**Comment by AlexeyTishkin** [comment]
> Вот тут зачем представник, если в кассе все равно запрет.

Вот здесь обсуждали: [1211](https://github.com/a2develop/bugTracker/issues/1211).
Надо issue открыть и указать, что "Оплата іншим дебіторам" не проводится с юр. лицом.

**Comment by AlexeyTishkin** [comment]
> В остальном все работает как описано.

Тогда закрываю.

**Comment by AlexeyTishkin** [comment]
> Вот тут зачем представник, если в кассе все равно запрет.

Уже должно проводиться.
