### ISSUE TITLE
Отображение МФО в печатных формах в случае счета в формате IBAN.

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#439]
[1209](https://github.com/a2develop/bugTracker/issues/1209).
В печатных формах Счета исходящего, Расходной накладной МФО не отображается. В печатной форме Платежного поручения МФО отображается как "0". 

Проверить отображение, печать для счетов в формате IBAN и старом.

**Comment by Anestezia** [comment]
все работает как описано. IBAN -- мфо = 0, в выставляемом нами счете и платежке на оплату. В старом формате  мфо идет полностью.
