### ISSUE TITLE
Пустой список счетов на главной

### ISSUE THREAD

**Issue by alex-kukhtin** [a2develop/testing#44]
https://github.com/a2develop/bugTracker/issues/468

**Comment by AndriyNesterenya** [comment]
Победили, но чуток криво.
Сейчас свежесозданному юзеру в пустом списке счетов предлагается добавить счет.
При этом открывается окно вида 
![image](https://user-images.githubusercontent.com/38098758/45497474-921ef780-b780-11e8-99a9-27156812d6b8.png)
где в поле названия юрлица значится "Моє підприємство" и его нельзя редактировать.
А у свежесозданного юзера в названии ничего другого быть не может - свойства предприятия не заполнены.

Думаю, стоит заменить ссылку на свойства Моей фирмы и текст с "Додати рахунок зараз" заменить на что-то типа "Заповніть властивості підприємства".

**Comment by shevchuk-vadim** [comment]
Это уже другой вопрос. Нужно писать новое ишью. А это нужно закрывать, нечего ему здесь висеть.

**Comment by AndriyNesterenya** [comment]
Ну так закрываем.
Написал новое в общем списке.
