### ISSUE TITLE
Номер расчетного счета в реквизитах моей фирмы/контрагента.

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#440]
Добавлен валидатор, разрешающий ввод только букв латинского алфавита в верхнем регистре и цифры.

Проверить ввод номера.

**Comment by Anestezia** [comment]
В моей фирме и у контрагента работает. Надо поставить в персонал, зарплатный проект и во властивости физ.лица
![image](https://user-images.githubusercontent.com/42540074/69625140-a4681700-104e-11ea-9209-ca41d05763fd.png)
В свойствах физ.лиц в Персонале вообще не ищет по Іван-коду банк. Пишу сюда, потому что эти вопросы связаны. Если я в Персонале в свойства физлица ввела счет в формате Айбан -- он сохранился без вопросов, то если я этого же человека открыла через список Контрагентов, то там уже ошибку выдает.
![image](https://user-images.githubusercontent.com/42540074/69626906-40dfe880-1052-11ea-8f40-5ff48575b9f7.png)

**Comment by Illya-Lykhachov** [comment]
Валидатор добавлен у физлиц и в зарплатных договорах.
И банк по IBAN находит

**Comment by Anestezia** [comment]
Да, есть. Можно закрывать
