### ISSUE TITLE
Платежные поручения. Селектор выбора расчетного счета моей фирмы.

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#441]
Добавлена возможность создания нового счета.

Проверить создание нового расчетного счета во входящих/исходящих платежных поручениях.

**Comment by Anestezia** [comment]
Есть создание в обоих вариантах.
При создании в новом формате счета:  нет подтягивания банка по мфо, которое уже зашито в номере счета. Запрашивает, какой банк. Со временем надо бы сделать
![image](https://user-images.githubusercontent.com/42540074/69627591-9c5ea600-1053-11ea-8d3e-3668839bf6f3.png)
 
![image](https://user-images.githubusercontent.com/42540074/69628996-a503ac00-1054-11ea-8636-ec76c678c268.png)

**Comment by AlexeyTishkin** [comment]
> При создании в новом формате счета: нет подтягивания банка по мфо, которое уже зашито в номере счета. 

На скринах счет НЕ IBAN.
Для IBAN банк должен установиться и запретиться.

**Comment by Anestezia** [comment]
Да, все работает, можно закрывать.
