### ISSUE TITLE
Платежные поручения. Выбор/сброс родительского документа теперь возможен в проведенном документе.

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#442]
Проверить выбор родительского документа в не проведенном платеже. После выбора:
1. Номер, дата, сумма родительского документа отображаются в панели задач в разделе "Підстава". При клике на наименование - открытие.
2. Должны заполниться свойства: контрагент, договор, проект, сумма (согласно родительского документа).
3. Свойства контрагент, договор, проект должны быть запрещены для редактирования.

Проверить сброс родительского документа в не проведенном платеже. После сброса:
1. В панели задач в разделе "Підстава" должна быть только ссылка "Обрати підставу".
2. Содержимое документа не должно измениться.
3. Свойства контрагент, договор, проект должны быть разрешені для редактирования.

Проверить выбор родительского документа в проведенном платеже. После выбора:
1. Номер, дата, сумма родительского документа отображаются в панели задач в разделе "Підстава". При клике на наименование - открытие.
2. Содержимое документа не должно измениться.

Проверить сброс родительского документа в проведенном платеже. После сброса:
1. В панели задач в разделе "Підстава" должна быть только ссылка "Обрати підставу".
2. Содержимое документа не должно измениться.

После выбора родительского документа проверить:
1. Отображение платежа:
   * внутри родительского докумета
   * в списке документов в детализирующем разделе "Дочерние документы"
2. Статус родительноского документа в Операции (beta).

**Comment by Anestezia** [comment]
В не проведенном: Все работает как описано.
В проведенном: Первый и второй блок(после сброса):, 1-2 -- как описано.
3 блок  
Если сбросить, то в цепочке документов изнутри платежки стоит Сброшенный документ-основание. Отдельно платежка в цепочке не отображается. 
![image](https://user-images.githubusercontent.com/42540074/70063443-70fa2f00-15f0-11ea-84be-3f5c76cca715.png)

Если выбрать другое основание, то платеж не меняется, основание другое в Операциях (бета) фиксируется -- сумма платежа учитывается. В цепочке в бете висит другое (левое) основание. 
![image](https://user-images.githubusercontent.com/42540074/70063529-9f780a00-15f0-11ea-818e-2c47d6267424.png)

Если выбрано неверное основание, то в списке платежек извне в цепочке это основание не отображается и внутри платежки тоже.
![image](https://user-images.githubusercontent.com/42540074/70063398-5c1d9b80-15f0-11ea-8971-869e9db22f93.png)

**Comment by AlexeyTishkin** [comment]
> Если сбросить, то в цепочке документов изнутри платежки стоит Сброшенный документ-основание. Отдельно платежка в цепочке не отображается.

Исправил.
Остальные вопросы после этого надо проверить повторно. Связаны с одной проблемой.

**Comment by Anestezia** [comment]
Теперь цепочка формируется правильно. Если подставить левое основание, то платеж проведенный не меняется и это основание в бете указывается с платежом другим. В общем проблемы не вижу особо. люди пусть сами разбираются. что куда крепить. Возможно это даже поможет тем, кто недавно спрашивал, как перераскрепить в цепочке документы. Кстати, на давно введенные это новшество тоже распространяется? В любом случае, я думаю, можно закрывать.

**Comment by AlexeyTishkin** [comment]
> Если подставить левое основание

А что значит "левое основание" ? Выбрать в качестве основания можно Счет/Накладную только от того контрагента, который указан в платеже. Соответствие договора/проекта при выборе основания для проведенного - игнорируется. Так работает ?

**Comment by AlexeyTishkin** [comment]
> Кстати, на давно введенные это новшество тоже распространяется?

Да.

**Comment by Anestezia** [comment]
https://github.com/a2develop/testing/issues/442#issuecomment-562039749
Да, так работает. Я имела в виду, что платеж на сумму по одному счету (у одного контрагента), а подкрепить можно другое основание по 
этому же контрагенту, но на другую сумму. Это трогать не надо, чтоб люди могли свои ошибки исправить. В общем, предлагаю закрыть.

**Comment by AlexeyTishkin** [comment]
> Я имела в виду, что платеж на сумму по одному счету (у одного контрагента), а подкрепить можно другое основание по этому же контрагенту, но на другую сумму.

Тогда все правильно.
