### ISSUE TITLE
Операция "Повернення постачальнику" сделана в новом интерфейсе (диалоге)

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#443]
Проверить:
1. Создание:
   * создается как дочерняя из операции "Придбання матеріальних активів".
   * создается как самостоятельная с последующим выбором родительской операции ("Придбання матеріальних активів").
2. Редактирование.
3. Проведение.
4. Отражение в учете.
5. Отмену проведения.
6. Печать.
7. Отображение в списках.
8. Копирование.

**Comment by Anestezia** [comment]
По поверненню постачальника: 
1. Нужен перенос названия в допечатной форме
![image](https://user-images.githubusercontent.com/42540074/70055065-756b1b80-15e1-11ea-9c7c-37f85a81d0b3.png)
2. Перенос на печатной и электронной форме нужен для длинного названия фирмы
3. Кроме вышеописанного в редактировании проведенного, нет редактирования даты.
![image](https://user-images.githubusercontent.com/42540074/70055522-5faa2600-15e2-11ea-9713-f7b899c72837.png)

Остальное работает, отображение в списках и учете, распроведение, привязка, как от самостоятельного, так и в созданном на основании. Если удалить строки - выдает объяснимую ошибку и не печатает, не проводит, не сохраняет в редактировании проведенного. --Это гуд!

**Comment by AlexeyTishkin** [comment]
> Нужен перенос названия в допечатной форме

Для однообразия сделал обрезание названия. В рабочих формах в этом месте нет переносов.

**Comment by AlexeyTishkin** [comment]
> Перенос на печатной и электронной форме нужен для длинного названия фирмы

Сделал.

**Comment by AlexeyTishkin** [comment]
> Кроме вышеописанного в редактировании проведенного, нет редактирования даты.

Полного редактирования нет, можно менять только определенные свойства. Количество, в частности.

**Comment by Anestezia** [comment]
Да, все есть. А что насчет Додати рядок?

**Comment by AlexeyTishkin** [comment]
> А что насчет Додати рядок?

Таблица с ТМЦ заполняется на основе родительского документа. Можно только убрать не нужные строки.

**Comment by Anestezia** [comment]
Тогда закрываем
