### ISSUE TITLE
Операция "Повернення від покупця" сделана в новом интерфейсе (диалоге)

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#444]
Проверить:
1. Создание:
   * создается как дочерняя из операции "Реалізація запасів".
   * создается как самостоятельная с последующим выбором родительской операции ("Реалізація запасів").
2. Редактирование.
3. Проведение.
4. Отражение в учете.
5. Отмену проведения.
6. Печать.
7. Отображение в списках.
8. Копирование.

**Comment by Anestezia** [comment]
По поверненню від покупця:
1. В печатной и сохраняемой версиях нужен перенос для длинного названия фирмы
![image](https://user-images.githubusercontent.com/42540074/70051810-88c6b880-15da-11ea-891e-ef80ae79070f.png)
2. В режиме редактирования проведенного мало что редактируется. Строку не добавить, контрагента - договор - проект не поменять. (Ладно еще контрагента, но дог и проект бы хорошо.)
![image](https://user-images.githubusercontent.com/42540074/70052750-a006a580-15dc-11ea-9ac5-5fe898dc3177.png)
3. В скопированном документе нельзя поменять Контрагента. Я думаю. что такая возможность нужна.

**Comment by AlexeyTishkin** [comment]
> Ладно еще контрагента, но дог и проект бы хорошо

Возврат к определенной накладной. Не может быть реализация по одному договору/проекту, а возврат по другим.

**Comment by AlexeyTishkin** [comment]
> В скопированном документе нельзя поменять Контрагента. Я думаю. что такая возможность нужна.

В скопированном документе есть родитель. У дочернего не может быть другого контрагента. Если нужен другой контрагент, то надо либо выбрать другое основание, либо его сбросить.

**Comment by AlexeyTishkin** [comment]
> В печатной и сохраняемой версиях нужен перенос для длинного названия фирмы

Сделал.

**Comment by Anestezia** [comment]
Ок. перенос есть. с остальным понятно. Закрываем?
