### ISSUE TITLE
Отчет "Оборотна відомість за розрахунками з постачальниками (покупцями)"

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#445]
Приведен к новому внешнему виду.
Строится с договора (Придбання/Продажі - Договори - Договор - Открыть - Звіти).
Проверить:
1. Построение.
2. Печать.
3. Экспорт в Excel.

**Comment by Anestezia** [comment]
Что-то я не вижу, где у меня переставить в настройках печати на альбомный лист этот отчет, а то так не влезает при 100% масштабе
![image](https://user-images.githubusercontent.com/42540074/70227148-c18d9b80-175a-11ea-9cc7-d43bf80624aa.png)
И к чему-то лепится второй лист, который выглядит пустым.
И не знаю, важно ли, но подставляется короткое название фирмы
![image](https://user-images.githubusercontent.com/42540074/70227431-3e207a00-175b-11ea-9505-d518fa555de0.png)
Экспорт в порядке. Заполнение тоже, доки из отчета открываются. Это касается обоих отчетов. Нормально печать выглядит на 97%.

**Comment by AlexeyTishkin** [comment]
> Что-то я не вижу, где у меня переставить в настройках печати на альбомный лист этот отчет, а то так не влезает при 100% масштабе

Альбомный лист уже выбран.
Похоже, что не помещается из-за полей. Попробуй пользовательские поставить.
У меня на стандартном принтере XPS и полях по умолчанию такой эффект виден при масштабе 101%.

А такая же оборотка с контрагента как печатается ?

**Comment by AlexeyTishkin** [comment]
> И не знаю, важно ли, но подставляется короткое название фирмы

Это внутренний отчет. Там полное не нужно.

**Comment by Anestezia** [comment]
Такая же с контрагента так же. Ладно, пусть люди масштаб уменьшают пока при печати. В 1С это постоянно делать приходилось.

**Comment by AlexeyTishkin** [comment]
> Такая же с контрагента так же

Тогда это не отчет. От принтера зависит.

**Comment by AlexeyTishkin** [comment]
Тогда закрываю.
