### ISSUE TITLE
Операции "Податковий кредит", "Податкове зобов'язання" сделаны в новом интерфейсе (диалоге)

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#446]
Проверить:
1. Создание:
   * операция "Податковий кредит" создается как дочерняя из операций "Отримання рахунку", "Придбання матеріальних активів", "Придбання послуг", "Імпорт послуг".
   * операция "Податкове зобов'язання" создается как дочерняя из операций "Виставлення рахунку", "Реалізація запасів", "Формування відомості РРО", "Реалізація послуг", "Експорт запасів", "Імпорт послуг".
   * создаются как самостоятельные.
2. Редактирование.
3. Проведение.
4. Отражение в учете.
5. Экспорт в XML.
6. Экспорт в Сонату.
7. Отмену проведения.
8. Отображение в списках.
9. Копирование.
10. Поддержку версии 9 (дата документа до 01/12/2018):
   * открытие уже имеющихся документов (если есть).
   * переключение даты документа на старый период: после смены даты вопрос с подтверждением, после подтверждения отображение документа в форме версии 9.

**Comment by Anestezia** [comment]
Поля кривовато у документа отдельно созданного.
![image](https://user-images.githubusercontent.com/42540074/71099786-8492c180-21bc-11ea-9d78-f7402e4ee4f1.png)

**Comment by Anestezia** [comment]
Из ведомости РРО странное поведение. 
![image](https://user-images.githubusercontent.com/42540074/71161471-13055280-2252-11ea-8d9b-23d15a7e58aa.png)
а вот сама ведомость
![image](https://user-images.githubusercontent.com/42540074/71161518-2adcd680-2252-11ea-8337-4539f7690f2d.png)
Табличная часть есть, а вот на кого выписывать НН, не понятно.

**Comment by Anestezia** [comment]
Предыдущий вопрос снят. Все работает. В учете и списках отображается, отправляется, сохраняется, проверку в Сонате проходит, копируется, редактируется, старая форма также отображается с сообщением. Из отчетов документы открываются.
