### ISSUE TITLE
Операции "Коригування податкового кредиту", "Коригування податкового зобов'язання" сделаны в новом интерфейсе (диалоге)

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#447]
Проверить:
1. Создание:
   * операция "Коригування податкового кредиту" создается как дочерняя из операции "Податковий кредит".
   * операция "Коригування податкового зобов'язання" создается как дочерняя из операции "Податкове зобов'язання".
2. Редактирование.
3. Проведение.
4. Отражение в учете.
5. Экспорт в XML.
6. Экспорт в Сонату.
7. Отмену проведения.
8. Поддержку версии 9 (дата документа до 01/12/2018):
   * открытие уже имеющихся документов (если есть).
   * переключение даты документа на старый период: после смены даты вопрос с подтверждением, после подтверждения отображение документа в форме версии 9.

**Comment by Anestezia** [comment]
Все работает, отображается, создается, копируется. в старую форму с сообщением переходит. Сонатовскую проверку проходит.
