### ISSUE TITLE
Добавлена операция "Повернення з бюджету помилково (надлишково) сплачених коштів"

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#449]
[1242](https://github.com/a2develop/bugTracker/issues/1242).
Бухгалтерія - Платежі - Створити платіж - Зареєструвати повернення з бюджету.

Проверить:
1. Создание.
2. Редактирование.
3. Проведение.
4. Отражение в учете.
5. Отмену проведения.
6. Отображение в списках.
7. Копирование.
8. Выбор основания.

**Comment by Anestezia** [comment]
По все пунктам все ок. Основание сразу отображается в цепочке, из отчетов документ открывается, копируется, редактируется.
