### ISSUE TITLE
Вступительный баланс. Зарплата. Новый документ "Вступительный баланс по сотруднику"

### ISSUE THREAD

**Issue by Illya-Lykhachov** [a2develop/testing#450]
Если работает, Оставим только его, а другие операции грохнем

**Comment by Anestezia** [comment]
Пока нет печатной формы, предлагаю убрать от туда кнопки печать и экспорт.
Также предлагаю протестировать ее пока, в следующем релизе убирать, если все ок и клиентам зайдет.
Как-то так подписать эти поля, а то не понятно, что к чему
![image](https://user-images.githubusercontent.com/42540074/71192278-a3fb1e80-2290-11ea-9233-8587869df9ff.png)
Не отображается в списке документов по сотруднику. Только приказ виден. а ввода нач. остатков нет. 
![image](https://user-images.githubusercontent.com/42540074/71192381-d0af3600-2290-11ea-86f3-feaad0380c45.png)
В плане счетов этот документ тоже не отображается.

**Comment by Anestezia** [comment]
Похоже, что вообще в проводки по 661-663 не попадает. Только в ведомость расчетную - Отчеты_персонал. Также не понятно с проводками по кнопке Проводки. Если Большая сумма (оклад/средняя) идет на 661 счет, то в Расчетную ведомость попадают только суммы из двух верхних ячеек.
![image](https://user-images.githubusercontent.com/42540074/71193390-ba09de80-2292-11ea-9803-f875c5b77724.png)
![image](https://user-images.githubusercontent.com/42540074/71193405-c2fab000-2292-11ea-967a-bc8e43b9d1a9.png)
![image](https://user-images.githubusercontent.com/42540074/71193419-cdb54500-2292-11ea-81da-b8c9308dbf8b.png)

Почему по 661 суммы отнимаются? И что с ними дальше
![image](https://user-images.githubusercontent.com/42540074/71193598-06551e80-2293-11ea-8dc7-0f77a14684f4.png)

П.С. удалить кнопки печати и экспорта и в старых документах начального зарплатного баланса

**Comment by Illya-Lykhachov** [comment]
печать и экспорт убрал

**Comment by Illya-Lykhachov** [comment]
добавил подписи к суммам остатков по счетам

**Comment by Illya-Lykhachov** [comment]
отображается в списке документов по сотруднику

**Comment by Illya-Lykhachov** [comment]
> В плане счетов этот документ тоже не отображается.

В плане счетов вступительный баланс вообще не отображается

**Comment by Illya-Lykhachov** [comment]
Проводки правильные и попадают во все отчёты.

![image](https://user-images.githubusercontent.com/35328100/71308415-fcebc380-2404-11ea-8f6c-2f6bc12ac6f7.png)
Эти суммы можешь увидеть в этих отчётах
![image](https://user-images.githubusercontent.com/35328100/71308440-3f150500-2405-11ea-9211-33c947f8ae7c.png)
а так же в расчётно платёжной ведомости.
![image](https://user-images.githubusercontent.com/35328100/71308477-cbbfc300-2405-11ea-9b69-91b95c5dcc4b.png)
Эти суммы не являются вступительным балансом и нужны только для расчёта средней зарплаты

**Comment by Illya-Lykhachov** [comment]
Если замечаний нет, я удаляю из менюшки создания новых документов вступительного баланса по зарплате старые шаблоны операций

**Comment by Anestezia** [comment]
К основной таблице все равно нет разъяснения.

**Comment by Anestezia** [comment]
В схеме рахунка по счетам 661 и 663 не нашла цифр из ячеек залишок по 661 и 663. Только в отчете по розрахункам з контрагентами эти суммы фигурируют. В списке операций этого документа нет в плане счетов.  Если задействованы проводки по 661\663, то в Загальній ОСВ в сальдо на початок разве эти суммы не должны быть?
![image](https://user-images.githubusercontent.com/42540074/72078742-578c8700-3302-11ea-9afa-6fd0bd3008dd.png)

**Comment by Anestezia** [comment]
Проводки внутри документа вообще непонятные: 
1. 
![image](https://user-images.githubusercontent.com/42540074/72078884-9d494f80-3302-11ea-80d9-71c2bffce4f2.png)
2. 
![image](https://user-images.githubusercontent.com/42540074/72078902-a5a18a80-3302-11ea-850d-5ae73842d031.png)
3. 
![image](https://user-images.githubusercontent.com/42540074/72078931-af2af280-3302-11ea-839e-556e15f52608.png)
Куда идут эти суммы с минусом? Почему показывается, что это тоже по 661 и 663 счетам и почему данные из нижней таблицы отнимаются от того, что в верхних ячейках.
