### ISSUE TITLE
Персонал/зарплата. Новый отчёт "Расчётные листы"

### ISSUE THREAD

**Issue by Illya-Lykhachov** [a2develop/testing#451]

**Comment by Anestezia** [comment]
На печати Расчетной ведомости при увольнении нет компенсации за отпуск.
![image](https://user-images.githubusercontent.com/42540074/71969560-91c92c00-320f-11ea-82ed-05b1e72b3d21.png)
![photo_2020-01-08_12-06-28](https://user-images.githubusercontent.com/42540074/71969575-9857a380-320f-11ea-8815-d7a05888e699.jpg)

**Comment by Anestezia** [comment]
В самом отчете пустой лист. Разные периоды пробовала и разных сотрудников. Данные по ним точно есть. 
![image](https://user-images.githubusercontent.com/42540074/71969738-f4222c80-320f-11ea-85e6-e04f082b0c5d.png)

**Comment by Illya-Lykhachov** [comment]
> На печати Расчетной ведомости при увольнении нет компенсации за отпуск.

Исправлено

**Comment by Illya-Lykhachov** [comment]
> В самом отчете пустой лист. Разные периоды пробовала и разных сотрудников. Данные по ним точно есть.

Исправлено

**Comment by Anestezia** [comment]
В отчете теперь есть информация, или по всем сразу или по выбранному сотруднику. Но вот экспорт в эксель все закидывает в одну строку
![image](https://user-images.githubusercontent.com/42540074/72056837-05357100-32d6-11ea-99e4-8dbba01a9b07.png)
По второму вопросу о расчетной ведомости при увольнении, есть отпуск (компенсация). Надеюсь, не бывает такого, чтоб и просто отпускные в периоде расчета были и компенсация, а то понадобится еще для простого отпуска ячейка.

**Comment by Illya-Lykhachov** [comment]
> По второму вопросу о расчетной ведомости при увольнении, есть отпуск (компенсация). Надеюсь, не бывает такого, чтоб и просто отпускные в периоде расчета были и компенсация, а то понадобится еще для простого отпуска ячейка.

Это невозможно. Если пошел в отпуск, то компенсировать нечего

**Comment by Illya-Lykhachov** [comment]
> В отчете теперь есть информация, или по всем сразу или по выбранному сотруднику. Но вот экспорт в эксель все закидывает в одну строку

В этом отчёте вложенные таблицы. Экспорт в Excel их не видит.
Пока убрал экспорт в Excel

**Comment by Anestezia** [comment]
Исправлено, работает. Можно закрывать.
