### ISSUE TITLE
Добавлены виды объектов учета: "Матеріали с/г призначення" (счет 208), "Продукція с/г виробництва" (счет 27)

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#452]
[1259](https://github.com/a2develop/bugTracker/issues/1259)

Проверить:
1. Создание.
2. Редактирование.
3. Отображение в списках.
4. Копирование.
5. Выбор в документах.
6. Приобретение.
7. Реализацию.
8. Отражение в отчетах.

**Comment by AndriyNesterenya** [comment]
Не попадают в фильтры по отчетам типа оборотной ведомости по складу при переходе из об'єктів обліку.
![image](https://user-images.githubusercontent.com/38098758/71915698-f4291a80-3184-11ea-896f-922b68ef1999.png)

Хотя в саму ведомость попадают. 
![image](https://user-images.githubusercontent.com/38098758/71915930-74e81680-3185-11ea-9447-ea8356e897c4.png)

**Comment by Anestezia** [comment]
С сообщением выше согласна. В остальном все работает. В списках отображается. даже в плане счетов и отчетах из него.

**Comment by AlexeyTishkin** [comment]
> Не попадают в фильтры по отчетам типа оборотной ведомости по складу при переходе из об'єктів обліку.

Добавил.

**Comment by Anestezia** [comment]
Есть. работает.
