### ISSUE TITLE
Новая форма платежного поручения

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#455]
[1262](https://github.com/a2develop/bugTracker/issues/1262)

Проверить печать/экспорт из:
1. Платежа контрагенту.
2. Входного платежа.
3. Личного кабинета.

**Comment by AndriyNesterenya** [comment]
Входящий/исходящий платежи ОК.

В форме платежки из личного кабинета не подтягивается банк и счет клиента ни у основной фирмы, ни у дополнительных.

![image](https://user-images.githubusercontent.com/38098758/71769912-61437280-2f2f-11ea-97c0-b880908426a5.png)
