### ISSUE TITLE
Код SWIFT

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#459]
[1272](https://github.com/a2develop/bugTracker/issues/1272)

Проверить работу и отображение сообщений об ошибках.

**Comment by Anestezia** [comment]
Подсказка есть, видна. Только на иностранных банках. А что с отечественными?
![image](https://user-images.githubusercontent.com/42540074/72243989-f0b6e880-35f5-11ea-85f0-f4d955824ef2.png)
![image](https://user-images.githubusercontent.com/42540074/72244014-01fff500-35f6-11ea-98e1-de3311abb486.png)

**Comment by AlexeyTishkin** [comment]
> А что с отечественными?

Что не так ? На скрине введен.

**Comment by Anestezia** [comment]
На скрине не показывает, что сам код введен не правильно. Не горит красным, нет подсказки, что код состоит из стольки-то букв и цифр

**Comment by AlexeyTishkin** [comment]
Почему введен не правильно ? 11 цифр.

**Comment by Anestezia** [comment]
У наших банков только цифры в коде, буквы отсутствуют? 
Тогда закрываем.

**Comment by AlexeyTishkin** [comment]
> У наших банков только цифры в коде, буквы отсутствуют?

Формат кода единый для всех.
8 или 11
букв (анг.) или цифр
На остальное должен ругаться.

**Comment by Anestezia** [comment]
Ругается
