### ISSUE TITLE
Отчёт в ЕФСС. Таблица 5. Заполнение колонок 12-15

### ISSUE THREAD

**Issue by Illya-Lykhachov** [a2develop/testing#46]

**Comment by Anestezia** [comment]
С 12 по 15 колонки данные подтягивает корректно, после заполнения соответствующих полей в карточках персонала. Переносит в сонату тоже ок. Проверку сонатовскую проходит.

**Comment by AndriyNesterenya** [comment]
Так закрывайте, мабуть....
