### ISSUE TITLE
Механизм импорта объектов учета

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#461]
[1027](https://github.com/a2develop/bugTracker/issues/1027)

Добавлена возможность импорта кодов ДКПП. 

Проверить импорт.

**Comment by Anestezia** [comment]
Попробовала импортировать, воспользовалась файлом-образцом. В самом образце не понятен код 49.10.11-00.00?
![image](https://user-images.githubusercontent.com/42540074/72340121-4cee3b00-36d0-11ea-9fc2-25451ed5c75c.png)
Мало того, что код такой не существует, так еще и появились вопросы к виду формата ячейки. Или такой странный код был введен намеренно?
Также вписала свой код во второй объект в файле. При импорте система дала сообщение, что объект уже существует, поэтому я нажала кнопку (карандашик) тут же. Изменила название. Все равно выдало то, что уже существует. В самом списке объект переименовался тот, что был раньше. Но вот вывелась такая картина
![image](https://user-images.githubusercontent.com/42540074/72340100-4233a600-36d0-11ea-83ee-f21f69f37e64.png)

**Comment by AlexeyTishkin** [comment]
> В самом образце не понятен код 49.10.11-00.00?

![image](https://user-images.githubusercontent.com/35917940/72340581-24b30c00-36d1-11ea-95d9-fa2df6ca9878.png)

![image](https://user-images.githubusercontent.com/35917940/72340669-40b6ad80-36d1-11ea-9815-b58320f5bb69.png)

**Comment by AlexeyTishkin** [comment]
> так еще и появились вопросы к виду формата ячейки

Что с форматом ?

**Comment by Anestezia** [comment]
Нормально затягивается, в списке объектов эта характеристика отображается. В налоговые накладные подтягивается.

**Comment by Anestezia** [comment]
если 11-00.00 -- это нормально, тогда нет вопросов. Можно закрывать
