### ISSUE TITLE
Добавлен вид объекта учета: "Тара й тарні матеріали" (счет 204)

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#462]
Проверить:
1. Создание.
2. Редактирование.
3. Отображение в списках.
4. Копирование.
5. Выбор в документах.
6. Приобретение.
7. Реализацию.
8. Отражение в отчетах.

**Comment by MaksymTikhomirov** [comment]
+++

**Comment by AndriyNesterenya** [comment]
Ковіряю - тестирую на живых примерах, вытащенных из 1С 77 нашего живого клиента.
Пока нашел только кривое англоязычное сообщение при неправильном формате экселевского файла при импорте контрагентов
![image](https://user-images.githubusercontent.com/38098758/72185785-43c54b80-33fc-11ea-8759-6c7efde34fa3.png)

**Comment by AndriyNesterenya** [comment]
Работает, но та же история с нулями наблюдается в поле "номер платника ПДВ". 
Более того, первые 7 цифр должны повторять номер ЕДРПОУ, в который мы слева добавляем нули. 
Первая мысль - при наличии в этом поле значения длиной меньше 12  & при длине ЕДРПОУ в этой же строке != 10 (не ФОП) - дополнять нулями слева до 12.

**Comment by AndriyNesterenya** [comment]
Создание/Редактирование/Отображение в списках/Копирование без замечаний.
Дубликаты не создаются.
Списки в порядке.
Редактируется нормально.

Остальное еще буду копать.

**Comment by AlexeyTishkin** [comment]
> Пока нашел только кривое англоязычное сообщение при неправильном формате экселевского файла при импорте контрагентов

А при чем здесь Тара ? Это отдельным issue с примером файла.

**Comment by AlexeyTishkin** [comment]
> Работает, но та же история с нулями наблюдается в поле "номер платника ПДВ".

Это тоже не сюда.

**Comment by AlexeyTishkin** [comment]
> Создание/Редактирование/Отображение в списках/Копирование без замечаний.

Это относится к Таре ?

**Comment by AndriyNesterenya** [comment]
Пардон - это все к импорту контрагентов. Промахнулся веткой

**Comment by Anestezia** [comment]
Все работает.
