### ISSUE TITLE
Операция "Виставлення інвойсу" сделана в новом интерфейсе (диалоге)

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#463]
Проверить:
1. Создание.
2. Редактирование.
3. Проведение.
4. Создание связанных документов.
5. Отмену проведения.
6. Печать.
7. Режим редактирования проведенного документа.
8. Отображение в списках.
9. Копирование.

**Comment by Anestezia** [comment]
Немного смещены окна правые
![image](https://user-images.githubusercontent.com/42540074/72980157-b3670d80-3de2-11ea-945b-ed04e180e96f.png)
Имею администратрский доступ. Создала инвойс, от него создала реализацию, оставила ее черновиком, закрыла оба документа. В списке операций он висит непроведенный, нажимаю извне кнопку удалить реализацию, а мне пишет. Доступ заборонено
![image](https://user-images.githubusercontent.com/42540074/72980778-e65dd100-3de3-11ea-9eb7-49a65b79de73.png)

**Comment by Anestezia** [comment]
В остальном все ок. сохранение и печать в порядке. Настройка печатной формы -- не нашла где на печати задействуется верхний/нижний колонтитул, коды уктзед и артикул.

**Comment by AlexeyTishkin** [comment]
> Немного смещены окна правые

Исправил.

**Comment by AlexeyTishkin** [comment]
> Имею администратрский доступ. Создала инвойс, от него создала реализацию, оставила ее черновиком, закрыла оба документа. В списке операций он висит непроведенный, нажимаю извне кнопку удалить реализацию, а мне пишет. Доступ заборонено

Исправил.

**Comment by AlexeyTishkin** [comment]
> не нашла где на печати задействуется верхний/нижний колонтитул, коды уктзед и артикул.

На данный момент нигде. Не понадобилось еще.

**Comment by Anestezia** [comment]
Форма в порядке. можно закрывать
