### ISSUE TITLE
Множественные изменения и исправления в документе Акт приема-передачи необоротных активов

### ISSUE THREAD

**Issue by htrofymova** [a2develop/testing#464]
Нужно проверить все режимы документа:
1. В этом документе возможны две операции
2. Возможны разные виды необоротных активов.
Обратить внимание на формирование проводок: 
1. если поступление на склад, то должны быть проводки по складу; 
2. поступление для нематериальных - ДТ 154 (если не выбран другой счет затрат), основные - ДТ 152, інші необоротні матеріальні - ДТ 153.
Заполнение склада не обязательно только если выбраны счета: 39, 92 или 949

**Comment by Anestezia** [comment]
Все работает, кроме общего ввода разных типов объектов в одном документе. На это отдельный ишью. Этот можно закрывать.
