### ISSUE TITLE
Податкова декларація з податку на додану вартість

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#465]
[1265](https://github.com/a2develop/bugTracker/issues/1265)

Новые формы налоговой отчетности: Податкова декларація з податку на додану вартість (J0200121, F0200121), Приложение 1 - Розрахунок коригування сум податку на додану вартість (J0200521, F0200421), Приложение 5 - Розшифровки податкових зобов'язань та податкового кредиту в розрізі контрагентів (J0215121, F0215121). 

Проверить:
1. Создание.
2. Заполнение.
3. Редактирование.
4. Проведение.
5. Отмену проведения.
6. Создание Приложений 1, 5 (для декларации).
7. Формирование XML.
8. Экспорт в Сонату.

Проверить под юр. лицом и ФОПом.

**Comment by Anestezia** [comment]
Основная налоговая декларация проводится, даже если есть рядки, для которых идут Додатки. А после проведения додатки уже не создать. Приходятся распровести, создать и провести их, и только потом провести основную. Это не сразу понятно новичку. Хотя и  не критично. 
Экспорт в хмл работает. В Сонату загружается, но там бланков нет. В пакет внутри сонаты также не добавляется. 
В остальном все ок. В додатках тоже.

**Comment by AlexeyTishkin** [comment]
> Основная налоговая декларация проводится, даже если есть рядки, для которых идут Додатки.

Отдельный issue: запрещать проведение в случае, если заполнены суммы в строках, привязанных к приложению, а приложение не создано.

**Comment by AlexeyTishkin** [comment]
> А после проведения додатки уже не создать.

Это правильно. В отчетах другая логика. Проводятся вначале дочерние приложения, потом основной отчет.

**Comment by AlexeyTishkin** [comment]
> В пакет внутри сонаты также не добавляется.

Нет пока такого функционала. Для пакета можно выгрузить три отчета в XML, а потом в Сонате сделать импорт.

**Comment by AlexeyTishkin** [comment]
> Основная налоговая декларация проводится, даже если есть рядки, для которых идут Додатки. 

Сделал предупреждение.

**Comment by Anestezia** [comment]
предупреждение работает.

**Comment by AlexeyTishkin** [comment]
А остальное ? Закрываем ?

**Comment by Anestezia** [comment]
Других вопросов не было. С пакетом итак понятно.
