### ISSUE TITLE
Отчет ФОП по ЕСВ

### ISSUE THREAD

**Issue by htrofymova** [a2develop/testing#466]
Исправлено, согласно https://github.com/a2develop/bugTracker/issues/1278.
Нужно проверить:
изменения дат в родительском отчете (в основной таблице);
пересчет итоговых сумм;
выгрузка в Сонату и проч. без нулей в пустых ячейках.

**Comment by Anestezia** [comment]
Суммы считаются правильно, выгружается без нулей в пустых ячейках.
