### ISSUE TITLE
Уточнюючий розрахунок податкових зобов'язань з податку на додану вартість у зв'язку з виправленням самостійно виявлених помилок

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#467]
[1265](https://github.com/a2develop/bugTracker/issues/1265)

Новая форма налоговой отчетности: Уточнюючий розрахунок податкових зобов'язань з податку на додану вартість у зв'язку з виправленням самостійно виявлених помилок (J0217021, F0217021). 

Проверить:
1. Создание.
2. Редактирование.
3. Проведение.
4. Отмену проведения.
5. Создание Приложений 1, 5.
7. Формирование XML (розрахунка и приложений).
8. Экспорт в Сонату (розрахунка и приложений).

Проверить под юр. лицом и ФОПом.

**Comment by Anestezia** [comment]
Странно, но провести не могу, а уточненка первая у меня. То, что у меня декларация подалась за 01 месяц, и уточненка тоже за 01 месяц. Это имеется в виду? Так я же уточняю. Не должно запрещать.
![image](https://user-images.githubusercontent.com/42540074/73010792-bdf1c900-3e1b-11ea-88bb-7cb57be98759.png)
Все поудаляла, оставила только декларацию НДС, ФОП, уточненка сначала провелась, я выбрала период уточнения на месяц раньше, и потом я выбрала период уточнения в этом же месяце, провелась. Не стали проводиться Додатки.

**Comment by AlexeyTishkin** [comment]
> Не стали проводиться Додатки.

В Приложениях, которые создаются из уточняющего расчета добавлено свойство "Номер нового звітного/уточнюючого документа". При создании равно 1.
Принцип следующий: первое подаваемое приложение имеет тип "Звітний" и номер равный 0 (в этом случае номер указывать не надо и он не отображается). Для каждого последующего приложения этого же типа для данного отчётного периода тип должен быть "Звітний новий" или "Уточнюючий" и значение номера увеличивается на единицу. При создании приложения с типом "Звітний новий" или "Уточнюючий" номер устанавливает в 1, последующая нумерация осуществляется пользователем вручную.

**Comment by Anestezia** [comment]
Номер вижу дополнений к уточненке. 
По Звитной новой: Я создала звитну нову декл.НДС, тут же проставился номер 1, Провела, на период не жаловалось. Распровела. создала додаток. (а к этому моменту в периоде у меня уже есть одна декл.  с додатками и одна уточненка с додатками). Делаю додаток к звитной новой -- ставит автоматом 1. Провести не дает, вспоминаю, что  нужно дальше руками номер ставить после 1. Ставлю 2, Проводится, но оставляет №1 после этого проведения.

**Comment by AlexeyTishkin** [comment]
> Ставлю 2, Проводится, но оставляет №1 после этого проведения.

Исправил.

**Comment by Anestezia** [comment]
Все работает.
