### ISSUE TITLE
ОС для неприбыльных

### ISSUE THREAD

**Issue by htrofymova** [a2develop/testing#468]
По поводу https://github.com/a2develop/bugTracker/issues/1285
Изменена структура многострочных проводок, нужно проверить адекватное отображение в отчетах.
Пример лучше сделать "чистый": 
1. 2 объекта ОЗ
2.  "Безоплатне отримання": первый - "нецільове надходження", второй - выбрать вариант целевого поступления.
3. Ввод в эксплуатацию
4. Амортизация. в следующем месяце.
Смотрим проводки ( при целевом поступлении 48-е счета в приходной накладной и акте ввода в эксплуатацию должны быть одинаковыми) и перечисленные в обращении пользователя отчеты.

**Comment by Anestezia** [comment]
48-е счета в приходной накладной и акте ввода в эксплуатацию  одинаковые. 
Проводки по амортизации такие
![image](https://user-images.githubusercontent.com/42540074/72995706-07351f00-3e02-11ea-80eb-1f244e2d8a3c.png)
![image](https://user-images.githubusercontent.com/42540074/72995786-2a5fce80-3e02-11ea-95f5-95bf534205ca.png)
![image](https://user-images.githubusercontent.com/42540074/72995923-6b57e300-3e02-11ea-94b8-1f8a4fd70fa4.png)
![image](https://user-images.githubusercontent.com/42540074/72995962-79a5ff00-3e02-11ea-8235-9e6782a220dd.png)
