### ISSUE TITLE
Множественные изменения документа Введення в експлуатацію необоротних активів.

### ISSUE THREAD

**Issue by htrofymova** [a2develop/testing#469]
Изменено проведение операций для неприбыльных организаций:
1. "Целевое" безоплатное получение - проводки по 48-м счетам формируются автоматически, вводить код строки отчета и выбирать счет не нужно. Соответствующие элементы больше в диалоге не появляются.
2. "нецелевое" безоплатное получение - проводки по 48-м счетам не формируются.

Нужно проверить ВСЕ варианты операций, возможных в этом документе.

**Comment by Anestezia** [comment]
По этому вопросу все ок.
