### ISSUE TITLE
ЕСВ табл. 5. Колонки 11, 13

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#47]
[519](https://github.com/a2develop/bugTracker/issues/519)
Теперь при заполнении ячейки в этих колонках пустые.

**Comment by Anestezia** [comment]
Подтверждаю. При переносе в Сонату проблем нет.
![image](https://user-images.githubusercontent.com/42540074/45423282-84dc0d00-b69b-11e8-8b0b-72e3e0c7b1ce.png)
