### ISSUE TITLE
Звіт про використання доходів (прибутків) неприбуткової організації 

### ISSUE THREAD

**Issue by htrofymova** [a2develop/testing#470]
Изменен алгоритм заполнения отчета. 
Добавлена расшифровка строк (если код строки синий, то можно развернуть реестр проводок по этому коду).
Нужно проверить.
Заполняются 1 и 2 части.
1 часть = обороты по кредиту 7 класса, кроме 791, 792, 793. Если в документе выбран код строки (Вид надходжень), то сумма попадет в эту самую строку, если не выбран, то 73 счет - пасивні доходи, все прочее - інші доходи.
2 часть = оборотьі по дебету 9 класса, кроме 91 счета. Если в документе выбран код строки (Вид витрат), то сумма попадет в эту самую строку, если не выбран, то 92 и 949 счет - 2.3 вартість активів..., все прочее - 2.6 інші видатки (витрати). Вьібрать код строки для затрат на данньій момент можно только в расходном кассовом ордере и платежном поручении.

**Comment by Anestezia** [comment]
Работает
