### ISSUE TITLE
Розрахунок податкових зобов’язань, нарахованих отримувачем послуг, не зареєстрованим як платник ПДВ, які постачаються нерезидентами, у тому числі їх постійними представництвами, не зареєстрованими платниками податків, на митній території України

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#471]
[1265](https://github.com/a2develop/bugTracker/issues/1265)

Проверить:
1. Создание.
2. Заполнение.
3. Редактирование.
4. Экспорт в XML.
5. Экспорт в Сонату.

Проверить под юр. лицом и ФОПом.

**Comment by Anestezia** [comment]
Нужен инструмент подбора контрагента в первую и вторую таблицы
![image](https://user-images.githubusercontent.com/42540074/73004571-410d2200-3e10-11ea-8f28-bc9c9e8c9b51.png)
Автоподсчет сумм
 
![image](https://user-images.githubusercontent.com/42540074/73005362-84b45b80-3e11-11ea-8b6c-48595a4e695c.png)
Я обновила сонату

**Comment by Anestezia** [comment]
Если ставить Уточнююча, то не активна кнопка Провести
![image](https://user-images.githubusercontent.com/42540074/73005704-0f955600-3e12-11ea-8a9f-3380b347ef66.png)
Остальные ок.

**Comment by AlexeyTishkin** [comment]
> Нужен инструмент подбора контрагента в первую и вторую таблицы

Это отдельным issue.

**Comment by AlexeyTishkin** [comment]
> Автоподсчет сумм

Сделал.

**Comment by AlexeyTishkin** [comment]
> Если ставить Уточнююча, то не активна кнопка Провести

Исправил.

**Comment by Anestezia** [comment]
Автоподсчет есть, проведение есть
![image](https://user-images.githubusercontent.com/42540074/73934866-fb5c5900-48e7-11ea-9680-f2465de81b2d.png)
