### ISSUE TITLE
Добавлена операция "Безоплатне одержання необоротних активів"

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#472]
[1198](https://github.com/a2develop/bugTracker/issues/1198)

Проверить:
1. Создание.
2. Редактирование.
3. Проведение.
4. Отражение в учете.
5. Отмену проведения.
6. Отображение в списках.
7. Копирование.

**Comment by Anestezia** [comment]
Все работает, в учете отражается. Редактируется проведенный, экспорт и печать работают.
