### ISSUE TITLE
Регламентированные отчеты

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#473]
[1282](https://github.com/a2develop/bugTracker/issues/1282)

Кнопка "експорт xml" в не проведенных отчетах теперь запрещается (раньше скрывалась).

Проверить поведение кнопки (разрешена/запрещена).

**Comment by Anestezia** [comment]
Вроде ок. Она есть в отчетах и дополнениях к ним, при непроведенном состоянии не активна, при проведении активна, работает.
