### ISSUE TITLE
Отчеты по объектам учета

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#474]
[1291](https://github.com/a2develop/bugTracker/issues/1291)

В отчеты "Оборотна відомість по складу", "Оборотна відомість по об'єктах обліку", "Валовий прибуток", "Оборотність запасів" добавлен фильтр по группам объектов. .

Проверить построение отчетов.

**Comment by Anestezia** [comment]
Отбор идет, отчеты строятся по выбранным группам, с клавиатуры тоже можно вводить название группы -- ищет.
