### ISSUE TITLE
Отчет "Фінансовий звіт суб'єкта малого підприємництва" (S0110011)

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#475]
[1218](https://github.com/a2develop/bugTracker/issues/1218)

Автоматическая корректировка погрешности округления в строку 1420 заменена сообщением. В случае возникновения погрешности сообщение выдается в момент заполнения отчета (кнопка "Заполнить").

Проверить заполнение.

**Comment by AlexeyTishkin** [comment]
Для возникновения погрешности проще всего сделать так, чтобы в одной части была сумма только в одной строке, а во второй части эта же сумма была разбросана по нескольким строкам.
К примеру так:
![image](https://user-images.githubusercontent.com/35917940/73743034-59593700-4756-11ea-8476-663930a2b794.png)

**Comment by Anestezia** [comment]
Вопрос по выводимому сообщению, может стоит написать тис. грн? А то в балансе это погрешность в 1 грн, а здесь в 10 копеек. в остальном все ок.
