### ISSUE TITLE
Отчет "Баланс (Звіт про фінансовий стан)" (S0100113)

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#476]
[1312](https://github.com/a2develop/bugTracker/issues/1312)

Автоматическая корректировка погрешности округления в строку 1420 заменена сообщением. В случае возникновения погрешности сообщение выдается в момент заполнения отчета (кнопка "Заполнить"). 

Проверить заполнение.

**Comment by Anestezia** [comment]
![image](https://user-images.githubusercontent.com/42540074/74931049-8dd02280-53e7-11ea-8c2f-4d77e641f61d.png)
Есть. Но сама сумма выглядит странно. При одном и том же кейсе, в этом отчете выводится разница в 1 грн. А в финзвите субъекта малого предпринимательства -- разница в 10 копеек. 
![image](https://user-images.githubusercontent.com/42540074/74931259-e8697e80-53e7-11ea-83f1-589bc088bd51.png)
Дезинформация?
Надо дописать везде тис. грн вместо грн. в выводимом сообщении?
