### ISSUE TITLE
Отчет "Податкова декларація з податку на прибуток підприємств"

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#477]
Добавлена возможность заполнения таблиц: "Доповнення до Податкової декларації з податку на прибуток підприємств (заповнюється і подається відповідно до пункту 46.4 статті 46 розділу ІІ Податкового кодексу України)", "Прийнято рішення про незастосування коригувань фінансового результату до оподаткування на усі різниці".

Проверить:
1. Добавление строк.
2. Редактирование значения.
3. Удаление строк.
4. Сохранение.
5. Экспорт XML.
6. Экспорт Соната.

**Comment by Anestezia** [comment]
Добавляется, редактируется, удаляется, в эспортном файле они есть.
