### ISSUE TITLE
Отчет "Додаток АМ"

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#478]
[1319](https://github.com/a2develop/bugTracker/issues/1319)

Изменено определение периода для расчета сумм начальной стоимости и начисленного износа. 
Проверить заполнение.
В случае возникновения проблем необходимо промоделировать кэйс на тестовом аккаунте (test@a2.net.ua).

**Comment by Anestezia** [comment]
Заполнение есть, экспорт тоже работает. а должны ли появляться отрицательные начальные остатки?
![image](https://user-images.githubusercontent.com/42540074/74945027-afd59f00-53ff-11ea-80c4-053319e57421.png)

**Comment by AlexeyTishkin** [comment]
> а должны ли появляться отрицательные начальные остатки?

Если есть какие-то проблемы с цифрами, то нужен пример на тестовом аккаунте.
