### ISSUE TITLE
Сделан импорт выписок для банка АТ «АЛЬФА-БАНК» МФО 300346

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#479]
[1332](https://github.com/a2develop/bugTracker/issues/1332)

Проверить импорт.

**Comment by Anestezia** [comment]
Затягивается только csv?  pdf -- нет? При ПДФ появилось это сообщение
![image](https://user-images.githubusercontent.com/42540074/74846936-fd87d400-5339-11ea-9b0e-be2237a7613c.png)
![image](https://user-images.githubusercontent.com/42540074/74846962-0a0c2c80-533a-11ea-9c7e-066d91f5c1df.png)
При ЦСВ -- это сообщение
![image](https://user-images.githubusercontent.com/42540074/74847049-2c05af00-533a-11ea-9646-6afc3c1af21e.png)

**Comment by Anestezia** [comment]
Все ок, работает 
![image](https://user-images.githubusercontent.com/42540074/74847621-1c3a9a80-533b-11ea-8220-2fbb0ece7c2a.png)
