### ISSUE TITLE
Справочники - Валюта - Курсы

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#48]
Проверить отображение/изменение курсов для любой валюты.

**Comment by Anestezia** [comment]
Курсы валют устанавливаются и отображаются в платежных документах корректно. 

Если задано несколько на разные даты, то при создании документа другой датой, подтягивается нужное значение курса, которое действовало на заданную дату.

Есть привязка к характеристикам валюты самого счета. Если расчетный счет в долларах, то автоматически выбирается значение долл. Если вручную попытаться изменить валюту документа на оплату, то реквизиты р\счета сбрасываются. Это хорошо.

Если в валютном документе на оплату сначала подтягивается курс, который мы задали в справочнике валют, а потом мы его вручную меняем, еще не проведя документ. То, если затем нажать на кнопку Оновити, курс снова не сбрасывается на заданное в карточке валюты значение. Если закрыть документ, так и не проведя его, а потом снова открыть, то курс сохраняется тот, который мы ввели вручную в самом документе на оплату в валюте, а не подтягивается из справочника. Просто особенность.
