### ISSUE TITLE
Податкова декларація з податку на прибуток підприємств

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#482]
[1264](https://github.com/a2develop/bugTracker/issues/1264)

Новые формы налоговой отчетности: Податкова декларація з податку на прибуток підприємств (J0100118, F0100703), Додаток РІ - Різниці (J0111818, F0171803), Додаток АМ - Інформація щодо нарахованої амортизації (J0110618, F0170603). 

Проверить:
1. Создание.
2. Заполнение.
3. Редактирование.
4. Проведение.
5. Отмену проведения.
6. Создание Приложений РІ, АМ (для декларации).
7. Формирование XML.
8. Экспорт в Сонату.

Проверить под юр. лицом и ФОПом.

**Comment by Anestezia** [comment]
Если сначала мы заполнили основную декларацию и только потом переходим к додаткам, то, например в додатке PI суммы вводятся вручную (или у меня при автозаполнении нет данных, чтоб можно было подтянуть). И после этого надо перезаполнить основнуб декларацию, суммы после проведения додатков сами не меняюются, сообщения предупреждающего об изменении нет. Если перезаполнить, то цифры уже другие с учетом тех, которые были в додатках внесены и проведены. Нужно или автоперезаполнение основной декларации, либо сообщение, что цифры изменились в связи с заполнением додатков. Нажмите кнопку Заповнити ще раз. Например, "У зв'язку з заповненням додатків цифри декларації могли змінитись. Натисніть кнопку "Заповнити" ще раз."

**Comment by Anestezia** [comment]
То же касается и ФОП, тем более, что Декларация выходит сразу заполненной . В остальном все ок. єкспорт, перепроведение, заполнение, редактирование

**Comment by AlexeyTishkin** [comment]
> Если сначала мы заполнили основную декларацию и только потом переходим к додаткам

Это отдельным issue.

**Comment by AlexeyTishkin** [comment]
> В остальном все ок. єкспорт, перепроведение, заполнение, редактирование

Тогда закрываю.
