### ISSUE TITLE
Договоры ГПХ

### ISSUE THREAD

**Issue by Illya-Lykhachov** [a2develop/testing#486]
Добавлен признаки дохода: аренда движимого и недвижимого имущества. В Акте по договору ГПХ в расчёт ЕСВ теперь зависит от признака дохода (аренда не облагается ЕСВ). Отчёт по форме 1-ДФ теперь учитывает признак дохода из договора ГПХ (не указан - 102)

**Comment by Anestezia** [comment]
Печатная форма акта при аренде весьма спорная, так как это не совсем услуга. 1ДФ заполняется по ним, коды ставит.
Экспорт в хмл не идет почему-то в 1ДФ
![image](https://user-images.githubusercontent.com/42540074/81932315-4925e300-95f4-11ea-9d2b-7b8b32ac11e2.png) и нет кнопок для Сонаты на 1ДФ.

**Comment by Anestezia** [comment]
Вроде все ок. Соната переустановлена, агент работает, налоговая, наименование и адрес проставлены, экспорт идет.
