### ISSUE TITLE
Продажи. Новвый подраздел - "Роздріб".

### ISSUE THREAD

**Issue by htrofymova** [a2develop/testing#487]
Появился новый позраздел "Роздріб".
Нужно проверить документ "Відомість РРО" - новый документ: заполняется при выборе z-отчета.
Так же посмотреть список этих документов.
Какие нужны бы отчеты для подраздела?
РРО теперь привязаны к складам: в свойствах склада включается отметка "Роздріб", появляется закладка "Реєстратори",  где РРО и создаются. - Тоже нужно проверить. 
Так же к розничному складу можно привязать прайс-лист и вид ценьі.

**Comment by Anestezia** [comment]
Все работает. Проводки формируются, со склада товар списывается. Оборотка по кассе в разрезе РРО. Оборотка по складу с фильтром РРО (?) Чтоб, например, можно было посмотреть, какой товар прошел именно через эту кассу за неделю.
