### ISSUE TITLE
Свойства объекта учета

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#49]
- [ ] Проверить отображение/изменение основных свойств в любом объекте

- [ ] На закладке "Загальні" при нажатии на гиперлинк "Показати ціни" должно открываться всплывающее окно "Ціни". Для существующего объекта. Для нового гиперлинка не должно быть.

**Comment by Anestezia** [comment]
Цены отображаются, как заявлено. Нет гиперлинка только в момент создания нового объекта учета. Как только он сохранен, и снова открывается, то уже появляется на вкладке "общие".
