### ISSUE TITLE
Проверить создание валютного счета своей фирме в банке-резиденте

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#5]
[191](https://github.com/a2develop/bugTracker/issues/191)

**Comment by Anestezia** [comment]
Работает. На вкладке Властивості моєї фірми добавляется без проблем. На вкладке Рахунки в банках отображается остаток по нему. Интересно, а как счет можно удалить?

**Comment by shevchuk-vadim** [comment]
Счет можно удалить там же, где его можно создать. Но удалить можно только тот счет, по которому нет операций.

**Comment by shevchuk-vadim** [comment]
Там был мелкий баг, из-за которого нельзя было удалить счет. Исправил. Нужно провериить в мастерах создания и диалогах свойств моей фирмы, контрагента, и банка.

**Comment by kattrina-brekhova** [comment]
добавляет. после того как сделала операции на вал. счетах - счет не удаляет
