### ISSUE TITLE
Всплывающее окно "Ціни"

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#50]
Вызывается:
1. В списке объектов при клике на цену.
2. В свойствах существующего объекта при клике на "Показати ціни" на закладке "Загальні".

Проверить:

- [x] При открытии должен быть выбрат основной прай-лист и вид цены. Отображены пять последних значений цен.

- [x] После смены прайс-листа в комбобоксе "виды цен" должнен быть выбран основной вид цены,  среди значений комбобокса вид цен только выбранного прайс-листа. Должен перезаполниться список со значениями цен.

- [x] После смены вида цены должен перезаполниться список со значениями цен.

- [x] При нажатии на кнопку "изменить" должен открыться диалог для редактирования цен.

**Comment by Anestezia** [comment]
Пункт первый - да. Работает, как описано в задании. Второй, третий и четвертый тоже.

**Comment by mik-man** [comment]
Настя не может даже галочки ставить, прав не хватает. ))
