### ISSUE TITLE
Диалог для редактирования цен

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#51]
Вызывается:
1. При нажатии кнопки "Изменить" во всплывающем диалоге "Ціни".
2. В списке объектов при клике на действие "Ціни".

Проверить:

- [ ] Селекторы "Прайс-лист", "Вид цены". Поведение такое как в документах: выбор, поиск, создание нового, редактирование свойств, сброс. Значение вида цены зависит от значения прайс-листа.

- [ ] Редактирование значений цен. Добавление/изменение/удаление. Должно быть корректное значение. Не должно быть дубликатов дат.

- [ ] Значения цен, которые были добавлены операцией "Створення прайс-листа". В колонке "Створена" должен отобразится гиперлинк с датой и номером документа. В строке нельзя идменить дату, значение. Строку нельзя удалить. При клике на гиперлинке должен открыться документ.

**Comment by Anestezia** [comment]
- [ ] Первый пункт работает корректно. 

Единственное, если создать новый прайс, но не задать вид цены, не создать его вообще, и попытаться ввести саму цену - ее числовое значение, то выдает ошибку и дальше не идет. Если вернуться к созданию необходимого вида цены в этом же окне, то ранее созданное числовое значение удаляется.
![image](https://user-images.githubusercontent.com/42540074/45545793-052d7a00-b824-11e8-8ce1-2e5c369f3f4a.png)
Несколько раз ошибка повторялась, потом перестала повторяться. Но изменения остались. В списке видов цен из первого окна есть вид цены 33, а в списке редактирования видов цен его уже нет.
![image](https://user-images.githubusercontent.com/42540074/45546145-204cb980-b825-11e8-96e3-ca760e344be6.png)
![image](https://user-images.githubusercontent.com/42540074/45546173-35294d00-b825-11e8-85f6-d61b16d69544.png)
Здесь нет вида цены 33. При этом редактировать само ценовое значение можно, Нажав в первом (маленьком окне) Изменить.  Попасть в редактирование этой цены можно только через первое меню, кнопка изменить и больше никак. Удалить тоже невозможно этот вид цены.

- [ ] Пункт второй Корректное значение цены. - Зачем после запятой шесть знаков? Может быть конфликт показателей, если из этого числа выделять НДС, будет округлять в декларации и додатках в разные стороны. Дубликаты дат запрещены в рамках одного вида цены. Добавление, изменение, удаление  - все ок. Вопрос!!! Зачем нужны несколько ценовых значений в рамках одного вида цены, если их невозможно выбрать при вводе в счете? Ставится только последняя по дате. Тогда зачем старые хранить? На память? Один прайс, один вид, одна цена. Другую выбрать нельзя из счета.

- [ ] Пункт третий работает как описано. В счете отображается только та цена, которая внесена последней по дате.

**Comment by AlexeyTishkin** [comment]
> Единственное, если создать новый прайс, но не задать вид цены, не создать его вообще

Сделал запрет кнопки "Створити" при отсутствии цены.

**Comment by AlexeyTishkin** [comment]
> В списке видов цен из первого окна есть вид цены 33, а в списке редактирования видов цен его уже нет.

Исправил.

**Comment by AlexeyTishkin** [comment]
> Зачем после запятой шесть знаков?

Обсудили.

**Comment by Anestezia** [comment]
Все в порядке, работает как заявлено.
