### ISSUE TITLE
Операция "Реалізація послуг"

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#52]
Добавлено наименование объекта для печати.
Проверить:

- [ ] Ввод/изменение/сохранение

- [ ] Печать объекта без наименования для печати

- [ ] Печать объекта с наименованием для печати

**Comment by Anestezia** [comment]
1. При вводе акта на основании счета, если две одинаковые товарные позиции, но с разными ценами в одном счете, то переносятся они обе в акт двумя разными позициями, только если в счете заполнено два или одно из полей "Назва для друку". Если эти поля не заполнены, то переносится одной общей товарной позицией с усредненной ценой.

2. Если в счете две таких позиции с "Назвою для друку", то после переноса в акт их остается две. затем можно "Назви для друку" в акте удалить, и при печати остаются две позиции с изначальным (верхняя строка) названием объекта. После проведения документа все сохраняется в этом виде с двумя позициями. Закрыть, открыть непроведенный акт - две товарные позиции сохраняются.
![image](https://user-images.githubusercontent.com/42540074/45539601-e4a8f400-b812-11e8-9f33-2a87131fa474.png)

3. При переносе позиций с наименованием для печати, переносятся обе позиции, на печать выводятся (нижняя строка)
![image](https://user-images.githubusercontent.com/42540074/45539824-7add1a00-b813-11e8-820d-c62240f4027d.png)

**Comment by AlexeyTishkin** [comment]
Так и должно быть. При создании связанной группировка по объекту + печатное имя.

**Comment by Anestezia** [comment]
Значит все ок
