### ISSUE TITLE
Создание связанной "Реалізації послуг" из "Виставлення рахунку"

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#53]
[528](https://github.com/a2develop/bugTracker/issues/528)
Проверить перенос наименований объектов для печати.

**Comment by Anestezia** [comment]
https://github.com/a2develop/testing/issues/52
Пункт первый.

**Comment by AlexeyTishkin** [comment]
Пункт первый - правильно. Это одинаковые объекты.

**Comment by Anestezia** [comment]
Значит всего достаточно и можно закрывать
