### ISSUE TITLE
Отображение реквизитов в печатной форме операции "Реалізація послуг"

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#54]
[527](https://github.com/a2develop/bugTracker/issues/527)
Проверить отображение/печать.

**Comment by Anestezia** [comment]
Реквизиты подтягиваются корректно. 
![image](https://user-images.githubusercontent.com/42540074/45538913-05704a00-b811-11e8-9361-dda8f6a98216.png)
