### ISSUE TITLE
Операция "Виставлення рахунку". Колонтитулы

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#56]
[76](https://github.com/a2develop/bugTracker/issues/76)

В рабочую форму добавлено отображение колонтитулов, которые будут печататься в каждом документе. 
Изменить текст можно непосредственно в рабочей форме.
В печатной форме верхний колонтитул печатается после реквизитов до даты и номера счета, нижний после таблицы с номенклатурой до подписей.

Проверить редактирование текста, отображение в рабочей форме, печать в печатной форме.

**Comment by Anestezia** [comment]
Колонтитулы отображаются корректно, на печать выводятся как заявлено. Редактируются, печатаются хоть по одной, хоть обе сразу. Примечание на печать не выводится, как и просили.
