### ISSUE TITLE
НН, Расчет корректировки к НН. Редактирование ячеек раздела Б в колонках 9, 11.

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#57]
[510](https://github.com/a2develop/bugTracker/issues/510)
В колонке 9 можно редактировать только в случае, если код ставки 903.
Проверить редактирование, сохранение, экспорт в XML.

**Comment by Anestezia** [comment]
Графа 9 редактируется только при ставке 903, редактируется, сохраняется, передается нормально.

П.С. Тут другой момент выскакивает. Снова незаполненные графы, при передаче в Сонату ставятся 0,00 и программа воспринимает их как заполненные значениямми

![image](https://user-images.githubusercontent.com/42540074/45677934-0b7e6780-bb3e-11e8-880b-8971a0bd140f.png)
 А просит, чтоб вот так: 
![image](https://user-images.githubusercontent.com/42540074/45678030-408aba00-bb3e-11e8-9489-a34a62e34f86.png)

**Comment by AlexeyTishkin** [comment]
> П.С. Тут другой момент выскакивает. Снова незаполненные графы, при передаче в Сонату ставятся 0,00 и программа воспринимает их как заполненные значениямми

Да, видел. Ждем изменений в ядре:
https://github.com/alex-kukhtin/A2v10/issues/126
