### ISSUE TITLE
Расчет корректировки к НН. Возможность корректировки цены. Возможность копирования строки

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#58]
[518](https://github.com/a2develop/bugTracker/issues/518)
Проверить возможность корректировки цены.

Добавил возможность копирования строки (в т.ч. для причины "Зміна номенклатури"). При нажатии на "копировать" вниз списка должна добавиться точная копия текущей строки. В копии возможны изменения во всех ячейках, включая объект учета.

**Comment by Anestezia** [comment]
Нужно, чтоб при копировании редактировался и "номер з/п рядка податкової накладної, що коригується". Без этого верно заполнить корректировку нельзя.

**Comment by AlexeyTishkin** [comment]
Там же ссылка на оригинальную строку налоговой. Он специально не редактируется.

**Comment by Anestezia** [comment]
— першим (з «-») «знімаємо» колишній рядок податкової накладної (ПН) із старою кількістю, а

— у другому рядку (з «+»), пронумерованому новим порядковим номером, якого не було в ПН, наводимо правильну кількість. 

Как быть с этим? Первая строка должна содержать номер строки в ПН, которую редактируем, а вторая строка должна иметь новый номер строки в ПН.
Таке коригування не пройде в ДФС, пришле помилку щодо нумерації, типу такої """Документ не може бути прийнятий -рядок №з/п 1. Зміна кількості. Відсутній відповідний рядок з № з/п 2"""

**Comment by AlexeyTishkin** [comment]
Это какие-то новые изменения ?
Насколько я помню, в корректировке нельзя было указывать номера строк, которых нет в родительской НН.
А если несколько строк меняется ? Как понять какая строка какой соответствует ?

**Comment by Anestezia** [comment]
В конце марта поменялись и причины и такие разъяснения. Теперь только двумя строками вносим любые изменения (цена, количество, номенклатура). Вот пример, который я нашла: 
![raschet_korrektirovki_1](https://user-images.githubusercontent.com/42540074/45739719-48a92f00-bbfc-11e8-8d96-f51e4898217f.png)
Вот вместе с накладной исходной: Там в ПН три товара, в РК строка 1 редактируется (сторнируется), строка 4 добавляется в ПН (измененная первая):
![1006](https://user-images.githubusercontent.com/42540074/45739839-8b6b0700-bbfc-11e8-9fe9-31e61b55bc94.jpg)
По поводу нескольких сразу:  видимо, задача просто одни убрать рядки, а другие добавить и чтоб нумерация не повторялась. Может так из трех товаров два меняются в цене или количестве: 1(-)=4(+); 2(-)=5(+).
Просто разрешить редактировать да и все.

И еще вопрос, который нужно уточнить. Написано, что в откорректированной строке первое значение вносим с (-), а второе с (+). У нас плюс не пишется. Просто положительное число и все. Может, на всякий случай, в редактируемой скопированной строке разрешить вписывать символы кроме цифр? Вдруг без этого ДФС тоже не примет? Также в этом смысле (добавление числа со знаком +) расчеты в разделе А РК. Вдруг тоже они там нужны? Я нашла пример, в котором сделано так, стоят плюсы в разделе А. Там в самих рядках указано это:
![raschet_korrektirovki_2](https://user-images.githubusercontent.com/42540074/45740562-37612200-bbfe-11e8-92ef-a62ad1c74a68.png)

**Comment by AlexeyTishkin** [comment]
> В конце марта поменялись и причины и такие разъяснения.

Да, с февраля не следил за изменениями...
Просто разрешить редактировать не получится. Я специально делал там отображение номера п/п родительской строки. Надо переделывать...

**Comment by AlexeyTishkin** [comment]
Надо выносить в отдельный issue. В нем просто ссылку на этот расширенный комментарий с картинками (или скопировать).

**Comment by AlexeyTishkin** [comment]
> И еще вопрос, который нужно уточнить. Написано, что в откорректированной строке первое значение вносим с (-), а второе с (+). У нас плюс не пишется. Просто положительное число и все. Может, на всякий случай, в редактируемой скопированной строке разрешить вписывать символы кроме цифр? Вдруг без этого ДФС тоже не примет?

Плюс не нужен, он даже по схеме корректировки не пройдет.
Кстати, а в Сонате ставится плюс ?

**Comment by Anestezia** [comment]
Нет в сонате плюса. Минус вручную поставить можно, плюс - нет. Пока тогда оставим эту тему. 
![image](https://user-images.githubusercontent.com/42540074/45743022-e3593c00-bc03-11e8-8049-a8948042639f.png)
