### ISSUE TITLE
Печатная форма авансового отчета

### ISSUE THREAD

**Issue by shevchuk-vadim** [a2develop/testing#59]
Что тестировать:
- [x] 1. Все правильно выводится на печать.
- [x] 2. При изменении лица или даты заполняется список документов, которым лицу были выданы деньги. Один и тот же документ не может попадать в два авансовых отчета.
- [x] 3. При проведении вычисляется остаток или перерасход предыдущего аванса.
- [x] 4. Привильно создается документ, которым вносится остаток или выдается перерасход.
- [x] 5. Если сумма остатка или перерасхода предыдущего аванса вычислена, то документы, котрые эту сумму могут изменить, нельзя провести или отменить в них проведение.
- [x] 6. При изменении лица или даты подставляется доложность. Без должности документ проводить запрещено.

**Comment by shevchuk-vadim** [comment]
6. При изменении лица или даты подставляется доложность. Без должности документ проводить запрещено.

**Comment by Anestezia** [comment]
1. На печать выводится все нужное
2. Работает как заявлено, один кассовый док. в два разных отчета не попадает.
3. Остаток, если есть, показывается.
4. Документ создается правильно, в зависимости от вида требуемой операции
5. Все ок. 
![image](https://user-images.githubusercontent.com/42540074/45886598-3842b100-bdc2-11e8-960b-81f9a3e778d7.png)
6. Подтягивается должность из карточки персонала, графа обязательна для заполнения.
