### ISSUE TITLE
В отчете "Прайс-лист" добавлена кнопка "Печать"

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#6]
[441](https://github.com/a2develop/bugTracker/issues/441)

**Comment by Anestezia** [comment]
А эта строчка вверху страницы будет видна на сервисе при печати?
![default](https://user-images.githubusercontent.com/42540074/45018063-dfd58a80-b031-11e8-8c94-0a8ffd019142.jpg)

**Comment by AlexeyTishkin** [comment]
Да. Это печать страницы "как есть". Будет еще экспорт в Excel, там будут только данные.

**Comment by kattrina-brekhova** [comment]
все ок - только строчка странная
