### ISSUE TITLE
В ОСВ по расчетным счетам добавлена подстановка счета по-умолчанию

### ISSUE THREAD

**Issue by shevchuk-vadim** [a2develop/testing#60]
Это в разделе Бухгалтерія\Звіти. И в национальной, и в иностранной валюте. Подставляется счет, который в документах использовался последним.
Заодно исправлен баг (https://github.com/a2develop/bugTracker/issues/539).

**Comment by Anestezia** [comment]
Подтверждаю. Работает и на валютных и на гривневых счетах.
