### ISSUE TITLE
Поддержка режима "Только чтение" при окончании триала

### ISSUE THREAD

**Issue by shevchuk-vadim** [a2develop/testing#62]
Под экаунтом с оконченным триалом в разделе "Бухгалтерия" проверить режим "Только чтение":
- [ ] 1. Запрещено создавать все элементы справочников.
- [ ] 2. Свойства всех эдементов справочников запрещено редактировать.
- [ ] 3. Запрещено создавать операции во всех списках операций, в т.ч. по элементам справочнников.
- [ ] 4. Во всех документах запрещены кнопки "видалити", "провести", "скасувати проведення", и "розрахувати".

https://github.com/a2develop/bugTracker/issues/537

**Comment by AndriyNesterenya** [comment]
Прокликал - по всем пунктам ОК
