### ISSUE TITLE
Всплывающее окно "Цены"

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#64]
1. Отображаются сразу все виды цен выбранного прайс-листа (ограничено тремя видами).
2. Отображаются только цены, которые действуют на сегодня (в следующей версии дату можно будет выбирать).
3. Для отображения истории цен добавлен чекбокс.

**Comment by Anestezia** [comment]
Так же, по всем трем пунктам работает как заявлено.
