### ISSUE TITLE
НН. Отображение поставщика/покупателя, у которого в свойствах не указано полное наименование

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#66]
[545](https://github.com/a2develop/bugTracker/issues/545)
В случае, если в свойствах контрагента не указано полное наименование в НН отображается обычное наименование.
Проверить отображение для контрагентов, у которых не указано полное наименование и для тех, у которых указано.

**Comment by AndriyNesterenya** [comment]
Годится, можно закрывать
