### ISSUE TITLE
Добавлены банковские мемориальные ордера

### ISSUE THREAD

**Issue by shevchuk-vadim** [a2develop/testing#68]
Это сделано, чтобы не ломать нумерацию платежных поручений, когда банки сами списывают деньги за обслуживание со счетов мемориальными ордерами. Надо убедиться, что в операцуих списания средств банком автонумерация документов не работает.
Кроме того, в рабочая и печатная форма документа в таких операциях аналогична платежному поручению, но название документа меняется на "мемориальный ордер".

**Comment by Anestezia** [comment]
автонумерации нет. все работает, в ведомость идет.
