### ISSUE TITLE
Расчет корректировки к НН. Возможность редактировать колонку 1.

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#70]
[543](https://github.com/a2develop/bugTracker/issues/543)
Добавлена возможность редактирования только для скопированных строк.

**Comment by Anestezia** [comment]
У нас строка скопированная редактируется (слайд 1), но при переносе в Сонату остается некорректной (слайд 2), как до изменения, т.е. только что скопированной.
слайд 1.

![image](https://user-images.githubusercontent.com/42540074/46063223-d8a72580-c174-11e8-9604-c7e82ef3398d.png)


слайд 2. 
![image](https://user-images.githubusercontent.com/42540074/46063164-ac8ba480-c174-11e8-9541-14847c0b4a3f.png)

**Comment by AlexeyTishkin** [comment]
Исправил.

**Comment by Anestezia** [comment]
да, с этим все ок.
