### ISSUE TITLE
Добавлены операции по уставному капиталу

### ISSUE THREAD

**Issue by shevchuk-vadim** [a2develop/testing#72]
Проверить работоспособность операций:
В прочих операциях -  формирование уставного капитала.
В кассовых и в банковских операциях - пополнение уставного капитала.
Во вступительном балансе - вступительный баланс по уставному и неоплаченному капиталу.

Все операции для моей фирмы - физлица появляться в списках не должны.

**Comment by Anestezia** [comment]
Все операции рабочие, в осв все идет. По документу В прочих операциях - формирование уставного капитала и В кассовых и в банковских операциях - пополнение уставного капитала - идет подбор плательщика из контрагентов, а по документам вступительного баланса по уставному и неоплаченному капиталу - из физических лиц (сотрудников).
