### ISSUE TITLE
Добавлено списание доходов и расходов на финансовый результат

### ISSUE THREAD

**Issue by shevchuk-vadim** [a2develop/testing#73]
Во всех операциях, где есть проводки по счетам 7 и 9 класса, при проведении добавляются проводки, списывающие суммы доходов и расходов на счет 791 (исключение - счет 91 списывается не на 791, а на 23 счет).

Нужно проверить операции:
1. Приобретение и реализацию (в том числе импорт-экспорт) ТМЦ и услуг.
2. Списание, оприходование, изготовление, и инвентаризацию ТМЦ.
3. Оплата банковских услуг и получение процентов по остаткам на счетах.
4. Отчет подотчетного лица.
5. Курсовые разницы и вознаграждение банку за куплю-продажу валюты.
6. Начисление налогов.

В общей оборотно-сальдовой ведомости сальдо по счетам 7 и 9 классов (кроме 79 счетов) должно быть закрыто.

**Comment by Anestezia** [comment]
Вроде все на месте, в каждом из запрашиваемых документов идет списание на 791 или 23.
ОСВ по 7 и 9 счетам закрыто все.
![image](https://user-images.githubusercontent.com/42540074/46343190-9e8ec580-c645-11e8-98fe-18d911b28d78.png)
