### ISSUE TITLE
В участке "Запасы" сделан запрет на проведение операций без строк.

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#74]
[555](https://github.com/a2develop/bugTracker/issues/555)
Проверить проведение операций в участке "Запасы", у которых отсутствуют строки.

**Comment by Anestezia** [comment]
Запрещает. 

![image](https://user-images.githubusercontent.com/42540074/46212573-fb853580-c33e-11e8-8ec1-b4e54965995e.png)
я все проклацала
