### ISSUE TITLE
Проверить экспорт Декларации НДС в Сонату.

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#76]
Изменился принцип формирования XML. В ячейки, в которых допустимо пустое значение, 0 теперь не пишется.
Сделать экспорт отчета в Сонату. В Сонате сделать проверку корректности.

**Comment by Anestezia** [comment]
Теперь переносит с пустыми ячейками. Проверку сонаты прошли. Этого должно быть достаточно.
