### ISSUE TITLE
Прайс-лист для нового тенанта.

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#79]
У нового тенанта должен быть прайс-лист "Відпускні ціни" с видом цены "Роздрібна".
[556](https://github.com/a2develop/bugTracker/issues/556)

**Comment by Illya-Lykhachov** [comment]
Коля, я что тестировщик? Этот ишью для проверки тестировщиками.

PS. Я уже проверил когда закрывал задачу 556 на разработку Лёше.
