### ISSUE TITLE
Податковый кредит. Подстановка ответственного лица

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#8]
Для "моей фирмы" - юр. лица исправлена подстановка ответственного лица.
[488](https://github.com/a2develop/bugTracker/issues/488)

**Comment by AlexeyTishkin** [comment]
Убрано заполнение поля Посадова (уповноважена) особа / фізична особа (законний представник).
[499](https://github.com/a2develop/bugTracker/issues/499)

**Comment by kattrina-brekhova** [comment]
в деве все ок
