### ISSUE TITLE
В свойствах контрагента добавлен тип "Кінцевий споживач"

### ISSUE THREAD

**Issue by shevchuk-vadim** [a2develop/testing#81]
Проверить создание в мастере, изменение свойств.
Проверить, не сломалась ли работа с типом "Фізична особа".

**Comment by mik-man** [comment]
Можно разъяснить, для чего это?

**Comment by AndriyNesterenya** [comment]
Есть такое, 
Работает, заполняется без кодов.

Предлагаю попутно переименовать столбец "Контакты" в "Контактні особи"
![image](https://user-images.githubusercontent.com/38098758/46421304-8351b200-c73a-11e8-87da-1926e8e819e9.png)

Народ в общей массе ожидает увидеть там адрес-телефон, а не людей для связи с юриками

**Comment by shevchuk-vadim** [comment]
Разъяснить, для чего, конечно, можно.
1. Для того, чтобы у физлиц можно было контролировать обязательность ИНН.
2. Для того, чтобы заблокировать возможность выбора неперсонифицированных физлиц в документах. Их почти нигде нельзя использовать.
3. Для того, чтобы не было препятствий для объединения физлиц контрагентов и сотрудников в один справочник.

**Comment by shevchuk-vadim** [comment]
Насчет "Контактов". Телефон у нас выводится в "Зв'язку". А адрес нигде. Он нужен? Если да, то надо добавить поле? Или вывести вместо контактного лица?

**Comment by AndriyNesterenya** [comment]
Убирать контактных лиц, как по мне, не стоит.
Еще один столбец, по-моему, будет в минус наглядности отображения данных.
Адрес можно порробовать выводить прямо под мылом/телефоном.
Как вариант - шрифтом помельче.
И очень желательно и контактных лиц и собственно контакты делать выделябельными :(
Чтобы юзер мог по-быстрому скопипастить их куда там ему надобно.

**Comment by shevchuk-vadim** [comment]
"Контакти" изменил на "Контактна особа".
Адрес в том же столбце, что и мыло с телефоном - это слишком высокая строка получится. Не уверен, что это хорошо. Пиши ишью с предложениями в багтрекер. А это закрываем?

**Comment by AndriyNesterenya** [comment]
Не буду пока писать.
Тема для обсуждения на досуге.
Закрываем.
