### ISSUE TITLE
Добавлены ограничения на выбор и создание типов контрагентов

### ISSUE THREAD

**Issue by shevchuk-vadim** [a2develop/testing#83]
Проверить, что нельзя выбрать контрагента недопустимого типа путем выбора из списка и набора с клавиатуры, а также что нельзя создать контрагента недопустимого типа из списка и из документа после ввода с клавиатуры.

Допустимые типы контрагентов:
- [ ] Приходный кассовый ордер - юрлицо, ФЛП, физлицо, конечный потребитель;
- [ ] Расходный кассовый ордер - ФЛП, физлицо;
- [ ] Приходное и расходное платежное поручение - Юрлицо, ФЛП, физлицо;
- [ ] Приходное и расходное платежное поручение в валюте - нерезидент;
- [ ] Авансовый отчет (поле "Кому")  - юрлицо, ФЛП;
- [ ] Акт взаимозачета  - юрлицо, ФЛП;
- [ ] Бухправка (по формированию капитала) - юрлицо, физлицо, нерезидент;
- [ ] Карточка вступительного баланса - юрлицо, ФЛП, физлицо, нерезидент;

**Comment by Anestezia** [comment]
Все работает как заявлено.
