### ISSUE TITLE
При выборе контрагента добавлена установка фильтра

### ISSUE THREAD

**Issue by shevchuk-vadim** [a2develop/testing#84]
- [ ] "Покупці" - в кассовых и банковских операциях с покупателями, вступительном балансе по покупателям;
- [ ] "Постачальники" - в кассовых и банковских операциях с поставщиками, в авансовом отчете, вступительном балансе по поставщикам;
- [ ] "Банки" - в банковских операциях по оплате банковских услуг, получению процентов по остаткам на счетах, расхода в кассу и прихода их кассы, операциях по купле-продаже валюты;
- [ ] "Державні органи" - в банковских операциях по перечислению налогов.

**Comment by Anestezia** [comment]
1. да
2. да
3. да. Только по этому документу мы не решили кого ставить получателем. Видаток з рахунку в банку в касу. Получатель - касса нашего предприятия, то есть наше предприятие?
![image](https://user-images.githubusercontent.com/42540074/46416796-f35b3a80-c730-11e8-80cc-261a7ff1f07d.png)

Надходження на рахунок в банку з каси нашого підприємства, тоже не совсем понятно, кто платник
![image](https://user-images.githubusercontent.com/42540074/46417190-c6f3ee00-c731-11e8-840d-61bd024af804.png)

4. да, все работает.
П.С. Вопрос по документу Повернення зарплати. Если депонируется зп нескольких человек, то кого мы ставим? На каждого по одному документу? Или кассира и в примечании - ведомость депонированной зп?

**Comment by shevchuk-vadim** [comment]
По третьему вопросу. Если документ - банковская платежка, то получателем никак не может быть касса предприятия, потому что у кассы нет счета в банке. А если получателем будет наше предприятие с каким-то счетом, то это будет операция не перемещения в кассу, а перемещения со счета на счет. Поэтому получатель здесь банк. А касса предприятия получателем становится не в платежке, а в кассовом ордере.

**Comment by shevchuk-vadim** [comment]
По возврату зарплаты. Эта операция делается в исключительных случаях, поэтому она всегда индивидуальна. На каждого работника всегда отдельный документ, что по кассе, что по банку.
Депонирование к возвратам отношения не имеет. Депонирование - это храниение неполученной работником зарплаты, с которой уже выплачены налоги. Может быть только при выдаче из кассы.

**Comment by shevchuk-vadim** [comment]
Закрываем?
