### ISSUE TITLE
Добавлены банковские операции с физлицами

### ISSUE THREAD

**Issue by shevchuk-vadim** [a2develop/testing#85]
Перечисление и возврат зарплаты, перечисление и возврат подотчетных сумм.
Если банковская карточка привязана к счету не физлица, а банка (как в Приватбанке), то нужно отметить, что получатель/плательщик является банком. При этом допустимым типом контрагент становится только юрлицо, и при выборе устанавливается фильтр "Банки". А для выбора физлица появляются поля перед назначением платежа. В проводки попадает физлицо, а не банк.

**Comment by AndriyNesterenya** [comment]
При попытке сотворить платежку "Надання коштів підзвітній особі" не дает импортировать банк
![image](https://user-images.githubusercontent.com/38098758/46426526-82734d00-c747-11e8-967b-94f2329f7cc8.png)
в списке пусто и при вводе шаблона поиска ничего не происходит.

**Comment by AndriyNesterenya** [comment]
При попытке сотворить платежку "Надання коштів підзвітній особі" есть неудобности и неочевидности.

Галку "Отримувач є банком" стоит обозвать более понятно пересічному юзеру 
Например "платіж на рахунок фіз.особи в банку".

По инструкции ставим эту галку - дальше не очень понятно что за "Код отримувача" туда писать.
ЕДРПОУ банка нормальный человек не знает, у него в реквизитах всегда пишут МФО.
При создании нового банка при установленной галке позволяет импортировать банк по ЕДРПОУ, но не показывает его в списке банков, т.к. воспринимает свежеимпортированный банк как контрагента.
![image](https://user-images.githubusercontent.com/38098758/46427155-50fb8100-c749-11e8-8eb4-a023fb51de4d.png)
Номер счета получателя ввести вручную нельзя, можно только выбрать из счетов контрагента.
И свежесозданного банка там тоже нет - он считается контрагентом, и почставить ему метку банка руками возможности нет.

Процедура получается мутная :(
После установки галки вместо импорта контрагента по ЕДРПОУ открывать диалог импорта банка по названию или МФО?
И сразу ставить ему метку, что это банк?

**Comment by shevchuk-vadim** [comment]
Вопрос создания банка в списке контрагентов непосредственно не связан с этим ишью. Тот же самый эффект будет, если попробовать создать банк в других операциях, где контрагентом должен быть банк, например, при покупке валюты.
У нас в списке контрагентов видны банки, но создать там банк нельзя. Это непорядок. Предлагаю на последней странице, там где роли, добавить и "Банк". При отмеченной галке тамже показывать МФО.
Если мы импортируем контрагента, то после его нахождения в ЕДРПОУ его можно также поискать и в списке банков. Если найден, то автоматичеки поставить галку "Банк" и заполнить МФО.

**Comment by AndriyNesterenya** [comment]
Думаю, это проблему решит.

**Comment by shevchuk-vadim** [comment]
По вопросу "Отримувач є банком". Конечно, эта ситуация немнго сложновата для понимания, но что поделать, если есть две ситуации с перечислениями на карточку? Причем, далеко ходить не надо, в Буккипер СааС. Приватбанк все катрочки держит на своем счете, а другие банки открывают счета физлицам. Изменение текста на "платіж на рахунок фіз.особи в банку" здесь ничего для понимания не даст, скорее наоброт. Когда работник хочет, чтобы ему зарплата перечислялась на карточку инливидуально, вне зарплатного проекта, он должен сообщить реквизиты для платежа на свою карту. Он эти реквизиты получает в своем банке, и сообщает работодателю. Поэтому работодатель, даже персічний, когда делает платеж, уже в курсе, кто должен быть отримувачем, работник или банк, а также ЕДРПОУ и МФО банка.

**Comment by shevchuk-vadim** [comment]
Закрываем?

**Comment by AndriyNesterenya** [comment]
Закрываем

**Comment by Anestezia** [comment]
Все работает как заявлено.
