### ISSUE TITLE
Проверить правильность автоматического заполнения Таблицы 6 "Звіту з персоніфікованого обліку платників ЄСВ (Додаток 4)".

### ISSUE THREAD

**Issue by Illya-Lykhachov** [a2develop/testing#86]

**Comment by Anestezia** [comment]
1. Ячейка 10 код виду нарахувань - повинно в основних випадках бути пуста клітина, по аналогії з Декларацією з ПДВ. Они должны в Сонату переноситься пустыми полями. https://github.com/a2develop/bugTracker/issues/568#issue-368187643
2. Ячейка 21 - округление идет только до третьего знака, что в итоге выдает ошибку: 
![image](https://user-images.githubusercontent.com/42540074/46669783-18d8c000-cbd9-11e8-92d0-6575a46aceb3.png)
2373,98 х 22% = 522,2756 = 522,28 грн. С арифметикой надо подумать. Теперь получается, что сумма по колонке на копейку не сходится, а по суммарному рядку - это неправильно. 22660,37 х 22% = 4985,2814 грн. (На картинке виден ряд.)
3. количество дней больничных подтягивает правильно.
4. Количество календарных дней "у трудових відносинах "подтягивает правильно.
5. Колонка 22 - ОК.

**Comment by Illya-Lykhachov** [comment]
Пункт 1. Исправил.
Пункт 2. В суммах нет третьего знака, здесь берутся уже посчитанные (и округлённые) суммы взноса из базы (из расчётной ведомости и аванса)

**Comment by Anestezia** [comment]
1. В сервисе исправилось (рис.1), а в сонату все равно с нулями переносит (рис.2).
![image](https://user-images.githubusercontent.com/42540074/46790246-2613bd00-cd47-11e8-90ac-fa2e54cc395f.png)
![image](https://user-images.githubusercontent.com/42540074/46790257-2e6bf800-cd47-11e8-97b1-66aa0dce4d6c.png)

2. Пусть, третьего знака нет, а в копейку  все равно не идет. Что делать-то?

**Comment by AlexeyTishkin** [comment]
> В сервисе исправилось (рис.1), а в сонату все равно с нулями переносит (рис.2).

Где можно глянуть пример ?

**Comment by Illya-Lykhachov** [comment]
Насчёт "Третьего знака".
Никто и ни при каких обстоятельствах не умножает общий ФОТ на 22%! Забудьте об этом атавизме навсегда. Последний раз так делали при СССР, когда не было **персонифицированного** учёта (взнос платили в целом по предприятию) и был только один % взноса на всех.
С момента внедрения персонифицированного учёта суммы взноса рассчитываются и округляются для каждого сотрудника отдельно! Т. е. 2373,98 * 22% = 522,28 грн. и никаких "хвостов".
Итоги по этому отчёту - это только итого по колонкам. Между собой итоги не перемножаются. Хотя бы потому, что на некоторых сотрудников-инвалидов может начисляться и по 8.41%.

PS. Не вижу, чтобы Соната ругалась на ошибки в суммах?

**Comment by Anestezia** [comment]
PS. Не вижу, чтобы Соната ругалась на ошибки в суммах?
Так на последней картинке же, первая строка сонатовской ругани. Пишет, что должна быть сумма 522,28, а у нас рассчиталось 522,27. 
2373,98 х 22% = 522,2756 = 522,28 грн.  
С общим ФОТ - уже понятно). Значит это ок.

**Comment by Illya-Lykhachov** [comment]
Проблема с выделением отпускных в отдельную строку. При этом приходится делить сумму взноса на 2 части.
Сколько было начислено Меняйло зарплаты, отпускных, и ЕСФ на ФОТ?
