### ISSUE TITLE
Операция "Придбання запасів". Проведение

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#87]
Изменилась процедура проведения в бухгалтерском и складском журналах.
Проверить отражение сумм в журналах в случаях:
1. Моя фирма - плательщик НДС, накладная без НДС. С/с без НДС, проводки по НДС нет.
2. Моя фирма - плательщик НДС, накладная с НДС. С/с без НДС, проводка по НДС есть.
3. Моя фирма - не плательщик НДС, накладная без НДС. С/с без НДС, проводки по НДС нет.
4. Моя фирма - не плательщик НДС, накладная с НДС. С/с с НДС, проводки по НДС нет.

**Comment by Anestezia** [comment]
Вроде все так, как описано работает.
