### ISSUE TITLE
Операция "Імпорт запасів"

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#88]
Новая операция.
Проверить пересчет грн <-> валюта.
Колонки "Мито", "Сума ПДВ" заполняются вручную.

Проверить формирование проводок в случаях:
1. Наша фирма - плательщик НДС. В с/с входит пошлина. НДС двумя проводками: 644-377, 6411-644.
2. Наша фирма - не плательщик НДС. В с/с входит пошлина, НДС. Проводки по НДС нет.

Проверить отражение в отчетах:
1. По объекту - Оборотная ведомость по складу.
2. Загальна оборотна-сальдова відомість.

Проверить с/с в момент реализации.

**Comment by AlexeyTishkin** [comment]
Проверить отражение в отчетах:
1. По поставщику - Оборотна відомість за розрахунками з постачальниками у валюті.
2. По таможне - Оборотна відомість за розрахунками з іншими дебіторами.

**Comment by AlexeyTishkin** [comment]
В Деларацию НДС операция должна попадать в строки 11.1, 11.2.

**Comment by AndriyNesterenya** [comment]
Из файла стандартного вида импортится замечательно.

В файле есть поле "Залишок".
Верно ли я понимаю, если такого-то наименования в запасах еще не было - создастся и пропишетется начальный баланс из "Залишку" в файле?
А если наименование уже есть - остаток не изменится?

**Comment by AndriyNesterenya** [comment]
Прочитал в "Что нового" про импорт.
Час мучил импорт из Экселя.
Полез сюда - а тут про совсем другой импорт :)
Буду повторять + прошу подключить Настю.

**Comment by Anestezia** [comment]
Коди митниць - довідник ще не працює. А при заповненні картки контрагента-державного органу важко знайти інформацію про його ЄДРПОУ.
Пересчет гривна-валюта корректирует гривневую сумму по округлению относительно валюты. кнопка активна 1 раз, потом исчезает.
1. Формирование проводок так, как описано в задании в 1 и 2 случаях. 
2. В указанных отчетах отображается у плательщика ндс - по складу на сумму с\с включая "мито", у неплательщика - на сумму "мито" + ндс.
3. Платежи таможне отображаются полностью в отчете Оборотна відомість за розрахунками з іншими дебіторами.
4. В отчете по поставщику отражается стоимость товара по инвойсу.
5. В Декларации НДС отображается в колонках 11.1 и 11.2 соответственно, правильность арифметики не проверяет, просто подтягивает данные, введенные вручную. (В моем примере сумма НДС по ставке 7% была завышена, относительно базы в соседней ячейке).  

Короче, все ок, кроме справочника.

**Comment by AlexeyTishkin** [comment]
> кнопка активна 1 раз, потом исчезает.

Кнопка появляется каждый раз после изменения курса валюты. И выключается сразу после пересчета.

**Comment by AlexeyTishkin** [comment]
> Короче, все ок, кроме справочника.

Справочник - отдельная задача.
