### ISSUE TITLE
В личном кабинете добавлена возможность сформировать счет на оплату

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#9]
[466](https://github.com/a2develop/bugTracker/issues/466)
Необходимо согласовать внешний вид.

**Comment by AlexeyTishkin** [comment]
Добавлено платежное поручение для оплаты наличкой через кассу банка.

**Comment by mik-man** [comment]
Внес предложения к внешнему виду, надо их рассмотреть, принять или отклонить.

**Comment by kattrina-brekhova** [comment]
все чудесно конечно, а если я хочу сумму больше, или меньше?...
можно только 295 - и все, другие суммы система не воспринимает

**Comment by AlexeyTishkin** [comment]
Другая сумма в процессе. Есть техническая проблема. И на сумму есть отдельный issue.

**Comment by AlexeyTishkin** [comment]
По поводу Колиных предложений что ?
