### ISSUE TITLE
Деларация НДС. Заполнение строк 11.1, 11.2

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#91]
В Декларации НДС сделано заполнение строк 11.1, 11.2. Попадают данные из операции "Імпорт запасів".

**Comment by Anestezia** [comment]
да, попадают. Но, повторюсь, так как данные по ндс вводятся вручную в импорте запасов, то так и подтягиваются, без проверки на арифметическую корректность.

**Comment by AlexeyTishkin** [comment]
НДС начисляется на таможенную стоимость товаров с учетом пошлины. Таможенная стоимость может оличаться от контрактной. Поэтому суммы НДС берем как есть из ГТД.
