### ISSUE TITLE
При импорте контрагента добавлена заполнение признака, кода, и города банка

### ISSUE THREAD

**Issue by shevchuk-vadim** [a2develop/testing#93]
Если контрагент одновременно присутствует в каталоге банков.
В свойствах контрагента добавлено отображение роли "Банк" без возможности редактирования.

**Comment by AndriyNesterenya** [comment]
Работает.
Единственный неприятный и непонятный для юзера момент : пока не уберется фокус с поля ввода ЕДРПОУ - ничего не ищется.
Если юзер не вводил код с клавы, после чего с большой вероятностью нажмется Enter, а копипастил с сайта банка или другого документа - сменить фокус его нужно как-то заставлять.
Может в подобных местах подсказки всплывающие или появляющиеся при попадании фокуса на поле рядом, или просто постоянным текстом писать что-то типа 
![image](https://user-images.githubusercontent.com/38098758/46731038-50577300-cc92-11e8-9113-b6c8fafc4c96.png)

**Comment by AndriyNesterenya** [comment]
... можно закрывать.
Вопрос с фокусами уйдет в отдельное обсуждение.
