### ISSUE TITLE
При создании банка по коду добавлена загрузка свойств банка из каталога банков

### ISSUE THREAD

**Issue by shevchuk-vadim** [a2develop/testing#94]
В свойствах и мастерах создания моей фирмы, контрагента, банка, и счета в банке.
https://github.com/a2develop/bugTracker/issues/563

**Comment by AndriyNesterenya** [comment]
Не совсем хорошо получилось.
Берем существующий банк с МФО 322539
Через импорт находится чудесно
![image](https://user-images.githubusercontent.com/38098758/46580812-944d3c80-ca34-11e8-8530-51b58deffd83.png)

Пишем этот код в поле МФО
![image](https://user-images.githubusercontent.com/38098758/46580819-b8a91900-ca34-11e8-879c-630c45a3f194.png)
появляется предложение создать такую запись

Жмем на "+" - попадаем в создавалку банка с пустыми полями, без всякой связи с введенным МФО
![image](https://user-images.githubusercontent.com/38098758/46580831-edb56b80-ca34-11e8-9818-1c245794805e.png)

Не стоит ли при нажатии на "+" открывать импорт и передавать туда МФО сразу?

**Comment by shevchuk-vadim** [comment]
А оно и есть сразу. Я сделал в пятницу вечером, на выходных никто дев не обновлял. Попробуй еще раз.

**Comment by AndriyNesterenya** [comment]
А вот теперь - чистое и незамутненное щасте.
Ура.
