### ISSUE TITLE
С подотчетным лицом теперь можно рассчитываться по безналичному расчету

### ISSUE THREAD

**Issue by shevchuk-vadim** [a2develop/testing#95]
1. В авансовом отчете добавлена подстановка платежных поручений в качестве документов получения денег подотчетным лицом.
2. В авансовом отчете добавлена возможность создать платежное поручене в качестве документа, которым внесен остаток или выдан перерасход.

**Comment by Anestezia** [comment]
1. ок
2. ок.

Не совсем понятна ситуация, когда, например, я за свои деньги купила что-то за 330 грн., принесла отчет авансовый и мне на основании этого отчета (документ на основании) выдана перевитрата 330 грн. 08.10.18. все проведено. Потом 09.10.18. мне с банковского счета документом Надання коштів підзвітній особі выдают еще 225 грн. Я открываю создание Звіт підзвітної особи на 09.10.18., а на мне висит прошлый долг. А ведь я за него фактически отчиталась.
![image](https://user-images.githubusercontent.com/42540074/46676350-0797af80-cbe9-11e8-8eaa-7a7914d09a49.png)
Такая ситуация у нас не предусмотрена?

**Comment by shevchuk-vadim** [comment]
Исправил ошибку, из-за которой операция по выплате перерасхода попадала в следующий авансовый отчет. Нужно протестировать.

**Comment by Anestezia** [comment]
Еще не работает. Точно всё накатили (дев)?

**Comment by Anestezia** [comment]
уже все ок
