### ISSUE TITLE
НН, РК. Заполнениие поля "Посадова особа..."

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#96]
[564](https://github.com/a2develop/bugTracker/issues/564)
Изменено заполнение поля "Посадова особа..." в НН и РК.
Проверить отображения для случаев:
1. Моя фирма - ФОП без принятого главного бухгалтера.
2. Моя фирма - ФОП с принятым главного бухгалтера.

Проверить формирование XML.

**Comment by Anestezia** [comment]
да, все ок. можно закрывать.

**Comment by Anestezia** [comment]
https://github.com/a2develop/bugTracker/issues/564#issuecomment-427813350

Вот бы эти изменения отображались уже на этапе нажатия кнопки ОНОВИТИ. Это для клиента ожидаемо, а вот игры со сменой даты - не интуитивно. Такое возможно?

**Comment by AlexeyTishkin** [comment]
> Вот бы эти изменения отображались уже на этапе нажатия кнопки ОНОВИТИ

По нажатию "Обновить" перезагружаются данные из БД. А в БД уже то лицо, которое было при первом сохранении.

**Comment by AlexeyTishkin** [comment]
Как вариант - рядом с "особою" сделать кнопку "оновити" по которой загрузится текущее ответственное лицо.
