### ISSUE TITLE
НН, РК. Поле "номер філії".

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/testing#97]
[565](https://github.com/a2develop/bugTracker/issues/565)
Поле "номер філії" теперь доступно для редактирования.
Проверить возможность редактирования, сохранение/загрузку, экспорт в XML.

**Comment by Anestezia** [comment]
В ПН доступно для редактирования, в созданном на основании РК - не доступно для редактирования. Но это не проблема. В хмл строки филии отображаются и в ПН и в РК. В Сонате отображаются.

**Comment by AlexeyTishkin** [comment]
РК создается на основе НН. В нем не может быть других кодов филиалов.
