### ISSUE TITLE
В мастере создания контрагента добавлены описания типов

### ISSUE THREAD

**Issue by shevchuk-vadim** [a2develop/testing#98]

**Comment by AndriyNesterenya** [comment]
Работает, выглядит доходчиво.
"Інше" не ассоциируется с конечными покупателями без кодов, но уже смирились и в хелпе опишем.

Напрягает только отсутствие точек в конце описаний.
Странно выглядит, когда в конце первого предложения точка есть, а у второго - нет.
![image](https://user-images.githubusercontent.com/38098758/46726668-7d525880-cc87-11e8-962a-3ee5177d95a4.png)

**Comment by shevchuk-vadim** [comment]
Точки добавил.
Закрываем?

**Comment by AndriyNesterenya** [comment]
Закрываем
