### ISSUE TITLE
Виставлення рахунку, в ПДФ не влазить адреса, написана на 2 або 3 строки

### ISSUE THREAD

**Issue by Anestezia** [a2develop/testing#99]
![image](https://user-images.githubusercontent.com/42540074/46665815-88e14900-cbcd-11e8-848d-b617dbfe5e83.png)
 Якщо у Властивостях моєї фірми на вкладці Контакти написати адресу у дві або у три строки, тобто, якщо в когось адреса дуже велика, то маємо такий глюк при зберіганні в форматі ПДФ.

**Comment by AlexeyTishkin** [comment]
Напиши в комментариях текст, чтобы было на чем проверить.
